param()
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Version='appscript-0.3.9-task203-role-split-transport-resilient'
$Web='1XzludErvxZ3px6qf1aLNU4LZWVU9NqJXYzSrnOm0HoDjUR9XN8flhSir';$Factory='14OHCqUDMAgpqB6JvPw_XQfFH8NlIUlVUK163RrFH1Drz3HxIc53B4IL2';$Email='homedesigntaedi@gmail.com'
$ExpectedWeb='afe09428756cb3269fa21d4b6567e99cb322b3c39def243adadd3c68c8a0e7b9';$ExpectedFactory='a2e0b3014c8289b8e25687adb32da099710b72ec0a5e5161533f8f97ee6016a0'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent';$Receipt='APPSCRIPT_TASK203_ROLE_SPLIT_RESILIENT_0.3.9.json';New-Item -ItemType Directory -Force -Path $Root|Out-Null
function FindCentral{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path $c -PathType Container){return $c}}};''}
function Save($o){$j=$o|ConvertTo-Json -Depth 100;$j|Set-Content (Join-Path $Root $Receipt) -Encoding UTF8;try{$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$j|Set-Content (Join-Path $d $Receipt) -Encoding UTF8}}catch{}}
function GitBlob([byte[]]$b){$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{(($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Sha256([byte[]]$b){$s=[Security.Cryptography.SHA256]::Create();try{(($s.ComputeHash($b)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function ClaspPath{foreach($n in @('clasp.cmd','clasp.ps1','clasp')){$c=Get-Command $n -ErrorAction SilentlyContinue;if($c){return $c.Source}};foreach($p in @((Join-Path $env:APPDATA 'npm\clasp.cmd'),(Join-Path $env:APPDATA 'npm\clasp.ps1'))){if(Test-Path $p){return $p}};''}
function Run([string]$File,[string[]]$Args,[int]$Timeout=90,[string]$Cwd=''){$psi=New-Object Diagnostics.ProcessStartInfo;$ext=[IO.Path]::GetExtension($File).ToLowerInvariant();if($ext-eq'.cmd'){$psi.FileName=$env:ComSpec;$psi.Arguments='/d /s /c ""'+$File+'" '+(($Args|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')+'"'}elseif($ext-eq'.ps1'){$psi.FileName='powershell.exe';$psi.Arguments='-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$File+'" '+(($Args|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')}else{$psi.FileName=$File;$psi.Arguments=(($Args|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')};$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;if($Cwd){$psi.WorkingDirectory=$Cwd};$p=[Diagnostics.Process]::Start($psi);if(-not$p.WaitForExit($Timeout*1000)){try{$p.Kill()}catch{};return [ordered]@{ok=$false;exit=124;stdout='';stderr='TIMEOUT'}};[ordered]@{ok=($p.ExitCode-eq0);exit=$p.ExitCode;stdout=$p.StandardOutput.ReadToEnd();stderr=$p.StandardError.ReadToEnd()}}
function Names([string]$t){$f=New-Object Collections.Generic.HashSet[string];$v=New-Object Collections.Generic.HashSet[string];foreach($m in [regex]::Matches($t,'(?m)\bfunction\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*\(')){[void]$f.Add($m.Groups[1].Value)};foreach($m in [regex]::Matches($t,'(?m)^\s*(?:var|let|const)\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*=\s*function\s*\(')){[void]$f.Add($m.Groups[1].Value)};foreach($m in [regex]::Matches($t,'(?m)^\s*(?:var|let|const)\s+([A-Za-z_$][A-Za-z0-9_$]*)\b')){[void]$v.Add($m.Groups[1].Value)};[ordered]@{functions=@($f|Sort-Object);variables=@($v|Sort-Object)}}
function CloneBaseline([string]$Clasp,[string]$Id,[string]$Label){$d=Join-Path $env:TEMP ('t203-r9-'+$Label+'-'+(Get-Date -Format 'yyyyMMdd_HHmmss_fff'));New-Item -ItemType Directory -Force -Path $d|Out-Null;$x=Run $Clasp @('clone-script',$Id) 150 $d;if(-not$x.ok){throw('CLONE_'+$Label+'_FAIL '+$x.stderr)};$parts=@();$all='';foreach($f in @(Get-ChildItem $d -Recurse -File|Sort-Object FullName)){$rel=$f.FullName.Substring($d.Length).TrimStart('\');$b=[IO.File]::ReadAllBytes($f.FullName);$parts+=($rel+'|'+$f.Length+'|'+(Sha256 $b));if($f.Extension-in@('.js','.gs')){$all+=[Text.Encoding]::UTF8.GetString($b)+"`n"}};$n=Names $all;[ordered]@{aggregate=(Sha256 ([Text.Encoding]::UTF8.GetBytes(($parts-join"`n"))));functions=$n.functions;variables=$n.variables}}
function Public([string]$Repo,[string]$Path,[string]$Sha){$o=[ordered]@{ok=$false;transport='RAW';shaExpected=$Sha;shaActual='';text='';error=''};try{$wc=New-Object Net.WebClient;try{$wc.Headers['User-Agent']='HomeDesign-T203-R9';$b=$wc.DownloadData('https://raw.githubusercontent.com/'+$Repo+'/main/'+$Path+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds())}finally{$wc.Dispose()};$o.shaActual=GitBlob $b;if($o.shaActual-ne$Sha){throw'GIT_BLOB_SHA_MISMATCH'};$o.text=[Text.Encoding]::UTF8.GetString($b);$o.ok=$true}catch{$o.error=$_.Exception.Message};[pscustomobject]$o}
function Private([string]$Repo,[string]$Path,[string]$Sha){$o=[ordered]@{ok=$false;transport='GH_EXISTING_AUTH';shaExpected=$Sha;shaActual='';text='';ghPresent=$false;authOk=$false;error=''};try{$gh=Get-Command gh.exe -ErrorAction SilentlyContinue;if(-not$gh){$gh=Get-Command gh -ErrorAction SilentlyContinue};if(-not$gh){throw'GH_NOT_FOUND'};$o.ghPresent=$true;$a=Run $gh.Source @('auth','status','-h','github.com') 30;$o.authOk=$a.ok;if(-not$a.ok){throw'GH_AUTH_UNAVAILABLE'};$x=Run $gh.Source @('api','repos/'+$Repo+'/contents/'+$Path,'-H','Accept: application/vnd.github.raw+json') 60;if(-not$x.ok){throw('GH_API_FAIL '+$x.stderr)};$txt=$x.stdout.TrimEnd("`r","`n");$b=[Text.Encoding]::UTF8.GetBytes($txt);$o.shaActual=GitBlob $b;if($o.shaActual-ne$Sha){throw'GIT_BLOB_SHA_MISMATCH'};$o.text=$txt;$o.ok=$true}catch{$o.error=$_.Exception.Message};[pscustomobject]$o}
function Intersect($A,$B){$h=@{};foreach($x in @($A)){$h[[string]$x]=1};@($B|Where-Object{$h.ContainsKey([string]$_)}|Sort-Object -Unique)}
function Analyze($s,$src,$wf,$ff,$wv,$fv){if(-not$src.ok){return [ordered]@{name=$s.name;origin=$s.repo;expectedRole=$s.role;sourceAvailable=$false;transport=$src.transport;shaExpected=$s.sha;error=$src.error;writePrerequisite=if($s.private){'PRIVATE_SOURCE_DRIVE_SNAPSHOT_OR_EXISTING_GH_AUTH'}else{'PUBLIC_SOURCE_TRANSPORT_FIX'}}};$n=Names $src.text;$fs=@($n.functions);$vs=@($n.variables);$web=@($fs|Where-Object{$_-match'(?i)(doGet|doPost|Web|HandleGet|HandlePost|JsonStore|DriveStore|Api)'});$fac=@($fs|Where-Object{$_-match'(?i)(Factory|Scheduler|Scheduled|Tick|Wake|Queue|Librarian|Crosscheck|Audit|Autofix|Governor|Repair|Worker|Pipeline)'});$heur=if($web.Count-gt0-and$fac.Count-eq0){'WEBAPP'}elseif($fac.Count-gt0-and$web.Count-eq0){'FACTORY'}elseif($fac.Count-gt0-and$web.Count-gt0){'MIXED_REVIEW'}else{'SHARED_REVIEW'};$tr=@();foreach($t in @('ScriptApp.newTrigger','ScriptApp.getProjectTriggers','ScriptApp.deleteTrigger','newTrigger(')){if($src.text.Contains($t)){$tr+=$t}};[ordered]@{name=$s.name;origin=$s.repo;expectedRole=$s.role;sourceAvailable=$true;transport=$src.transport;shaExpected=$s.sha;shaActual=$src.shaActual;functions=$fs;variables=$vs;heuristicRole=$heur;webSignals=$web;factorySignals=$fac;definesDoGet=($fs-contains'doGet');definesDoPost=($fs-contains'doPost');triggerTokens=@($tr|Sort-Object -Unique);webFunctionCollisions=(Intersect $wf $fs);factoryFunctionCollisions=(Intersect $ff $fs);webVariableCollisions=(Intersect $wv $vs);factoryVariableCollisions=(Intersect $fv $vs)}}
$r=[ordered]@{ok=$false;action='READONLY_TASK203_ROLE_SPLIT_TRANSPORT_RESILIENT';version=$Version;authorizedUserOk=$false;baselineUnchanged=$false;webAppHead=$null;factoryHead=$null;sourceCount=16;availableSourceCount=0;unavailableSources=@();sources=@();duplicateFunctions=@();duplicateVariables=@();entrypointRisk=@();triggerTokenSources=@();rolePlan=@();privateSupportReady=$false;safeToPush=$false;nextGate='REVIEW_REQUIRED';stage='START';error='';readOnly=$true;pushPerformed=$false;newProject=$false;newDeployment=$false;newTrigger=$false;oauthChanged=$false;scopeChanged=$false;normalChromeTouched=$false;startedAt=(Get-Date).ToString('o');completedAt=''}
try{$clasp=ClaspPath;if(-not$clasp){throw'CLASP_NOT_FOUND'};$a=Run $clasp @('show-authorized-user','--json') 45;$r.authorizedUserOk=($a.ok-and(($a.stdout+$a.stderr).ToLowerInvariant().Contains($Email)));if(-not$r.authorizedUserOk){throw'CLASP_AUTH_UNAVAILABLE'};$r.stage='BASELINE';$r.webAppHead=CloneBaseline $clasp $Web 'web';$r.factoryHead=CloneBaseline $clasp $Factory 'factory';$r.baselineUnchanged=($r.webAppHead.aggregate-eq$ExpectedWeb-and$r.factoryHead.aggregate-eq$ExpectedFactory);if(-not$r.baselineUnchanged){throw'BASELINE_DRIFT_ABORT'};$specs=@(
@{name='ContentOS_Drive_JSON_Cache_V3';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/ContentOS_Drive_JSON_Cache_V3.gs';sha='6fa5b3b597213eebf18c960bde6372c5b95eb67d';role='WEBAPP';private=$false},
@{name='ContentOS_Runtime_Registry_V3';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/ContentOS_Runtime_Registry_V3.gs';sha='9ea1cbf7113c00f3fc157ca92455f3ffb92af503';role='WEBAPP';private=$false},
@{name='ContentOS_Free_Backdata_Pipeline';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/ContentOS_Free_Backdata_Pipeline.gs';sha='0ef1e2ae9cdad77f727ea73d09ae5cc811813ac2';role='FACTORY';private=$false},
@{name='ContentOS_Unified_Scheduler';repo='8friend8ship-cloud/contents-os-git';path='apps-script/ContentOS_Unified_Scheduler.gs';sha='4bbabc0a1de6a176c0c580505af9b8aafa3d07cc';role='FACTORY';private=$true},
@{name='ContentOS_Unified_Scheduler_V13_Overlay_20260902';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/ContentOS_Unified_Scheduler_V13_Overlay_20260902.gs';sha='72183f03781e61f624e08cc23f4e0bb143901a18';role='FACTORY';private=$false},
@{name='Central_Image_Queens_Seed_AutoLearn_V2';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/Central_Image_Queens_Seed_AutoLearn_V2.gs';sha='8c24b07c1c5c7a2e3e17f27e277435997c35244b';role='FACTORY';private=$false},
@{name='ContentOS_Image_Learning_Web_Adapter_V2';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/ContentOS_Image_Learning_Web_Adapter_V2.gs';sha='7d09e951d10991ef30f1850eeeac3f1605098a42';role='WEBAPP';private=$false},
@{name='ImageSupply_Governor_V1';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/ImageSupply_Governor_V1.gs';sha='f8aaf57903b4e2fd4a8a820563020b4cc46f15f5';role='FACTORY';private=$false},
@{name='ImageSupply_Governor_PrePost_V2';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/ImageSupply_Governor_PrePost_V2.gs';sha='35c541cc8967501945736b9260d1b5db4c24ea12';role='FACTORY';private=$false},
@{name='Central_Sheet_Runtime_Audit_Autofix_20260902';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/Central_Sheet_Runtime_Audit_Autofix_20260902.gs';sha='1203f81bd0c34f857a1ab81bcafa2c3ec61a57fa';role='FACTORY';private=$false},
@{name='Central_Librarian_Knowledge_Automation';repo='8friend8ship-cloud/contents-os-git';path='apps-script/Central_Librarian_Knowledge_Automation.gs';sha='4631330d911dc8b5ae8e92b07a150b7986d1bc7e';role='FACTORY';private=$true},
@{name='ContentOS_DryWriter_Runtime_Config_Repair_20260902';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/ContentOS_DryWriter_Runtime_Config_Repair_20260902.gs';sha='642da2ac1e1dfa5131e445427d0e4a96c51ec3b9';role='FACTORY';private=$false},
@{name='Central_Workflow_Bridge_Crosscheck_20260902';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/Central_Workflow_Bridge_Crosscheck_20260902.gs';sha='91bcb4179d0a4651fe05422466e3bf9bc2ff68c2';role='FACTORY';private=$false},
@{name='OpenAI_5_Worker_Runtime_20260902';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/OpenAI_5_Worker_Runtime_20260902.gs';sha='afa81ad549d3ca0cea21954d1d84ce9956cd12ce';role='FACTORY';private=$false},
@{name='CentralTabletRemoteDispatcher_20260902';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/CentralTabletRemoteDispatcher_20260902.gs';sha='2d9a13af5108d028178c5ded5dbdcb4084be60ef';role='FACTORY';private=$false},
@{name='Central_Runtime_Strict_X2_20260902';repo='8friend8ship-cloud/Analyzer-12.09';path='apps-script/Central_Runtime_Strict_X2_20260902.gs';sha='818af11e0e1bcd0ca84dd9c1cc31ebf08e40b3de';role='FACTORY';private=$false});$r.stage='SOURCE_ANALYSIS';$items=@();foreach($s in $specs){$src=if($s.private){Private $s.repo $s.path $s.sha}else{Public $s.repo $s.path $s.sha};$items+=,(Analyze $s $src $r.webAppHead.functions $r.factoryHead.functions $r.webAppHead.variables $r.factoryHead.variables)};$r.sources=$items;$r.availableSourceCount=@($items|Where-Object{$_.sourceAvailable}).Count;$r.unavailableSources=@($items|Where-Object{-not$_.sourceAvailable}|ForEach-Object{[ordered]@{name=$_.name;origin=$_.origin;expectedRole=$_.expectedRole;transport=$_.transport;error=$_.error;writePrerequisite=$_.writePrerequisite}});$r.privateSupportReady=(@($items|Where-Object{$_.origin-eq'8friend8ship-cloud/contents-os-git'-and$_.sourceAvailable}).Count-eq2);$fm=@{};$vm=@{};foreach($i in $items|Where-Object{$_.sourceAvailable}){foreach($f in @($i.functions)){if(-not$fm[$f]){$fm[$f]=@()};$fm[$f]+=$i.name};foreach($v in @($i.variables)){if(-not$vm[$v]){$vm[$v]=@()};$vm[$v]+=$i.name}};$r.duplicateFunctions=@($fm.Keys|Where-Object{$fm[$_].Count-gt1}|Sort-Object|ForEach-Object{[ordered]@{name=$_;sources=@($fm[$_])}});$r.duplicateVariables=@($vm.Keys|Where-Object{$vm[$_].Count-gt1}|Sort-Object|ForEach-Object{[ordered]@{name=$_;sources=@($vm[$_])}});$r.entrypointRisk=@($items|Where-Object{$_.sourceAvailable-and($_.definesDoGet-or$_.definesDoPost)}|ForEach-Object{$_.name});$r.triggerTokenSources=@($items|Where-Object{$_.sourceAvailable-and@($_.triggerTokens).Count-gt0}|ForEach-Object{[ordered]@{name=$_.name;tokens=$_.triggerTokens}});$r.rolePlan=@($items|ForEach-Object{[ordered]@{name=$_.name;target=$_.expectedRole;sourceAvailable=$_.sourceAvailable;heuristic=if($_.sourceAvailable){$_.heuristicRole}else{'NOT_SCANNED'};webCollisionCount=if($_.sourceAvailable){@($_.webFunctionCollisions).Count}else{0};factoryCollisionCount=if($_.sourceAvailable){@($_.factoryFunctionCollisions).Count}else{0};entrypointRisk=if($_.sourceAvailable){[bool]($_.definesDoGet-or$_.definesDoPost)}else{$false}}});$r.ok=($r.availableSourceCount-ge14);$r.stage='DONE';$r.safeToPush=$false;$r.nextGate=if($r.privateSupportReady){'CENTRAL_ROLE_PLAN_REVIEW_THEN_BUILD_WRITE_SAFE_PATCH'}else{'CREATE_PRIVATE_SUPPORT_DRIVE_SNAPSHOT_THEN_BUILD_WRITE_SAFE_PATCH'}
}catch{$r.error=$_.Exception.Message;$r.stage='ERROR'}finally{$r.completedAt=(Get-Date).ToString('o');Save $r};$r|ConvertTo-Json -Depth 100 -Compress;if($r.ok){exit 0}else{exit 2}
