param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.110'
$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function Tabs{$r=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3;$o=$r.Content|ConvertFrom-Json;$a=@();if($o -is [System.Array]){foreach($x in $o){$a+=$x}}elseif($null-ne$o){$a+=$o};return $a}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$sec*1000));try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($r.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_CLOSED'};$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);return([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 30 -Compress;$bb=[Text.Encoding]::UTF8.GetBytes($j);$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};return $r.result.value}
function Click($w,[ref]$q,[double]$x,[double]$y){[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$x;y=$y});[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mousePressed';x=$x;y=$y;button='left';clickCount=1});Start-Sleep -Milliseconds 120;[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseReleased';x=$x;y=$y;button='left';clickCount=1})}
function Connect([string]$u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};return $w}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($my+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveCentral([string]$Name,$Object){try{$j=$Object|ConvertTo-Json -Depth 90;$j|Set-Content -LiteralPath (Join-Path $Root $Name) -Encoding UTF8;$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$p=Join-Path $d $Name;$j|Set-Content -LiteralPath $p -Encoding UTF8;return $p}}catch{};return ''}
$result=[ordered]@{ok=$false;action='AGENT_1.1.110_SOURCE_RESEARCH_STATE_READONLY';version=$Version;targetUrl=$TargetUrl;startedAt=(Get-Date).ToString('o');exactTab=$false;sourceTabClicked=$false;body='';controls=@();editors=@();savedSourceSignals=@();fastResearchComplete=$false;importVisible=$false;viewVisible=$false;normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;stage='START';error='';centralPath=''}
$w=$null
try{
 $pages=@(Tabs|Where-Object{[string]$_.type-eq'page'});$tab=$pages|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1;if(-not$tab){$tab=$pages|Where-Object{[string]$_.url-like'https://notebook.google.com/*'}|Select-Object -First 1};if(-not$tab){throw 'NO_NOTEBOOKLM_PAGE'}
 $w=Connect([string]$tab.webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{});$u=[string](Eval $w ([ref]$q) 'location.href');if($u-ne$TargetUrl){[void](Send $w ([ref]$q) 'Page.navigate' @{url=$TargetUrl});Start-Sleep -Seconds 2};if([string](Eval $w ([ref]$q) 'location.href')-ne$TargetUrl){throw 'EXACT_NOTEBOOK_NAVIGATION_FAILED'};$result.exactTab=$true
 $x=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const a=[...document.querySelectorAll('[role=tab]')].filter(vis).filter(e=>String(e.innerText||e.textContent||'').trim().includes('\uCD9C\uCC98'));if(!a.length)return{ok:false};const r=a[0].getBoundingClientRect();return{ok:true,x:r.left+r.width/2,y:r.top+r.height/2}})()";if(-not$x.ok){throw 'SOURCE_TAB_NOT_FOUND'};Click $w ([ref]$q) ([double]$x.x) ([double]$x.y);$result.sourceTabClicked=$true;Start-Sleep -Seconds 3
 $p=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const norm=s=>String(s||'').replace(/\s+/g,' ').trim();const body=document.body?.innerText||'';const controls=[...document.querySelectorAll('button,[role=button],[role=tab],a')].filter(vis).map(e=>{const r=e.getBoundingClientRect();return{tag:e.tagName,role:e.getAttribute('role')||'',aria:e.getAttribute('aria-label')||'',title:e.getAttribute('title')||'',text:norm(e.innerText||e.textContent||'').slice(0,220),disabled:!!e.disabled,ariaDisabled:e.getAttribute('aria-disabled'),x:r.left,y:r.top,w:r.width,h:r.height}}).filter(x=>x.text||x.aria||x.title).slice(0,160);const editors=[...document.querySelectorAll('input,textarea,[contenteditable=true]')].filter(vis).map(e=>{const r=e.getBoundingClientRect();return{tag:e.tagName,type:e.getAttribute('type')||'',aria:e.getAttribute('aria-label')||'',placeholder:e.getAttribute('placeholder')||'',readonly:!!e.readOnly,disabled:!!e.disabled,value:String(e.value||e.textContent||'').slice(0,500),x:r.left,y:r.top,w:r.width,h:r.height}}).slice(0,80);const saved=[];for(const e of [...document.querySelectorAll('*')].filter(vis)){const s=norm(e.innerText||e.textContent||'');if(/^\uC18C\uC2A4\s*[0-9]+\uAC1C$/.test(s)||/^[0-9]+\s*sources?$/i.test(s)||s.includes('\uC800\uC7A5\uB41C \uC18C\uC2A4'))saved.push(s.slice(0,300))}return{body:body.slice(0,18000),controls,editors,saved:[...new Set(saved)].slice(0,50),fast:body.includes('Fast Research \uC644\uB8CC'),imp:body.includes('\uAC00\uC838\uC624\uAE30'),view:body.includes('\uBCF4\uAE30')}})()";$result.body=[string]$p.body;$result.controls=$p.controls;$result.editors=$p.editors;$result.savedSourceSignals=$p.saved;$result.fastResearchComplete=[bool]$p.fast;$result.importVisible=[bool]$p.imp;$result.viewVisible=[bool]$p.view;$result.ok=$true;$result.stage='DONE'
}catch{$result.error=$_.Exception.Message}
finally{if($w){try{$w.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o');$result.centralPath=SaveCentral 'AGENT_1.1.110_SOURCE_RESEARCH_STATE_READONLY_RESULT.json' $result}
$result|ConvertTo-Json -Depth 90 -Compress
if($result.ok){exit 0}else{exit 2}
