param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.112'
$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$PromptB64='7IiY7KeR65CcIOyGjOyKpOulvCDrsJTtg5XsnLzroZwgQUkg7L2Y7YWQ7LigIOyDneyCsCDsm4ztgaztlIzroZzsmrDsl5DshJwg7JuQ7J6Q66OMIOyImOynkSwg7ZW17IusIO2MqO2EtCDrtoTshJ0sIOyerOyCrOyaqSDqsIDriqXtlZwg7YWc7ZSM66a/7ZmULCDsi6TsoJwg7IKs7Jqp7J6QIOqwgOy5mCDqsoDspp3snZgg7Z2Q66aE7J2EIO2VnOq1reyWtOuhnCDrqoXtmZXtlZjqsowg7KCV66as7ZW0IOyjvOyEuOyalC4g7ZW17IusIOq3vOqxsOyZgCDsi6TsoIQg7KCB7JqpIOyInOyEnOulCDtlajqu5gg7KCV66as7ZWY6rOgLCDsnbQg64K07Jqp7J2EIOuwlO2DleycvOuhnCBBSSDsmKTrlJTsmKQg7Jik67KE67ew66W8IOunjOuTpCDsiJgg7J6I6rKMIOykgOu5hO2VtCDso7zshLjsmpQuIOqzoOycoCDrp4jsu6Q6IE5MTV9GUkVTSF9BTExfMjAyNjA4MjlfMTkxNS4='
$Prompt=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($PromptB64))
$Marker='NLM_FRESH_ALL_20260829_1915'
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$MarkerFile=Join-Path $Root 'AGENT_1.1.112_CHAT_PROMPT_SUBMIT_ONCE_RESULT.json'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function Tabs{$r=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3;$o=$r.Content|ConvertFrom-Json;$a=@();if($o -is [System.Array]){foreach($x in $o){$a+=$x}}elseif($null-ne$o){$a+=$o};return $a}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$sec*1000));try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($r.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_CLOSED'};$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);return([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 30 -Compress;$bb=[Text.Encoding]::UTF8.GetBytes($j);$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};return $r.result.value}
function Click($w,[ref]$q,[double]$x,[double]$y){[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$x;y=$y});[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mousePressed';x=$x;y=$y;button='left';clickCount=1});Start-Sleep -Milliseconds 100;[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseReleased';x=$x;y=$y;button='left';clickCount=1})}
function Connect([string]$u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};return $w}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($my+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveCentral([string]$Name,$Object){try{$j=$Object|ConvertTo-Json -Depth 70;$j|Set-Content -LiteralPath $MarkerFile -Encoding UTF8;$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$p=Join-Path $d $Name;$j|Set-Content -LiteralPath $p -Encoding UTF8;return $p}}catch{};return ''}
if(Test-Path -LiteralPath $MarkerFile){try{$prior=Get-Content -LiteralPath $MarkerFile -Raw -Encoding UTF8|ConvertFrom-Json;if([bool]$prior.ok){[void](SaveCentral 'AGENT_1.1.112_CHAT_PROMPT_SUBMIT_ONCE_RESULT.json' $prior);$prior|ConvertTo-Json -Depth 70 -Compress;exit 0}}catch{}}
$result=[ordered]@{ok=$false;action='AGENT_1.1.112_CHAT_PROMPT_SUBMIT_ONCE';version=$Version;targetUrl=$TargetUrl;startedAt=(Get-Date).ToString('o');exactTab=$false;chatTabClicked=$false;editorFound=$false;promptFilled=$false;sendControl=$null;sendClicked=$false;markerVisible=$false;editorCleared=$false;chatSubmitted=$false;normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;stage='START';error='';centralPath=''}
$w=$null
try{
 $pages=@(Tabs|Where-Object{[string]$_.type-eq'page'});$tab=$pages|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1;if(-not$tab){$tab=$pages|Where-Object{[string]$_.url-like'https://notebook.google.com/*'}|Select-Object -First 1};if(-not$tab){throw 'NO_NOTEBOOKLM_PAGE'}
 $w=Connect([string]$tab.webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{});$u=[string](Eval $w ([ref]$q) 'location.href');if($u-ne$TargetUrl){[void](Send $w ([ref]$q) 'Page.navigate' @{url=$TargetUrl});Start-Sleep -Seconds 2};if([string](Eval $w ([ref]$q) 'location.href')-ne$TargetUrl){throw 'EXACT_NOTEBOOK_NAVIGATION_FAILED'};$result.exactTab=$true
 $tabInfo=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const a=[...document.querySelectorAll('[role=tab]')].filter(vis).filter(e=>String(e.innerText||e.textContent||'').trim().includes('\uCC44\uD305'));if(!a.length)return{ok:false};const r=a[0].getBoundingClientRect();return{ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:String(a[0].innerText||a[0].textContent||'').trim()}})()";if(-not$tabInfo.ok){throw 'CHAT_TAB_NOT_FOUND'};Click $w ([ref]$q) ([double]$tabInfo.x) ([double]$tabInfo.y);$result.chatTabClicked=$true;Start-Sleep -Seconds 1
 $pj=$Prompt|ConvertTo-Json -Compress;$fill=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>4&&r.height>4&&s.display!=='none'&&s.visibility!=='hidden'};const all=[...document.querySelectorAll('textarea,[contenteditable=true]')].filter(vis);const e=all.find(x=>{const a=String(x.getAttribute('aria-label')||'');const p=String(x.getAttribute('placeholder')||'');return a.includes('\uCFFC\uB9AC \uC0C1\uC790')||p.includes('\uC9C8\uBB38')||p.includes('\uCC3D\uC791')||/ask|create/i.test(p)})||all[0];if(!e)return{ok:false,count:all.length};const val=$pj;e.focus();if('value'in e){const proto=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const set=Object.getOwnPropertyDescriptor(proto,'value')?.set;if(set)set.call(e,val);else e.value=val}else{e.textContent=val};e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:val}));e.dispatchEvent(new Event('change',{bubbles:true}));const r=e.getBoundingClientRect();return{ok:true,len:('value'in e?e.value:e.textContent).length,left:r.left,top:r.top,right:r.right,bottom:r.bottom,cx:r.left+r.width/2,cy:r.top+r.height/2,placeholder:e.getAttribute('placeholder')||'',aria:e.getAttribute('aria-label')||''}})()";if(-not$fill.ok){throw 'CHAT_EDITOR_NOT_FOUND'};$result.editorFound=$true;$result.promptFilled=([int]$fill.len-gt20);if(-not$result.promptFilled){throw 'CHAT_PROMPT_FILL_FAILED'}
 $send=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled&&String(e.getAttribute('aria-disabled')).toLowerCase()!=='true'};const right=Number($($fill.right)),top=Number($($fill.top)),bottom=Number($($fill.bottom));const bs=[...document.querySelectorAll('button,[role=button]')].filter(vis).map(e=>{const r=e.getBoundingClientRect(),raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title'),e.querySelector('mat-icon')?.textContent].join(' '));return{e,r,raw}});let hit=bs.find(o=>/send|submit|arrow_upward|north|\uC804\uC1A1/i.test(o.raw));if(!hit)hit=bs.filter(o=>o.r.left>=right-140&&o.r.top<=bottom+40&&o.r.bottom>=top-40).sort((a,b)=>Math.abs((a.r.left+a.r.width/2)-right)-Math.abs((b.r.left+b.r.width/2)-right))[0];if(!hit)return{ok:false,candidates:bs.slice(-30).map(o=>o.raw.slice(0,120))};const r=hit.r;return{ok:true,x:r.left+r.width/2,y:r.top+r.height/2,raw:hit.raw.slice(0,220)}})()";$result.sendControl=$send;if(-not$send.ok){throw 'CHAT_SEND_CONTROL_NOT_FOUND'};Click $w ([ref]$q) ([double]$send.x) ([double]$send.y);$result.sendClicked=$true
 $deadline=(Get-Date).AddSeconds(45);do{Start-Sleep -Seconds 1;$v=Eval $w ([ref]$q) "(() => {const body=document.body?.innerText||'';const es=[...document.querySelectorAll('textarea,[contenteditable=true]')].filter(e=>{const r=e.getBoundingClientRect();return r.width>2&&r.height>2});let val='';for(const e of es){const p=String(e.getAttribute('placeholder')||'');if(p.includes('\uC9C8\uBB38')||p.includes('\uCC3D\uC791')||/ask|create/i.test(p)){val=String(('value'in e?e.value:e.textContent)||'');break}}return{marker:body.includes('NLM_FRESH_ALL_20260829_1915'),editorValue:val.slice(0,120),body:body.slice(0,9000)}})()";if([bool]$v.marker){$result.markerVisible=$true};if([string]$v.editorValue-eq''){$result.editorCleared=$true};if($result.markerVisible-and$result.editorCleared){break}}while((Get-Date)-lt$deadline);$result.chatSubmitted=($result.sendClicked-and$result.markerVisible);if(-not$result.chatSubmitted){throw 'CHAT_SUBMIT_NOT_VERIFIED'};$result.ok=$true;$result.stage='DONE'
}catch{$result.error=$_.Exception.Message}
finally{if($w){try{$w.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o');$result.centralPath=SaveCentral 'AGENT_1.1.112_CHAT_PROMPT_SUBMIT_ONCE_RESULT.json' $result}
$result|ConvertTo-Json -Depth 70 -Compress
if($result.ok){exit 0}else{exit 2}
