param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.117'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$ProjectKeyB64='MjAyNi0wOC0zMF9Db250ZW50T1NfQUnsvZjthZDsuKDsg53sgrDsm4ztgaztlIzroZzsmrBf66as7ISc7LmY'
$MyDriveKoB64='64K0IOuTnOudvOydtOu4jA=='
$FactoryB64='Tk9URUJPT0tMTV9GQUNUT1JZ'
$OutputB64='MDNfT1VUUFVUX0FVRElPX1ZJREVPX1NMSURFUw=='
function U([string]$b){return [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b))}
$ProjectKey=U $ProjectKeyB64;$MyDriveKo=U $MyDriveKoB64;$FactoryName=U $FactoryB64;$OutputName=U $OutputB64
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$DownloadHelper=Join-Path $Root 'RunNotebookLMDirectCDPDownloadSyncedV3.117.runtime.ps1'
$PythonVerifier=Join-Path $Root 'notebooklm_raw_download_capture.117.py'
$VerifyDir=Join-Path $Root 'RawVerifier117'
$MarkerFile=Join-Path $Root 'AGENT_1.1.117_AUDIO_READY_DOWNLOAD_DRIVE_VERIFY_RESULT.json'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function Raw([string]$p){return 'https://raw.githubusercontent.com/'+$Repo+'/main/'+$p+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($MyDriveKo+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveCentral([string]$Name,$Object){try{$j=$Object|ConvertTo-Json -Depth 90;$j|Set-Content -LiteralPath $MarkerFile -Encoding UTF8;$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$p=Join-Path $d $Name;$j|Set-Content -LiteralPath $p -Encoding UTF8;return $p}}catch{};return ''}
function Tabs{$r=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3;$o=$r.Content|ConvertFrom-Json;$a=@();if($o-is[System.Array]){foreach($x in $o){$a+=$x}}elseif($null-ne$o){$a+=$o};return $a}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$sec*1000));try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($r.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_CLOSED'};$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);return([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 30 -Compress;$bb=[Text.Encoding]::UTF8.GetBytes($j);$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};return $r.result.value}
function Connect([string]$u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};return $w}
function LastJson([string]$Text){$p=$null;foreach($line in @($Text -split "`r?`n"|Where-Object{$_.Trim()}|Select-Object -Last 80)){try{$j=$line|ConvertFrom-Json;if($j){$p=$j}}catch{}};return $p}
function ResolveDriveProjectPath{$hits=@();foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($base in @((Join-Path $r $MyDriveKo),(Join-Path $r 'My Drive'),(Join-Path $r 'Google Drive'))){if(-not(Test-Path -LiteralPath $base -PathType Container)){continue};$p=Join-Path $base ($FactoryName+'\'+$OutputName+'\'+$ProjectKey);if(Test-Path -LiteralPath $p -PathType Container){$hits+=$p}}};return @($hits|Select-Object -Unique)}
if(Test-Path -LiteralPath $MarkerFile){try{$prior=Get-Content -LiteralPath $MarkerFile -Raw -Encoding UTF8|ConvertFrom-Json;if([bool]$prior.ok){[void](SaveCentral 'AGENT_1.1.117_AUDIO_READY_DOWNLOAD_DRIVE_VERIFY_RESULT.json' $prior);$prior|ConvertTo-Json -Depth 90 -Compress;exit 0}}catch{}}
$result=[ordered]@{ok=$false;action='AGENT_1.1.117_AUDIO_READY_DOWNLOAD_DRIVE_VERIFY';version=$Version;targetUrl=$TargetUrl;startedAt=(Get-Date).ToString('o');exactTab=$false;artifactReady=$false;artifactText='';readyEvidence=$null;downloadHelperFetched=$false;downloadHelperPatched=$false;downloadOk=$false;downloadFile=$null;pythonVerifierFetched=$false;pythonVerified=$false;pythonReceipt=$null;driveProjectPaths=@();driveCopy=$null;sha256='';state='WAITING';normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;stage='START';error='';centralPath=''}
$w=$null
try{
  $result.stage='READY_CHECK';$pages=@(Tabs|Where-Object{[string]$_.type-eq'page'});$tab=$pages|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1;if(-not$tab){throw 'EXACT_NOTEBOOK_TAB_NOT_FOUND'};$result.exactTab=$true
  $w=Connect([string]$tab.webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{})
  $ready=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const body=String(document.body?.innerText||'');const busy=/generating|creating|\uC0DD\uC131 \uC911|\uB9CC\uB4DC\uB294 \uC911/i.test(body);const audio=[...document.querySelectorAll('audio')].filter(vis);const buttons=[...document.querySelectorAll('button,[role=button]')].filter(vis);const mediaButtons=buttons.filter(e=>{const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title'),e.querySelector('mat-icon')?.textContent].join(' '));return /play|download|more_vert|\uC7AC\uC0DD|\uB2E4\uC6B4\uB85C\uB4DC|\uB354\uBCF4\uAE30/i.test(raw)});let seed=audio[0]||mediaButtons.find(e=>/play|\uC7AC\uC0DD/i.test(String([e.innerText,e.getAttribute('aria-label'),e.getAttribute('title')].join(' '))))||mediaButtons[0]||null;let text='';let node=seed;for(let i=0;node&&i<8;i++,node=node.parentElement){const t=String(node.innerText||node.textContent||'').trim();if(t.length>=4&&t.length<=1200&&(/audio overview|\uC624\uB514\uC624 \uC624\uBC84\uBDF0/i.test(t)||node.querySelector?.('audio')||[...node.querySelectorAll?.('button,[role=button]')||[]].some(b=>/play|download|\uC7AC\uC0DD|\uB2E4\uC6B4\uB85C\uB4DC/i.test(String([b.innerText,b.getAttribute('aria-label'),b.getAttribute('title')].join(' ')))))){text=t;break}}const ready=!busy&&(audio.length>0||mediaButtons.some(e=>/play|download|\uC7AC\uC0DD|\uB2E4\uC6B4\uB85C\uB4DC/i.test(String([e.innerText,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')))));return{ready,busy,audioCount:audio.length,mediaButtonCount:mediaButtons.length,artifactText:text.slice(0,1000),bodySample:body.slice(0,2400)}})()"
  $result.readyEvidence=$ready;$result.artifactReady=[bool]$ready.ready;$result.artifactText=[string]$ready.artifactText
  if(-not$result.artifactReady){$result.ok=$true;$result.state='WAITING';$result.stage='DONE_WAITING'}else{
    if(-not$result.artifactText){$result.artifactText='오디오 오버뷰'}
    $result.stage='FETCH_PRIMARY_DOWNLOAD_HELPER';Invoke-WebRequest -UseBasicParsing -Uri (Raw 'local-agent/governor/RunNotebookLMDirectCDPDownloadSyncedV3.ps1') -OutFile $DownloadHelper -TimeoutSec 30;$result.downloadHelperFetched=$true
    $dtxt=Get-Content -LiteralPath $DownloadHelper -Raw -Encoding UTF8
    $old="function Get-NotebookTab {`$m=@(Get-CdpTabs|Where-Object{[string]`$_.type -eq 'page' -and [string]`$_.url -like 'https://notebook.google.com/notebook/*'});if(`$m.Count -lt 1){return `$null};return `$m[0]}"
    $new="function Get-NotebookTab {`$m=@(Get-CdpTabs|Where-Object{[string]`$_.type -eq 'page' -and [string]`$_.url -eq `$NotebookUrl});if(`$m.Count -lt 1){return `$null};return `$m[0]}"
    if(-not$dtxt.Contains($old)){throw 'DOWNLOAD_EXACT_TAB_PATCH_ANCHOR_NOT_FOUND'};$dtxt=$dtxt.Replace($old,$new).Replace("throw'","throw '")
    [IO.File]::WriteAllText($DownloadHelper,$dtxt,(New-Object Text.UTF8Encoding($true)));$tok=$null;$pe=$null;[void][Management.Automation.Language.Parser]::ParseFile($DownloadHelper,[ref]$tok,[ref]$pe);if($pe.Count){throw ('DOWNLOAD_HELPER_PARSE_FAIL '+(($pe|ForEach-Object{$_.Message})-join' | '))};$result.downloadHelperPatched=$true
    $result.stage='PRIMARY_DOWNLOAD';$dout=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $DownloadHelper -NotebookUrl $TargetUrl -ArtifactText $result.artifactText -RemoteDebuggingPort 9223 -TimeoutSeconds 180 2>&1|Out-String;$dp=LastJson $dout;if(-not$dp){throw ('DOWNLOAD_RESULT_JSON_NOT_FOUND '+$dout.Trim())};if(-not[bool]$dp.ok){throw ('PRIMARY_DOWNLOAD_FAILED '+[string]$dp.error)};$files=@($dp.files);if($files.Count-lt1){throw 'PRIMARY_DOWNLOAD_FILE_LIST_EMPTY'};$f=$files[0];$src=[string]$f.fullName;if(-not(Test-Path -LiteralPath $src -PathType Leaf)){throw ('DOWNLOADED_FILE_NOT_FOUND '+$src)};$fi=Get-Item -LiteralPath $src;$result.downloadOk=$true;$result.downloadFile=[ordered]@{name=$fi.Name;fullName=$fi.FullName;size=[int64]$fi.Length;extension=$fi.Extension;lastWriteTime=$fi.LastWriteTime.ToString('o')};$result.sha256=(Get-FileHash -LiteralPath $src -Algorithm SHA256).Hash.ToLowerInvariant()
    $result.stage='PYTHON_INDEPENDENT_VERIFY';Invoke-WebRequest -UseBasicParsing -Uri (Raw 'local-agent/python/notebooklm_raw_download_capture.py') -OutFile $PythonVerifier -TimeoutSec 30;$result.pythonVerifierFetched=$true;Remove-Item -LiteralPath $VerifyDir -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force -Path $VerifyDir|Out-Null;$pout=& python $PythonVerifier --source-file $src --drive-dir $VerifyDir --expected-media audio 2>&1|Out-String;$pp=$pout|ConvertFrom-Json;if(-not[bool]$pp.ok){throw ('PYTHON_VERIFY_FAILED '+$pout.Trim())};$result.pythonReceipt=$pp;$result.pythonVerified=([string]$pp.sourceSha256-eq$result.sha256 -and [string]$pp.destinationSha256-eq$result.sha256 -and [string]$pp.detectedMediaFamily-eq'audio' -and [bool]$pp.sourceImmutableVerified);if(-not$result.pythonVerified){throw 'PYTHON_VERIFY_GATE_FAILED'}
    $result.stage='DRIVE_COPY_PRIMARY';$deadline=(Get-Date).AddSeconds(90);$paths=@();do{$paths=@(ResolveDriveProjectPath);if($paths.Count){break};Start-Sleep -Seconds 3}while((Get-Date)-lt$deadline);$result.driveProjectPaths=$paths;if($paths.Count-lt1){throw 'DRIVE_PROJECT_SYNC_PATH_NOT_FOUND'};$destDir=$paths[0];$ext=$fi.Extension;if(-not$ext){$ext='.m4a'};$name=$ProjectKey+'_AUDIO_OVERVIEW_'+(Get-Date -Format 'yyyyMMdd_HHmmss')+$ext;$dest=Join-Path $destDir $name;Copy-Item -LiteralPath $src -Destination $dest -Force;Start-Sleep -Seconds 2;$df=Get-Item -LiteralPath $dest -ErrorAction Stop;$dsha=(Get-FileHash -LiteralPath $dest -Algorithm SHA256).Hash.ToLowerInvariant();if($df.Length-ne$fi.Length-or$dsha-ne$result.sha256){throw 'DRIVE_COPY_SIZE_OR_SHA_MISMATCH'};$result.driveCopy=[ordered]@{name=$df.Name;fullName=$df.FullName;size=[int64]$df.Length;sha256=$dsha;parent=$destDir};$result.ok=$true;$result.state='DOWNLOADED_AND_DRIVE_COPIED';$result.stage='DONE'
  }
}catch{$result.ok=$false;$result.state='ERROR';$result.error=$_.Exception.Message}
finally{if($w){try{$w.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o');$result.centralPath=SaveCentral 'AGENT_1.1.117_AUDIO_READY_DOWNLOAD_DRIVE_VERIFY_RESULT.json' $result}
$result|ConvertTo-Json -Depth 90 -Compress
if($result.ok){exit 0}else{exit 2}
