param()
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$Version='1.1.85'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$Helper=Join-Path $Root 'InspectNotebookLMCDPPortsV1.ps1'
$ExpectedHelperSha='f762b9c6f93d57e111130379cf51dede22a90e2c'
$HelperRaw='https://raw.githubusercontent.com/8friend8ship-cloud/notebooklm-webapp-bridge/main/local-agent/diagnostics/InspectNotebookLMCDPPortsV1.ps1'
$HelperContents='https://api.github.com/repos/8friend8ship-cloud/notebooklm-webapp-bridge/contents/local-agent/diagnostics/InspectNotebookLMCDPPortsV1.ps1?ref=main'
$ResultMarker=Join-Path $Root 'AGENT_1.1.85_NOTEBOOKLM_CDP_PORT_TAB_INVENTORY.json'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[] ($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$myDriveKo=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not $r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($myDriveKo+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveCentral([string]$Name,$Object){try{$central=FindCentral;if(-not $central){return ''};$dir=Join-Path $central 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $dir|Out-Null;$p=Join-Path $dir $Name;$Object|ConvertTo-Json -Depth 50|Set-Content -LiteralPath $p -Encoding UTF8;return $p}catch{return ''}}
function EnsureHelper{if(Test-Path -LiteralPath $Helper){try{if((GitBlobSha1 $Helper).ToLowerInvariant() -eq $ExpectedHelperSha){return 'LOCAL_VERIFIED'}}catch{}};$tmp=$Helper+'.download';Remove-Item $tmp -Force -ErrorAction SilentlyContinue;$rawOk=$false;try{Invoke-WebRequest -UseBasicParsing -Uri ($HelperRaw+'?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -OutFile $tmp -TimeoutSec 30;$rawOk=$true}catch{};if(-not $rawOk){$r=Invoke-RestMethod -UseBasicParsing -Uri ($HelperContents+'&hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -TimeoutSec 30;if(-not $r.content){throw 'HELPER_CONTENTS_API_NO_CONTENT'};[IO.File]::WriteAllBytes($tmp,[Convert]::FromBase64String(([string]$r.content -replace '\s','')))};$actual=(GitBlobSha1 $tmp).ToLowerInvariant();if($actual -ne $ExpectedHelperSha){Remove-Item $tmp -Force -ErrorAction SilentlyContinue;throw "HELPER_SHA_MISMATCH actual=$actual expected=$ExpectedHelperSha"};Move-Item -LiteralPath $tmp -Destination $Helper -Force;return $(if($rawOk){'RAW_VERIFIED'}else{'CONTENTS_API_VERIFIED'})}
$result=[ordered]@{ok=$false;action='AGENT_1.1.85_NOTEBOOKLM_CDP_PORT_TAB_INVENTORY';version=$Version;helperSha=$ExpectedHelperSha;helperFetch='';startedAt=(Get-Date).ToString('o');inventory=$null;normalChromeTouched=$false;oauthChanged=$false;scopeChanged=$false;error='';centralPath=''}
try{$result.helperFetch=EnsureHelper;$out=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Helper 2>&1|Out-String;$payload=$null;foreach($line in @($out -split "`r?`n"|Where-Object{$_.Trim()})[-1..-([Math]::Min(20,@($out -split "`r?`n"|Where-Object{$_.Trim()}).Count))]){try{$payload=$line|ConvertFrom-Json;if($payload){break}}catch{}};if(-not $payload){try{$payload=$out.Trim()|ConvertFrom-Json}catch{}};if(-not $payload){throw ('PORT_INVENTORY_JSON_NOT_FOUND: '+$out.Trim())};$result.inventory=$payload;$result.ok=[bool]$payload.ok;if(-not $result.ok){$result.error=[string]$payload.error}}catch{$result.error=$_.Exception.Message}
finally{$result.completedAt=(Get-Date).ToString('o');$result.centralPath=SaveCentral 'AGENT_1.1.85_NOTEBOOKLM_CDP_PORT_TAB_INVENTORY.json' $result;$result|ConvertTo-Json -Depth 50|Set-Content -LiteralPath $ResultMarker -Encoding UTF8}
$result|ConvertTo-Json -Depth 50 -Compress
if($result.ok){exit 0}else{exit 2}
