param([switch]$SelfTestRecovery)
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$Version='CENTRAL_AGENT_TAB_SUPERVISOR_V7_WINDOW_V3_PINNED_20260909'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$CleanupScript=Join-Path $Root 'RunOwnedUiCleanup.ps1'
$RecoveryScript=Join-Path $Root 'CentralTabAutoRecovery.ps1'
$PowerGuardScript=Join-Path $Root 'CentralAgentPowerContinuityGuard.ps1'
$PowerGuardReceipt=Join-Path $Root 'POWER_CONTINUITY_GUARD_LAST.json'
$WindowActivityScript=Join-Path $Root 'WindowActivitySupervisor.ps1'
$Registry=Join-Path $Root 'RUN_OWNED_UI_REGISTRY.json'
$Receipt=Join-Path $Root 'CENTRAL_TAB_SUPERVISOR_LAST.json'
$RecoveryReceipt=Join-Path $Root 'CENTRAL_TAB_RECOVERY_LAST.json'
$Pins=@{
 'local-agent/bootstrap/CentralAgentPowerContinuityGuard.ps1'=@{commit='f5e5a023b0b1ed6bd1f644a57be24fea02fe28ca';sha='b33d1ce889049e64706048ca8242e79b47b78e9c'}
 'local-agent/bootstrap/WindowActivitySupervisor.ps1'=@{commit='c89f18ade90b6d0e45aa7a8d6766f6cf67675eb0';sha='f6d66229cacd1bf3be6af4d63cce49326e18a8c5'}
}
function Test-Host{try{$h=Invoke-RestMethod 'http://127.0.0.1:8765/health' -TimeoutSec 3;return [bool]$h.ok}catch{return $false}}
function Test-Cdp{try{$v=Invoke-RestMethod 'http://127.0.0.1:9224/json/version' -TimeoutSec 3;return [bool]$v.Browser}catch{return $false}}
function Test-Remote{try{$p=@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{[string]$_.CommandLine-match'(?i)desktop-commander'-and[string]$_.CommandLine-match'(?i)(?:^|\s)remote(?:\s|$)'});if($p.Count-eq0){return $false};$ids=@($p.ProcessId);return (@(Get-NetTCPConnection -State Established -ErrorAction SilentlyContinue|Where-Object{$ids-contains$_.OwningProcess}).Count-gt0)}catch{return $false}}
function Find-Central{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(-not$d.Root){continue};foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return''}
function GitBlob([byte[]]$b){$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Install-Verified([byte[]]$Bytes,[string]$Expected,[string]$Dest){$sha=(GitBlob $Bytes).ToLowerInvariant();if($sha-ne$Expected.ToLowerInvariant()){throw'SHA_MISMATCH'};$tmp=$Dest+'.download';[IO.File]::WriteAllBytes($tmp,$Bytes);Move-Item $tmp $Dest -Force;return $sha}
function Refresh-Verified([string]$RepoPath,[string]$Dest){
 $pin=$Pins[$RepoPath]
 try{$u='https://api.github.com/repos/'+$Repo+'/contents/'+$RepoPath+'?ref=main&cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();$x=Invoke-RestMethod -Uri $u -Headers @{'User-Agent'='HomeDesign-Central-Supervisor-V7';'Accept'='application/vnd.github+json'} -TimeoutSec 10;$b=[Convert]::FromBase64String(([string]$x.content-replace'\s',''));return (Install-Verified $b ([string]$x.sha) $Dest)}catch{}
 if($pin){try{$u='https://raw.githubusercontent.com/'+$Repo+'/'+[string]$pin.commit+'/'+$RepoPath;$wc=New-Object Net.WebClient;try{$wc.Headers['User-Agent']='HomeDesign-Central-Supervisor-V7';$b=$wc.DownloadData($u)}finally{$wc.Dispose()};return (Install-Verified $b ([string]$pin.sha) $Dest)}catch{};try{if(Test-Path $Dest){$b=[IO.File]::ReadAllBytes($Dest);$sha=(GitBlob $b).ToLowerInvariant();if($sha-eq([string]$pin.sha).ToLowerInvariant()){return $sha}}}catch{}}
 return''
}
function Get-PowerGuardProcesses{return @(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{[string]$_.CommandLine-match'(?i)CentralAgentPowerContinuityGuard\.ps1'})}
function Read-PowerReceipt{try{if(Test-Path $PowerGuardReceipt){return (Get-Content $PowerGuardReceipt -Raw -Encoding UTF8|ConvertFrom-Json)}}catch{};return $null}
function Ensure-PowerGuard{
 $o=[ordered]@{sha='';started=$false;restarted=$false;after=0;ok=$false;receiptVersion='';systemRequiredHeld=$false;acPower=$false;remoteProcessPresent=$false;error=''}
 try{$o.sha=Refresh-Verified 'local-agent/bootstrap/CentralAgentPowerContinuityGuard.ps1' $PowerGuardScript;if(-not$o.sha){throw'POWER_GUARD_REFRESH_FAILED'};$rr=Read-PowerReceipt;$ver=$(if($rr){[string]$rr.version}else{''});$procs=Get-PowerGuardProcesses;if($procs.Count-gt0-and$ver-notmatch'^POWER_CONTINUITY_GUARD_V3_'){foreach($p in $procs){try{Stop-Process -Id ([int]$p.ProcessId) -Force}catch{}};Start-Sleep -Seconds 1;$o.restarted=$true};if((Get-PowerGuardProcesses).Count-eq0){Start-Process powershell.exe -ArgumentList @('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',$PowerGuardScript) -WindowStyle Hidden|Out-Null;$o.started=$true;Start-Sleep -Seconds 3};$o.after=(Get-PowerGuardProcesses).Count;$rr=Read-PowerReceipt;if($rr){$o.receiptVersion=[string]$rr.version;$o.systemRequiredHeld=[bool]$rr.systemRequiredHeld;$o.acPower=[bool]$rr.acPower;$o.remoteProcessPresent=[bool]$rr.remoteProcessPresent};$need=[bool]($o.acPower-and$o.remoteProcessPresent);$o.ok=[bool]($o.after-gt0-and$o.receiptVersion-match'^POWER_CONTINUITY_GUARD_V3_'-and((-not$need)-or$o.systemRequiredHeld))}catch{$o.error=$_.Exception.Message};return [pscustomobject]$o
}
function Run-Json([string]$Path){$o=[ordered]@{exit=9;obj=$null;raw='';error=''};try{$o.raw=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Path 2>&1|Out-String;$o.exit=$LASTEXITCODE;try{$o.obj=$o.raw|ConvertFrom-Json}catch{$lines=@($o.raw-split"`r?`n"|Where-Object{$_.Trim().StartsWith('{')});if($lines.Count){$o.obj=$lines[-1]|ConvertFrom-Json}else{throw}}}catch{$o.error=$_.Exception.Message};return [pscustomobject]$o}
$started=(Get-Date).ToString('o');$issues=New-Object System.Collections.Generic.List[string]
$pg=Ensure-PowerGuard;if(-not$pg.ok){$issues.Add('POWER_CONTINUITY_GUARD_DOWN')}
$waSha=Refresh-Verified 'local-agent/bootstrap/WindowActivitySupervisor.ps1' $WindowActivityScript;$wa=$null
if(-not$waSha){$issues.Add('WINDOW_ACTIVITY_REFRESH_FAILED')}elseif(Test-Path $WindowActivityScript){$wa=Run-Json $WindowActivityScript;if(-not$wa.obj){$issues.Add('WINDOW_ACTIVITY_NO_READBACK')}elseif([string]$wa.obj.version-notmatch'^WINDOW_ACTIVITY_SUPERVISOR_V3_'){$issues.Add('WINDOW_ACTIVITY_VERSION_MISMATCH')}elseif(-not[bool]$wa.obj.ok){$issues.Add('WINDOW_ACTIVITY_NOT_OK')}}else{$issues.Add('WINDOW_ACTIVITY_MISSING')}
$cl=$null;if(Test-Path $CleanupScript){$cl=Run-Json $CleanupScript;if(-not$cl.obj){$issues.Add('CLEANUP_NO_READBACK')}elseif(-not[bool]$cl.obj.ok){$issues.Add('CLEANUP_NOT_OK')}}else{$issues.Add('CLEANUP_MISSING')}
$host=Test-Host;$cdp=Test-Cdp;$remote=Test-Remote;if(-not$host){$issues.Add('LOCAL_HOST_DOWN')};if(-not$cdp){$issues.Add('CFT_CDP_9224_DOWN')};if(-not$remote){$issues.Add('REMOTE_DC_OFFLINE')}
$authRemain=$false;if($wa-and$wa.obj){if([int]$wa.obj.duplicateFamiliesRemaining-gt0){$authRemain=$true};if([int]$wa.obj.ttlCloseFailures-gt0){$issues.Add('AUTH_TTL_CLOSE_FAILURE')}};if($authRemain){$issues.Add('AUTH_DUPLICATE_REMAINS')};if($SelfTestRecovery){$issues.Add('SELF_TEST_RECOVERY_TRIGGER')}
$recoveryTriggered=$false;$recoveryCooldown=$false;$recoveryExit=$null
if($issues.Count-gt0-and(Test-Path $RecoveryScript)){$recent=$false;try{if(Test-Path $RecoveryReceipt){$recent=(((Get-Date)-(Get-Item $RecoveryReceipt).LastWriteTime).TotalSeconds-lt120)}}catch{};if($recent-and-not$SelfTestRecovery){$recoveryCooldown=$true}else{try{& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $RecoveryScript -Reason ($issues-join',')|Out-Null;$recoveryExit=$LASTEXITCODE;$recoveryTriggered=$true}catch{$recoveryExit=9}}}
$host2=Test-Host;$cdp2=Test-Cdp;$remote2=Test-Remote;$waObj=$(if($wa){$wa.obj}else{$null});$clObj=$(if($cl){$cl.obj}else{$null});$waOk=[bool]($waObj-and[bool]$waObj.ok-and[string]$waObj.version-match'^WINDOW_ACTIVITY_SUPERVISOR_V3_');$clOk=[bool]($clObj-and[bool]$clObj.ok)
$out=[ordered]@{ok=[bool]($pg.ok-and$waOk-and$clOk-and$host2-and$cdp2-and$remote2-and-not$authRemain);version=$Version;startedAt=$started;completedAt=(Get-Date).ToString('o');phase='PINNED_FALLBACK+POWER_V3+WINDOW_V3_AUTH_TTL10M+VERIFY_RECOVER';powerGuardOk=[bool]$pg.ok;powerGuardSha=[string]$pg.sha;powerGuardReceiptVersion=[string]$pg.receiptVersion;powerGuardSystemRequiredHeld=[bool]$pg.systemRequiredHeld;powerGuardProcessAfter=[int]$pg.after;windowActivitySha=$waSha;windowActivityVersion=$(if($waObj){[string]$waObj.version}else{''});windowActivityOk=$waOk;windowActivityMonitorCount=$(if($waObj){[int]$waObj.monitorCount}else{0});windowActivityCaptureCount=$(if($waObj){[int]$waObj.captureCount}else{0});windowActivityAuthTtlSec=$(if($waObj){[int]$waObj.authWindowTtlSec}else{0});windowActivityExpiredSingleAuth=$(if($waObj){[int]$waObj.expiredSingleAuthCount}else{0});windowActivityTtlCloseFailures=$(if($waObj){[int]$waObj.ttlCloseFailures}else{0});windowActivityClosedSuperseded=$(if($waObj){[int]$waObj.closedSupersededCount}else{0});windowActivityDuplicateFamiliesRemaining=$(if($waObj){[int]$waObj.duplicateFamiliesRemaining}else{0});cleanupVersion=$(if($clObj){[string]$clObj.version}else{''});hostOk=$host2;cdp9224Ok=$cdp2;remoteDcOk=$remote2;issues=@($issues);recoveryTriggered=$recoveryTriggered;recoveryExit=$recoveryExit;recoveryCooldown=$recoveryCooldown;policy='VISIBLE!=WORKING;AUTH_HARD_TTL_600S;WAITING_USER_NOT_INDEFINITE;ENUM_WINDOWS_V3;DUAL_MONITOR_10M;PINNED_RAW_LOCAL_LASTGOOD;POWER_V3;REMOTE_EXACT_REPAIR'}
$json=$out|ConvertTo-Json -Depth 30;$json|Set-Content -LiteralPath $Receipt -Encoding UTF8;try{$c=Find-Central;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$json|Set-Content -LiteralPath (Join-Path $d 'CENTRAL_TAB_SUPERVISOR_LAST.json') -Encoding UTF8}}catch{};$out|ConvertTo-Json -Depth 30 -Compress;if($out.ok){exit 0}else{exit 4}
