param([switch]$SelfTestRecovery)
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$Version='CENTRAL_AGENT_TAB_SUPERVISOR_V19_REMOTE_SINGLETON_UIA_SAFE_20260910'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$CleanupScript=Join-Path $Root 'RunOwnedUiCleanup.ps1'
$RecoveryScript=Join-Path $Root 'CentralTabAutoRecovery.ps1'
$PowerGuardScript=Join-Path $Root 'CentralAgentPowerContinuityGuard.ps1'
$PowerGuardReceipt=Join-Path $Root 'POWER_CONTINUITY_GUARD_LAST.json'
$RemoteGuardScript=Join-Path $Root 'DesktopCommanderKeepAlive.ps1'
$WindowActivityScript=Join-Path $Root 'WindowActivitySupervisor.ps1'
$InactiveGovernorScript=Join-Path $Root 'InactiveProcessGovernor.ps1'
$Receipt=Join-Path $Root 'CENTRAL_TAB_SUPERVISOR_LAST.json'
$RecoveryReceipt=Join-Path $Root 'CENTRAL_TAB_RECOVERY_LAST.json'
$RequiredPowerGuardVersion='POWER_CONTINUITY_GUARD_V6_AC_SYSTEM_AWAKE_SCREEN_OFF_20260909'
$RequiredRemoteGuardPattern='^REMOTE_DC_KEEPALIVE_V5_'
$Pins=@{
 'local-agent/bootstrap/CentralAgentPowerContinuityGuard.ps1'=@{commit='b40b7b2e4ca3e5e44e8ad792e436bee3b990095d';sha='42a44d82401e44caf2320e137dac27a3199c3b99';dest=$PowerGuardScript}
 'local-agent/bootstrap/DesktopCommanderKeepAlive.ps1'=@{commit='6bf8e97c869a1cdfa2bc1e6cee9bd17f298351ab';sha='b0c95ac00154d8d1577523c6663f6204af184fe3';dest=$RemoteGuardScript}
 'local-agent/bootstrap/WindowActivitySupervisor.ps1'=@{commit='95aacd1d1416d6e41906ff6be0b935f8e032ade8';sha='29d260473f3fdbc993b86e0900dc9833bf158609';dest=$WindowActivityScript}
 'local-agent/bootstrap/InactiveProcessGovernor.ps1'=@{commit='5d4cd5171d031c9d8252f03adb06925f5380181f';sha='5a9df27edd089d62f2eaf473a6cbdb984bd287b2';dest=$InactiveGovernorScript}
 'local-agent/bootstrap/RunOwnedUiCleanup.ps1'=@{commit='7c7631047ff322ecb8836386c6408f8651304398';sha='c45a7da297c10003850a1ef08faf779b0f5be984';dest=$CleanupScript}
}
function Find-Central{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(-not$d.Root){continue};foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function GitBlob([byte[]]$b){$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Refresh-Pinned([string]$RepoPath){
 $pin=$Pins[$RepoPath];if(-not$pin){return ''};$dest=[string]$pin.dest;$expected=([string]$pin.sha).ToLowerInvariant()
 try{$u='https://raw.githubusercontent.com/'+$Repo+'/'+[string]$pin.commit+'/'+$RepoPath;$wc=New-Object Net.WebClient;try{$wc.Headers['User-Agent']='HomeDesign-Supervisor-V19';$b=$wc.DownloadData($u)}finally{$wc.Dispose()};$actual=(GitBlob $b).ToLowerInvariant();if($actual-ne$expected){throw 'PIN_SHA_MISMATCH'};$tmp=$dest+'.v19';[IO.File]::WriteAllBytes($tmp,$b);Move-Item $tmp $dest -Force;return $actual}catch{}
 try{if(Test-Path $dest){$b=[IO.File]::ReadAllBytes($dest);$actual=(GitBlob $b).ToLowerInvariant();if($actual-eq$expected){return $actual}}}catch{}
 return ''
}
function Run-Json([string]$Path,[string[]]$Args=@()){$o=[ordered]@{exit=9;obj=$null;raw='';error=''};try{$o.raw=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Path @Args 2>&1|Out-String;$o.exit=$LASTEXITCODE;try{$o.obj=$o.raw|ConvertFrom-Json}catch{$lines=@($o.raw-split"`r?`n"|Where-Object{$_.Trim().StartsWith('{')});if($lines.Count){$o.obj=$lines[-1]|ConvertFrom-Json}else{throw}}}catch{$o.error=$_.Exception.Message};return [pscustomobject]$o}
function Test-LocalHost{try{$h=Invoke-RestMethod 'http://127.0.0.1:8765/health' -TimeoutSec 3;return [bool]$h.ok}catch{return $false}}
function Test-Cdp{try{$v=Invoke-RestMethod 'http://127.0.0.1:9224/json/version' -TimeoutSec 3;return [bool]$v.Browser}catch{return $false}}
function Test-Remote{try{$p=@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{([string]$_.Name)-match'(?i)^node(?:\.exe)?$'-and[string]$_.CommandLine-match'(?i)desktop-commander'-and[string]$_.CommandLine-match'(?i)(?:^|\s)remote(?:\s|$)'});if($p.Count-eq0){return $false};$ids=@($p|ForEach-Object{[int]$_.ProcessId});return (@(Get-NetTCPConnection -State Established -ErrorAction SilentlyContinue|Where-Object{$ids-contains$_.OwningProcess}).Count-gt0)}catch{return $false}}
function Read-PowerReceipt{try{if(Test-Path $PowerGuardReceipt){return Get-Content $PowerGuardReceipt -Raw -Encoding UTF8|ConvertFrom-Json}}catch{};return $null}
function Get-PowerGuardProcs{return @(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{[string]$_.CommandLine-match'(?i)CentralAgentPowerContinuityGuard\.ps1'})}
function Ensure-PowerGuard{
 $o=[ordered]@{sha='';ok=$false;processCount=0;receiptVersion='';acPower=$false;systemRequiredHeld=$false;displayRequiredHeld=$false;screenOffAllowed=$false;restarted=$false;error=''}
 try{$o.sha=Refresh-Pinned 'local-agent/bootstrap/CentralAgentPowerContinuityGuard.ps1';if(-not$o.sha){throw 'POWER_GUARD_REFRESH_FAILED'};$rr=Read-PowerReceipt;$procs=@(Get-PowerGuardProcs);$restart=($procs.Count-eq0-or-not$rr-or[string]$rr.version-ne$RequiredPowerGuardVersion);if($restart){foreach($p in $procs){try{Stop-Process -Id ([int]$p.ProcessId) -Force -ErrorAction SilentlyContinue}catch{}};Start-Sleep -Milliseconds 500;Start-Process powershell.exe -ArgumentList @('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',$PowerGuardScript) -WindowStyle Hidden|Out-Null;Start-Sleep -Seconds 3;$o.restarted=$true};$procs=@(Get-PowerGuardProcs);$rr=Read-PowerReceipt;$o.processCount=$procs.Count;if($rr){$o.receiptVersion=[string]$rr.version;$o.acPower=[bool]$rr.acPower;$o.systemRequiredHeld=[bool]$rr.systemRequiredHeld;$o.displayRequiredHeld=[bool]$rr.displayRequiredHeld;$o.screenOffAllowed=[bool]$rr.screenOffAllowed;$o.ok=[bool]($procs.Count-eq1-and$o.receiptVersion-eq$RequiredPowerGuardVersion-and$o.screenOffAllowed-and-not$o.displayRequiredHeld-and((-not$o.acPower)-or$o.systemRequiredHeld))}}catch{$o.error=$_.Exception.Message};return [pscustomobject]$o
}
$started=(Get-Date).ToString('o');$issues=New-Object System.Collections.Generic.List[string]
$pg=Ensure-PowerGuard;if(-not$pg.ok){$issues.Add('POWER_GUARD_NOT_CANONICAL')}
$remoteSha=Refresh-Pinned 'local-agent/bootstrap/DesktopCommanderKeepAlive.ps1';$waSha=Refresh-Pinned 'local-agent/bootstrap/WindowActivitySupervisor.ps1';$igSha=Refresh-Pinned 'local-agent/bootstrap/InactiveProcessGovernor.ps1';$clSha=Refresh-Pinned 'local-agent/bootstrap/RunOwnedUiCleanup.ps1'
if(-not$remoteSha){$issues.Add('REMOTE_GUARD_REFRESH_FAILED')};if(-not$waSha){$issues.Add('WINDOW_UIA_REFRESH_FAILED')};if(-not$igSha){$issues.Add('INACTIVE_R2_REFRESH_FAILED')};if(-not$clSha){$issues.Add('CLEANUP_V7_REFRESH_FAILED')}
$rg=$(if($remoteSha){Run-Json $RemoteGuardScript}else{$null});$wa=$(if($waSha){Run-Json $WindowActivityScript}else{$null});$cl=$(if($clSha){Run-Json $CleanupScript}else{$null});$ig=$(if($igSha){Run-Json $InactiveGovernorScript}else{$null})
$rgOk=[bool]($rg-and$rg.obj-and[bool]$rg.obj.ok-and[string]$rg.obj.version-match$RequiredRemoteGuardPattern);$waOk=[bool]($wa-and$wa.obj-and[bool]$wa.obj.ok-and[string]$wa.obj.version-match'^WINDOW_ACTIVITY_SUPERVISOR_V6_' -and[int]$wa.obj.windowCount-gt0-and-not[bool]$wa.obj.falsePassDetected);$clOk=[bool]($cl-and$cl.obj-and[bool]$cl.obj.ok-and[string]$cl.obj.version-match'^RUN_OWNED_UI_CLEANUP_V7_');$igOk=[bool]($ig-and$ig.obj-and[bool]$ig.obj.ok-and[string]$ig.obj.version-match'^INACTIVE_PROCESS_GOVERNOR_V1_R2_')
if(-not$rgOk){$issues.Add('REMOTE_GUARD_NOT_OK')};if(-not$waOk){$issues.Add('WINDOW_UIA_NOT_OK_OR_EMPTY')};if(-not$clOk){$issues.Add('CLEANUP_V7_NOT_OK')};if(-not$igOk){$issues.Add('INACTIVE_R2_NOT_OK')}
$host0=Test-LocalHost;$cdp0=Test-Cdp;$remote0=Test-Remote;if(-not$host0){$issues.Add('LOCAL_HOST_DOWN')};if(-not$cdp0){$issues.Add('CFT_CDP_9224_DOWN')};if(-not$remote0){$issues.Add('REMOTE_DC_OFFLINE')};if($SelfTestRecovery){$issues.Add('SELF_TEST_RECOVERY_TRIGGER')}
$recoveryTriggered=$false;$recoveryExit=$null;$recoveryCooldown=$false
if($issues.Count-gt0-and(Test-Path $RecoveryScript)){$recent=$false;try{if(Test-Path $RecoveryReceipt){$recent=(((Get-Date)-(Get-Item $RecoveryReceipt).LastWriteTime).TotalSeconds-lt120)}}catch{};if($recent-and-not$SelfTestRecovery){$recoveryCooldown=$true}else{try{& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $RecoveryScript -Reason ($issues-join',')|Out-Null;$recoveryExit=$LASTEXITCODE;$recoveryTriggered=$true}catch{$recoveryExit=9}}}
$host1=Test-LocalHost;$cdp1=Test-Cdp;$remote1=Test-Remote
$out=[ordered]@{ok=[bool]($pg.ok-and$rgOk-and$waOk-and$clOk-and$igOk-and$host1-and$cdp1-and$remote1-and$issues.Count-eq0);version=$Version;startedAt=$started;completedAt=(Get-Date).ToString('o');phase='POWER_V6_SCREEN_OFF+REMOTE_V5_SINGLETON+WINDOW_V6_UIA_SAFE+CLEANUP_V7_DEAD_PRUNE+INACTIVE_R2_EXACT_PID';powerGuardOk=[bool]$pg.ok;powerGuardSha=[string]$pg.sha;powerGuardReceiptVersion=[string]$pg.receiptVersion;powerGuardProcessCount=[int]$pg.processCount;powerGuardAc=[bool]$pg.acPower;powerGuardSystemRequiredHeld=[bool]$pg.systemRequiredHeld;powerGuardDisplayRequiredHeld=[bool]$pg.displayRequiredHeld;powerGuardScreenOffAllowed=[bool]$pg.screenOffAllowed;remoteGuardSha=$remoteSha;remoteGuardVersion=$(if($rg-and$rg.obj){[string]$rg.obj.version}else{''});remoteGuardOk=$rgOk;windowActivitySha=$waSha;windowActivityVersion=$(if($wa-and$wa.obj){[string]$wa.obj.version}else{''});windowActivityOk=$waOk;windowCount=$(if($wa-and$wa.obj){[int]$wa.obj.windowCount}else{0});nativeVisibleCount=$(if($wa-and$wa.obj){[int]$wa.obj.nativeVisibleCount}else{0});windowEnumerationErrors=$(if($wa-and$wa.obj){[int]$wa.obj.enumerationErrorCount}else{-1});windowRegistryFlatCount=$(if($wa-and$wa.obj){[int]$wa.obj.registryFlatCount}else{0});windowFalsePass=$(if($wa-and$wa.obj){[bool]$wa.obj.falsePassDetected}else{$true});cleanupSha=$clSha;cleanupVersion=$(if($cl-and$cl.obj){[string]$cl.obj.version}else{''});cleanupOk=$clOk;cleanupRegistryFlatCount=$(if($cl-and$cl.obj){[int]$cl.obj.registryFlatCount}else{0});cleanupClosedCount=$(if($cl-and$cl.obj){[int]$cl.obj.closedCount}else{0});cleanupPrunedCount=$(if($cl-and$cl.obj-and$null-ne$cl.obj.prunedCount){[int]$cl.obj.prunedCount}else{0});inactiveGovernorSha=$igSha;inactiveGovernorVersion=$(if($ig-and$ig.obj){[string]$ig.obj.version}else{''});inactiveGovernorOk=$igOk;inactiveCandidateCount=$(if($ig-and$ig.obj){[int]$ig.obj.candidateCount}else{0});inactiveForcedCount=$(if($ig-and$ig.obj){[int]$ig.obj.forcedCount}else{0});hostOk=$host1;cdp9224Ok=$cdp1;remoteDcOk=$remote1;issues=@($issues);recoveryTriggered=$recoveryTriggered;recoveryExit=$recoveryExit;recoveryCooldown=$recoveryCooldown;policy='SCREEN_CAN_OFF;AC_SYSTEM_SLEEP_BLOCKED;AUTH_VALID_NO_REVERIFY_FOR_TRANSPORT;REMOTE_SINGLETON_MUTEX;UIAUTOMATION_WINDOW_AUDIT;REGISTERED_UI_CLEANUP;DEAD_REGISTRY_AUTO_PRUNE;REGISTERED_TERMINAL_INACTIVE_300S;SHARED_BROWSER_FORCE_KILL_FORBIDDEN;EXACT_NODE_REMOTE_REPAIR'}
$json=$out|ConvertTo-Json -Depth 40;$json|Set-Content -LiteralPath $Receipt -Encoding UTF8;try{$c=Find-Central;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$json|Set-Content -LiteralPath (Join-Path $d 'CENTRAL_TAB_SUPERVISOR_LAST.json') -Encoding UTF8}}catch{};$out|ConvertTo-Json -Depth 40 -Compress;if($out.ok){exit 0}else{exit 4}
