param([switch]$SelfTestRecovery)
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$Version='CENTRAL_AGENT_TAB_SUPERVISOR_V27_EXPIRED_CONTROL_SAFE_20260911'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$CleanupScript=Join-Path $Root 'RunOwnedUiCleanup.ps1'
$RecoveryScript=Join-Path $Root 'CentralTabAutoRecovery.ps1'
$PowerGuardScript=Join-Path $Root 'CentralAgentPowerContinuityGuard.ps1'
$PowerGuardReceipt=Join-Path $Root 'POWER_CONTINUITY_GUARD_LAST.json'
$RemoteGuardScript=Join-Path $Root 'DesktopCommanderKeepAlive.ps1'
$WindowActivityScript=Join-Path $Root 'WindowActivitySupervisor.ps1'
$InactiveGovernorScript=Join-Path $Root 'InactiveProcessGovernor.ps1'
$WorkloadGovernorScript=Join-Path $Root 'WorkloadAdmissionGovernor.ps1'
$FlowDemandScript=Join-Path $Root 'FlowDemandGuard.ps1'
$WatchdogScript=Join-Path $Root 'HomeDesignLocalWatchdog.ps1'
$CloudControlReceipt=Join-Path $Root 'REMOTE_CLOUD_CONTROL_APPLIED.json'
$Receipt=Join-Path $Root 'CENTRAL_TAB_SUPERVISOR_LAST.json'
$RecoveryReceipt=Join-Path $Root 'CENTRAL_TAB_RECOVERY_LAST.json'
$RequiredPowerGuardVersion='POWER_CONTINUITY_GUARD_V8_FAILSAFE_NO_TRUE_SLEEP_20260910'
$RequiredRemoteGuardPattern='^REMOTE_DC_KEEPALIVE_V9_'
$RequiredWorkloadPattern='^WORKLOAD_ADMISSION_GOVERNOR_V3_'
$RequiredFlowPattern='^FLOW_DEMAND_GUARD_V1_'
$Pins=@{
 'local-agent/bootstrap/HomeDesignLocalWatchdog.ps1'=@{commit='352fb3eaa2f50f83533049cbc513cd951dbd0009';sha='d3e91ae2e8e921dce32b7d3171aed6011e64eddb';dest=$WatchdogScript}
 'local-agent/bootstrap/CentralAgentPowerContinuityGuard.ps1'=@{commit='e51cda9f4e8dc960bf4c7485c7e6aaa0c5bee469';sha='a841e22a2405c559aed181e22aef948db4c9acdf';dest=$PowerGuardScript}
 'local-agent/bootstrap/DesktopCommanderKeepAlive.ps1'=@{commit='222060260f475d1dcf45336015d5df17a72f6e7d';sha='65e82f454a78e6f2aa2188040f63764a045562e1';dest=$RemoteGuardScript}
 'local-agent/bootstrap/FlowDemandGuard.ps1'=@{commit='15cf8b4a01a5d0e157289a459f1d102fafb78fe6';sha='64742526c4a32657786aa7aabae999c501c9f673';dest=$FlowDemandScript}
 'local-agent/bootstrap/WindowActivitySupervisor.ps1'=@{commit='95aacd1d1416d6e41906ff6be0b935f8e032ade8';sha='29d260473f3fdbc993b86e0900dc9833bf158609';dest=$WindowActivityScript}
 'local-agent/bootstrap/InactiveProcessGovernor.ps1'=@{commit='5d4cd5171d031c9d8252f03adb06925f5380181f';sha='5a9df27edd089d62f2eaf473a6cbdb984bd287b2';dest=$InactiveGovernorScript}
 'local-agent/bootstrap/WorkloadAdmissionGovernor.ps1'=@{commit='8a8d3a3d1d5fdcb1ce55afb13c9a9579b3ae1b52';sha='89b5889714fcf92855dcadc5b5a573bf694055a6';dest=$WorkloadGovernorScript}
 'local-agent/bootstrap/RunOwnedUiCleanup.ps1'=@{commit='7c7631047ff322ecb8836386c6408f8651304398';sha='c45a7da297c10003850a1ef08faf779b0f5be984';dest=$CleanupScript}
}
function Find-Central{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(-not$d.Root){continue};foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function GitBlob([byte[]]$b){$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Refresh-Pinned([string]$RepoPath){$pin=$Pins[$RepoPath];if(-not$pin){return ''};$dest=[string]$pin.dest;$expected=([string]$pin.sha).ToLowerInvariant();try{$u='https://raw.githubusercontent.com/'+$Repo+'/'+[string]$pin.commit+'/'+$RepoPath;$wc=New-Object Net.WebClient;try{$wc.Headers['User-Agent']='HomeDesign-Supervisor-V25';$b=$wc.DownloadData($u)}finally{$wc.Dispose()};$actual=(GitBlob $b).ToLowerInvariant();if($actual-ne$expected){throw 'PIN_SHA_MISMATCH'};$tmp=$dest+'.v25';[IO.File]::WriteAllBytes($tmp,$b);Move-Item $tmp $dest -Force;return $actual}catch{};try{if(Test-Path $dest){$actual=(GitBlob ([IO.File]::ReadAllBytes($dest))).ToLowerInvariant();if($actual-eq$expected){return $actual}}}catch{};return ''}
function Run-Json([string]$Path,[string[]]$ScriptArgs=@()){$o=[ordered]@{exit=9;obj=$null;raw='';error=''};try{$o.raw=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Path @ScriptArgs 2>&1|Out-String;$o.exit=$LASTEXITCODE;try{$o.obj=$o.raw|ConvertFrom-Json}catch{$lines=@($o.raw-split"`r?`n"|Where-Object{$_.Trim().StartsWith('{')});if($lines.Count){$o.obj=$lines[-1]|ConvertFrom-Json}else{throw}}}catch{$o.error=$_.Exception.Message};return [pscustomobject]$o}
function Test-LocalHost{try{$h=Invoke-RestMethod 'http://127.0.0.1:8765/health' -TimeoutSec 3;return [bool]$h.ok}catch{return $false}}
function Test-Cdp{try{$v=Invoke-RestMethod 'http://127.0.0.1:9224/json/version' -TimeoutSec 3;return [bool]$v.Browser}catch{return $false}}
function Test-Remote{try{$p=@(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{([string]$_.Name)-match'(?i)^node(?:\.exe)?$'-and[string]$_.CommandLine-match'(?i)desktop-commander'-and[string]$_.CommandLine-match'(?i)(?:^|\s)remote(?:\s|$)'});if($p.Count-eq0){return $false};$ids=@($p|ForEach-Object{[int]$_.ProcessId});return (@(Get-NetTCPConnection -State Established -ErrorAction SilentlyContinue|Where-Object{$ids-contains$_.OwningProcess}).Count-gt0)}catch{return $false}}
function Read-PowerReceipt{try{if(Test-Path $PowerGuardReceipt){return Get-Content $PowerGuardReceipt -Raw -Encoding UTF8|ConvertFrom-Json}}catch{};return $null}
function Get-PowerGuardProcs{return @(Get-CimInstance Win32_Process -ErrorAction SilentlyContinue|Where-Object{[string]$_.CommandLine-match'(?i)CentralAgentPowerContinuityGuard\.ps1'})}
function Ensure-PowerGuard{$o=[ordered]@{sha='';ok=$false;processCount=0;receiptVersion='';mode='';remoteLeaseActive=$false;systemRequiredHeld=$false;displayRequiredHeld=$false;screenOffAllowed=$true;trueSleepAllowed=$true;restarted=$false;error=''};try{$o.sha=Refresh-Pinned 'local-agent/bootstrap/CentralAgentPowerContinuityGuard.ps1';if(-not$o.sha){throw 'POWER_GUARD_REFRESH_FAILED'};$rr=Read-PowerReceipt;$procs=@(Get-PowerGuardProcs);$restart=($procs.Count-eq0-or-not$rr-or[string]$rr.version-ne$RequiredPowerGuardVersion);if($restart){foreach($p in $procs){try{Stop-Process -Id ([int]$p.ProcessId) -Force -ErrorAction SilentlyContinue}catch{}};Start-Sleep -Milliseconds 500;Start-Process powershell.exe -ArgumentList @('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',$PowerGuardScript) -WindowStyle Hidden|Out-Null;Start-Sleep -Seconds 3;$o.restarted=$true};$procs=@(Get-PowerGuardProcs);$rr=Read-PowerReceipt;$o.processCount=$procs.Count;if($rr){$o.receiptVersion=[string]$rr.version;$o.mode=[string]$rr.mode;$o.remoteLeaseActive=[bool]$rr.remoteLeaseActive;$o.systemRequiredHeld=[bool]$rr.systemRequiredHeld;$o.displayRequiredHeld=[bool]$rr.displayRequiredHeld;$o.screenOffAllowed=[bool]$rr.screenOffAllowed;$o.trueSleepAllowed=[bool]$rr.trueSleepAllowed;$modeOk=[bool]($o.systemRequiredHeld-and-not$o.trueSleepAllowed-and(((-not$o.remoteLeaseActive)-and-not$o.displayRequiredHeld)-or($o.remoteLeaseActive-and$o.displayRequiredHeld-and-not$o.screenOffAllowed)));$o.ok=[bool]($procs.Count-eq1-and$o.receiptVersion-eq$RequiredPowerGuardVersion-and$modeOk)}}catch{$o.error=$_.Exception.Message};return [pscustomobject]$o}
function Get-CloudControl{
  $o=[ordered]@{valid=$false;requestId='';action='';reason='';alreadyApplied=$false;status='UNREAD';error=''}
  try{
    $u='https://api.github.com/repos/'+$Repo+'/contents/local-agent/control/remote-recovery.json?ref=main&cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()
    $x=Invoke-RestMethod $u -Headers @{'User-Agent'='HomeDesign-Supervisor-V27';'Accept'='application/vnd.github+json'} -TimeoutSec 10
    $j=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String(([string]$x.content-replace'\s','')))|ConvertFrom-Json
    $o.requestId=[string]$j.requestId;$o.action=[string]$j.action;$o.reason=[string]$j.reason
    if([string]$j.device-ne$env:COMPUTERNAME){$o.status='IGNORED_DEVICE_MISMATCH';return [pscustomobject]$o}
    if([string]$j.action-ne'FORCE_REMOTE_RESTART_ONCE'){$o.status='IGNORED_ACTION_NOT_ALLOWED';return [pscustomobject]$o}
    if([datetime]$j.expiresAt-lt(Get-Date).ToUniversalTime()){$o.status='IGNORED_EXPIRED';return [pscustomobject]$o}
    try{if(Test-Path $CloudControlReceipt){$a=Get-Content $CloudControlReceipt -Raw -Encoding UTF8|ConvertFrom-Json;if([string]$a.requestId-eq$o.requestId){$o.alreadyApplied=$true;$o.status='ALREADY_APPLIED';return [pscustomobject]$o}}}catch{}
    $o.valid=$true;$o.status='VALID_PENDING'
  }catch{$o.status='ERROR';$o.error=$_.Exception.Message}
  [pscustomobject]$o
}
$started=(Get-Date).ToString('o');$issues=New-Object System.Collections.Generic.List[string]
$watchdogSha=Refresh-Pinned 'local-agent/bootstrap/HomeDesignLocalWatchdog.ps1';if(-not$watchdogSha){$issues.Add('WATCHDOG_V15_SELF_ROLLOUT_FAILED')}
$pg=Ensure-PowerGuard;if(-not$pg.ok){$issues.Add('POWER_GUARD_FAILSAFE_NOT_HELD')}
$remoteSha=Refresh-Pinned 'local-agent/bootstrap/DesktopCommanderKeepAlive.ps1';$flowSha=Refresh-Pinned 'local-agent/bootstrap/FlowDemandGuard.ps1';$waSha=Refresh-Pinned 'local-agent/bootstrap/WindowActivitySupervisor.ps1';$igSha=Refresh-Pinned 'local-agent/bootstrap/InactiveProcessGovernor.ps1';$wgSha=Refresh-Pinned 'local-agent/bootstrap/WorkloadAdmissionGovernor.ps1';$clSha=Refresh-Pinned 'local-agent/bootstrap/RunOwnedUiCleanup.ps1'
if(-not$remoteSha){$issues.Add('REMOTE_GUARD_REFRESH_FAILED')};if(-not$flowSha){$issues.Add('FLOW_DEMAND_GUARD_REFRESH_FAILED')};if(-not$waSha){$issues.Add('WINDOW_UIA_REFRESH_FAILED')};if(-not$igSha){$issues.Add('INACTIVE_R2_REFRESH_FAILED')};if(-not$wgSha){$issues.Add('WORKLOAD_GOVERNOR_REFRESH_FAILED')};if(-not$clSha){$issues.Add('CLEANUP_V7_REFRESH_FAILED')}
$flow=$(if($flowSha){Run-Json $FlowDemandScript @('-Apply')}else{$null});$flowOk=[bool]($flow-and$flow.obj-and[bool]$flow.obj.ok-and[string]$flow.obj.version-match$RequiredFlowPattern);$flowRequired=[bool]($flowOk-and[bool]$flow.obj.allowOpen);if(-not$flowOk){$issues.Add('FLOW_DEMAND_GUARD_NOT_OK')}
$cloud=Get-CloudControl;$remoteArgs=@();if($cloud.valid-and-not$cloud.alreadyApplied){$remoteArgs=@('-ForceRestart')}
$rg=$(if($remoteSha){Run-Json $RemoteGuardScript $remoteArgs}else{$null});if($cloud.valid-and-not$cloud.alreadyApplied-and$rg-and$rg.obj-and[bool]$rg.obj.restartAttempted){try{[ordered]@{requestId=$cloud.requestId;appliedAt=(Get-Date).ToString('o');action=$cloud.action;reason=$cloud.reason;remoteGuardVersion=[string]$rg.obj.version}|ConvertTo-Json|Set-Content $CloudControlReceipt -Encoding UTF8}catch{}}
$wa=$(if($waSha){Run-Json $WindowActivityScript}else{$null});$wg=$(if($wgSha){Run-Json $WorkloadGovernorScript @('-Apply')}else{$null});$cl=$(if($clSha){Run-Json $CleanupScript}else{$null});$ig=$(if($igSha){Run-Json $InactiveGovernorScript}else{$null})
$rgOk=[bool]($rg-and$rg.obj-and[bool]$rg.obj.ok-and[string]$rg.obj.version-match$RequiredRemoteGuardPattern);$waOk=[bool]($wa-and$wa.obj-and[bool]$wa.obj.ok-and[string]$wa.obj.version-match'^WINDOW_ACTIVITY_SUPERVISOR_V6_'-and[int]$wa.obj.windowCount-gt0-and-not[bool]$wa.obj.falsePassDetected);$wgOk=[bool]($wg-and$wg.obj-and[bool]$wg.obj.ok-and[string]$wg.obj.version-match$RequiredWorkloadPattern);$clOk=[bool]($cl-and$cl.obj-and[bool]$cl.obj.ok-and[string]$cl.obj.version-match'^RUN_OWNED_UI_CLEANUP_V7_');$igOk=[bool]($ig-and$ig.obj-and[bool]$ig.obj.ok-and[string]$ig.obj.version-match'^INACTIVE_PROCESS_GOVERNOR_V1_R2_')
if(-not$rgOk){$issues.Add('REMOTE_GUARD_NOT_OK')};if(-not$waOk){$issues.Add('WINDOW_UIA_NOT_OK_OR_EMPTY')};if(-not$wgOk){$issues.Add('WORKLOAD_ADMISSION_NOT_OK')};if(-not$clOk){$issues.Add('CLEANUP_V7_NOT_OK')};if(-not$igOk){$issues.Add('INACTIVE_R2_NOT_OK')}
$host0=Test-LocalHost;$cdp0=Test-Cdp;$remote0=Test-Remote;if(-not$host0){$issues.Add('LOCAL_HOST_DOWN')};if($flowRequired-and-not$cdp0){$issues.Add('FLOW_REQUIRED_CFT_CDP_9224_DOWN')};if(-not$remote0){$issues.Add('REMOTE_DC_OFFLINE')};if($SelfTestRecovery){$issues.Add('SELF_TEST_RECOVERY_TRIGGER')}
$recoveryTriggered=$false;$recoveryExit=$null;$recoveryCooldown=$false
if($issues.Count-gt0-and(Test-Path $RecoveryScript)){$recent=$false;try{if(Test-Path $RecoveryReceipt){$recent=(((Get-Date)-(Get-Item $RecoveryReceipt).LastWriteTime).TotalSeconds-lt120)}}catch{};if($recent-and-not$SelfTestRecovery){$recoveryCooldown=$true}else{try{& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $RecoveryScript -Reason ($issues-join',')|Out-Null;$recoveryExit=$LASTEXITCODE;$recoveryTriggered=$true}catch{$recoveryExit=9}}}
$host1=Test-LocalHost;$cdp1=Test-Cdp;$remote1=Test-Remote;$cdpEffective=[bool]((-not$flowRequired)-or$cdp1)
$out=[ordered]@{ok=[bool]($pg.ok-and$flowOk-and$rgOk-and$waOk-and$wgOk-and$clOk-and$igOk-and$host1-and$cdpEffective-and$remote1-and$issues.Count-eq0);version=$Version;startedAt=$started;completedAt=(Get-Date).ToString('o');phase='WATCHDOG_V15_SELF_ROLLOUT;POWER_V8;REMOTE_V9_THROW_TOKEN_FIX+CLOUD_ONESHOT;FLOW_DEMAND_V1;WINDOW_V6;WORKLOAD_V3;CLEANUP_V7;INACTIVE_R2';watchdogV15Sha=$watchdogSha;powerGuardOk=[bool]$pg.ok;powerGuardSha=[string]$pg.sha;powerGuardReceiptVersion=[string]$pg.receiptVersion;powerGuardSystemRequiredHeld=[bool]$pg.systemRequiredHeld;powerGuardDisplayRequiredHeld=[bool]$pg.displayRequiredHeld;remoteGuardSha=$remoteSha;remoteGuardVersion=$(if($rg-and$rg.obj){[string]$rg.obj.version}else{''});remoteGuardOk=$rgOk;remotePreflightDecision=$(if($rg-and$rg.obj){[string]$rg.obj.postflightDecision}else{''});remoteRestartAttempted=$(if($rg-and$rg.obj){[bool]$rg.obj.restartAttempted}else{$false});remoteChainRootCount=$(if($rg-and$rg.obj){[int]$rg.obj.remoteChainRootCountAfter}else{0});remoteHumanGate=$(if($rg-and$rg.obj){[bool]$rg.obj.humanGate}else{$false});remoteSessionRestored=$(if($rg-and$rg.obj){[bool]$rg.obj.sessionRestored}else{$false});cloudControlRequestId=[string]$cloud.requestId;cloudControlValid=[bool]$cloud.valid;cloudControlAlreadyApplied=[bool]$cloud.alreadyApplied;cloudControlStatus=[string]$cloud.status;cloudControlError=[string]$cloud.error;flowDemandGuardSha=$flowSha;flowDemandGuardOk=$flowOk;flowDemandDecision=$(if($flow-and$flow.obj){[string]$flow.obj.decision}else{''});flowRuntimeRequired=$flowRequired;flowActiveDemand=$(if($flow-and$flow.obj){[int]$flow.obj.activeFlowDemand}else{0});flowFreshDemand=$(if($flow-and$flow.obj){[int]$flow.obj.freshFlowDemand}else{0});windowActivityOk=$waOk;workloadGovernorOk=$wgOk;workloadAdmissionAfter=$(if($wg-and$wg.obj){[string]$wg.obj.admissionAfter.level}else{''});automationDuplicatePressureAfter=$(if($wg-and$wg.obj){[int]$wg.obj.duplicateWindowsAfter.automationDuplicatePressure}else{0});cleanupOk=$clOk;inactiveGovernorOk=$igOk;hostOk=$host1;cdp9224RawOk=$cdp1;cdp9224Required=$flowRequired;cdp9224EffectiveOk=$cdpEffective;remoteDcOk=$remote1;issues=@($issues);recoveryTriggered=$recoveryTriggered;recoveryExit=$recoveryExit;recoveryCooldown=$recoveryCooldown;policy='CLOUD_CONTROL_IS_FIXED_ONE_SHOT_REMOTE_RESTART_ONLY;NO_ARBITRARY_COMMAND;LOCAL_PREFLIGHT_STILL_REQUIRED;FLOW_CDP_DEMAND_GATED;USER_WINDOWS_PROTECTED;USER_WINDOW_CLOSE_OR_FOCUS_CHANGE_IS_NOT_REMOTE_FAILURE;NO_BROAD_KILL'}
$json=$out|ConvertTo-Json -Depth 50;$json|Set-Content -LiteralPath $Receipt -Encoding UTF8;try{$c=Find-Central;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$json|Set-Content -LiteralPath (Join-Path $d 'CENTRAL_TAB_SUPERVISOR_LAST.json') -Encoding UTF8}}catch{};$out|ConvertTo-Json -Depth 50 -Compress;if($out.ok){exit 0}else{exit 4}
