param([switch]$SelfTest)
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$Version='INACTIVE_PROCESS_GOVERNOR_V2_5M_EXACT_PID_20260909'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$StatePath=Join-Path $Root 'WINDOW_ACTIVITY_STATE.json'
$Receipt=Join-Path $Root 'INACTIVE_PROCESS_GOVERNOR_LAST.json'
$InactiveSec=300
$ExitWaitSec=7
$TerminalStates='(?i)^(COMPLETE|COMPLETED|DONE|CLOSED|STALE|SUPERSEDED|ABANDONED|EXPIRED|FAILED|CANCELLED|CANCELED)$'
$SharedProcess='(?i)^(chrome|msedge|chatgpt|googledrivefs|codex|explorer|dwm|taskmgr|commonagent|phoneexperiencehost|textinputhost|searchhost|startmenuexperiencehost|shellexperiencehost)$'
$ProtectedCmd='(?i)desktop-commander|HomeDesignLocalWatchdog|CentralAgent(Tab|Power|Auto)|CentralTabAutoRecovery|AgentBootstrap|PowerContinuity|GoogleDriveFS|codex'
Add-Type -AssemblyName UIAutomationClient,UIAutomationTypes -ErrorAction SilentlyContinue
function Save-Json([string]$Path,$Object){try{$Object|ConvertTo-Json -Depth 50|Set-Content -LiteralPath $Path -Encoding UTF8}catch{}}
function Get-ProcMeta([int]$TargetPid){try{$c=Get-CimInstance Win32_Process -Filter ('ProcessId='+$TargetPid) -ErrorAction Stop;$p=Get-Process -Id $TargetPid -ErrorAction Stop;return [pscustomobject]@{pid=$TargetPid;name=[string]$p.ProcessName;startUtc=$(try{$p.StartTime.ToUniversalTime().ToString('o')}catch{''});cmd=[string]$c.CommandLine;mainHwnd=[int64]$p.MainWindowHandle;hasExited=$false}}catch{return $null}}
function Is-Protected($Meta){if(-not$Meta){return $true};if([string]$Meta.name-match$SharedProcess){return $true};if([string]$Meta.cmd-match$ProtectedCmd){return $true};return $false}
function Same-Start($Meta,[string]$Expected){if(-not$Expected){return $true};try{return ([datetime]::Parse($Meta.startUtc).ToUniversalTime()-eq[datetime]::Parse($Expected).ToUniversalTime())}catch{return $false}}
function Close-UiaExact([int64]$Hwnd,[int]$TargetPid){try{$e=[System.Windows.Automation.AutomationElement]::FromHandle([IntPtr]$Hwnd);if(-not$e){return [pscustomobject]@{sent=$false;closed=$true;state='ALREADY_CLOSED'}};$actual=0;try{$actual=[int]$e.Current.ProcessId}catch{};if($actual-ne$TargetPid){return [pscustomobject]@{sent=$false;closed=$false;state='PID_MISMATCH_PROTECTED'}};$pat=$e.GetCurrentPattern([System.Windows.Automation.WindowPattern]::Pattern);$pat.Close();Start-Sleep -Milliseconds 700;$left=$null;try{$left=[System.Windows.Automation.AutomationElement]::FromHandle([IntPtr]$Hwnd)}catch{};return [pscustomobject]@{sent=$true;closed=($null-eq$left);state=$(if($null-eq$left){'UIA_CLOSED'}else{'UIA_CLOSE_SENT_STILL_VISIBLE'})}}catch{return [pscustomobject]@{sent=$false;closed=$false;state=('UIA_ERROR:'+$_.Exception.Message)}}}
function Stop-Owned([int]$TargetPid,[int64]$Hwnd,[string]$ExpectedStart,[bool]$ForceEligible,[string]$Reason){$r=[ordered]@{pid=$TargetPid;hwnd=$Hwnd;reason=$Reason;gracefulSent=$false;gracefulExited=$false;forceEligible=$ForceEligible;forced=$false;exited=$false;state='';protected=$false};$m=Get-ProcMeta $TargetPid;if(-not$m){$r.exited=$true;$r.state='ALREADY_EXITED';return [pscustomobject]$r};if(-not(Same-Start $m $ExpectedStart)){$r.state='PID_REUSE_OR_START_MISMATCH';$r.protected=$true;return [pscustomobject]$r};if(Is-Protected $m){$r.protected=$true;$x=Close-UiaExact $Hwnd $TargetPid;$r.gracefulSent=[bool]$x.sent;$r.gracefulExited=[bool]$x.closed;$r.exited=[bool]$x.closed;$r.state='SHARED_OR_PROTECTED_'+[string]$x.state;return [pscustomobject]$r};try{$p=Get-Process -Id $TargetPid -ErrorAction Stop;$r.gracefulSent=[bool]$p.CloseMainWindow();try{$r.gracefulExited=[bool]$p.WaitForExit($ExitWaitSec*1000)}catch{} }catch{};if($r.gracefulExited){$r.exited=$true;$r.state='GRACEFUL_EXIT';return [pscustomobject]$r};if(-not$ForceEligible){$r.state='GRACEFUL_FAILED_FORCE_NOT_ELIGIBLE';return [pscustomobject]$r};$m2=Get-ProcMeta $TargetPid;if(-not$m2){$r.exited=$true;$r.state='EXITED_DURING_WAIT';return [pscustomobject]$r};if(-not(Same-Start $m2 $ExpectedStart)-or(Is-Protected $m2)){$r.protected=$true;$r.state='RECHECK_PROTECTED_OR_PID_REUSE';return [pscustomobject]$r};try{Stop-Process -Id $TargetPid -Force -ErrorAction Stop;$r.forced=$true;Start-Sleep -Milliseconds 500;$r.exited=(-not[bool](Get-Process -Id $TargetPid -ErrorAction SilentlyContinue));$r.state=$(if($r.exited){'FORCED_EXACT_PID_EXIT'}else{'FORCE_SENT_STILL_RUNNING'})}catch{$r.state='FORCE_ERROR:'+$_.Exception.Message};return [pscustomobject]$r}
function Resource-Snapshot{$os=Get-CimInstance Win32_OperatingSystem -ErrorAction SilentlyContinue;$cpu=Get-CimInstance Win32_Processor -ErrorAction SilentlyContinue|Measure-Object LoadPercentage -Average;[pscustomobject]@{time=(Get-Date).ToString('o');cpuPct=[math]::Round([double]$cpu.Average,1);memoryUsedPct=$(if($os){[math]::Round((1-($os.FreePhysicalMemory/$os.TotalVisibleMemorySize))*100,1)}else{$null});freeMb=$(if($os){[math]::Round($os.FreePhysicalMemory/1024,0)}else{$null});processCount=@(Get-Process -ErrorAction SilentlyContinue).Count}}
function Run-SelfTest{$tests=@();for($i=1;$i-le2;$i++){$code="Add-Type -AssemblyName System.Windows.Forms; `$f=New-Object System.Windows.Forms.Form; `$f.Text='CENTRAL_AGENT_ENDTASK_SELFTEST_$i'; `$f.Width=420; `$f.Height=160; `$f.Add_FormClosing({param(`$s,`$e);`$e.Cancel=`$true}); [void]`$f.ShowDialog()";$enc=[Convert]::ToBase64String([Text.Encoding]::Unicode.GetBytes($code));$p=Start-Process powershell.exe -ArgumentList @('-NoProfile','-STA','-WindowStyle','Hidden','-EncodedCommand',$enc) -PassThru;$deadline=(Get-Date).AddSeconds(8);do{Start-Sleep -Milliseconds 200;$p.Refresh()}while($p.MainWindowHandle-eq0-and(Get-Date)-lt$deadline);$start=$(try{$p.StartTime.ToUniversalTime().ToString('o')}catch{''});$x=Stop-Owned $p.Id ([int64]$p.MainWindowHandle) $start $true ('SELFTEST_'+$i);$tests+=$x;if(-not$x.exited){try{Stop-Process -Id $p.Id -Force -ErrorAction SilentlyContinue}catch{}}};return $tests}
$before=Resource-Snapshot
if($SelfTest){$t=Run-SelfTest;$after=Resource-Snapshot;$ok=(@($t|Where-Object{$_.exited}).Count-eq2-and@($t|Where-Object{$_.forced}).Count-eq2);$out=[ordered]@{ok=$ok;version=$Version;mode='SELFTEST';tests=$t;protectedNames=@(Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.ProcessName-match$SharedProcess}|Select-Object -ExpandProperty ProcessName -Unique);resourceBefore=$before;resourceAfter=$after;policy='GRACEFUL_THEN_EXACT_PID_FORCE;SHARED_PROCESS_NEVER_FORCE'};Save-Json $Receipt $out;$out|ConvertTo-Json -Depth 20 -Compress;if($ok){exit 0}else{exit 4}}
$state=$null;try{if(Test-Path $StatePath){$state=Get-Content $StatePath -Raw -Encoding UTF8|ConvertFrom-Json}}catch{}
$results=@();$candidates=@();$now=[datetime]::UtcNow
if($state-and$state.windows){foreach($w in @($state.windows)){try{$age=($now-[datetime]::Parse([string]$w.lastChangedUtc).ToUniversalTime()).TotalSeconds}catch{$age=0};$terminal=([string]$w.registeredState-match$TerminalStates);$candidate=[bool]($w.registered-and$terminal-and-not[bool]$w.foreground-and[int]$w.unchangedSamples-ge1-and$age-ge$InactiveSec);if($candidate){$candidates+=$w;$results+=Stop-Owned ([int]$w.pid) ([int64]$w.hwnd) ([string]$w.processStartUtc) $true 'REGISTERED_TERMINAL_INACTIVE_5M'}}}
$after=Resource-Snapshot
$out=[ordered]@{ok=$true;version=$Version;mode='RUNTIME';time=(Get-Date).ToString('o');inactiveSec=$InactiveSec;candidateCount=$candidates.Count;resultCount=$results.Count;forcedCount=@($results|Where-Object{$_.forced}).Count;exitedCount=@($results|Where-Object{$_.exited}).Count;protectedSharedCount=@($results|Where-Object{$_.protected}).Count;results=$results;resourceBefore=$before;resourceAfter=$after;policy='ONLY_REGISTERED_TERMINAL+INACTIVE>=300S+UNCHANGED;GRACEFUL_7S_THEN_EXACT_PID_FORCE;SHARED/PROTECTED_PROCESS_FORCE_KILL_FORBIDDEN'}
Save-Json $Receipt $out;$out|ConvertTo-Json -Depth 30 -Compress;exit 0