param([string]$BeforeReopenFamily='')
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$Version='WINDOW_ACTIVITY_SUPERVISOR_V5_UIA_AUTH_TTL10M_20260909'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$StatePath=Join-Path $Root 'WINDOW_ACTIVITY_STATE.json'
$Receipt=Join-Path $Root 'WINDOW_ACTIVITY_LAST.json'
$CaptureDir=Join-Path $Root 'WindowActivity'
$Registry=Join-Path $Root 'RUN_OWNED_UI_REGISTRY.json'
$VisualIntervalSec=600
$AuthWindowTtlSec=600
$StaleSamples=2
New-Item -ItemType Directory -Force -Path $Root,$CaptureDir|Out-Null
Add-Type -AssemblyName System.Windows.Forms -ErrorAction SilentlyContinue
Add-Type -AssemblyName System.Drawing -ErrorAction SilentlyContinue
Add-Type -AssemblyName UIAutomationClient,UIAutomationTypes -ErrorAction SilentlyContinue
function Save-Json([string]$Path,$Object){try{$Object|ConvertTo-Json -Depth 50|Set-Content -LiteralPath $Path -Encoding UTF8}catch{}}
function Sha256-Bytes([byte[]]$Bytes){$s=[Security.Cryptography.SHA256]::Create();try{return (($s.ComputeHash($Bytes)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Bitmap-Hash($Bitmap){try{$ms=New-Object IO.MemoryStream;try{$Bitmap.Save($ms,[System.Drawing.Imaging.ImageFormat]::Png);return Sha256-Bytes $ms.ToArray()}finally{$ms.Dispose()}}catch{return ''}}
function Family-FromTitle([string]$Title){if($Title-match'(?i)Desktop Commander Remote MCP|mcp\.desktopcommander\.app.*verify'){return'REMOTE_DC_AUTH'};if($Title-match'(?i)(네이버|NAVER).*(로그인|인증|QR|계정)|(?:로그인|인증|QR).*(네이버|NAVER)'){return'NAVER_AUTH'};if($Title-match'(?i)NICE|나이스|본인.?인증|휴대폰.?인증|아이핀|i-?PIN'){return'NICE_AUTH'};if($Title-match'(?i)Google 계정|Sign in.*Google|Google Accounts|accounts\.google'){return'GOOGLE_AUTH'};if($Title-match'(?i)(카카오|Kakao).*(로그인|인증|계정)|(?:로그인|인증).*(카카오|Kakao)'){return'KAKAO_AUTH'};return''}
function Rect-Intersect([int]$l1,[int]$t1,[int]$r1,[int]$b1,[int]$l2,[int]$t2,[int]$r2,[int]$b2){$l=[math]::Max($l1,$l2);$t=[math]::Max($t1,$t2);$r=[math]::Min($r1,$r2);$b=[math]::Min($b1,$b2);if($r-le$l-or$b-le$t){return $null};return [System.Drawing.Rectangle]::FromLTRB($l,$t,$r,$b)}
function Get-Uia([int64]$Hwnd){try{return [System.Windows.Automation.AutomationElement]::FromHandle([IntPtr]$Hwnd)}catch{return $null}}
function Close-Exact([int64]$Hwnd,[string]$ExpectedFamily){try{$e=Get-Uia $Hwnd;if(-not$e){return [pscustomobject]@{closed=$true;state='ALREADY_CLOSED'}};$title=[string]$e.Current.Name;$fam=Family-FromTitle $title;if($ExpectedFamily-and$fam-ne$ExpectedFamily){return [pscustomobject]@{closed=$false;state='FAMILY_MISMATCH_PROTECTED'}};$pat=$e.GetCurrentPattern([System.Windows.Automation.WindowPattern]::Pattern);$pat.Close();Start-Sleep -Milliseconds 700;$left=Get-Uia $Hwnd;return [pscustomobject]@{closed=($null-eq$left);state=$(if($null-eq$left){'CLOSED_EXACT_UIA'}else{'CLOSE_SENT_STILL_VISIBLE'})}}catch{return [pscustomobject]@{closed=$false;state=('ERROR:'+$_.Exception.Message)}}}
function Find-Central{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(-not$d.Root){continue};foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return''}
$prev=$null;try{if(Test-Path $StatePath){$prev=Get-Content $StatePath -Raw -Encoding UTF8|ConvertFrom-Json}}catch{};$prevByKey=@{};if($prev-and$prev.windows){foreach($w in @($prev.windows)){$prevByKey[[string]$w.key]=$w}}
$registryItems=@();try{if(Test-Path $Registry){$registryItems=@(Get-Content $Registry -Raw -Encoding UTF8|ConvertFrom-Json)}}catch{};$registeredHwnd=@{};foreach($ri in $registryItems){try{if([int64]$ri.hwnd-gt0){$registeredHwnd[[string][int64]$ri.hwnd]=$ri}}catch{}}
$virtual=[System.Windows.Forms.SystemInformation]::VirtualScreen;$fullBmp=$null;$fullGraphics=$null;try{$fullBmp=New-Object System.Drawing.Bitmap($virtual.Width,$virtual.Height);$fullGraphics=[System.Drawing.Graphics]::FromImage($fullBmp);$fullGraphics.CopyFromScreen($virtual.Left,$virtual.Top,0,0,$fullBmp.Size)}catch{}
$windows=New-Object System.Collections.Generic.List[object]
foreach($p in @(Get-Process -ErrorAction SilentlyContinue|Where-Object{$_.MainWindowHandle-ne0-and-not[string]::IsNullOrWhiteSpace($_.MainWindowTitle)})){
 try{$hw=[int64]$p.MainWindowHandle;$e=Get-Uia $hw;if(-not$e){continue};$br=$e.Current.BoundingRectangle;if($br.Width-lt120-or$br.Height-lt80){continue};$title=[string]$e.Current.Name;if([string]::IsNullOrWhiteSpace($title)){$title=[string]$p.MainWindowTitle};$family=Family-FromTitle $title;$key=([string]$p.Id+':'+[string]$hw);$l=[int][math]::Round($br.X);$t=[int][math]::Round($br.Y);$r=$l+[int][math]::Round($br.Width);$b=$t+[int][math]::Round($br.Height);$contentHash='';$shouldHash=($family-ne''-or$p.ProcessName-match'(?i)chrome|msedge|powershell|pwsh|cmd|windowsterminal');if($shouldHash-and$fullBmp){$ix=Rect-Intersect $l $t $r $b $virtual.Left $virtual.Top ($virtual.Left+$virtual.Width) ($virtual.Top+$virtual.Height);if($ix){try{$rel=New-Object System.Drawing.Rectangle(($ix.Left-$virtual.Left),($ix.Top-$virtual.Top),$ix.Width,$ix.Height);$crop=$fullBmp.Clone($rel,$fullBmp.PixelFormat);try{$contentHash=Bitmap-Hash $crop}finally{$crop.Dispose()}}catch{}}};$shape=Sha256-Bytes ([Text.Encoding]::UTF8.GetBytes(($title+'|'+$l+'|'+$t+'|'+$r+'|'+$b+'|'+$family)));$nowIso=(Get-Date).ToUniversalTime().ToString('o');$first=$nowIso;$last=$nowIso;$unchanged=0;if($prevByKey.ContainsKey($key)){$old=$prevByKey[$key];$first=[string]$old.firstSeenUtc;if([string]$old.shapeHash-eq$shape-and(([string]$old.contentHash-eq$contentHash)-or-not$contentHash)){$unchanged=[int]$old.unchangedSamples+1;$last=[string]$old.lastChangedUtc}};$reg=$null;if($registeredHwnd.ContainsKey([string]$hw)){$reg=$registeredHwnd[[string]$hw]};$windows.Add([pscustomobject][ordered]@{key=$key;pid=[int]$p.Id;hwnd=$hw;process=[string]$p.ProcessName;processStartUtc=$(try{$p.StartTime.ToUniversalTime().ToString('o')}catch{''});title=$title;family=$family;left=$l;top=$t;right=$r;bottom=$b;foreground=[bool]$e.Current.HasKeyboardFocus;shapeHash=$shape;contentHash=$contentHash;unchangedSamples=$unchanged;firstSeenUtc=$first;lastChangedUtc=$last;registered=[bool]($null-ne$reg);registeredState=$(if($reg){[string]$reg.state}else{''});registeredOwner=$(if($reg){[string]$reg.owner}else{''})})}catch{}
}
$nowUtc=(Get-Date).ToUniversalTime();$visualDue=$true;try{if($prev.lastVisualCaptureUtc){$visualDue=(($nowUtc-[datetime]::Parse([string]$prev.lastVisualCaptureUtc).ToUniversalTime()).TotalSeconds-ge$VisualIntervalSec)}}catch{};$captures=@();if($visualDue-and$fullBmp){$screens=@([System.Windows.Forms.Screen]::AllScreens);$idx=0;foreach($s in $screens){$idx++;$b=$s.Bounds;$rel=New-Object System.Drawing.Rectangle(($b.Left-$virtual.Left),($b.Top-$virtual.Top),$b.Width,$b.Height);try{$shot=$fullBmp.Clone($rel,$fullBmp.PixelFormat);try{$rawHash=Bitmap-Hash $shot;$g=[System.Drawing.Graphics]::FromImage($shot);try{foreach($w in @($windows|Where-Object{$_.family-ne''})){$ix=Rect-Intersect $w.left $w.top $w.right $w.bottom $b.Left $b.Top $b.Right $b.Bottom;if($ix){$mask=New-Object System.Drawing.Rectangle(($ix.Left-$b.Left),($ix.Top-$b.Top),$ix.Width,$ix.Height);$g.FillRectangle([System.Drawing.Brushes]::Gray,$mask)}}}finally{$g.Dispose()};$last=Join-Path $CaptureDir ("MONITOR_${idx}_LAST.png");$old=Join-Path $CaptureDir ("MONITOR_${idx}_PREV.png");if(Test-Path $last){Copy-Item $last $old -Force};$shot.Save($last,[System.Drawing.Imaging.ImageFormat]::Png);$captures+=[pscustomobject]@{monitor=$idx;bounds=$b.ToString();rawHash=$rawHash;maskedPath=$last;masked=$true}}finally{$shot.Dispose()}}catch{}}};if($fullGraphics){$fullGraphics.Dispose()};if($fullBmp){$fullBmp.Dispose()}
$closed=@();$expiredSingle=@();$stale=@();$duplicateFamilies=@();foreach($grp in @($windows|Where-Object{$_.family-ne''}|Group-Object family)){$arr=@($grp.Group);if($arr.Count-gt1){$duplicateFamilies+=$grp.Name;$canonical=@($arr|Where-Object{$_.foreground}|Select-Object -First 1);if($canonical.Count-eq0){$canonical=@($arr|Sort-Object @{Expression={try{[datetime]$_.firstSeenUtc}catch{[datetime]::MinValue}};Descending=$true}|Select-Object -First 1)};$c=$canonical[0];foreach($w in $arr){if($w.hwnd-eq$c.hwnd){continue};$age=0;try{$age=($nowUtc-[datetime]::Parse([string]$w.firstSeenUtc).ToUniversalTime()).TotalSeconds}catch{};$older=$false;try{$older=([datetime]$w.firstSeenUtc-lt[datetime]$c.firstSeenUtc)}catch{};$inactive=([int]$w.unchangedSamples-ge1-and-not[bool]$w.foreground);if($age-ge$AuthWindowTtlSec-or$older-or$inactive){$x=Close-Exact ([int64]$w.hwnd) ([string]$w.family);$closed+=[pscustomobject]@{family=$grp.Name;hwnd=$w.hwnd;pid=$w.pid;reason=$(if($age-ge$AuthWindowTtlSec){'AUTH_TTL_EXPIRED_10M'}else{'SUPERSEDED_STALE_DUPLICATE'});ageSec=[math]::Round($age,0);closeState=$x.state;closed=$x.closed}}}}elseif($arr.Count-eq1){$w=$arr[0];$age=0;try{$age=($nowUtc-[datetime]::Parse([string]$w.firstSeenUtc).ToUniversalTime()).TotalSeconds}catch{};if($age-ge$AuthWindowTtlSec){$x=Close-Exact ([int64]$w.hwnd) ([string]$w.family);$rec=[pscustomobject]@{family=$w.family;hwnd=$w.hwnd;pid=$w.pid;reason='SINGLE_AUTH_TTL_EXPIRED_10M';ageSec=[math]::Round($age,0);foreground=$w.foreground;closeState=$x.state;closed=$x.closed};$expiredSingle+=$rec;$closed+=$rec}elseif([int]$w.unchangedSamples-ge$StaleSamples){$stale+=[pscustomobject]@{family=$w.family;hwnd=$w.hwnd;pid=$w.pid;reason='WAIT_AUTH_TTL_LT10M';ageSec=[math]::Round($age,0)}}}}
$preReopenClosed=@();if($BeforeReopenFamily){$target=$BeforeReopenFamily.ToUpperInvariant();foreach($w in @($windows|Where-Object{([string]$_.family).ToUpperInvariant()-eq$target})){$x=Close-Exact ([int64]$w.hwnd) ([string]$w.family);$preReopenClosed+=[pscustomobject]@{family=$w.family;hwnd=$w.hwnd;pid=$w.pid;reason='PRE_REOPEN_CLOSE_OLD_WINDOW';closeState=$x.state;closed=$x.closed}}}
$remainingDup=0;foreach($grp in @($windows|Where-Object{$_.family-ne''}|Group-Object family)){$alive=@($grp.Group|Where-Object{Get-Uia ([int64]$_.hwnd)});if($alive.Count-gt1){$remainingDup++}};$ttlCloseFailures=@($expiredSingle|Where-Object{-not$_.closed}).Count;$nowText=$nowUtc.ToString('s')+'Z';$lastCaptureText='';if($visualDue){$lastCaptureText=$nowText}elseif($prev){$lastCaptureText=[string]$prev.lastVisualCaptureUtc};$state=[ordered]@{version=$Version;timeUtc=$nowText;lastVisualCaptureUtc=$lastCaptureText;windows=$windows.ToArray();captures=$captures};Save-Json $StatePath $state
$out=[ordered]@{ok=($remainingDup-eq0-and$ttlCloseFailures-eq0);version=$Version;time=(Get-Date).ToString('o');visualDue=$visualDue;monitorCount=@([System.Windows.Forms.Screen]::AllScreens).Count;captureCount=$captures.Count;captures=$captures;windowCount=$windows.Count;authWindowCount=@($windows|Where-Object{$_.family-ne''}).Count;authWindowTtlSec=$AuthWindowTtlSec;duplicateFamilies=@($duplicateFamilies|Sort-Object -Unique);duplicateFamiliesRemaining=$remainingDup;closedSuperseded=@($closed);closedSupersededCount=@($closed|Where-Object{$_.closed}).Count;expiredSingleAuth=@($expiredSingle);expiredSingleAuthCount=@($expiredSingle|Where-Object{$_.closed}).Count;ttlCloseFailures=$ttlCloseFailures;staleBeforeTtl=@($stale);preReopenFamily=$BeforeReopenFamily;preReopenClosed=@($preReopenClosed);activityRule='VISIBLE!=WORKING;UIAUTOMATION_MAINWINDOW+PIXEL_HASH+KEYBOARD_FOCUS+FIRST_SEEN';closeRule='AUTH_HARD_TTL_600S;SINGLE_OR_DUPLICATE_EXPIRED_UIA_EXACT_WINDOW_CLOSE;WAITING_USER_NOT_INDEFINITE';capturePolicy='ALL_MONITORS_10M;MASK_AUTH_WINDOWS;KEEP_LAST_PREV'};$json=$out|ConvertTo-Json -Depth 50;$json|Set-Content -LiteralPath $Receipt -Encoding UTF8;try{$c=Find-Central;if($c){$d=Join-Path $c 'Runtime_Readback\WindowActivity';New-Item -ItemType Directory -Force -Path $d|Out-Null;$json|Set-Content -LiteralPath (Join-Path $d 'WINDOW_ACTIVITY_LAST.json') -Encoding UTF8;foreach($cap in $captures){$idx=[int]$cap.monitor;$src=[string]$cap.maskedPath;$dst=Join-Path $d ("MONITOR_${idx}_LAST.png");$old=Join-Path $d ("MONITOR_${idx}_PREV.png");if(Test-Path $dst){Copy-Item $dst $old -Force};if(Test-Path $src){Copy-Item $src $dst -Force}}}}catch{};$out|ConvertTo-Json -Depth 50 -Compress;if($out.ok){exit 0}else{exit 4}
