param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$AgentVersion='1.1.29'
$HostVersion='1.2.4'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$Root=Join-Path $Base 'LocalAgent'
$ExtensionRoot=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge'
$UserData=Join-Path $Base 'ChromeUserData'
$CftRoot=Join-Path $Base 'ChromeForTesting'
$BackupRoot=Join-Path $Root 'Backups'
$StateFile=Join-Path $Root 'state.json'
$ReadbackFile=Join-Path $Root 'VIDEO_LOCAL_RUNTIME_READBACK.json'
$RecoveryFile=Join-Path $Root 'AGENT_1.1.29_RECOVERY.json'
$HostFile=Join-Path $Root 'HomeDesignLocalCommandHost.ps1'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$HostUrl='https://raw.githubusercontent.com/8friend8ship-cloud/notebooklm-webapp-bridge/main/local-agent/releases/1.2.4/HomeDesignLocalCommandHost.ps1'
$HostExpected='01cee0022b14748f638ee245d8632c1ff3ecde6e'
New-Item -ItemType Directory -Force -Path $Root,$ExtensionRoot,$BackupRoot|Out-Null

function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[] ($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function ReadJson([string]$Path){if(-not(Test-Path -LiteralPath $Path)){return $null};try{return Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{return $null}}
function HostHealth{try{return Invoke-RestMethod -Uri 'http://127.0.0.1:8765/health' -Method Get -TimeoutSec 3}catch{return $null}}
function RefreshVerified([string]$Url,[string]$Path,[string]$Expected){$tmp=$Path+'.download';Invoke-WebRequest -UseBasicParsing -Uri ($Url+'?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -OutFile $tmp -TimeoutSec 30;$actual=(GitBlobSha1 $tmp).ToLowerInvariant();if($actual -ne $Expected.ToLowerInvariant()){Remove-Item -LiteralPath $tmp -Force -ErrorAction SilentlyContinue;throw "SHA_MISMATCH path=$Path actual=$actual expected=$Expected"};Move-Item -LiteralPath $tmp -Destination $Path -Force}
function StopHost{try{foreach($p in @(Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -match 'HomeDesignLocalCommandHost'})){try{& taskkill.exe /PID ([int]$p.ProcessId) /T /F 2>$null|Out-Null}catch{}}}catch{}}
function StartHost124{$args=@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',('"'+$HostFile+'"'));Start-Process powershell.exe -ArgumentList $args -WindowStyle Hidden|Out-Null;$deadline=(Get-Date).AddSeconds(20);do{Start-Sleep -Milliseconds 500;$h=HostHealth;if($h -and [bool]$h.ok -and [string]$h.version -eq $HostVersion -and [bool]$h.asyncJobs){return $h}}while((Get-Date)-lt $deadline);throw 'HOST_1.2.4_START_FAILED'}
function EnsureHost124{$h=HostHealth;if($h -and [bool]$h.ok -and [string]$h.version -eq $HostVersion -and [bool]$h.asyncJobs){return [ordered]@{ok=$true;changed=$false;beforeVersion=[string]$h.version;afterVersion=[string]$h.version;healthy=$true;asyncJobs=$true}};$before=$(if($h){[string]$h.version}else{''});RefreshVerified $HostUrl $HostFile $HostExpected;StopHost;Start-Sleep -Milliseconds 700;$after=StartHost124;return [ordered]@{ok=$true;changed=$true;beforeVersion=$before;afterVersion=[string]$after.version;healthy=[bool]$after.ok;asyncJobs=[bool]$after.asyncJobs}}
function Dedicated{try{return @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like "*$UserData*"})}catch{return @()}}
function StopDedicated{foreach($p in @(Dedicated)){try{Stop-Process -Id ([int]$p.ProcessId) -Force -ErrorAction SilentlyContinue}catch{}};Start-Sleep -Seconds 1}
function FindChrome{if(-not(Test-Path -LiteralPath $CftRoot)){return $null};return Get-ChildItem -LiteralPath $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction SilentlyContinue|Sort-Object FullName -Descending|Select-Object -First 1}
function LaunchDedicated([string]$Front){$c=FindChrome;if(-not $c){throw 'CHROME_FOR_TESTING_NOT_FOUND'};$args=@("--user-data-dir=$UserData",'--profile-directory=Default',"--load-extension=$ExtensionRoot",'--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',$Front);$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$c.FullName;$psi.WorkingDirectory=$c.Directory.FullName;$psi.UseShellExecute=$false;$psi.Arguments=($args|ForEach-Object{if($_ -match '\s'){'"'+$_+'"'}else{$_}})-join ' ';[void][Diagnostics.Process]::Start($psi);$deadline=(Get-Date).AddSeconds(12);do{Start-Sleep -Milliseconds 500;if((Dedicated).Count -gt 0){return}}while((Get-Date)-lt $deadline);throw 'DEDICATED_CHROME_START_FAILED'}
function GetRelease{$url='https://raw.githubusercontent.com/'+$Repo+'/main/runtime/stable/release.json?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();$r=(Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 10).Content|ConvertFrom-Json;if(-not $r.enabled){throw 'BRIDGE_STABLE_DISABLED'};if([string]$r.action -ne 'apply'){throw 'BRIDGE_STABLE_NOT_APPLY'};if([bool]$r.requiresUserApproval){throw 'BRIDGE_RELEASE_REQUIRES_USER_APPROVAL'};return $r}
function TestRelease($r){try{$m=ReadJson (Join-Path $ExtensionRoot 'manifest.json');if(-not $m -or [string]$m.version -ne [string]$r.version){return $false};foreach($f in @($r.files)){$rp=[string]$f.path;if($rp -match '\.\.' -or [IO.Path]::IsPathRooted($rp)){return $false};$p=Join-Path $ExtensionRoot $rp.Replace('/','\');if(-not(Test-Path -LiteralPath $p)){return $false};if((GitBlobSha1 $p).ToLowerInvariant() -ne ([string]$f.gitBlobSha1).ToLowerInvariant()){return $false}};return $true}catch{return $false}}
function InstallRelease($r){$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$stage=Join-Path $Root ('Stage\Bridge_'+$stamp);$backup=Join-Path $BackupRoot ('Bridge_'+$stamp);New-Item -ItemType Directory -Force -Path $stage,$backup|Out-Null;foreach($f in @($r.files)){$rp=[string]$f.path;if($rp -match '\.\.' -or [IO.Path]::IsPathRooted($rp)){throw 'UNSAFE_RELEASE_PATH'};$dst=Join-Path $stage $rp.Replace('/','\');$par=Split-Path $dst -Parent;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};$url=([string]$r.baseUrl).TrimEnd('/')+'/'+$rp+'?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $dst -TimeoutSec 10;$actual=(GitBlobSha1 $dst).ToLowerInvariant();if($actual -ne ([string]$f.gitBlobSha1).ToLowerInvariant()){throw "EXTENSION_SHA_MISMATCH:$rp actual=$actual expected=$($f.gitBlobSha1)"}};if(Test-Path -LiteralPath $ExtensionRoot){Copy-Item -LiteralPath $ExtensionRoot -Destination (Join-Path $backup 'extension') -Recurse -Force};StopDedicated;Get-ChildItem -LiteralPath $ExtensionRoot -Force -ErrorAction SilentlyContinue|Remove-Item -Recurse -Force;Copy-Item (Join-Path $stage '*') -Destination $ExtensionRoot -Recurse -Force;if(-not(TestRelease $r)){throw 'EXTENSION_POST_INSTALL_VERIFY_FAILED'};LaunchDedicated ([string]$r.frontUrl);return $backup}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$root=[string]$d.Root;if(-not $root){continue};foreach($c in @((Join-Path $root $target),(Join-Path $root ('My Drive\'+$target)),(Join-Path $root ('내 드라이브\'+$target)),(Join-Path $root ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c){return $c}}};return ''}
function WriteCentral([string]$Name,[string]$Json){$central=FindCentral;if(-not $central){return $false};try{$dest=Join-Path $central 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $dest|Out-Null;$Json|Set-Content -LiteralPath (Join-Path $dest $Name) -Encoding UTF8;return $true}catch{return $false}}
function DownloadText([string]$Url,[string]$Path){$tmp=$Path+'.download';Invoke-WebRequest -UseBasicParsing -Uri ($Url+'?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -OutFile $tmp -TimeoutSec 30;Move-Item -LiteralPath $tmp -Destination $Path -Force}
function TaskXml([string]$TaskName){try{$text=& schtasks.exe /Query /TN $TaskName /XML 2>$null|Out-String;if($LASTEXITCODE -ne 0){return ''};return [string]$text}catch{return ''}}
function EnsureLoginRunFallback([string]$Watchdog){$runKey='HKCU:\Software\Microsoft\Windows\CurrentVersion\Run';$name='HomeDesignAutomationAutoResume';$command='powershell.exe -NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File "'+$Watchdog+'"';try{New-Item -Path $runKey -Force|Out-Null;$current=(Get-ItemProperty -Path $runKey -Name $name -ErrorAction SilentlyContinue).$name;$changed=([string]$current -ne $command);if($changed){Set-ItemProperty -Path $runKey -Name $name -Value $command -Type String};$verify=(Get-ItemProperty -Path $runKey -Name $name -ErrorAction Stop).$name;return [ordered]@{ok=([string]$verify -eq $command);changed=$changed;name=$name;command=$command}}catch{return [ordered]@{ok=$false;changed=$false;name=$name;command=$command;error=$_.Exception.Message}}}
function EnsureAutoResume{$taskName='HomeDesignAutomation-AutoResume';$runner=Join-Path $Root 'HomeDesignAutoResume.ps1';$watchdog=Join-Path $Root 'HomeDesignLocalWatchdog.ps1';$installer=Join-Path $Root 'INSTALL_AUTO_RESUME_TASK.ps1';$base='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/bootstrap/';DownloadText ($base+'HomeDesignAutoResume.ps1') $runner;DownloadText ($base+'HomeDesignLocalWatchdog.ps1') $watchdog;$before=TaskXml $taskName;$taskHealthy=([string]$before -match 'HomeDesignLocalWatchdog\.ps1' -and [string]$before -match '<Enabled>true</Enabled>' -and [string]$before -match 'PT5M');$taskRepaired=$false;$installExit=$null;if(-not $taskHealthy){DownloadText ($base+'INSTALL_AUTO_RESUME_TASK.ps1') $installer;& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $installer | Out-Null;$installExit=$LASTEXITCODE;$taskRepaired=$true};$after=TaskXml $taskName;$taskOk=([string]$after -match 'HomeDesignLocalWatchdog\.ps1' -and [string]$after -match '<Enabled>true</Enabled>' -and [string]$after -match 'PT5M');$loginRun=EnsureLoginRunFallback $watchdog;$ok=($taskOk -or [bool]$loginRun.ok);return [ordered]@{ok=[bool]$ok;taskName=$taskName;taskHealthy=[bool]$taskOk;taskRepaired=$taskRepaired;installExit=$installExit;loginRunHealthy=[bool]$loginRun.ok;loginRunChanged=[bool]$loginRun.changed;loginRun=$loginRun;runnerPresent=(Test-Path -LiteralPath $runner);watchdogPresent=(Test-Path -LiteralPath $watchdog);checkedAt=(Get-Date).ToString('o')}}
function BuildState($r,[bool]$changed,[string]$backup,$autoResume,$hostRecovery,[string[]]$errors){$h=HostHealth;$m=ReadJson (Join-Path $ExtensionRoot 'manifest.json');$runtimeOk=($h -and [bool]$h.ok -and [string]$h.version -eq $HostVersion -and [bool]$h.asyncJobs -and $m -and [string]$m.version -eq [string]$r.version -and (Dedicated).Count -gt 0 -and (TestRelease $r));$ok=($runtimeOk -and $autoResume -and [bool]$autoResume.ok);return [ordered]@{ok=[bool]$ok;status=$(if($ok){'SELF_HEAL_PASS'}else{'SELF_HEAL_FAILED'});agentVersion=$AgentVersion;agentMode='HOST_SELF_HEAL_PLUS_AUTORESUME_1.1.29';commandHostVersion=$(if($h){[string]$h.version}else{''});hostHealthy=$(if($h){[bool]$h.ok}else{$false});hostAsyncJobs=$(if($h){[bool]$h.asyncJobs}else{$false});extensionVersion=$(if($m){[string]$m.version}else{''});releaseActionId=$(if($r){[string]$r.actionId}else{''});dedicatedChromeRunning=((Dedicated).Count -gt 0);extensionChanged=$changed;backupPath=$backup;hostRecovery=$hostRecovery;autoResumeTaskHealthy=$(if($autoResume){[bool]$autoResume.taskHealthy}else{$false});autoResumeTaskRepaired=$(if($autoResume){[bool]$autoResume.taskRepaired}else{$false});loginRunFallbackHealthy=$(if($autoResume){[bool]$autoResume.loginRunHealthy}else{$false});loginRunFallbackChanged=$(if($autoResume){[bool]$autoResume.loginRunChanged}else{$false});autoResume=$autoResume;errors=@($errors);updatedAt=(Get-Date).ToString('o')}}
function PersistState($state){$json=$state|ConvertTo-Json -Depth 30;$json|Set-Content -LiteralPath $StateFile -Encoding UTF8;$json|Set-Content -LiteralPath $ReadbackFile -Encoding UTF8;[void](WriteCentral 'VIDEO_LOCAL_RUNTIME_READBACK.json' $json);return $state}

$result=[ordered]@{action='AGENT_1.1.29_HOST_SELF_HEAL_PLUS_AUTORESUME';startedAt=(Get-Date).ToString('o');hostBefore=$null;hostRecovery=$null;targetBridge='';installedBefore='';changed=$false;backupPath='';autoResume=$null;state=$null;ok=$false;error=''}
$rel=$null
try{$result.hostBefore=HostHealth;$result.autoResume=EnsureAutoResume;if(-not [bool]$result.autoResume.ok){throw 'AUTO_RESUME_PERSISTENCE_NOT_HEALTHY'};$result.hostRecovery=EnsureHost124;if(-not [bool]$result.hostRecovery.ok){throw 'HOST_SELF_HEAL_FAILED'};$rel=GetRelease;$result.targetBridge=[string]$rel.version;$before=ReadJson (Join-Path $ExtensionRoot 'manifest.json');$result.installedBefore=$(if($before){[string]$before.version}else{'NONE'});if(-not(TestRelease $rel)){$result.backupPath=InstallRelease $rel;$result.changed=$true}elseif((Dedicated).Count -le 0){LaunchDedicated ([string]$rel.frontUrl)};$result.state=PersistState (BuildState $rel $result.changed $result.backupPath $result.autoResume $result.hostRecovery @());$result.ok=[bool]$result.state.ok;if(-not $result.ok){throw 'POST_RECOVERY_STATE_NOT_VERIFIED'}}catch{$result.error=$_.Exception.Message;$result.ok=$false;try{$failure=BuildState $rel $result.changed $result.backupPath $result.autoResume $result.hostRecovery @($result.error);$result.state=PersistState $failure}catch{}}
$result.completedAt=(Get-Date).ToString('o')
$recoveryJson=$result|ConvertTo-Json -Depth 30
$recoveryJson|Set-Content -LiteralPath $RecoveryFile -Encoding UTF8
[void](WriteCentral 'AGENT_1.1.29_RECOVERY.json' $recoveryJson)
if($result.ok){exit 0}else{exit 2}
