param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.104'
$TargetNotebookId='8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$TargetUrl='https://notebook.google.com/notebook/'+$TargetNotebookId
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
New-Item -ItemType Directory -Force -Path $Root | Out-Null
function Tabs{$r=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3;$o=$r.Content | ConvertFrom-Json;$a=@();if($o -is [System.Array]){foreach($x in $o){$a += $x}}elseif($null -ne $o){$a += $o};return $a}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$sec*1000));try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($r.MessageType -eq [System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_CLOSED'};$m.Write($b,0,$r.Count)}while(-not $r.EndOfMessage);return ([Text.Encoding]::UTF8.GetString($m.ToArray()) | ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$j=@{id=$id;method=$method;params=$params} | ConvertTo-Json -Depth 30 -Compress;$bb=[Text.Encoding]::UTF8.GetBytes($j);$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id -eq $id){if($z.error){throw ('CDP_'+$method+':'+($z.error | ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$false};return $r.result.value}
function Connect([string]$wsUrl){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$wsUrl,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};return $w}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not $r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($my+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveCentral([string]$Name,$Object){try{$j=$Object | ConvertTo-Json -Depth 60;$j | Set-Content -LiteralPath (Join-Path $Root $Name) -Encoding UTF8;$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d | Out-Null;$p=Join-Path $d $Name;$j | Set-Content -LiteralPath $p -Encoding UTF8;return $p}}catch{};return ''}
$result=[ordered]@{ok=$false;action='AGENT_1.1.104_CHAT_STUDIO_DOM_READONLY';version=$Version;targetUrl=$TargetUrl;startedAt=(Get-Date).ToString('o');exactTab=$false;navigated=$false;url='';title='';controls=$null;bodySample='';normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;clicked=$false;submitted=$false;generated=$false;stage='START';error='';centralPath=''}
$w=$null
try{$pages=@(Tabs | Where-Object{[string]$_.type -eq 'page'});$tab=$pages | Where-Object{[string]$_.url -eq $TargetUrl} | Select-Object -First 1;if(-not $tab){$tab=$pages | Where-Object{[string]$_.url -like 'https://notebook.google.com/*'} | Select-Object -First 1};if(-not $tab){throw 'NO_NOTEBOOKLM_PAGE_FOR_READONLY_DIAG'};$w=Connect ([string]$tab.webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.enable' @{});$u=[string](Eval $w ([ref]$q) 'location.href');if($u -ne $TargetUrl){[void](Send $w ([ref]$q) 'Page.navigate' @{url=$TargetUrl});$result.navigated=$true;$d=(Get-Date).AddSeconds(20);do{Start-Sleep -Milliseconds 500;$u=[string](Eval $w ([ref]$q) 'location.href');if($u -eq $TargetUrl){break}}while((Get-Date) -lt $d)};if($u -ne $TargetUrl){throw ('EXACT_URL_NOT_REACHED '+$u)};Start-Sleep -Seconds 2;$result.exactTab=$true;$result.url=$u;$probe=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const pack=e=>({tag:e.tagName,role:e.getAttribute('role')||'',aria:e.getAttribute('aria-label')||'',placeholder:e.getAttribute('placeholder')||'',title:e.getAttribute('title')||'',text:String(e.innerText||e.textContent||'').trim().slice(0,220),x:Math.round(e.getBoundingClientRect().x),y:Math.round(e.getBoundingClientRect().y),w:Math.round(e.getBoundingClientRect().width),h:Math.round(e.getBoundingClientRect().height)});const texts=[...document.querySelectorAll('h1,h2,h3,[role=heading],[role=tab],button,[role=button],a')].filter(vis).map(pack).filter(x=>/chat|studio|audio|\uCC44\uD305|\uC2A4\uD29C\uB514\uC624|\uC624\uB514\uC624/i.test([x.text,x.aria,x.title].join(' '))).slice(0,80);const editors=[...document.querySelectorAll('textarea,[role=textbox],[contenteditable=true],input')].filter(vis).map(pack).slice(0,80);return {title:document.title,url:location.href,matchedControls:texts,editors:editors,body:(document.body?.innerText||'').slice(0,5000)}})()";$result.title=[string]$probe.title;$result.controls=[ordered]@{matchedControls=@($probe.matchedControls);editors=@($probe.editors)};$result.bodySample=[string]$probe.body;$result.ok=$true;$result.stage='DONE'}catch{$result.error=$_.Exception.Message}
finally{if($w){try{$w.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o');$result.centralPath=SaveCentral 'AGENT_1.1.104_CHAT_STUDIO_DOM_READONLY_RESULT.json' $result}
$result | ConvertTo-Json -Depth 60 -Compress
if($result.ok){exit 0}else{exit 2}
