param(
  [string]$TargetNotebookId='8d1eda83-cfe3-4487-b2bc-266a5be3465c',
  [string]$SourceText='2026-08-29 신규 NotebookLM E2E 검증 전용 원문. 이 노트북은 기존 프로젝트와 완전히 분리한다. 핵심 흐름은 FRESH_NOTEBOOK → SOURCE → AUDIO_OVERVIEW → SLIDES → VIDEO_OVERVIEW → REPORT → MIND_MAP → FLASHCARDS → QUIZ → INFOGRAPHIC → DATA_TABLE → NATIVE_DOWNLOAD → DRIVE_READBACK 이다. 고유 마커: NLM_FRESH_ALL_20260829_1915.',
  [string]$PromptText='이 새 노트북의 신규 소스만 사용해 한국어 AI 오디오 오버뷰를 새로 생성할 준비를 해주세요. 기존 오디오 재사용 금지. 먼저 이 소스의 핵심 내용을 확인하고 스튜디오의 AI 오디오 오버뷰 생성 단계로 이동할 수 있게 준비해 주세요.',
  [int]$RemoteDebuggingPort=9223,
  [int]$TimeoutSeconds=120,
  [int]$CdpCommandTimeoutSeconds=8
)
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$TargetNotebookUrl='https://notebook.google.com/notebook/'+$TargetNotebookId
$Marker='NLM_FRESH_ALL_20260829_1915'
function Get-FlatTabs {
  $resp=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$RemoteDebuggingPort/json/list") -TimeoutSec 3
  $obj=$resp.Content|ConvertFrom-Json
  $flat=@();if($obj -is [System.Array]){foreach($x in $obj){$flat+=$x}}elseif($null -ne $obj){$flat+=$obj};return $flat
}
function Receive-Cdp([System.Net.WebSockets.ClientWebSocket]$Ws,[int]$Seconds){$buf=New-Object byte[] 65536;$ms=New-Object IO.MemoryStream;$cts=New-Object Threading.CancellationTokenSource;$cts.CancelAfter([Math]::Max(1000,$Seconds*1000));try{do{$seg=New-Object ArraySegment[byte] -ArgumentList @(,$buf);try{$res=$Ws.ReceiveAsync($seg,$cts.Token).GetAwaiter().GetResult()}catch{throw 'CDP_RECEIVE_TIMEOUT_OR_CLOSED'};if($res.MessageType -eq [System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_WEBSOCKET_CLOSED'};$ms.Write($buf,0,$res.Count)}while(-not $res.EndOfMessage);return [Text.Encoding]::UTF8.GetString($ms.ToArray())|ConvertFrom-Json}finally{$cts.Dispose();$ms.Dispose()}}
function Send-Cdp([System.Net.WebSockets.ClientWebSocket]$Ws,[ref]$Seq,[string]$Method,[hashtable]$Params=@{}){$Seq.Value++;$id=$Seq.Value;$json=@{id=$id;method=$Method;params=$Params}|ConvertTo-Json -Depth 30 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($json);$seg=New-Object ArraySegment[byte] -ArgumentList @(,$bytes);$cts=New-Object Threading.CancellationTokenSource;$cts.CancelAfter([Math]::Max(1000,$CdpCommandTimeoutSeconds*1000));try{$Ws.SendAsync($seg,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$cts.Token).GetAwaiter().GetResult()}catch{throw ('CDP_SEND_TIMEOUT '+$Method)}finally{$cts.Dispose()};while($true){$msg=Receive-Cdp $Ws $CdpCommandTimeoutSeconds;if($msg.id -eq $id){if($msg.error){throw ('CDP_'+$Method+': '+($msg.error|ConvertTo-Json -Compress))};return $msg.result}}}
function Eval-Cdp($Ws,[ref]$Seq,[string]$Expr){$r=Send-Cdp $Ws $Seq 'Runtime.evaluate' @{expression=$Expr;returnByValue=$true;awaitPromise=$true;userGesture=$true};return $r.result.value}
function Click-Cdp($Ws,[ref]$Seq,[double]$X,[double]$Y){[void](Send-Cdp $Ws $Seq 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$X;y=$Y});[void](Send-Cdp $Ws $Seq 'Input.dispatchMouseEvent' @{type='mousePressed';x=$X;y=$Y;button='left';clickCount=1});Start-Sleep -Milliseconds 100;[void](Send-Cdp $Ws $Seq 'Input.dispatchMouseEvent' @{type='mouseReleased';x=$X;y=$Y;button='left';clickCount=1})}
function Connect-Page($Tab){$ws=New-Object System.Net.WebSockets.ClientWebSocket;$cts=New-Object Threading.CancellationTokenSource;$cts.CancelAfter([Math]::Max(1000,$CdpCommandTimeoutSeconds*1000));try{$ws.ConnectAsync([Uri]([string]$Tab.webSocketDebuggerUrl),$cts.Token).GetAwaiter().GetResult()}catch{$ws.Dispose();throw 'CDP_CONNECT_TIMEOUT_OR_FAILED'}finally{$cts.Dispose()};return $ws}
$result=[ordered]@{ok=$false;action='NOTEBOOKLM_EXACT_FRESH_SOURCE_BIND_CDP_V5';startedAt=(Get-Date).ToString('o');targetNotebookUrl=$TargetNotebookUrl;notebookUrl='';notebookId=$TargetNotebookId;sourceAdded=$false;sourceVerified=$false;promptFilled=$false;promptSubmitted=$false;studioSelected=$false;createdNotebook=$false;stage='START';error='';evidence=@{}}
$ws=$null
try{
  $result.stage='PAGE_CONNECT';$tabs=@(Get-FlatTabs|Where-Object{[string]$_.type -eq 'page'});if(-not $tabs){throw 'NO_CDP_PAGE_TARGET'};$tab=$tabs|Where-Object{[string]$_.url -like 'https://notebook.google.com/*'}|Select-Object -First 1;if(-not $tab){$tab=$tabs|Select-Object -First 1};$ws=Connect-Page $tab;$seq=0;[void](Send-Cdp $ws ([ref]$seq) 'Runtime.enable' @{});[void](Send-Cdp $ws ([ref]$seq) 'Page.enable' @{});[void](Send-Cdp $ws ([ref]$seq) 'Page.bringToFront' @{})
  $result.stage='NAVIGATE_EXACT_FRESH';[void](Send-Cdp $ws ([ref]$seq) 'Page.navigate' @{url=$TargetNotebookUrl});$deadline=(Get-Date).AddSeconds(30);do{Start-Sleep -Milliseconds 500;$u=[string](Eval-Cdp $ws ([ref]$seq) 'location.href');if($u -eq $TargetNotebookUrl){break}}while((Get-Date)-lt $deadline);if($u -ne $TargetNotebookUrl){throw ('EXACT_NOTEBOOK_NAVIGATION_FAILED url='+$u)};$result.notebookUrl=$u;Start-Sleep -Seconds 2
  $pre=Eval-Cdp $ws ([ref]$seq) "(() => {const txt=document.body?.innerText||'';return {title:document.title,url:location.href,marker:txt.includes('NLM_FRESH_ALL_20260829_1915'),zero:/소스\s*0건|0\s*sources?/i.test(txt),one:/소스\s*[1-9][0-9]*건|[1-9][0-9]*\s*sources?/i.test(txt),sample:txt.slice(0,2200)}})()";$result.evidence.before=$pre;if($pre.marker -or $pre.one){$result.sourceAdded=$true;$result.sourceVerified=$true}
  if(-not $result.sourceVerified){
    $result.stage='SOURCE_TAB';$find="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim();const t=raw.toLowerCase();if(raw==='출처'||raw.startsWith('출처 ')||t==='sources'||t.startsWith('sources ')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:raw}}}return {ok:false,sample:(document.body?.innerText||'').slice(0,1200)}})()";$x=Eval-Cdp $ws ([ref]$seq) $find;if(-not $x.ok){throw ('SOURCE_TAB_NOT_FOUND: '+[string]$x.sample)};Click-Cdp $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 800
    $result.stage='ADD_SOURCE';$find="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const txt=document.body?.innerText||'';if(/복사한 텍스트|copied text|paste text/i.test(txt))return {ok:false,dialogOpen:true};for(const e of [...document.querySelectorAll('button,[role=button],a')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' '));const t=raw.toLowerCase();if(raw.includes('소스 추가')||t.includes('add source')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:raw.slice(0,160)}}}return {ok:false,dialogOpen:false,sample:txt.slice(0,1400)}})()";$x=Eval-Cdp $ws ([ref]$seq) $find;if($x.ok){Click-Cdp $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 800}elseif(-not $x.dialogOpen){throw ('ADD_SOURCE_CONTROL_NOT_FOUND: '+[string]$x.sample)}
    $result.stage='PASTE_TYPE';$find="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('button,[role=button],a,div[tabindex]')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' '));const t=raw.toLowerCase();if(raw.includes('복사한 텍스트')||raw.includes('텍스트 붙여넣기')||t.includes('copied text')||t.includes('paste text')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:raw.slice(0,160)}}}return {ok:false,sample:(document.body?.innerText||'').slice(0,1600)}})()";$x=Eval-Cdp $ws ([ref]$seq) $find;if(-not $x.ok){throw ('COPIED_TEXT_CONTROL_NOT_FOUND: '+[string]$x.sample)};Click-Cdp $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 700
    $sourceJson=$SourceText|ConvertTo-Json -Compress;$result.stage='SOURCE_FILL';$fill="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const dialogs=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);const root=dialogs[dialogs.length-1]||document;const all=[...root.querySelectorAll('textarea,[contenteditable=true],input:not([type=hidden])')].filter(vis);const e=all.find(x=>x.tagName==='TEXTAREA')||all.find(x=>/텍스트|text|paste|붙여넣/i.test(String(x.getAttribute('placeholder')||'')))||all.find(x=>x.getAttribute('contenteditable')==='true');if(!e)return {ok:false,sample:(document.body?.innerText||'').slice(0,1600)};e.focus();if('value'in e){const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(s)s.call(e,$sourceJson);else e.value=$sourceJson;}else{e.textContent=$sourceJson;}e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:$sourceJson}));e.dispatchEvent(new Event('change',{bubbles:true}));return {ok:true,len:('value'in e?e.value:e.textContent).length,placeholder:e.getAttribute('placeholder')||''}})()";$x=Eval-Cdp $ws ([ref]$seq) $fill;if(-not $x.ok){throw ('SOURCE_EDITOR_NOT_FOUND: '+[string]$x.sample)};$result.evidence.editor=$x
    $result.stage='SOURCE_SUBMIT';$find="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};const dialogs=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);const root=dialogs[dialogs.length-1]||document;const exact=['삽입','추가','저장','insert','add','save'];for(const e of [...root.querySelectorAll('button,[role=button]')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).trim();const t=raw.toLowerCase().replace(/\s+/g,' ');if(exact.some(w=>t===w||t.startsWith(w+' '))){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:raw.slice(0,160)}}}return {ok:false,sample:[...root.querySelectorAll('button,[role=button]')].map(e=>String([e.innerText,e.getAttribute('aria-label')].join(' ')).trim()).filter(Boolean).slice(-30)}})()";$x=Eval-Cdp $ws ([ref]$seq) $find;if(-not $x.ok){throw ('SOURCE_SUBMIT_NOT_FOUND: '+(($x.sample|ConvertTo-Json -Compress)))};Click-Cdp $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.sourceAdded=$true
    $deadline=(Get-Date).AddSeconds(35);do{Start-Sleep -Milliseconds 700;$v=Eval-Cdp $ws ([ref]$seq) "(() => {const txt=document.body?.innerText||'';return {zero:/소스\s*0건|0\s*sources?/i.test(txt),one:/소스\s*[1-9][0-9]*건|[1-9][0-9]*\s*sources?/i.test(txt),marker:txt.includes('NLM_FRESH_ALL_20260829_1915'),checks:[...document.querySelectorAll('input[type=checkbox],[role=checkbox],mat-checkbox')].length,sample:txt.slice(0,2200)}})()";if($v.marker -or $v.one -or (-not $v.zero -and $v.checks -gt 0)){$result.sourceVerified=$true;$result.evidence.sourceVerify=$v;break}}while((Get-Date)-lt $deadline);if(-not $result.sourceVerified){$result.evidence.sourceVerify=$v;throw 'SOURCE_ADD_NOT_VERIFIED'}
  }
  $result.stage='CHAT_PROMPT';$find="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim();if(raw==='채팅'||raw.toLowerCase()==='chat'){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";$x=Eval-Cdp $ws ([ref]$seq) $find;if($x.ok){Click-Cdp $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 600};$promptJson=$PromptText|ConvertTo-Json -Compress;$fill="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const all=[...document.querySelectorAll('textarea,[contenteditable=true]')].filter(vis);const e=all.find(x=>/질문|창작|ask|create/i.test(String([x.getAttribute('placeholder'),x.getAttribute('aria-label')].join(' '))))||all[all.length-1];if(!e)return {ok:false};e.focus();if('value'in e){const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(s)s.call(e,$promptJson);else e.value=$promptJson;}else{e.textContent=$promptJson;}e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:$promptJson}));e.dispatchEvent(new Event('change',{bubbles:true}));return {ok:true,len:('value'in e?e.value:e.textContent).length}})()";$x=Eval-Cdp $ws ([ref]$seq) $fill;$result.promptFilled=[bool]$x.ok;$result.evidence.prompt=$x
  if($result.promptFilled){$find="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};const els=[...document.querySelectorAll('button,[role=button]')].filter(vis);for(const e of els){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).toLowerCase();if(/send|submit|전송|보내기|arrow_forward/.test(raw)){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}const cand=els.map(e=>({e,r:e.getBoundingClientRect()})).filter(x=>x.r.left>innerWidth*0.65&&x.r.top>innerHeight*0.55).sort((a,b)=>b.r.left-a.r.left)[0];if(cand)return {ok:true,x:cand.r.left+cand.r.width/2,y:cand.r.top+cand.r.height/2};return {ok:false}})()";$x=Eval-Cdp $ws ([ref]$seq) $find;if($x.ok){Click-Cdp $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.promptSubmitted=$true;Start-Sleep -Milliseconds 600}}
  $result.stage='STUDIO';$find="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim();if(raw==='스튜디오'||raw.toLowerCase()==='studio'){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";$x=Eval-Cdp $ws ([ref]$seq) $find;if($x.ok){Click-Cdp $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.studioSelected=$true}
  $result.ok=($result.sourceVerified -and $result.notebookUrl -eq $TargetNotebookUrl -and -not $result.createdNotebook);$result.stage=if($result.ok){'PASS'}else{'GATE_FAIL'}
}catch{$result.error=$_.Exception.Message}
finally{if($ws){try{$ws.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o')}
$result|ConvertTo-Json -Depth 50 -Compress
if($result.ok){exit 0}else{exit 2}
