param(
  [string]$TargetNotebookId='8d1eda83-cfe3-4487-b2bc-266a5be3465c',
  [string]$TitleB64='MjAyNi0wOC0zMF9Db250ZW50T1NfQUnsvZjthZDsuKDsg53sgrDsm4ztgaztlIzroZzsmrBf66as7ISc7LmY',
  [string]$ResearchQueryB64='QUkg7L2Y7YWQ7LigIOyDneyCsCDsm4ztgaztlIzroZzsmrAg642w7J207YSwIOyImOynkSDrtoTshJ0g7YWc7ZSM66a/IOyCrOyaqeyekCDqsIDsuZgg6rKA7KadIOyCrOuhgA==',
  [string]$ChatPromptB64='7IiY7KeR65CcIOyGjOyKpOulvCDrsJTtg5XsnLzroZwgQUkg7L2Y7YWQ7LigIOyDneyCsCDsm4ztgaztlIzroZzsmrDsl5DshJwg7JuQ7J6Q66OMIOyImOynkSwg7ZW17IusIO2MqO2EtCDrtoTshJ0sIOyerOyCrOyaqSDqsIDriqXtlZwg7YWc7ZSM66a/7ZmULCDsi6TsoJwg7IKs7Jqp7J6QIOqwgOy5mCDqsoDspp3snZgg7Z2Q66aE7J2EIO2VnOq1reyWtOuhnCDrqoXtmZXtlZjqsowg7KCV66as7ZW0IOyjvOyEuOyalC4g7ZW17IusIOq3vOqxsOyZgCDsi6TsoIQg7KCB7JqpIOyInOyEnOulvCDtlajqu5gg7KCV66as7ZWY6rOgLCDsnbQg64K07Jqp7J2EIOuwlO2DleycvOuhnCBBSSDsmKTrlJTsmKQg7Jik67KE67ew66W8IOunjOuTpCDsiJgg7J6I6rKMIOykgOu5hO2VtCDso7zshLjsmpQuIOqzoOycoCDrp4jsu6Q6IE5MTV9GUkVTSF9BTExfMjAyNjA4MjlfMTkxNS4=',
  [string]$StudioInstructionB64='7IiY7KeR65CcIOyGjOyKpOunjCDqt7zqsbDroZwg7IKs7Jqp7ZWY6rOgIO2VnOq1reyWtOuhnCDtlbXsi6wg7Z2Q66aELCDsi6TsoJwg7KCB7JqpIOyInOyEnCwg7IKs7Jqp7J6QIOqwgOy5mCDqsoDspp0g7Y+s7J247Yq466W8IOykkeyLrOycvOuhnCBBSSDsmKTrlJTsmKQg7Jik67KE67ew66W8IOyDneyEse2VmOyEuOyalC4=',
  [int]$RemoteDebuggingPort=9223,
  [int]$ResearchTimeoutSeconds=180,
  [int]$ChatTimeoutSeconds=120,
  [int]$ArtifactTimeoutSeconds=900,
  [int]$CdpCommandTimeoutSeconds=8
)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
function U([string]$b){[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b))}
$Title=U $TitleB64;$ResearchQuery=U $ResearchQueryB64;$ChatPrompt=U $ChatPromptB64;$StudioInstruction=U $StudioInstructionB64
$TargetUrl='https://notebook.google.com/notebook/'+$TargetNotebookId
function Tabs{$r=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$RemoteDebuggingPort/json/list") -TimeoutSec 4;$o=$r.Content|ConvertFrom-Json;$a=@();if($o -is [System.Array]){foreach($x in $o){$a+=$x}}elseif($null-ne$o){$a+=$o};$a}
function Recv($w,[int]$s){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$s*1000));try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($r.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw'CDP_CLOSED'};$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);[Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$m,[hashtable]$p=@{}){$q.Value++;$id=$q.Value;$j=@{id=$id;method=$m;params=$p}|ConvertTo-Json -Depth 30 -Compress;$bb=[Text.Encoding]::UTF8.GetBytes($j);$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$CdpCommandTimeoutSeconds*1000));try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w $CdpCommandTimeoutSeconds;if($z.id-eq$id){if($z.error){throw('CDP_'+$m+':'+($z.error|ConvertTo-Json -Compress))};return$z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};$r.result.value}
function Click($w,[ref]$q,[double]$x,[double]$y){[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$x;y=$y});[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mousePressed';x=$x;y=$y;button='left';clickCount=1});Start-Sleep -Milliseconds 100;[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseReleased';x=$x;y=$y;button='left';clickCount=1})}
$result=[ordered]@{ok=$false;action='NOTEBOOKLM_EXACT_ORDERED_RESEARCH_AUDIO_V1';notebookId=$TargetNotebookId;notebookUrl='';titleTarget=$Title;titleVerified=$false;researchFilled=$false;researchSubmitted=$false;researchResultsReady=$false;sourcesImported=$false;sourceCount=0;sourceVerified=$false;chatFilled=$false;chatSubmitted=$false;studioSelected=$false;audioSelected=$false;studioInstructionFilled=$false;generateClicked=$false;artifactReady=$false;stage='START';error='';evidence=@{};startedAt=(Get-Date).ToString('o')}
$w=$null
try{
  $t=@(Tabs|Where-Object{[string]$_.type-eq'page'}|Where-Object{[string]$_.url-like'https://notebook.google.com/*'}|Select-Object -First 1);if(-not$t){throw'NO_NOTEBOOKLM_PAGE'}
  [System.Net.WebSockets.ClientWebSocket]$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]([string]$t[0].webSocketDebuggerUrl),$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{});[void](Send $w ([ref]$q) 'Page.navigate' @{url=$TargetUrl});Start-Sleep -Seconds 2;$result.notebookUrl=[string](Eval $w ([ref]$q) 'location.href');if($result.notebookUrl-ne$TargetUrl){throw'EXACT_NOTEBOOK_NAVIGATION_FAILED'}
  $result.stage='TITLE_SET';$tj=$Title|ConvertTo-Json -Compress;$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const e=[...document.querySelectorAll('editable-project-title,h1,[data-testid*=title]')].find(v);if(!e)return {ok:false};const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:(e.innerText||e.textContent||'').trim()}})()";if(-not$x.ok){throw'TITLE_CONTROL_NOT_FOUND'};Click $w ([ref]$q) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 500;$x=Eval $w ([ref]$q) "(() => {const val=$tj;const root=document.querySelector('editable-project-title')||document;const a=[...root.querySelectorAll('input,textarea,[contenteditable=true]'),document.activeElement].filter(Boolean);const e=a.find(x=>x instanceof HTMLInputElement||x instanceof HTMLTextAreaElement||x.getAttribute?.('contenteditable')==='true');if(!e)return {ok:false};e.focus();if('value'in e){const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(s)s.call(e,val);else e.value=val}else{e.textContent=val};e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:val}));e.dispatchEvent(new Event('change',{bubbles:true}));e.dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));e.dispatchEvent(new KeyboardEvent('keyup',{key:'Enter',code:'Enter',keyCode:13,which:13,bubbles:true}));return {ok:true}})()";if(-not$x.ok){[void](Send $w ([ref]$q) 'Input.dispatchKeyEvent' @{type='keyDown';key='a';code='KeyA';modifiers=2});[void](Send $w ([ref]$q) 'Input.dispatchKeyEvent' @{type='keyUp';key='a';code='KeyA';modifiers=2});[void](Send $w ([ref]$q) 'Input.insertText' @{text=$Title});[void](Send $w ([ref]$q) 'Input.dispatchKeyEvent' @{type='keyDown';key='Enter';code='Enter';windowsVirtualKeyCode=13});[void](Send $w ([ref]$q) 'Input.dispatchKeyEvent' @{type='keyUp';key='Enter';code='Enter';windowsVirtualKeyCode=13})};Start-Sleep -Seconds 1;$v=Eval $w ([ref]$q) "(() => {const e=document.querySelector('editable-project-title')||document.querySelector('h1');return {text:(e?.innerText||e?.textContent||'').trim(),title:document.title}})()";$result.evidence.title=$v;$result.titleVerified=([string]$v.text-eq$Title);if(-not$result.titleVerified){throw'TITLE_READBACK_FAILED'}
  $result.stage='SOURCE_TAB';$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(v)){const s=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim();if(s==='\uCD9C\uCC98'||s.toLowerCase()==='sources'){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if(-not$x.ok){throw'SOURCE_TAB_NOT_FOUND'};Click $w ([ref]$q) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 700
  $result.stage='RESEARCH_FILL';$rj=$ResearchQuery|ConvertTo-Json -Compress;$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const all=[...document.querySelectorAll('input,textarea,[role=textbox],[contenteditable=true]')].filter(v);const e=all.find(x=>{const m=String([x.getAttribute('placeholder'),x.getAttribute('aria-label')].join(' ')).toLowerCase();return (m.includes('\uC6F9')&&m.includes('\uC18C\uC2A4'))||m.includes('search')&&m.includes('source')});if(!e)return {ok:false,sample:(document.body?.innerText||'').slice(0,1200)};e.focus();const val=$rj;if('value'in e){const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(s)s.call(e,val);else e.value=val}else{e.textContent=val};e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:val}));e.dispatchEvent(new Event('change',{bubbles:true}));const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}})()";if(-not$x.ok){throw('WEB_SOURCE_SEARCH_EDITOR_NOT_FOUND '+[string]$x.sample)};$result.researchFilled=$true
  $result.stage='RESEARCH_SUBMIT';$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};for(const e of [...document.querySelectorAll('button,[role=button]')].filter(v)){const m=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title'),e.querySelector('mat-icon')?.textContent].join(' ')).toLowerCase();if(m.includes('search')||m.includes('\uAC80\uC0C9')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if($x.ok){Click $w ([ref]$q) ([double]$x.x) ([double]$x.y)}else{[void](Send $w ([ref]$q) 'Input.dispatchKeyEvent' @{type='keyDown';key='Enter';code='Enter';windowsVirtualKeyCode=13});[void](Send $w ([ref]$q) 'Input.dispatchKeyEvent' @{type='keyUp';key='Enter';code='Enter';windowsVirtualKeyCode=13})};$result.researchSubmitted=$true
  $result.stage='WAIT_RESEARCH';$d=(Get-Date).AddSeconds($ResearchTimeoutSeconds);do{Start-Sleep -Seconds 2;$v=Eval $w ([ref]$q) "(() => {const t=document.body?.innerText||'';const c=[...document.querySelectorAll('input[type=checkbox],[role=checkbox],mat-checkbox')].length;const b=[...document.querySelectorAll('button,[role=button]')].map(e=>String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')));return {checks:c,imp:b.some(x=>/import|add|\uAC00\uC838\uC624\uAE30|\uCD94\uAC00/i.test(x)&&!/add source|\uC18C\uC2A4 \uCD94\uAC00/i.test(x)),busy:/searching|researching|\uAC80\uC0C9 \uC911|\uC870\uC0AC \uC911/i.test(t),sample:t.slice(0,1600)}})()";if(($v.checks-gt0-or$v.imp)-and-not$v.busy){$result.researchResultsReady=$true;$result.evidence.research=$v;break}}while((Get-Date)-lt$d);if(-not$result.researchResultsReady){throw'RESEARCH_RESULTS_NOT_READY'}
  $result.stage='IMPORT_SOURCES';$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const c of [...document.querySelectorAll('input[type=checkbox],[role=checkbox],mat-checkbox')].filter(v).slice(0,5)){const ck=c.checked===true||c.getAttribute('aria-checked')==='true';if(!ck){try{c.click()}catch{}}}for(const e of [...document.querySelectorAll('button,[role=button]')].filter(v)){const m=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).toLowerCase();if((/import|add/.test(m)||m.includes('\uAC00\uC838\uC624\uAE30')||m.includes('\uCD94\uAC00'))&&!m.includes('add source')&&!m.includes('\uC18C\uC2A4 \uCD94\uAC00')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:m.slice(0,100)}}}return {ok:false}})()";if(-not$x.ok){throw'IMPORT_SOURCES_BUTTON_NOT_FOUND'};Click $w ([ref]$q) ([double]$x.x) ([double]$x.y);$result.sourcesImported=$true
  $result.stage='SOURCE_VERIFY';$d=(Get-Date).AddSeconds(60);do{Start-Sleep -Seconds 2;$v=Eval $w ([ref]$q) "(() => {const t=document.body?.innerText||'';const m=t.match(/\uC18C\uC2A4\s*([0-9]+)\uAC74/i)||t.match(/([0-9]+)\s*sources?/i);return {count:m?Number(m[1]):0}})()";$result.sourceCount=[int]$v.count;if($result.sourceCount-gt0){$result.sourceVerified=$true;break}}while((Get-Date)-lt$d);if(-not$result.sourceVerified){throw'SOURCE_COUNT_ZERO'}
  $result.stage='CHAT';$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(v)){const s=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim();if(s==='\uCC44\uD305'||s.toLowerCase()==='chat'){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if(-not$x.ok){throw'CHAT_TAB_NOT_FOUND'};Click $w ([ref]$q) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 700;$pj=$ChatPrompt|ConvertTo-Json -Compress;$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const a=[...document.querySelectorAll('textarea,[role=textbox],[contenteditable=true]')].filter(v);const e=a.find(x=>{const m=String([x.getAttribute('placeholder'),x.getAttribute('aria-label')].join(' ')).toLowerCase();return m.includes('\uC9C8\uBB38')||m.includes('\uCC3D\uC791')||m.includes('ask')||m.includes('message')})||a[a.length-1];if(!e)return {ok:false};e.focus();const val=$pj;if('value'in e){const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(s)s.call(e,val);else e.value=val}else{e.textContent=val};e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:val}));return {ok:true}})()";if(-not$x.ok){throw'CHAT_EDITOR_NOT_FOUND'};$result.chatFilled=$true;$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};for(const e of [...document.querySelectorAll('button,[role=button]')].filter(v)){const m=String([e.getAttribute('aria-label'),e.getAttribute('title'),e.querySelector('mat-icon')?.textContent].join(' ')).toLowerCase();if(/send|arrow_upward|north|arrow_forward|\uBCF4\uB0B4\uAE30|\uC804\uC1A1/.test(m)){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if($x.ok){Click $w ([ref]$q) ([double]$x.x) ([double]$x.y)}else{[void](Send $w ([ref]$q) 'Input.dispatchKeyEvent' @{type='keyDown';key='Enter';code='Enter';windowsVirtualKeyCode=13});[void](Send $w ([ref]$q) 'Input.dispatchKeyEvent' @{type='keyUp';key='Enter';code='Enter';windowsVirtualKeyCode=13})};$result.chatSubmitted=$true;Start-Sleep -Seconds 5
  $result.stage='STUDIO';$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(v)){const s=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim();if(s==='\uC2A4\uD29C\uB514\uC624'||s.toLowerCase()==='studio'){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if(-not$x.ok){throw'STUDIO_TAB_NOT_FOUND'};Click $w ([ref]$q) ([double]$x.x) ([double]$x.y);$result.studioSelected=$true;Start-Sleep -Milliseconds 800;$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('button,[role=button],a')].filter(v)){const m=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).toLowerCase();if(m.includes('audio overview')||m.includes('\uC624\uB514\uC624 \uC624\uBC84\uBDF0')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if(-not$x.ok){throw'AUDIO_OVERVIEW_CONTROL_NOT_FOUND'};Click $w ([ref]$q) ([double]$x.x) ([double]$x.y);$result.audioSelected=$true;Start-Sleep -Seconds 1
  $sj=$StudioInstruction|ConvertTo-Json -Compress;$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const a=[...document.querySelectorAll('textarea,[role=textbox],[contenteditable=true]')].filter(v);const e=a.find(x=>{const m=String([x.getAttribute('placeholder'),x.getAttribute('aria-label')].join(' ')).toLowerCase();return m.includes('instruction')||m.includes('focus')||m.includes('custom')||m.includes('\uC9C0\uC2DC')||m.includes('\uB9DE\uCDA4')});if(!e)return {ok:false};e.focus();const val=$sj;if('value'in e){const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(s)s.call(e,val);else e.value=val}else{e.textContent=val};e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:val}));return {ok:true}})()";if($x.ok){$result.studioInstructionFilled=$true}
  $result.stage='GENERATE';$x=Eval $w ([ref]$q) "(() => {const v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};for(const e of [...document.querySelectorAll('button,[role=button]')].filter(v)){const m=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title'),e.querySelector('mat-icon')?.textContent].join(' ')).toLowerCase();if(/generate|create|arrow_forward|send|\uC0DD\uC131|\uB9CC\uB4E4\uAE30/.test(m)){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:m.slice(0,100)}}}return {ok:false}})()";if(-not$x.ok){throw'GENERATE_CONTROL_NOT_FOUND'};Click $w ([ref]$q) ([double]$x.x) ([double]$x.y);$result.generateClicked=$true
  $result.stage='WAIT_ARTIFACT';$d=(Get-Date).AddSeconds($ArtifactTimeoutSeconds);do{Start-Sleep -Seconds 5;$v=Eval $w ([ref]$q) "(() => {const t=(document.body?.innerText||'').toLowerCase();const a=[...document.querySelectorAll('audio')].some(e=>e.src||e.currentSrc);const b=[...document.querySelectorAll('button,[role=button]')].map(e=>String([e.innerText,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).toLowerCase()).some(x=>/play|download|\uC7AC\uC0DD|\uB2E4\uC6B4\uB85C\uB4DC/.test(x));return {ready:a||b,busy:/generating|creating|\uC0DD\uC131 \uC911|\uB9CC\uB4DC\uB294 \uC911/.test(t)}})()";if($v.ready-and-not$v.busy){$result.artifactReady=$true;break}}while((Get-Date)-lt$d);if(-not$result.artifactReady){throw'AUDIO_ARTIFACT_NOT_READY_WITHIN_TIMEOUT'}
  $result.ok=$true;$result.stage='DONE'
}catch{$result.error=$_.Exception.Message}
finally{if($w){try{$w.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o')}
$result|ConvertTo-Json -Depth 50 -Compress
if($result.ok){exit 0}else{exit 2}
