param(
  [string]$TargetNotebookId='8d1eda83-cfe3-4487-b2bc-266a5be3465c',
  [string]$ResearchQuery='AI 콘텐츠 생산 워크플로우 데이터 수집 분석 템플릿 사용자 가치 검증 사례',
  [string]$PromptText='수집된 소스를 바탕으로 AI 콘텐츠 생산 워크플로우에서 원자료 수집, 핵심 패턴 분석, 재사용 가능한 템플릿화, 실제 사용자 가치 검증의 흐름을 한국어로 명확하게 정리해 주세요. 핵심 근거와 실전 적용 순서를 함께 정리하고, 이 내용을 바탕으로 AI 오디오 오버뷰를 만들 수 있게 준비해 주세요. 고유 마커: NLM_FRESH_ALL_20260829_1915.',
  [int]$RemoteDebuggingPort=9223,
  [int]$ResearchTimeoutSeconds=180,
  [int]$ChatTimeoutSeconds=120,
  [int]$CdpCommandTimeoutSeconds=8
)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$TargetUrl='https://notebook.google.com/notebook/'+$TargetNotebookId
function Get-Tabs{$r=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$RemoteDebuggingPort/json/list") -TimeoutSec 4;$o=$r.Content|ConvertFrom-Json;$a=@();if($o -is [System.Array]){foreach($x in $o){$a+=$x}}elseif($null-ne$o){$a+=$o};return $a}
function Recv([System.Net.WebSockets.ClientWebSocket]$ws,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$sec*1000));try{do{$seg=New-Object ArraySegment[byte] -ArgumentList @(,$b);$res=$ws.ReceiveAsync($seg,$c.Token).GetAwaiter().GetResult();if($res.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw'CDP_CLOSED'};$m.Write($b,0,$res.Count)}while(-not$res.EndOfMessage);return [Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json}finally{$c.Dispose();$m.Dispose()}}
function Send($ws,[ref]$seq,[string]$method,[hashtable]$params=@{}){$seq.Value++;$id=$seq.Value;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 30 -Compress;$bytes=[Text.Encoding]::UTF8.GetBytes($j);$seg=New-Object ArraySegment[byte] -ArgumentList @(,$bytes);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$CdpCommandTimeoutSeconds*1000));try{[void]$ws.SendAsync($seg,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$msg=Recv $ws $CdpCommandTimeoutSeconds;if($msg.id-eq$id){if($msg.error){throw('CDP_'+$method+':'+($msg.error|ConvertTo-Json -Compress))};return$msg.result}}}
function Eval($ws,[ref]$seq,[string]$expr){$r=Send $ws $seq 'Runtime.evaluate' @{expression=$expr;returnByValue=$true;awaitPromise=$true;userGesture=$true};return$r.result.value}
function Click($ws,[ref]$seq,[double]$x,[double]$y){[void](Send $ws $seq 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$x;y=$y});[void](Send $ws $seq 'Input.dispatchMouseEvent' @{type='mousePressed';x=$x;y=$y;button='left';clickCount=1});Start-Sleep -Milliseconds 100;[void](Send $ws $seq 'Input.dispatchMouseEvent' @{type='mouseReleased';x=$x;y=$y;button='left';clickCount=1})}
$result=[ordered]@{ok=$false;action='NOTEBOOKLM_RESEARCH_FIRST_AUDIO_OVERVIEW_V2';targetNotebookId=$TargetNotebookId;notebookUrl='';sourceModalOpened=$false;researchFilled=$false;researchSubmitted=$false;researchResultsReady=$false;sourcesImported=$false;sourceCountVerified=$false;chatSelected=$false;promptFilled=$false;promptSubmitted=$false;chatSettled=$false;studioSelected=$false;audioClicked=$false;generateClicked=$false;stage='START';error='';evidence=@{};startedAt=(Get-Date).ToString('o')}
$ws=$null
try{
  $tabs=@(Get-Tabs|Where-Object{[string]$_.type-eq'page'});$tab=$tabs|Where-Object{[string]$_.url-like'https://notebook.google.com/*'}|Select-Object -First 1;if(-not$tab){throw'NO_NOTEBOOKLM_PAGE'}
  [System.Net.WebSockets.ClientWebSocket]$ws=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$ws.ConnectAsync([Uri]([string]$tab.webSocketDebuggerUrl),$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};$seq=0;[void](Send $ws ([ref]$seq) 'Runtime.enable' @{});[void](Send $ws ([ref]$seq) 'Page.enable' @{});[void](Send $ws ([ref]$seq) 'Page.bringToFront' @{});[void](Send $ws ([ref]$seq) 'Page.navigate' @{url=$TargetUrl});Start-Sleep -Seconds 2;$result.notebookUrl=[string](Eval $ws ([ref]$seq) 'location.href');if($result.notebookUrl-ne$TargetUrl){throw'EXACT_NOTEBOOK_NAVIGATION_FAILED'}
  $result.stage='OPEN_SOURCE_MODAL';$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const ds=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);if(ds.length)return {ok:true,already:true};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim().toLowerCase();if(raw==='출처'||raw==='sources'){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,tab:true}}}return {ok:false}})()";if($x.ok-and$x.tab){Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 500};$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const ds=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);if(ds.length)return {ok:true,dialog:true};for(const e of [...document.querySelectorAll('button,[role=button],a')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).toLowerCase();if(raw.includes('소스 추가')||raw.includes('add source')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if($x.ok-and-not$x.dialog){Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);Start-Sleep -Milliseconds 700};$result.sourceModalOpened=$true
  $result.stage='RESEARCH_FILL';$rq=$ResearchQuery|ConvertTo-Json -Compress;$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const ds=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);const root=ds[ds.length-1]||document;const all=[...root.querySelectorAll('input,textarea,[role=textbox],[contenteditable=true]')].filter(vis);const e=all.find(x=>/웹에서 새 소스|search.*source|새 소스.*검색|search/i.test(String([x.getAttribute('placeholder'),x.getAttribute('aria-label')].join(' '))))||all[0];if(!e)return {ok:false,sample:(root.innerText||'').slice(0,1800)};e.focus();const v=$rq;if('value'in e){const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(s)s.call(e,v);else e.value=v;}else{e.textContent=v;}e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:v}));e.dispatchEvent(new Event('change',{bubbles:true}));return {ok:true,len:('value'in e?e.value:e.textContent).length}})()";if(-not$x.ok){throw('RESEARCH_EDITOR_NOT_FOUND '+[string]$x.sample)};$result.researchFilled=$true
  $result.stage='RESEARCH_SUBMIT';$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};const ds=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);const root=ds[ds.length-1]||document;for(const e of [...root.querySelectorAll('button,[role=button]')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title'),e.querySelector('mat-icon')?.textContent].join(' ')).toLowerCase();if(/search|검색/.test(raw)){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,raw:raw.slice(0,120)}}}return {ok:false,sample:(root.innerText||'').slice(0,1600)}})()";if(-not$x.ok){throw('RESEARCH_SEARCH_BUTTON_NOT_FOUND '+[string]$x.sample)};Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.researchSubmitted=$true
  $result.stage='WAIT_RESEARCH_RESULTS';$deadline=(Get-Date).AddSeconds([Math]::Max(60,$ResearchTimeoutSeconds));do{Start-Sleep -Seconds 2;$v=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const ds=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);const root=ds[ds.length-1]||document;const t=root.innerText||'';const checks=[...root.querySelectorAll('input[type=checkbox],[role=checkbox],mat-checkbox')].filter(vis);const buttons=[...root.querySelectorAll('button,[role=button]')].filter(vis).map(e=>String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).trim()).filter(Boolean);return {checks:checks.length,hasImport:buttons.some(x=>/가져오기|추가|import|add/i.test(x)&&!/소스 추가|add source/i.test(x)),busy:/검색 중|searching|researching|조사 중|찾는 중/i.test(t),sample:t.slice(0,2200),buttons:buttons.slice(-25)}})()";if(($v.checks-gt0-or$v.hasImport)-and-not$v.busy){$result.researchResultsReady=$true;$result.evidence.research=$v;break}}while((Get-Date)-lt$deadline);if(-not$result.researchResultsReady){$result.evidence.research=$v;throw'RESEARCH_RESULTS_NOT_READY'}
  $result.stage='IMPORT_SOURCES';$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const ds=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);const root=ds[ds.length-1]||document;for(const c of [...root.querySelectorAll('input[type=checkbox],[role=checkbox],mat-checkbox')].filter(vis).slice(0,5)){const checked=c.checked===true||c.getAttribute('aria-checked')==='true'||c.classList.contains('mat-mdc-checkbox-checked');if(!checked){try{c.click()}catch{}}}for(const e of [...root.querySelectorAll('button,[role=button]')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).trim();const t=raw.toLowerCase();if((/가져오기|import|추가|add/.test(t))&&!/소스 추가|add source/.test(t)){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:raw.slice(0,120)}}}return {ok:false,sample:(root.innerText||'').slice(0,1800)}})()";if(-not$x.ok){throw('IMPORT_SOURCES_BUTTON_NOT_FOUND '+[string]$x.sample)};Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.sourcesImported=$true
  $result.stage='VERIFY_SOURCE_COUNT';$deadline=(Get-Date).AddSeconds(60);do{Start-Sleep -Seconds 2;$v=Eval $ws ([ref]$seq) "(() => {const t=document.body?.innerText||'';const m=t.match(/소스\s*([0-9]+)건/i)||t.match(/([0-9]+)\s*sources?/i);return {count:m?Number(m[1]):0,sample:t.slice(0,2200)}})()";if($v.count-gt0){$result.sourceCountVerified=$true;$result.evidence.sourceCount=$v;break}}while((Get-Date)-lt$deadline);if(-not$result.sourceCountVerified){$result.evidence.sourceCount=$v;throw'SOURCE_COUNT_ZERO_AFTER_IMPORT'}
  $result.stage='CHAT_TAB';$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim().toLowerCase();if(raw==='채팅'||raw==='chat'){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if(-not$x.ok){throw'CHAT_TAB_NOT_FOUND'};Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.chatSelected=$true;Start-Sleep -Milliseconds 700
  $result.stage='CHAT_FILL';$pj=$PromptText|ConvertTo-Json -Compress;$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const all=[...document.querySelectorAll('textarea,[role=textbox],[contenteditable=true],[contenteditable=plaintext-only]')].filter(vis);const e=all.find(x=>/질문|창작|ask|create|message|prompt/i.test(String([x.getAttribute('placeholder'),x.getAttribute('aria-label'),x.getAttribute('data-placeholder')].join(' '))))||all[all.length-1];if(!e)return {ok:false};e.focus();const v=$pj;if('value'in e){const p=e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype;const s=Object.getOwnPropertyDescriptor(p,'value')?.set;if(s)s.call(e,v);else e.value=v;}else{e.textContent=v;}e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:v}));e.dispatchEvent(new Event('change',{bubbles:true}));return {ok:true}})()";if(-not$x.ok){throw'CHAT_EDITOR_NOT_FOUND'};$result.promptFilled=$true
  $result.stage='CHAT_SUBMIT';$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};for(const e of [...document.querySelectorAll('button,[role=button]')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title'),e.querySelector('mat-icon')?.textContent].join(' ')).toLowerCase();if(/send|submit|보내기|전송|arrow_upward|arrow_forward/.test(raw)){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if(-not$x.ok){throw'CHAT_SEND_ARROW_NOT_FOUND'};Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.promptSubmitted=$true
  $result.stage='WAIT_CHAT_SETTLED';$deadline=(Get-Date).AddSeconds([Math]::Max(45,$ChatTimeoutSeconds));do{Start-Sleep -Seconds 2;$v=Eval $ws ([ref]$seq) "(() => {const t=document.body?.innerText||'';return {busy:/페이지 읽는 중|소스 참조 중|generating|생성 중|검색 중|searching/i.test(t),marker:t.includes('NLM_FRESH_ALL_20260829_1915'),sample:t.slice(0,2500)}})()";if(-not$v.busy){$result.chatSettled=$true;$result.evidence.chat=$v;break}}while((Get-Date)-lt$deadline)
  $result.stage='STUDIO';$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('[role=tab],button,[role=button],a')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).trim().toLowerCase();if(raw==='스튜디오'||raw==='studio'){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if(-not$x.ok){throw'STUDIO_TAB_NOT_FOUND'};Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.studioSelected=$true;Start-Sleep -Seconds 1
  $result.stage='AUDIO';$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};for(const e of [...document.querySelectorAll('button,[role=button],a,div[tabindex]')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).toLowerCase();if(raw.includes('ai 오디오 오버뷰')||raw.includes('audio overview')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if(-not$x.ok){throw'AUDIO_OVERVIEW_CONTROL_NOT_FOUND'};Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.audioClicked=$true;Start-Sleep -Seconds 1
  $result.stage='AUDIO_GENERATE';$x=Eval $ws ([ref]$seq) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};const ds=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(vis);const root=ds[ds.length-1]||document;for(const e of [...root.querySelectorAll('button,[role=button]')].filter(vis)){const raw=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).trim().toLowerCase();if(raw==='생성'||raw==='만들기'||raw==='generate'||raw==='create'||raw.startsWith('생성 ')){const r=e.getBoundingClientRect();return {ok:true,x:r.left+r.width/2,y:r.top+r.height/2}}}return {ok:false}})()";if($x.ok){Click $ws ([ref]$seq) ([double]$x.x) ([double]$x.y);$result.generateClicked=$true};$result.ok=($result.sourceCountVerified-and$result.promptSubmitted-and$result.studioSelected-and$result.audioClicked);$result.stage=if($result.generateClicked){'AUDIO_GENERATION_STARTED'}else{'AUDIO_SETTINGS_OPENED'}
}catch{$result.error=$_.Exception.Message}finally{if($ws){try{$ws.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o')}
$result|ConvertTo-Json -Depth 30 -Compress
if($result.ok){exit 0}else{exit 2}
