param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='appscript-0.3.2-webapp05-exact-script-readonly-source-inspector'
$ScriptId='1XzludErvxZ3px6qf1aLNU4LZWVU9NqJXYzSrnOm0HoDjUR9XN8flhSir'
$CanonicalEmail='homedesigntaedi@gmail.com'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$Receipt='APPSCRIPT_WEBAPP05_EXACT_SCRIPT_SOURCE_INSPECTOR_0.3.2.json'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function FindCentral{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};''}
function Save($o){$j=$o|ConvertTo-Json -Depth 60;$j|Set-Content -LiteralPath (Join-Path $Root $Receipt) -Encoding UTF8;try{$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$j|Set-Content -LiteralPath (Join-Path $d $Receipt) -Encoding UTF8}}catch{}}
function ClaspPath{foreach($name in @('clasp.cmd','clasp.ps1','clasp')){$c=Get-Command $name -ErrorAction SilentlyContinue;if($c){return $c.Source}};foreach($p in @((Join-Path $env:APPDATA 'npm\clasp.cmd'),(Join-Path $env:APPDATA 'npm\clasp.ps1'))){if(Test-Path -LiteralPath $p){return $p}};''}
function RunClasp([string]$Clasp,[string[]]$ClaspArgs,[int]$TimeoutSec=60,[string]$Cwd=''){$psi=New-Object Diagnostics.ProcessStartInfo;$ext=[IO.Path]::GetExtension($Clasp).ToLowerInvariant();if($ext-eq'.cmd'){$psi.FileName=$env:ComSpec;$psi.Arguments='/d /s /c ""'+$Clasp+'" '+(($ClaspArgs|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')+'"'}elseif($ext-eq'.ps1'){$psi.FileName='powershell.exe';$psi.Arguments='-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$Clasp+'" '+(($ClaspArgs|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')}else{$psi.FileName=$Clasp;$psi.Arguments=(($ClaspArgs|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')};$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;if($Cwd){$psi.WorkingDirectory=$Cwd};$p=[Diagnostics.Process]::Start($psi);if(-not$p.WaitForExit($TimeoutSec*1000)){try{$p.Kill()}catch{};return [ordered]@{ok=$false;exit=124;stdout='';stderr='TIMEOUT'}};[ordered]@{ok=($p.ExitCode-eq0);exit=$p.ExitCode;stdout=$p.StandardOutput.ReadToEnd();stderr=$p.StandardError.ReadToEnd()}}
$r=[ordered]@{ok=$false;action='READONLY_EXACT_SCRIPT_SOURCE_INSPECT';version=$Version;scriptId=$ScriptId;authorizedUser='';authorizedUserOk=$false;fileCount=0;files=@();functions=@();signatures=[ordered]@{processTaskQueue=$false;contentOsUnifiedSchedulerTick=$false;doPost=$false;doGet=$false;spreadsheetApp=$false};stage='START';error='';readOnly=$true;newProject=$false;newDeployment=$false;newTrigger=$false;oauthChanged=$false;startedAt=(Get-Date).ToString('o');completedAt=''}
try{$clasp=ClaspPath;if(-not$clasp){throw'CLASP_NOT_FOUND'};$auth=RunClasp $clasp @('show-authorized-user','--json') 45;$r.authorizedUser=($auth.stdout+' '+$auth.stderr).Trim();$r.authorizedUserOk=($auth.ok-and$r.authorizedUser.ToLowerInvariant().Contains($CanonicalEmail));if(-not$r.authorizedUserOk){throw'AUTH_READBACK_FAIL'};$dir=Join-Path $env:TEMP ('webapp05-source-inspect-'+(Get-Date -Format 'yyyyMMdd_HHmmss'));New-Item -ItemType Directory -Force -Path $dir|Out-Null;$r.stage='CLONE';$c=RunClasp $clasp @('clone-script',$ScriptId) 120 $dir;if(-not$c.ok){$c=RunClasp $clasp @('clone',$ScriptId) 120 $dir};if(-not$c.ok){throw('CLONE_FAIL '+$c.stderr)};$r.stage='INSPECT';$funcs=New-Object System.Collections.Generic.HashSet[string];foreach($f in @(Get-ChildItem -LiteralPath $dir -Recurse -File -ErrorAction SilentlyContinue)){$rel=$f.FullName.Substring($dir.Length).TrimStart('\');$entry=[ordered]@{path=$rel;extension=$f.Extension;bytes=[int64]$f.Length;textRead=$false};if($f.Length-lt2097152){try{$txt=Get-Content -LiteralPath $f.FullName -Raw -Encoding UTF8 -ErrorAction Stop;$entry.textRead=$true;if($txt-match'processTaskQueue'){$r.signatures.processTaskQueue=$true};if($txt-match'contentOsUnifiedSchedulerTick'){$r.signatures.contentOsUnifiedSchedulerTick=$true};if($txt-match'function\s+doPost\s*\('){$r.signatures.doPost=$true};if($txt-match'function\s+doGet\s*\('){$r.signatures.doGet=$true};if($txt-match'SpreadsheetApp'){$r.signatures.spreadsheetApp=$true};foreach($m in [regex]::Matches($txt,'(?m)\bfunction\s+([A-Za-z_$][A-Za-z0-9_$]*)\s*\(')){[void]$funcs.Add([string]$m.Groups[1].Value)}}catch{}};$r.files+=,$entry};$r.fileCount=$r.files.Count;$r.functions=@($funcs|Sort-Object);$r.ok=$true;$r.stage='DONE'}catch{$r.error=$_.Exception.Message;$r.stage='ERROR'}finally{$r.completedAt=(Get-Date).ToString('o');Save $r};$r|ConvertTo-Json -Depth 60 -Compress;if($r.ok){exit 0}else{exit 2}
