param()

$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$AgentVersion='1.1.50'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
$LegacyAgent=Join-Path $Root 'HomeDesignLocalAgent-1.1.46.ps1'
$LegacyAgentUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/releases/1.1.46/HomeDesignLocalAgent.ps1'
$LegacyAgentSha='b72e57af70f77578fddb3de49f6581a37e2de792'
$PowerHelper=Join-Path $Root 'Setup-PowerContinuity.ps1'
$PowerHelperUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/capture/Setup-PowerContinuity.ps1'
$PowerHelperSha='7d6e2578fbbc78c12687dd0f701778517d204f51'
$QueueMarker=Join-Path $Root 'queue-integrity-sync-v2-1.1.45-dispatch.json'
$PersonaMarker=Join-Path $Root 'persona-bind-v1-1.1.46-dispatch.json'
$State=Join-Path $Root 'state.json'
function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[] ($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function FetchPinned([string]$Url,[string]$Destination,[string]$ExpectedSha){$tmp=$Destination+'.download';Invoke-WebRequest -UseBasicParsing -Uri ($Url+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -OutFile $tmp -TimeoutSec 30;$actual=(GitBlobSha1 $tmp).ToLowerInvariant();if($actual -ne $ExpectedSha.ToLowerInvariant()){Remove-Item $tmp -Force -ErrorAction SilentlyContinue;throw ('SHA_MISMATCH:'+$actual+':'+$ExpectedSha)};Move-Item -LiteralPath $tmp -Destination $Destination -Force;return $actual}
function FindCentralRoot{$centralName=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$myDriveKo=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($drv in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(-not $drv.Root){continue};foreach($cand in @((Join-Path $drv.Root $centralName),(Join-Path $drv.Root ($myDriveKo+'\'+$centralName)),(Join-Path $drv.Root ('My Drive\'+$centralName)),(Join-Path $drv.Root ('Google Drive\'+$centralName)))){if(Test-Path -LiteralPath $cand -PathType Container){return $cand}}};return ''}
function SaveJson([string]$Path,$Object){if(-not $Path){return};$parent=Split-Path -Parent $Path;if($parent){New-Item -ItemType Directory -Force -Path $parent|Out-Null};$Object|ConvertTo-Json -Depth 60|Set-Content -LiteralPath $Path -Encoding UTF8}
function ReadJson([string]$Path){if(-not $Path -or -not(Test-Path -LiteralPath $Path)){return $null};try{return Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{return $null}}
function MarkerAlive([string]$Path){$m=ReadJson $Path;if(-not $m -or -not $m.pid){return $false};try{return [bool](Get-Process -Id ([int]$m.pid) -ErrorAction SilentlyContinue)}catch{return $false}}
function RecoverMarkerOnce([string]$Marker,[string]$Result,[string]$ExpectedSourceSha,[string]$TicketName){if(-not(Test-Path -LiteralPath $Marker)){return $false};if($Result -and (Test-Path -LiteralPath $Result)){return $false};if(MarkerAlive $Marker){return $false};$m=ReadJson $Marker;if(-not $m -or [string]$m.sourceSha -ne $ExpectedSourceSha){return $false};$ticket=Join-Path $Root $TicketName;if(Test-Path -LiteralPath $ticket){return $false};$stale=$Marker+'.stale.'+(Get-Date -Format 'yyyyMMdd_HHmmss');Move-Item -LiteralPath $Marker -Destination $stale -Force;SaveJson $ticket ([ordered]@{ok=$true;action='ABANDONED_DISPATCH_MARKER_RECOVERY_ONCE';sourceSha=$ExpectedSourceSha;staleMarker=$stale;at=(Get-Date).ToString('o')});return $true}
function InvokeChild([string]$Path,[string[]]$ScriptArgs){$all=@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$Path)+@($ScriptArgs);$out=& powershell.exe @all 2>&1|Out-String;return [ordered]@{exitCode=$LASTEXITCODE;stdout=$out.Trim();args=@($ScriptArgs)}}
function LastJson([string]$Text){$parsed=$null;foreach($line in @($Text -split "`r?`n")){if(-not $line -or -not $line.Trim()){continue};try{$c=$line.Trim()|ConvertFrom-Json;if($c -and $null -ne $c.ok){$parsed=$c}}catch{}};return $parsed}
function PowerDesired($Status){if(-not $Status -or -not [bool]$Status.ok){return $false};$s=$Status.state;if(-not $s -or -not [bool]$s.ok){return $false};if(-not $Status.watchdog -or -not [bool]$Status.watchdog.exists){return $false};if(-not $Status.night -or -not [bool]$Status.night.exists){return $false};return [bool]([string]$s.nightStart -eq '02:00' -and [string]$s.nightEnd -eq '05:00' -and [int]$s.idleDisplayMinutes -eq 30 -and [string]$s.acAutomaticSleep -eq 'DISABLED' -and [string]$s.acAutomaticHibernate -eq 'DISABLED' -and [string]$s.acUsbSelectiveSuspend -eq 'DISABLED' -and [string]$s.keyboardFreezeGuard -eq 'NO_AC_SLEEP_RESUME_PLUS_USB_SELECTIVE_SUSPEND_DISABLED' -and [string]$s.persistenceMode -eq 'HKCU_RUN_RESIDENT_WATCHER')}
$central=FindCentralRoot;$runtimeRoot='';$queueResult='';$personaResult='';if($central){$runtimeRoot=Join-Path $central 'Runtime_Readback';$queueResult=Join-Path $runtimeRoot 'AppsScript_QueueIntegrity\NOTEBOOKLM_QUEUE_INTEGRITY_SYNC.json';$personaResult=Join-Path $runtimeRoot 'AppsScript_Persona\WEBAPP_TEMPLATE_05_PERSONA_BIND_V1.json'}
$errors=@();$legacySha='';$helperSha='';$legacyRun=$null;$legacyParsed=$null;$queueRecovered=$false;$personaRecovered=$false;$before=$null;$install=$null;$after=$null;$installed=$false
try{$legacySha=FetchPinned $LegacyAgentUrl $LegacyAgent $LegacyAgentSha;$queueRecovered=RecoverMarkerOnce $QueueMarker $queueResult '9a06c6ef475a6427a04258c1ff84ebdc2ce498a3' 'queue-integrity-sync-v2-1.1.45-marker-recovery.once.json';$personaRecovered=RecoverMarkerOnce $PersonaMarker $personaResult '186e987af8cb61e7a11242a6a2c69251ec0e1c73' 'persona-bind-v1-1.1.46-marker-recovery.once.json';$legacyRun=InvokeChild $LegacyAgent @();$legacyParsed=LastJson ([string]$legacyRun.stdout)}catch{$errors+=('LEGACY_AGENT:'+$_.Exception.Message)}
try{$helperSha=FetchPinned $PowerHelperUrl $PowerHelper $PowerHelperSha;$r=InvokeChild $PowerHelper @('-StatusOnly');$before=LastJson ([string]$r.stdout);if(-not(PowerDesired $before)){$installed=$true;$r=InvokeChild $PowerHelper @('-Install','-NightStart','02:00','-NightEnd','05:00','-IdleDisplayMinutes','30');$install=LastJson ([string]$r.stdout);if([int]$r.exitCode -ne 0 -or -not $install -or -not [bool]$install.ok){throw ('POWER_INSTALL_FAILED:'+ [string]$r.exitCode+':'+[string]$r.stdout)}};$r=InvokeChild $PowerHelper @('-StatusOnly');$after=LastJson ([string]$r.stdout);if(-not(PowerDesired $after)){throw ('POWER_READBACK_MISMATCH:'+ [string]$r.stdout)}}catch{$errors+=('POWER_CONTINUITY:'+$_.Exception.Message)}
$powerOk=[bool]($helperSha -eq $PowerHelperSha -and (PowerDesired $after));$legacyOk=[bool]($legacySha -eq $LegacyAgentSha -and $legacyRun -and [int]$legacyRun.exitCode -eq 0 -and $legacyParsed -and [bool]$legacyParsed.ok);$status=if($powerOk -and $legacyOk){'POWER_CONTINUITY_AND_LEGACY_GOVERNORS_PASS'}elseif($powerOk){'POWER_CONTINUITY_PASS_LEGACY_GOVERNOR_HOLD'}else{'POWER_CONTINUITY_FAILED'}
$receipt=[ordered]@{ok=$powerOk;governanceOk=$legacyOk;action='AGENT_1.1.50_POWER_CONTINUITY_SELF_HEAL';agentVersion=$AgentVersion;status=$status;legacyAgentVersion='1.1.46';legacyAgentSha=$legacySha;legacyExitCode=if($legacyRun){$legacyRun.exitCode}else{$null};legacyResult=$legacyParsed;queueMarkerRecoveredOnce=$queueRecovered;personaMarkerRecoveredOnce=$personaRecovered;powerHelperSha=$helperSha;powerInstalledThisCycle=$installed;powerStatusBefore=$before;powerInstallResult=$install;powerContinuity=$after;requiredPolicy=[ordered]@{idleDisplayMinutes=30;nightStart='02:00';nightEnd='05:00';acAutomaticSleep='DISABLED';acAutomaticHibernate='DISABLED';acUsbSelectiveSuspend='DISABLED';keyboardFreezeGuard='NO_AC_SLEEP_RESUME_PLUS_USB_SELECTIVE_SUSPEND_DISABLED';persistenceMode='HKCU_RUN_RESIDENT_WATCHER';batterySleepAndUsbPolicyOverride=$false};newProjectCreated=$false;oauthChanged=$false;scopeChanged=$false;newDeployment=$false;newTrigger=$false;paidGeminiApiCalled=$false;generateClicked=$false;creditSpend=$false;normalChromeRestarted=$false;errors=$errors;at=(Get-Date).ToString('o')}
if($runtimeRoot){SaveJson (Join-Path $runtimeRoot 'AGENT_1.1.50_POWER_CONTINUITY_SELF_HEAL.json') $receipt;SaveJson (Join-Path $runtimeRoot 'POWER_CONTINUITY_RUNTIME_READBACK.json') $receipt}
try{$s=ReadJson $State;if(-not $s){$s=[pscustomobject]@{}};$s|Add-Member agentVersion $AgentVersion -Force;$s|Add-Member agentMode 'POWER_CONTINUITY_SELF_HEAL_1.1.50' -Force;$s|Add-Member ok $powerOk -Force;$s|Add-Member governanceOk $legacyOk -Force;$s|Add-Member status $status -Force;$s|Add-Member powerContinuityOk $powerOk -Force;$s|Add-Member updatedAt ((Get-Date).ToString('o')) -Force;SaveJson $State $s}catch{}
$receipt|ConvertTo-Json -Depth 60 -Compress;if($powerOk){exit 0}else{exit 2}
