param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.114'
$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($my+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveCentral([string]$Name,$Object){try{$j=$Object|ConvertTo-Json -Depth 80;$j|Set-Content -LiteralPath (Join-Path $Root $Name) -Encoding UTF8;$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$j|Set-Content -LiteralPath (Join-Path $d $Name) -Encoding UTF8}}catch{}}
function Tabs{$r=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3;$o=$r.Content|ConvertFrom-Json;$a=@();if($o -is [System.Array]){foreach($x in $o){$a+=$x}}elseif($null-ne$o){$a+=$o};return $a}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$sec*1000));try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($r.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_CLOSED'};$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);return([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 30 -Compress;$bb=[Text.Encoding]::UTF8.GetBytes($j);$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};return $r.result.value}
function Connect([string]$u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};return $w}
$result=[ordered]@{ok=$false;action='AGENT_1.1.114_CHAT_SEND_CONTROL_CHROME_READONLY';version=$Version;targetUrl=$TargetUrl;startedAt=(Get-Date).ToString('o');cdpBrowser='';protocolVersion='';pageCount=0;notebookPageCount=0;dedicatedProcesses=@();exactTab=$false;editor=$null;nearButtons=@();allButtons=@();normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;stage='START';error=''}
$w=$null
try{
 $v=Invoke-RestMethod -Uri ("http://127.0.0.1:$Port/json/version") -TimeoutSec 3;$result.cdpBrowser=[string]$v.Browser;$result.protocolVersion=[string]$v.'Protocol-Version'
 $pages=@(Tabs|Where-Object{[string]$_.type-eq'page'});$result.pageCount=$pages.Count;$result.notebookPageCount=@($pages|Where-Object{[string]$_.url-like'https://notebook.google.com/*'}).Count
 $userData=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\ChromeUserData';foreach($p in @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like ('*'+$userData+'*')})){$path='';$fv='';try{$gp=Get-Process -Id ([int]$p.ProcessId) -ErrorAction Stop;$path=[string]$gp.Path;if($path-and(Test-Path -LiteralPath $path)){$fv=[string](Get-Item -LiteralPath $path).VersionInfo.FileVersion}}catch{};$result.dedicatedProcesses+=,[ordered]@{pid=[int]$p.ProcessId;path=$path;fileVersion=$fv;commandLine=[string]$p.CommandLine}}
 $tab=$pages|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1;if(-not$tab){throw 'EXACT_NOTEBOOK_TAB_NOT_FOUND'};$result.exactTab=$true
 $w=Connect([string]$tab.webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{})
 $snap=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const es=[...document.querySelectorAll('textarea,[contenteditable=true]')].filter(vis);const e=es.find(x=>{const p=String(x.getAttribute('placeholder')||'');const a=String(x.getAttribute('aria-label')||'');return p.includes('\\uC9C8\\uBB38')||p.includes('\\uCC3D\\uC791')||a.includes('\\uCFFC\\uB9AC')||/ask|create/i.test(p)})||es[0];if(!e)return{ok:false,editorCount:es.length};const er=e.getBoundingClientRect();const value=String(('value'in e?e.value:e.textContent)||'');const buttons=[...document.querySelectorAll('button,[role=button]')].filter(vis).map(b=>{const r=b.getBoundingClientRect();const icon=String(b.querySelector('mat-icon')?.textContent||'').trim();return{tag:b.tagName,aria:String(b.getAttribute('aria-label')||''),title:String(b.getAttribute('title')||''),text:String(b.innerText||b.textContent||'').trim().slice(0,120),icon:icon,disabled:Boolean(b.disabled)||String(b.getAttribute('aria-disabled')).toLowerCase()==='true',x:r.left,y:r.top,w:r.width,h:r.height,cx:r.left+r.width/2,cy:r.top+r.height/2}});const near=buttons.filter(b=>b.x>=er.right-180&&b.x<=er.right+160&&b.y>=er.top-120&&b.y<=er.bottom+120);return{ok:true,editor:{placeholder:e.getAttribute('placeholder')||'',aria:e.getAttribute('aria-label')||'',valueLength:value.length,valueStart:value.slice(0,120),x:er.left,y:er.top,w:er.width,h:er.height,right:er.right,bottom:er.bottom},nearButtons:near,allButtons:buttons.slice(-80)}})()";if(-not$snap.ok){throw 'CHAT_EDITOR_READONLY_NOT_FOUND'};$result.editor=$snap.editor;$result.nearButtons=@($snap.nearButtons);$result.allButtons=@($snap.allButtons);$result.ok=$true;$result.stage='DONE'
}catch{$result.error=$_.Exception.Message}
finally{if($w){try{$w.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o');SaveCentral 'AGENT_1.1.114_CHAT_SEND_CONTROL_CHROME_READONLY_RESULT.json' $result}
$result|ConvertTo-Json -Depth 80 -Compress
if($result.ok){exit 0}else{exit 2}
