param()
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$AgentVersion='1.1.19'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$Root=Join-Path $Base 'LocalAgent'
$ExtensionRoot=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge'
$UserData=Join-Path $Base 'ChromeUserData'
$CftRoot=Join-Path $Base 'ChromeForTesting'
$GovRoot=Join-Path $Base 'ChromeGovernor'
$BackupRoot=Join-Path $Root 'Backups'
$StateFile=Join-Path $Root 'state.json'
$ReadbackFile=Join-Path $Root 'VIDEO_LOCAL_RUNTIME_READBACK.json'
$JobStateFile=Join-Path $Root 'video-job-state.json'
$HostFile=Join-Path $Root 'HomeDesignLocalCommandHost.ps1'
$WorkerFile=Join-Path $Root 'HomeDesignVideoAutoWorkerV2.ps1'
$NodeGov=Join-Path $GovRoot 'chromeGovernorFast.js'
$Policy=Join-Path $GovRoot 'policy.json'
$ReleaseFile=Join-Path $GovRoot 'release.json'
$GovState=Join-Path $GovRoot 'state.json'
$Inventory=Join-Path $GovRoot 'inventory.json'
$NormalRoot=Join-Path $env:LOCALAPPDATA 'Google\Chrome\User Data'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$HostPath='local-agent/releases/1.2.2/HomeDesignLocalCommandHost.ps1'
$HostSha='4704cbf9c8c4d8b702bdd819635a1b420e21a1b7'
$WorkerPath='local-agent/worker/HomeDesignVideoAutoWorkerV2.ps1'
$WorkerSha='7c428ae1f897d0409925bc3479ebaedea577665e'
$NodePath='local-agent/governor/chromeGovernorFast.js'
$NodeSha='6b2cc50985e72bfc1d271bcfde675bfb4a77427c'
New-Item -ItemType Directory -Force -Path $Root,$ExtensionRoot,$GovRoot,$BackupRoot|Out-Null

function ReadJson([string]$Path){if(-not(Test-Path -LiteralPath $Path)){return $null};try{return Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{return $null}}
function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[] ($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function ApiFile([string]$Path,[string]$Ref='main',[int]$Timeout=10){$H=@{'User-Agent'='HomeDesign-Local-Agent';'Accept'='application/vnd.github+json'};$U="https://api.github.com/repos/$Repo/contents/$Path?ref=$([Uri]::EscapeDataString($Ref))";return Invoke-RestMethod -Uri $U -Headers $H -Method Get -TimeoutSec $Timeout}
function ApiBytes($R){return [Convert]::FromBase64String(([string]$R.content -replace '\s',''))}
function EnsureApiFile([string]$RepoPath,[string]$LocalPath,[string]$Expected,[int]$Timeout=12){$Need=(-not(Test-Path -LiteralPath $LocalPath));if(-not $Need){$Need=((GitBlobSha1 $LocalPath).ToLowerInvariant() -ne $Expected.ToLowerInvariant())};if(-not $Need){return $false};$R=ApiFile $RepoPath 'main' $Timeout;if(([string]$R.sha).ToLowerInvariant() -ne $Expected.ToLowerInvariant()){throw "API_SHA_MISMATCH path=$RepoPath api=$($R.sha) expected=$Expected"};$Tmp=$LocalPath+'.download';[IO.File]::WriteAllBytes($Tmp,(ApiBytes $R));$Actual=(GitBlobSha1 $Tmp).ToLowerInvariant();if($Actual -ne $Expected.ToLowerInvariant()){Remove-Item $Tmp -Force -ErrorAction SilentlyContinue;throw "FILE_SHA_MISMATCH path=$RepoPath actual=$Actual expected=$Expected"};Move-Item $Tmp $LocalPath -Force;return $true}
function WriteApiText([string]$RepoPath,[string]$LocalPath,[int]$Timeout=10){$R=ApiFile $RepoPath 'main' $Timeout;$Tmp=$LocalPath+'.download';[IO.File]::WriteAllBytes($Tmp,(ApiBytes $R));Move-Item $Tmp $LocalPath -Force;return Get-Content $LocalPath -Raw -Encoding UTF8}
function Proc([string]$Needle,[string]$Name='powershell.exe'){try{return @(Get-CimInstance Win32_Process -Filter "Name='$Name'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like "*$Needle*"})}catch{return @()}}
function KillTree([int]$ProcessId){try{& taskkill.exe /PID $ProcessId /T /F 2>$null|Out-Null}catch{try{Stop-Process -Id $ProcessId -Force -ErrorAction SilentlyContinue}catch{}}}
function StartHidden([string]$File,[string[]]$Extra=@()){$A=@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',"`"$File`"")+$Extra;Start-Process powershell.exe -ArgumentList $A -WindowStyle Hidden|Out-Null}
function HostHealth{try{return Invoke-RestMethod -Uri 'http://127.0.0.1:8765/health' -Method Get -TimeoutSec 3}catch{return $null}}
function Host122{$H=HostHealth;return ($H -and [bool]$H.ok -and [string]$H.version -eq '1.2.2' -and [bool]$H.asyncJobs)}
function FindChrome(){if(-not(Test-Path -LiteralPath $CftRoot)){return $null};return Get-ChildItem -LiteralPath $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction SilentlyContinue|Sort-Object FullName -Descending|Select-Object -First 1}
function Dedicated(){try{return @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like "*$UserData*"})}catch{return @()}}
function StopDedicated(){foreach($P in @(Dedicated)){try{Stop-Process -Id ([int]$P.ProcessId) -Force -ErrorAction SilentlyContinue}catch{}};Start-Sleep -Seconds 2}
function LaunchDedicated([string]$Front){$C=FindChrome;if(-not $C){throw 'CHROME_FOR_TESTING_NOT_FOUND'};$Args=@("--user-data-dir=$UserData",'--profile-directory=Default',"--load-extension=$ExtensionRoot",'--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',$Front);$Psi=New-Object Diagnostics.ProcessStartInfo;$Psi.FileName=$C.FullName;$Psi.WorkingDirectory=$C.Directory.FullName;$Psi.UseShellExecute=$false;$Psi.Arguments=($Args|ForEach-Object{if($_ -match '\s'){'"'+$_+'"'}else{$_}})-join ' ';[void][Diagnostics.Process]::Start($Psi);Start-Sleep -Seconds 6;if((Dedicated).Count -le 0){throw 'DEDICATED_CHROME_START_FAILED'}}
function TestRelease($Rel){try{foreach($F in @($Rel.files)){$P=Join-Path $ExtensionRoot ([string]$F.path).Replace('/','\');if(-not(Test-Path -LiteralPath $P)){return $false};if((GitBlobSha1 $P).ToLowerInvariant() -ne ([string]$F.gitBlobSha1).ToLowerInvariant()){return $false}};$M=ReadJson (Join-Path $ExtensionRoot 'manifest.json');return ($M -and [string]$M.version -eq [string]$Rel.version)}catch{return $false}}
function InstallRelease($Rel){$Stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$Stage=Join-Path $Root ('Stage\'+$Stamp);$Backup=Join-Path $BackupRoot $Stamp;New-Item -ItemType Directory -Force -Path $Stage,$Backup|Out-Null;foreach($F in @($Rel.files)){$Rp=[string]$F.path;if($Rp -match '\.\.' -or [IO.Path]::IsPathRooted($Rp)){throw 'UNSAFE_RELEASE_PATH'};$Dst=Join-Path $Stage $Rp.Replace('/','\');$Par=Split-Path $Dst -Parent;if($Par){New-Item -ItemType Directory -Force -Path $Par|Out-Null};$U=([string]$Rel.baseUrl).TrimEnd('/')+'/'+$Rp;Invoke-WebRequest -UseBasicParsing -Uri $U -OutFile $Dst -TimeoutSec 15;if((GitBlobSha1 $Dst).ToLowerInvariant() -ne ([string]$F.gitBlobSha1).ToLowerInvariant()){throw "EXTENSION_SHA_MISMATCH:$Rp"}};if(Test-Path -LiteralPath $ExtensionRoot){Copy-Item -LiteralPath $ExtensionRoot -Destination (Join-Path $Backup 'extension') -Recurse -Force};StopDedicated;Get-ChildItem -LiteralPath $ExtensionRoot -Force -ErrorAction SilentlyContinue|Remove-Item -Recurse -Force;Copy-Item (Join-Path $Stage '*') -Destination $ExtensionRoot -Recurse -Force;if(-not(TestRelease $Rel)){throw 'EXTENSION_POST_INSTALL_VERIFY_FAILED'};LaunchDedicated ([string]$Rel.frontUrl)}
function QuoteArgs([object[]]$Items){return (($Items|ForEach-Object{$S=[string]$_;if($S -match '[\s"]'){'"'+($S -replace '"','\"')+'"'}else{$S}})-join ' ')}
function RunNode{$Node=Get-Command node.exe -ErrorAction SilentlyContinue;if(-not $Node){$Node=Get-Command node -ErrorAction SilentlyContinue};if(-not $Node){return [ordered]@{ok=$false;exitCode=127;error='NODE_NOT_FOUND'}};$Args=@($NodeGov,'--normalRoot',$NormalRoot,'--dedicatedUserData',$UserData,'--dedicatedExtensionRoot',$ExtensionRoot,'--policy',$Policy,'--release',$ReleaseFile,'--agentState',$StateFile,'--report',$GovState,'--inventory',$Inventory);$Psi=New-Object Diagnostics.ProcessStartInfo;$Psi.FileName=$Node.Source;$Psi.UseShellExecute=$false;$Psi.CreateNoWindow=$true;$Psi.RedirectStandardOutput=$true;$Psi.RedirectStandardError=$true;$Psi.Arguments=QuoteArgs $Args;$P=New-Object Diagnostics.Process;$P.StartInfo=$Psi;[void]$P.Start();$OT=$P.StandardOutput.ReadToEndAsync();$ET=$P.StandardError.ReadToEndAsync();if(-not $P.WaitForExit(30000)){KillTree ([int]$P.Id);try{[void]$P.WaitForExit(3000)}catch{};return [ordered]@{ok=$false;exitCode=124;error='NODE_GOVERNOR_TIMEOUT_30S';stdout=$(if($OT.IsCompleted){$OT.Result.Trim()}else{''});stderr=$(if($ET.IsCompleted){$ET.Result.Trim()}else{''})}};$P.WaitForExit();return [ordered]@{ok=($P.ExitCode -eq 0);exitCode=$P.ExitCode;stdout=$(if($OT.IsCompleted){$OT.Result.Trim()}else{''});stderr=$(if($ET.IsCompleted){$ET.Result.Trim()}else{''})}}
function FindCentral{$Target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($D in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$R=[string]$D.Root;if(-not $R){continue};foreach($C in @((Join-Path $R $Target),(Join-Path $R ('My Drive\'+$Target)),(Join-Path $R ('내 드라이브\'+$Target)),(Join-Path $R ('Google Drive\'+$Target)))){if(Test-Path -LiteralPath $C){return $C}}};foreach($C in @((Join-Path $env:USERPROFILE ('My Drive\'+$Target)),(Join-Path $env:USERPROFILE ('내 드라이브\'+$Target)),(Join-Path $env:USERPROFILE ('Google Drive\'+$Target)))){if(Test-Path -LiteralPath $C){return $C}};return ''}

$Mutex=New-Object System.Threading.Mutex($false,'HomeDesignLocalAgent119')
if(-not $Mutex.WaitOne(0,$false)){exit 0}
try{
  $Errors=@();$HostChanged=$false;$WorkerChanged=$false;$ExtensionChanged=$false
  try{$HostChanged=EnsureApiFile $HostPath $HostFile $HostSha 12;if($HostChanged -or -not(Host122)){foreach($P in @(Proc 'HomeDesignLocalCommandHost.ps1')){KillTree ([int]$P.ProcessId)};Start-Sleep -Milliseconds 700;StartHidden $HostFile;$Deadline=(Get-Date).AddSeconds(15);do{Start-Sleep -Milliseconds 500}while(-not(Host122) -and (Get-Date)-lt $Deadline)};if(-not(Host122)){throw 'HOST_1.2.2_HEALTH_FAILED'}}catch{$Errors+=('HOST: '+$_.Exception.Message)}
  try{$WorkerChanged=EnsureApiFile $WorkerPath $WorkerFile $WorkerSha 12;foreach($P in @(Proc 'HomeDesignVideoAutoWorker.ps1')){KillTree ([int]$P.ProcessId)};if((Proc 'HomeDesignVideoAutoWorkerV2.ps1').Count -eq 0){StartHidden $WorkerFile}}catch{$Errors+=('WORKER: '+$_.Exception.Message)}
  $Rel=$null
  try{$ReleaseText=WriteApiText 'runtime/stable/release.json' $ReleaseFile 10;$Rel=$ReleaseText|ConvertFrom-Json;if(-not $Rel.enabled){throw 'BRIDGE_STABLE_DISABLED'};$Needs=-not(TestRelease $Rel);if($Needs){InstallRelease $Rel;$ExtensionChanged=$true}elseif((Dedicated).Count -le 0){LaunchDedicated ([string]$Rel.frontUrl)}}catch{$Errors+=('BRIDGE: '+$_.Exception.Message)}
  try{EnsureApiFile $NodePath $NodeGov $NodeSha 12|Out-Null;WriteApiText 'local-agent/governor/policy.json' $Policy 10|Out-Null}catch{$Errors+=('GOV_INPUT: '+$_.Exception.Message)}
  $GovRun=$(if((Test-Path $NodeGov) -and (Test-Path $Policy) -and (Test-Path $ReleaseFile)){RunNode}else{[ordered]@{ok=$false;exitCode=2;error='GOVERNOR_INPUT_MISSING'}})
  $H=HostHealth;$M=ReadJson (Join-Path $ExtensionRoot 'manifest.json');$J=ReadJson $JobStateFile;$G=ReadJson $GovState;$Central=FindCentral;$DriveOk=$false;$CoreOk=($H -and [bool]$H.ok -and [string]$H.version -eq '1.2.2' -and [bool]$H.asyncJobs -and $M -and $Rel -and [string]$M.version -eq [string]$Rel.version -and (Dedicated).Count -gt 0 -and (Test-Path $WorkerFile))
  $S=[ordered]@{ok=[bool]$CoreOk;status=$(if($CoreOk -and $GovRun.ok){'SELF_HEAL_PASS'}elseif($CoreOk){'SELF_HEAL_CORE_PASS_GOVERNOR_DEGRADED'}else{'SELF_HEAL_FAILED'});agentVersion=$AgentVersion;agentMode='THIN_DIRECT_WITH_BRIDGE_STABLE_SELF_HEAL';commandHostVersion=$(if($H){[string]$H.version}else{''});hostHealthy=$(if($H){[bool]$H.ok}else{$false});hostAsyncJobs=$(if($H){[bool]$H.asyncJobs}else{$false});extensionVersion=$(if($M){[string]$M.version}else{''});releaseActionId=$(if($Rel){[string]$Rel.actionId}else{''});dedicatedChromeRunning=((Dedicated).Count -gt 0);videoWorkerVersion='VIDEO_AUTO_WORKER_V2';videoWorkerInstalled=(Test-Path $WorkerFile);videoWorkerRunning=((Proc 'HomeDesignVideoAutoWorkerV2.ps1').Count -gt 0);videoJobState=$J;governorCycleOk=[bool]$GovRun.ok;governorExitCode=$GovRun.exitCode;governorError=$(if($GovRun.error){[string]$GovRun.error}else{[string]$GovRun.stderr});governorSummary=$(if($G){$G.summary}else{$null});hostChanged=$HostChanged;workerChanged=$WorkerChanged;extensionChanged=$ExtensionChanged;errors=$Errors;updatedAt=(Get-Date).ToString('o')}
  $S|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $StateFile -Encoding UTF8;$S|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $ReadbackFile -Encoding UTF8
  if($Central){try{$R=Join-Path $Central 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $R|Out-Null;$S|ConvertTo-Json -Depth 30|Set-Content -LiteralPath (Join-Path $R 'VIDEO_LOCAL_RUNTIME_READBACK.json') -Encoding UTF8;if(Test-Path $GovState){$GD=Join-Path $Central 'Chrome_Extension_Governor';New-Item -ItemType Directory -Force -Path $GD|Out-Null;Copy-Item $GovState (Join-Path $GD 'CHROME_EXTENSION_GOVERNOR_RESULT.json') -Force;if(Test-Path $Inventory){Copy-Item $Inventory (Join-Path $GD 'CHROME_EXTENSION_INVENTORY.json') -Force}};$DriveOk=$true}catch{$Errors+=('DRIVE: '+$_.Exception.Message)}}
  if($DriveOk){$S.governorDriveSyncOk=$true;$S.governorCentralPath=$Central;$S|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $StateFile -Encoding UTF8;$S|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $ReadbackFile -Encoding UTF8}
  if($CoreOk){exit 0}else{exit 19}
}catch{try{[ordered]@{ok=$false;status='SELF_HEAL_FAILED';agentVersion=$AgentVersion;lastError=$_.Exception.Message;updatedAt=(Get-Date).ToString('o')}|ConvertTo-Json -Depth 20|Set-Content -LiteralPath $StateFile -Encoding UTF8}catch{};exit 19}finally{try{$Mutex.ReleaseMutex()}catch{};$Mutex.Dispose()}
