param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.124'
$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$UserData=Join-Path $Base 'ChromeUserData'
$ExtensionRoot=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge'
$CftRoot=Join-Path $Base 'ChromeForTesting'
$Receipt='AGENT_1.1.124_GENERATION_ONLY_AUDIO_START_RESULT.json'
$MarkerFile=Join-Path $Root $Receipt
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($my+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveCentral($o){$j=$o|ConvertTo-Json -Depth 80;$j|Set-Content -LiteralPath $MarkerFile -Encoding UTF8;try{$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$j|Set-Content -LiteralPath (Join-Path $d $Receipt) -Encoding UTF8}}catch{}}
function DebugReady{try{$v=Invoke-RestMethod -Uri ("http://127.0.0.1:$Port/json/version") -TimeoutSec 2;return [bool]$v.webSocketDebuggerUrl}catch{return $false}}
function FindChrome{if(Test-Path -LiteralPath $CftRoot){$x=Get-ChildItem -LiteralPath $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction SilentlyContinue|Sort-Object FullName -Descending|Select-Object -First 1;if($x){return [string]$x.FullName}};foreach($c in @((Join-Path ${env:ProgramFiles} 'Google\Chrome\Application\chrome.exe'),(Join-Path ${env:ProgramFiles(x86)} 'Google\Chrome\Application\chrome.exe'),(Join-Path $env:LOCALAPPDATA 'Google\Chrome\Application\chrome.exe'))){if($c -and(Test-Path -LiteralPath $c)){return [string]$c}};throw 'CHROME_EXE_NOT_FOUND'}
function DedicatedProcs{try{return @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like ("*"+$UserData+"*")})}catch{return @()}}
function StartDedicated{if(DebugReady){return};foreach($p in @(DedicatedProcs)){try{Stop-Process -Id ([int]$p.ProcessId) -Force -ErrorAction SilentlyContinue}catch{}};Start-Sleep -Milliseconds 700;$chrome=FindChrome;$args=@("--remote-debugging-port=$Port",'--remote-allow-origins=*',"--user-data-dir=$UserData",'--profile-directory=Default',"--load-extension=$ExtensionRoot",'--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',$TargetUrl);Start-Process -FilePath $chrome -ArgumentList $args|Out-Null;$d=(Get-Date).AddSeconds(25);do{Start-Sleep -Milliseconds 400;if(DebugReady){return}}while((Get-Date)-lt$d);throw 'CDP_PORT_NOT_READY'}
function Tabs{$o=(Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3).Content|ConvertFrom-Json;return @($o|Where-Object{[string]$_.type-eq'page'})}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter($sec*1000);try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);return([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$bb=[Text.Encoding]::UTF8.GetBytes((@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 20 -Compress));$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};return $r.result.value}
function Click($w,[ref]$q,$x,$y){[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$x;y=$y});[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mousePressed';x=$x;y=$y;button='left';clickCount=1});Start-Sleep -Milliseconds 100;[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseReleased';x=$x;y=$y;button='left';clickCount=1})}
function Connect($u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};return $w}
function EnsureExactTab{StartDedicated;$pages=@(Tabs);$exact=$pages|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1;if(-not$exact){$tab=$pages|Where-Object{[string]$_.url-like'https://notebook.google.com/*'}|Select-Object -First 1;if(-not$tab){$tab=$pages|Select-Object -First 1};if($tab){$w=Connect([string]$tab.webSocketDebuggerUrl);try{$q=0;[void](Send $w ([ref]$q) 'Page.enable' @{});[void](Send $w ([ref]$q) 'Page.navigate' @{url=$TargetUrl})}finally{$w.Dispose()}}};$d=(Get-Date).AddSeconds(30);do{Start-Sleep -Milliseconds 500;$exact=@(Tabs|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1);if($exact){return $exact[0]}}while((Get-Date)-lt$d);throw 'EXACT_NOTEBOOK_TAB_NOT_VERIFIED'}
$result=[ordered]@{ok=$false;action='GENERATION_ONLY_AUDIO_START_ASCII_SAFE';version=$Version;targetUrl=$TargetUrl;startedAt=(Get-Date).ToString('o');exactTab=$false;studioSelected=$false;audioSelected=$false;generateClicked=$false;generationStarted=$false;studioCandidate='';audioCandidate='';generateCandidate='';controlDump=@();downloadAttempted=$false;driveMirrorAttempted=$false;normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;stage='START';error=''}
$w=$null
try{$result.stage='EXACT_TAB';$tab=EnsureExactTab;$result.exactTab=([string]$tab.url-eq$TargetUrl);if(-not$result.exactTab){throw 'EXACT_TAB_FAILED'};$w=Connect([string]$tab.webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{});Start-Sleep -Seconds 2
$result.stage='STUDIO';$x=Eval $w ([ref]$q) "(() => {const K=String.fromCharCode(49828,53804,46356,50724);const v=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const tabs=[...document.querySelectorAll('[role=tab]')].filter(v);let e=tabs.find(e=>String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).includes(K));if(!e&&tabs.length>=2)e=tabs[1];if(!e){const all=[...document.querySelectorAll('button,[role=button],a')].filter(v);e=all.find(e=>String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).toLowerCase().includes('studio'))}if(!e)return{ok:false,tabs:tabs.map(x=>String(x.innerText||x.textContent||'')).slice(0,10)};const r=e.getBoundingClientRect();return{ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:String(e.innerText||e.textContent||e.getAttribute('aria-label')||'')}})()";if(-not$x.ok){throw('STUDIO_TAB_NOT_FOUND '+($x.tabs|ConvertTo-Json -Compress))};$result.studioCandidate=[string]$x.text;Click $w ([ref]$q) $x.x $x.y;$result.studioSelected=$true;Start-Sleep -Seconds 2
$result.stage='AUDIO';$x=Eval $w ([ref]$q) "(() => {const K=String.fromCharCode(50724,46356,50724,32,50724,48260,48624);const v=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const all=[...document.querySelectorAll('button,[role=button],a,[role=option],[role=menuitem],div[tabindex]')].filter(v).map(e=>{const r=e.getBoundingClientRect(),m=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' '));return{e,r,m}});let a=all.filter(o=>o.m.includes(K)||o.m.toLowerCase().includes('audio overview'));if(!a.length)a=all.filter(o=>/audio/i.test(o.m));if(!a.length)return{ok:false,dump:all.map(o=>o.m.trim()).filter(Boolean).slice(0,80)};a.sort((p,n)=>(p.r.width*p.r.height)-(n.r.width*n.r.height));const o=a[0],r=o.r;return{ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:o.m.slice(0,180)}})()";if(-not$x.ok){$result.controlDump=@($x.dump);throw 'AUDIO_OVERVIEW_CONTROL_NOT_FOUND'};$result.audioCandidate=[string]$x.text;Click $w ([ref]$q) $x.x $x.y;$result.audioSelected=$true;Start-Sleep -Seconds 2
$result.stage='GENERATE';$g=Eval $w ([ref]$q) "(() => {const K=String.fromCharCode(49373,49457);const v=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled&&String(e.getAttribute('aria-disabled')).toLowerCase()!=='true'};const roots=[...document.querySelectorAll('[role=dialog],mat-dialog-container,.mat-mdc-dialog-container')].filter(v);const root=roots[roots.length-1]||document;const all=[...root.querySelectorAll('button,[role=button]')].filter(v).map(e=>{const r=e.getBoundingClientRect(),m=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).trim();return{e,r,m}});let a=all.filter(o=>{const t=o.m.toLowerCase();return o.m===K||o.m.startsWith(K+' ')||t==='generate'||t.startsWith('generate ')||t==='create'||t.startsWith('create ')});if(!a.length)return{ok:false,dump:all.map(o=>o.m).filter(Boolean).slice(-50)};const o=a[a.length-1],r=o.r;return{ok:true,x:r.left+r.width/2,y:r.top+r.height/2,text:o.m.slice(0,160)}})()";if(-not$g.ok){$result.controlDump=@($g.dump);throw 'GENERATE_CONTROL_NOT_FOUND'};$result.generateCandidate=[string]$g.text;Click $w ([ref]$q) $g.x $g.y;$result.generateClicked=$true;Start-Sleep -Seconds 3
$s=Eval $w ([ref]$q) "(() => {const a=String.fromCharCode(49373,49457,32,51473),b=String.fromCharCode(47564,46300,45716,32,51473),k=String.fromCharCode(50724,46356,50724,32,50724,48260,48624);const t=String(document.body?.innerText||'').toLowerCase();return{busy:t.includes(a)||t.includes(b)||t.includes('generating')||t.includes('creating'),audio:[...document.querySelectorAll('audio')].length,hasAudioText:t.includes(k)||t.includes('audio overview')}})()";$result.generationStarted=([bool]$s.busy -or [int]$s.audio -gt0 -or ($result.generateClicked-and[bool]$s.hasAudioText));$result.ok=($result.exactTab-and$result.studioSelected-and$result.audioSelected-and$result.generateClicked-and$result.generationStarted);if(-not$result.ok){throw 'GENERATION_START_NOT_VERIFIED'};$result.stage='DONE'}catch{$result.error=$_.Exception.Message;$result.stage='ERROR'}finally{if($w){try{$w.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o');SaveCentral $result};$result|ConvertTo-Json -Depth 80 -Compress;if($result.ok){exit 0}else{exit 2}
