param()
$ErrorActionPreference='Continue';$ProgressPreference='SilentlyContinue'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent';New-Item -ItemType Directory -Force -Path $Root|Out-Null
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge';$Base=Join-Path $Root 'HomeDesignLocalAgent-1.1.38-base.ps1';$Probe=Join-Path $Root 'Run-ExactTargetNotebookLMRegression-1.1.39.ps1';$State=Join-Path $Root 'state.json'
$BaseUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/releases/1.1.38/HomeDesignLocalAgent.ps1';$BaseSha='67aeac9fb3f147875c600baeaf9ef8d847f6f3f7';$ProbeUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/governor/Run-ExactTargetNotebookLMRegression.ps1';$ProbeSha='ebab97b3f5cf39d829ee162e644179c30e2f6ba2'
function GitBlob([string]$p){$b=[IO.File]::ReadAllBytes($p);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|%{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Fetch([string]$u,[string]$d,[string]$sha){$t=$d+'.download';Invoke-WebRequest -UseBasicParsing -Uri ($u+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -OutFile $t -TimeoutSec 30;$a=(GitBlob $t).ToLowerInvariant();if($a -ne $sha.ToLowerInvariant()){Remove-Item $t -Force -ErrorAction SilentlyContinue;throw ('SHA_MISMATCH:'+ $a+':'+$sha)};Move-Item $t $d -Force}
function RunPs([string]$p,[int]$sec){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName='powershell.exe';$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.Arguments='-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$p+'"';$x=New-Object Diagnostics.Process;$x.StartInfo=$psi;[void]$x.Start();$ot=$x.StandardOutput.ReadToEndAsync();$et=$x.StandardError.ReadToEndAsync();if(-not $x.WaitForExit($sec*1000)){try{& taskkill.exe /PID $x.Id /T /F 2>$null|Out-Null}catch{};return [ordered]@{ok=$false;exit=-1;timedOut=$true;stdout=$ot.Result;stderr=$et.Result}};return [ordered]@{ok=($x.ExitCode -eq 0);exit=$x.ExitCode;timedOut=$false;stdout=$ot.Result.Trim();stderr=$et.Result.Trim()}}
function Central{ $n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ('내 드라이브\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)))){if(Test-Path $c -PathType Container){return $c}}};return ''}
$baseRun=$null;$probeRun=$null;$err='';try{Fetch $BaseUrl $Base $BaseSha;$baseRun=RunPs $Base 480}catch{$err+='BASE:'+($_.Exception.Message)+';'};try{Fetch $ProbeUrl $Probe $ProbeSha;$probeRun=RunPs $Probe 180}catch{$err+='PROBE:'+($_.Exception.Message)+';'}
$ok=[bool]($probeRun -and $probeRun.ok -and $probeRun.stdout -match 'NOTEBOOKLM_EXACT_TARGET_X2_REGRESSION');$receipt=[ordered]@{ok=$ok;action='AGENT_1.1.39_EXACT_TARGET_CHROME_AUTOMATION';agentVersion='1.1.39';base=$baseRun;exactTargetRegression=$probeRun;normalChromeUntouchedRequired=$true;generateClicked=$false;creditSpend=$false;oauthChanged=$false;scopeChanged=$false;error=$err;at=(Get-Date).ToString('o')};$c=Central;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$receipt|ConvertTo-Json -Depth 60|Set-Content (Join-Path $d 'AGENT_1.1.39_EXACT_TARGET_CHROME_AUTOMATION.json') -Encoding UTF8}
try{$s=$null;if(Test-Path $State){$s=Get-Content $State -Raw -Encoding UTF8|ConvertFrom-Json};if(!$s){$s=[pscustomobject]@{}};$s|Add-Member agentVersion '1.1.39' -Force;$s|Add-Member agentMode 'EXACT_TARGET_CHROME_AUTOMATION_1.1.39' -Force;$s|Add-Member ok $ok -Force;$s|Add-Member status $(if($ok){'SELF_HEAL_PASS'}else{'EXACT_TARGET_REGRESSION_FAILED'}) -Force;$s|Add-Member updatedAt ((Get-Date).ToString('o')) -Force;$s|ConvertTo-Json -Depth 40|Set-Content $State -Encoding UTF8}catch{}
if($ok){exit 0}else{exit 2}
