param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.111'
$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function Tabs{$r=Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3;$o=$r.Content|ConvertFrom-Json;$a=@();if($o -is [System.Array]){foreach($x in $o){$a+=$x}}elseif($null-ne$o){$a+=$o};return $a}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$sec*1000));try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($r.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_CLOSED'};$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);return([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$j=@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 30 -Compress;$bb=[Text.Encoding]::UTF8.GetBytes($j);$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};return $r.result.value}
function Click($w,[ref]$q,[double]$x,[double]$y){[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$x;y=$y});[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mousePressed';x=$x;y=$y;button='left';clickCount=1});Start-Sleep -Milliseconds 120;[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseReleased';x=$x;y=$y;button='left';clickCount=1})}
function Connect([string]$u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};return $w}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($my+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveCentral([string]$Name,$Object){try{$j=$Object|ConvertTo-Json -Depth 80;$j|Set-Content -LiteralPath (Join-Path $Root $Name) -Encoding UTF8;$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$p=Join-Path $d $Name;$j|Set-Content -LiteralPath $p -Encoding UTF8;return $p}}catch{};return ''}
$probe="(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const norm=s=>String(s||'').replace(/\s+/g,' ').trim();const body=document.body?.innerText||'';let exactCount=0;const countEls=[];for(const e of [...document.querySelectorAll('*')].filter(vis)){const s=norm(e.innerText||e.textContent||'');let m=s.match(/^\uC18C\uC2A4\s*([0-9]+)\uAC1C$/i)||s.match(/^([0-9]+)\s*sources?$/i);if(m){const n=Number(m[1]);if(Number.isFinite(n)){exactCount=Math.max(exactCount,n);countEls.push(s)}}}const sourceLike=[...document.querySelectorAll('source-item,[data-testid*=source],[class*=source-item],mat-list-option,[role=option]')].filter(vis).map(e=>norm(e.innerText||e.textContent||'').slice(0,180));const empty=/\uC800\uC7A5\uB41C \uC18C\uC2A4\uAC00 \uC5EC\uAE30\uC5D0 \uD45C\uC2DC\uB429\uB2C8\uB2E4/.test(body);return{exactCount,countEls:[...new Set(countEls)].slice(0,20),sourceLikeCount:sourceLike.length,sourceLike:sourceLike.slice(0,30),empty,body:body.slice(0,12000)}})()"
$result=[ordered]@{ok=$false;action='AGENT_1.1.111_IMPORT_CURRENT_SELECTED_RESEARCH_SOURCES';version=$Version;targetUrl=$TargetUrl;startedAt=(Get-Date).ToString('o');exactTab=$false;selectedCount=0;importState=$null;importClicked=$false;after=$null;actualSourceVerified=$false;savedCount=0;normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;stage='START';error='';centralPath=''}
$w=$null
try{
 $pages=@(Tabs|Where-Object{[string]$_.type-eq'page'});$tab=$pages|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1;if(-not$tab){$tab=$pages|Where-Object{[string]$_.url-like'https://notebook.google.com/*'}|Select-Object -First 1};if(-not$tab){throw 'NO_NOTEBOOKLM_PAGE'}
 $w=Connect([string]$tab.webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{});$u=[string](Eval $w ([ref]$q) 'location.href');if($u-ne$TargetUrl){[void](Send $w ([ref]$q) 'Page.navigate' @{url=$TargetUrl});Start-Sleep -Seconds 2};if([string](Eval $w ([ref]$q) 'location.href')-ne$TargetUrl){throw 'EXACT_NOTEBOOK_NAVIGATION_FAILED'};$result.exactTab=$true
 $deadline=(Get-Date).AddSeconds(15);do{Start-Sleep -Seconds 1;$state=Eval $w ([ref]$q) "(() => {const vis=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const norm=s=>String(s||'').replace(/\s+/g,' ').trim();const inputs=[...document.querySelectorAll('input[type=checkbox]')].filter(vis);const selected=inputs.filter(e=>e.checked&&!e.disabled).length;const a=[...document.querySelectorAll('button,[role=button],a,span,div')].filter(vis).filter(e=>norm(e.innerText||e.textContent||'')==='\uAC00\uC838\uC624\uAE30').sort((a,b)=>{const x=a.getBoundingClientRect(),y=b.getBoundingClientRect();return x.width*x.height-y.width*y.height});if(!a.length)return{ok:false,selected};const raw=a[0],e=raw.closest('button,[role=button],a')||raw,r=e.getBoundingClientRect();return{ok:true,selected,disabled:!!e.disabled,ariaDisabled:e.getAttribute('aria-disabled'),x:r.left+r.width/2,y:r.top+r.height/2,text:norm(e.innerText||e.textContent||'')}})()";if($state.ok -and [int]$state.selected-gt0){break}}while((Get-Date)-lt$deadline);$result.selectedCount=[int]$state.selected;$result.importState=$state;if(-not$state.ok){throw 'IMPORT_CONTROL_NOT_FOUND_IN_SELECTION_VIEW'};if($result.selectedCount-lt1){throw 'NO_SELECTED_SOURCES_IN_SELECTION_VIEW'};if([bool]$state.disabled -or [string]$state.ariaDisabled-eq'true'){throw 'IMPORT_DISABLED_IN_SELECTION_VIEW'}
 Click $w ([ref]$q) ([double]$state.x) ([double]$state.y);$result.importClicked=$true
 $deadline=(Get-Date).AddSeconds(180);do{Start-Sleep -Seconds 3;$after=Eval $w ([ref]$q) $probe;$result.after=$after;$result.savedCount=[int]$after.exactCount;if(([int]$after.exactCount-gt0)-or(([int]$after.sourceLikeCount-gt0)-and(-not[bool]$after.empty))){$result.actualSourceVerified=$true;break}}while((Get-Date)-lt$deadline);if(-not$result.actualSourceVerified){throw 'ACTUAL_SAVED_SOURCE_ZERO_AFTER_IMPORT'};$result.ok=$true;$result.stage='DONE'
}catch{$result.error=$_.Exception.Message}
finally{if($w){try{$w.Dispose()}catch{}};$result.completedAt=(Get-Date).ToString('o');$result.centralPath=SaveCentral 'AGENT_1.1.111_IMPORT_CURRENT_SELECTED_RESEARCH_SOURCES_RESULT.json' $result}
$result|ConvertTo-Json -Depth 80 -Compress
if($result.ok){exit 0}else{exit 2}
