param()
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$AgentVersion='1.1.70';$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$PinnedBase='9dce2a7bb83d96a3d846a92e24f468b7a67cb38a'
$PinnedInspect='49d5fc958c1e6d683156380e5ca18a101af27cf9'
$PinnedCapture='18d07e9b1796e154746df05fc35b110ced9148d7'
$PinnedAnalyze='e0514cb6933ce02a0be5087e4deb6876f49ab34c'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent';$Receipt=Join-Path $Root 'CHATGPT_IMAGE_DIRECT_PROBE_1.1.70.json';New-Item -ItemType Directory -Force -Path $Root|Out-Null
function Blob([string]$p){$b=[IO.File]::ReadAllBytes($p);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Api([string]$p){Invoke-RestMethod -Uri ('https://api.github.com/repos/'+$Repo+'/contents/'+$p+'?ref=main&cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -Headers @{'User-Agent'='HomeDesign-Local-Agent';'Accept'='application/vnd.github+json'} -TimeoutSec 30}
function SaveJ([string]$p,$o){$d=Split-Path $p -Parent;if($d){New-Item -ItemType Directory -Force -Path $d|Out-Null};$o|ConvertTo-Json -Depth 50|Set-Content $p -Encoding UTF8}
function Central{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue){foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path $c){return $c}}};''}
function FetchPinned([string]$path,[string]$sha,[string]$name){$r=Api $path;if(([string]$r.sha).ToLowerInvariant()-ne$sha.ToLowerInvariant()){throw('PIN_SHA_'+$name+':'+[string]$r.sha)};$p=Join-Path $Root $name;[IO.File]::WriteAllBytes($p,[Convert]::FromBase64String(([string]$r.content-replace'\s','')));if((Blob $p).ToLowerInvariant()-ne$sha.ToLowerInvariant()){throw('LOCAL_SHA_'+$name)};return $p}
$errors=@();$baseOk=$false;$central=Central;$inspectRc=-1;$captureRc=-1;$analyzeRc=-1;$contractStatus='';$contractOk=$false
try{$base=FetchPinned 'local-agent/releases/1.1.69/HomeDesignLocalAgent.ps1' $PinnedBase 'HomeDesignLocalAgent-1.1.69-pinned.ps1';& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $base;$baseOk=($LASTEXITCODE-eq0);if(-not$baseOk){$errors+=('BASE_EXIT_'+$LASTEXITCODE)}}catch{$errors+=('BASE:'+ $_.Exception.Message)}
try{$inspect=FetchPinned 'local-agent/governor/Inspect-ChatGPTImageAutoManifest.ps1' $PinnedInspect 'Inspect-ChatGPTImageAutoManifest-pinned.ps1';$capture=FetchPinned 'local-agent/governor/Capture-ChatGPTImageDeclaredEntrypointsV1.ps1' $PinnedCapture 'Capture-ChatGPTImageDeclaredEntrypointsV1-pinned.ps1';$analyze=FetchPinned 'local-agent/governor/Analyze-ChatGPTImageEntrypointContractV1.ps1' $PinnedAnalyze 'Analyze-ChatGPTImageEntrypointContractV1-pinned.ps1'}catch{$errors+=('FETCH:'+ $_.Exception.Message)}
if($inspect){try{& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $inspect -CentralRootOverride $central;$inspectRc=$LASTEXITCODE;if($inspectRc-ne0){$errors+=('INSPECT_EXIT_'+$inspectRc)}}catch{$errors+=('INSPECT:'+ $_.Exception.Message)}}
if($capture-and$inspectRc-eq0){try{& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $capture -CentralRootOverride $central;$captureRc=$LASTEXITCODE;if($captureRc-ne0){$errors+=('CAPTURE_EXIT_'+$captureRc)}}catch{$errors+=('CAPTURE:'+ $_.Exception.Message)}}
if($analyze-and$captureRc-eq0){try{& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $analyze -CentralRootOverride $central;$analyzeRc=$LASTEXITCODE;if($analyzeRc-ne0){$errors+=('ANALYZE_EXIT_'+$analyzeRc)}}catch{$errors+=('ANALYZE:'+ $_.Exception.Message)}}
if($central){$cp=Join-Path $central 'Runtime_Readback\CHROME\CHATGPT_IMAGE_ENTRYPOINT_CONTRACT_V1.json';if(Test-Path $cp){try{$c=Get-Content $cp -Raw -Encoding UTF8|ConvertFrom-Json;$contractStatus=[string]$c.status;$contractOk=[bool]$c.ok}catch{$errors+=('CONTRACT_READ:'+ $_.Exception.Message)}}}
$ok=($inspectRc-eq0-and$captureRc-eq0-and$analyzeRc-eq0-and$contractOk);$rec=[ordered]@{ok=$ok;action='CHATGPT_IMAGE_DIRECT_AUTOMATION_CONTRACT_PROBE';agentVersion=$AgentVersion;baseAgent='1.1.69';baseOk=$baseOk;inspectExitCode=$inspectRc;captureExitCode=$captureRc;analyzeExitCode=$analyzeRc;contractStatus=$contractStatus;contractOk=$contractOk;normalChromeTouched=$false;generateClicked=$false;creditSpend=$false;oauthChanged=$false;extensionMutated=$false;errors=$errors;at=(Get-Date).ToString('o')};SaveJ $Receipt $rec;if($central){SaveJ (Join-Path $central 'Runtime_Readback\CHROME\CHATGPT_IMAGE_DIRECT_PROBE_1.1.70.json') $rec};$rec|ConvertTo-Json -Depth 50 -Compress;if($ok){exit 0}else{exit 2}
