param()
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Version='1.1.127';$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c';$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent';$Receipt='AGENT_1.1.127_AUDIO_READINESS_READONLY_RESULT.json';$Marker=Join-Path $Root $Receipt
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($my+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function Save($o){$j=$o|ConvertTo-Json -Depth 80;$j|Set-Content -LiteralPath $Marker -Encoding UTF8;try{$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$j|Set-Content -LiteralPath (Join-Path $d $Receipt) -Encoding UTF8}}catch{}}
function Tabs{$o=(Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3).Content|ConvertFrom-Json;@($o|Where-Object{[string]$_.type-eq'page'})}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter($sec*1000);try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$r=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();$m.Write($b,0,$r.Count)}while(-not$r.EndOfMessage);([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$bb=[Text.Encoding]::UTF8.GetBytes((@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 20 -Compress));$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$r=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};$r.result.value}
function Click($w,[ref]$q,$x,$y){[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseMoved';x=$x;y=$y});[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mousePressed';x=$x;y=$y;button='left';clickCount=1});Start-Sleep -Milliseconds 100;[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseReleased';x=$x;y=$y;button='left';clickCount=1})}
function Connect($u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};$w}
$r=[ordered]@{ok=$false;action='AUDIO_READINESS_READONLY';version=$Version;targetUrl=$TargetUrl;startedAt=(Get-Date).ToString('o');exactTab=$false;studioSelected=$false;generating=$false;ready=$false;audioCount=0;hasAudio=$false;hasPlay=$false;bodyText='';controls=@();downloadAttempted=$false;driveMirrorAttempted=$false;normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;stage='START';error=''};$w=$null
try{$tab=@(Tabs|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1);if(-not$tab){throw 'EXACT_NOTEBOOK_TAB_NOT_FOUND'};$r.exactTab=$true;$w=Connect([string]$tab[0].webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{});$x=Eval $w ([ref]$q) "(() => {const K=String.fromCharCode(49828,53916,46356,50724);const v=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const tabs=[...document.querySelectorAll('[role=tab]')].filter(v);const e=tabs.find(e=>String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).includes(K));if(!e)return{ok:false,tabs:tabs.map(x=>String(x.innerText||x.textContent||''))};const b=e.getBoundingClientRect();return{ok:true,x:b.left+b.width/2,y:b.top+b.height/2}})()";if(-not$x.ok){throw 'STUDIO_TAB_NOT_FOUND'};Click $w ([ref]$q) $x.x $x.y;$r.studioSelected=$true;Start-Sleep -Seconds 2;$s=Eval $w ([ref]$q) "(() => {const A=String.fromCharCode(50724,46356,50724,32,50724,48260,48624),G=String.fromCharCode(49373,49457,32,51473),M=String.fromCharCode(47564,46300,45716,32,51473),P=String.fromCharCode(51116,49373);const body=String(document.body?.innerText||'');const low=body.toLowerCase();const els=[...document.querySelectorAll('button,[role=button],a,[role=option],[role=menuitem],div[tabindex],audio')].map(e=>String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' ')).trim()).filter(Boolean);const generating=low.includes('generating')||low.includes('creating')||body.includes(G)||body.includes(M);const audioCount=document.querySelectorAll('audio').length;const hasAudio=body.includes(A)||low.includes('audio overview');const hasPlay=els.some(x=>x.includes(P)||/\bplay\b/i.test(x));const ready=!generating&&hasAudio&&(audioCount>0||hasPlay||els.some(x=>/more_vert|download|share/i.test(x)));return{generating,audioCount,hasAudio,hasPlay,ready,body:body.slice(0,14000),controls:els.slice(0,220)}})()";$r.generating=[bool]$s.generating;$r.ready=[bool]$s.ready;$r.audioCount=[int]$s.audioCount;$r.hasAudio=[bool]$s.hasAudio;$r.hasPlay=[bool]$s.hasPlay;$r.bodyText=[string]$s.body;$r.controls=@($s.controls);$r.ok=$true;$r.stage='DONE'}catch{$r.error=$_.Exception.Message;$r.stage='ERROR'}finally{if($w){try{$w.Dispose()}catch{}};$r.completedAt=(Get-Date).ToString('o');Save $r};$r|ConvertTo-Json -Depth 80 -Compress;if($r.ok){exit 0}else{exit 2}
