param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$AgentVersion='1.1.6';$HostVersion='1.2.0'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7';$Root=Join-Path $Base 'LocalAgent';$ExtensionRoot=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge';$UserData=Join-Path $Base 'ChromeUserData';$CftRoot=Join-Path $Base 'ChromeForTesting';$BackupRoot=Join-Path $Root 'Backups';$StateFile=Join-Path $Root 'state.json';$ReadbackFile=Join-Path $Root 'VIDEO_LOCAL_RUNTIME_READBACK.json';$HostFile=Join-Path $Root 'HomeDesignLocalCommandHost.ps1';$GovernorRoot=Join-Path $Base 'ChromeGovernor'
$ReleaseUrl='https://raw.githubusercontent.com/8friend8ship-cloud/notebooklm-webapp-bridge/main/runtime/stable/release.json';$HostUrl='https://raw.githubusercontent.com/8friend8ship-cloud/notebooklm-webapp-bridge/main/local-agent/releases/1.2.0/HomeDesignLocalCommandHost.ps1';$HostSha='3cee6a57aa2fd2ab9bcf04f275f4c95296bba247'
New-Item -ItemType Directory -Force -Path $Root,$ExtensionRoot,$BackupRoot,$GovernorRoot|Out-Null
function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[] ($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Proc([string]$Needle){try{return @(Get-CimInstance Win32_Process -Filter "Name='powershell.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like "*$Needle*"})}catch{return @()}}
function AgeSec($p){try{$d=$p.CreationDate;if(-not($d -is [datetime])){$d=[Management.ManagementDateTimeConverter]::ToDateTime([string]$d)};return [Math]::Max(0,((Get-Date)-$d).TotalSeconds)}catch{return 0}}
function KillTree([int]$ProcessId){try{& taskkill.exe /PID $ProcessId /T /F 2>$null|Out-Null}catch{try{Stop-Process -Id $ProcessId -Force -ErrorAction SilentlyContinue}catch{}}}
function ClearStaleTasks(){$rules=@(@{n='RunChromeGovernorReadback.ps1';a=180},@{n='Run-AnimationTestDeploymentE2E.ps1';a=900},@{n='Render-VideoProductionManifest.ps1';a=900},@{n='Run-VideoFrameQA.ps1';a=600});$k=@();foreach($r in $rules){foreach($p in (Proc $r.n)){if((AgeSec $p)-gt [double]$r.a){KillTree ([int]$p.ProcessId);$k+=('{0}:{1}' -f $r.n,$p.ProcessId)}}};if($k.Count){Start-Sleep 2};return $k}
function EnsureFile([string]$Url,[string]$Path,[string]$Expected){$need=(-not(Test-Path $Path));if(-not $need){$need=(GitBlobSha1 $Path)-ne $Expected};if($need){$tmp=$Path+'.download';Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $tmp -TimeoutSec 60;if((GitBlobSha1 $tmp)-ne $Expected){Remove-Item $tmp -Force -ErrorAction SilentlyContinue;throw 'File hash mismatch'};Move-Item $tmp $Path -Force;return $true};return $false}
function TestHost(){try{$h=Invoke-RestMethod -Uri 'http://127.0.0.1:8765/health' -TimeoutSec 3;return ([bool]$h.ok -and [string]$h.version -eq $HostVersion -and [bool]$h.asyncJobs)}catch{return $false}}
function StartHidden([string]$File,[string[]]$Extra=@()){$args=@('-NoProfile','-ExecutionPolicy','Bypass','-WindowStyle','Hidden','-File',"`"$File`"")+$Extra;Start-Process powershell.exe -ArgumentList $args -WindowStyle Hidden|Out-Null;Start-Sleep -Milliseconds 600}
function FindChrome(){if(-not(Test-Path $CftRoot)){return $null};return Get-ChildItem $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction SilentlyContinue|Sort-Object FullName -Descending|Select-Object -First 1}
function Dedicated(){try{return @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like "*$UserData*"})}catch{return @()}}
function StopDedicated(){foreach($p in (Dedicated)){try{Stop-Process -Id $p.ProcessId -Force -ErrorAction SilentlyContinue}catch{}};Start-Sleep 2}
function LaunchDedicated([string]$Front){$c=FindChrome;if(-not $c){throw 'Chrome for Testing executable not found'};$args=@("--user-data-dir=$UserData",'--profile-directory=Default',"--load-extension=$ExtensionRoot",'--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',$Front);$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$c.FullName;$psi.WorkingDirectory=$c.Directory.FullName;$psi.UseShellExecute=$false;$psi.Arguments=($args|ForEach-Object{if($_ -match '\s'){'"'+$_+'"'}else{$_}})-join ' ';[void][Diagnostics.Process]::Start($psi);Start-Sleep 8;if((Dedicated).Count -le 0){throw 'Dedicated Chrome did not remain running'}}
function TestRelease($rel){foreach($f in @($rel.files)){$p=Join-Path $ExtensionRoot ([string]$f.path).Replace('/','\');if(-not(Test-Path $p)){return $false};if((GitBlobSha1 $p)-ne ([string]$f.gitBlobSha1).ToLowerInvariant()){return $false}};return $true}
function InstallRelease($rel){$stage=Join-Path $Root ('Stage\'+(Get-Date -Format 'yyyyMMdd_HHmmss'));$backup=Join-Path $BackupRoot (Get-Date -Format 'yyyyMMdd_HHmmss');New-Item -ItemType Directory -Force -Path $stage,$backup|Out-Null;foreach($f in @($rel.files)){$rp=[string]$f.path;if($rp -match '\.\.' -or [IO.Path]::IsPathRooted($rp)){throw 'Unsafe release path'};$dst=Join-Path $stage $rp.Replace('/','\');$par=Split-Path $dst -Parent;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};Invoke-WebRequest -UseBasicParsing -Uri (([string]$rel.baseUrl).TrimEnd('/')+'/'+$rp) -OutFile $dst -TimeoutSec 60;if((GitBlobSha1 $dst)-ne ([string]$f.gitBlobSha1).ToLowerInvariant()){throw "Extension hash mismatch: $rp"}};if(Test-Path $ExtensionRoot){Copy-Item $ExtensionRoot (Join-Path $backup 'extension') -Recurse -Force};StopDedicated;Get-ChildItem $ExtensionRoot -Force -ErrorAction SilentlyContinue|Remove-Item -Recurse -Force;Copy-Item (Join-Path $stage '*') $ExtensionRoot -Recurse -Force;if(-not(TestRelease $rel)){throw 'Installed extension verification failed'};LaunchDedicated ([string]$rel.frontUrl)}
function FindCentral(){foreach($l in 'D'..'Z'){foreach($p in @("$l`:\My Drive\00_중앙에이전트","$l`:\내 드라이브\00_중앙에이전트","$l`:\Google Drive\00_중앙에이전트","$l`:\00_중앙에이전트")){if(Test-Path $p){return $p}}};foreach($p in @((Join-Path $env:USERPROFILE 'My Drive\00_중앙에이전트'),(Join-Path $env:USERPROFILE '내 드라이브\00_중앙에이전트'),(Join-Path $env:USERPROFILE 'Google Drive\00_중앙에이전트'))){if(Test-Path $p){return $p}};return ''}
function RefreshGovernor(){
  $base='https://raw.githubusercontent.com/8friend8ship-cloud/notebooklm-webapp-bridge/main/local-agent/governor';$changes=@{}
  foreach($name in @('ChromeExtensionGovernor.ps1','SHOW_CHROME_EXTENSION_GOVERNOR_STATUS.ps1','GovernorDriveSync.ps1')){$dst=Join-Path $GovernorRoot $name;$tmp=$dst+'.download';Invoke-WebRequest -UseBasicParsing -Uri "$base/$name" -OutFile $tmp -TimeoutSec 60;$changed=(-not(Test-Path $dst));if(-not $changed){$changed=(Get-FileHash $dst -Algorithm SHA256).Hash -ne (Get-FileHash $tmp -Algorithm SHA256).Hash};if($changed){Move-Item $tmp $dst -Force}else{Remove-Item $tmp -Force};$changes[$name]=$changed}
  $gov=Join-Path $GovernorRoot 'ChromeExtensionGovernor.ps1';$sync=Join-Path $GovernorRoot 'GovernorDriveSync.ps1'
  if($changes['ChromeExtensionGovernor.ps1']){foreach($p in (Proc 'ChromeExtensionGovernor.ps1')){KillTree ([int]$p.ProcessId)}}
  if($changes['GovernorDriveSync.ps1']){foreach($p in (Proc 'GovernorDriveSync.ps1')){KillTree ([int]$p.ProcessId)}}
  if((Proc 'ChromeExtensionGovernor.ps1').Count -eq 0){StartHidden $gov @('-Loop')};if((Proc 'GovernorDriveSync.ps1').Count -eq 0){StartHidden $sync @('-Loop','-PollSeconds','900')}
  try{& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $gov | Out-Null}catch{};try{& powershell.exe -NoProfile -ExecutionPolicy Bypass -File $sync | Out-Null}catch{}
  return $changes
}
function WriteState($s){$s.agentVersion=$AgentVersion;$s.commandHostVersion=$HostVersion;$s.commandHostAsyncJobs=$true;$s.chromeGovernorRunning=((Proc 'ChromeExtensionGovernor.ps1').Count -gt 0);$s.chromeGovernorDriveSyncRunning=((Proc 'GovernorDriveSync.ps1').Count -gt 0);$s.updatedAt=(Get-Date).ToString('o');$s|ConvertTo-Json -Depth 30|Set-Content $StateFile -Encoding UTF8;$s|ConvertTo-Json -Depth 30|Set-Content $ReadbackFile -Encoding UTF8;$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$s|ConvertTo-Json -Depth 30|Set-Content (Join-Path $d 'VIDEO_LOCAL_RUNTIME_READBACK.json') -Encoding UTF8}}
$s=[ordered]@{ok=$false;status='STARTING';killed=@();extensionVersion='';hostHealthy=$false;dedicatedChromeRunning=$false;governorChanges=$null;lastError=''}
try{$s.killed=@(ClearStaleTasks);$hc=EnsureFile $HostUrl $HostFile $HostSha;if($hc -or -not(TestHost)){foreach($p in (Proc 'HomeDesignLocalCommandHost.ps1')){KillTree ([int]$p.ProcessId)};Start-Sleep -Milliseconds 700;StartHidden $HostFile;$dl=(Get-Date).AddSeconds(12);do{Start-Sleep -Milliseconds 500}while(-not(TestHost)-and (Get-Date)-lt $dl)};if(-not(TestHost)){throw 'Local Command Host 1.2.0 async health failed'};$rel=Invoke-RestMethod -Uri $ReleaseUrl -TimeoutSec 30;if(-not $rel.enabled){throw 'Bridge stable channel disabled'};$needs=-not(TestRelease $rel);if(-not $needs){try{$m=Get-Content (Join-Path $ExtensionRoot 'manifest.json') -Raw -Encoding UTF8|ConvertFrom-Json;$needs=([string]$m.version -ne [string]$rel.version)}catch{$needs=$true}};if($needs){InstallRelease $rel}else{if((Dedicated).Count -le 0){LaunchDedicated ([string]$rel.frontUrl)}};$s.governorChanges=RefreshGovernor;$m=Get-Content (Join-Path $ExtensionRoot 'manifest.json') -Raw -Encoding UTF8|ConvertFrom-Json;$s.ok=$true;$s.status='SELF_HEAL_PASS';$s.extensionVersion=[string]$m.version;$s.hostHealthy=(TestHost);$s.dedicatedChromeRunning=((Dedicated).Count -gt 0);$s.releaseActionId=[string]$rel.actionId;WriteState $s}catch{$s.ok=$false;$s.status='SELF_HEAL_FAILED';$s.lastError=$_.Exception.Message;$s.hostHealthy=(TestHost);$s.dedicatedChromeRunning=((Dedicated).Count -gt 0);WriteState $s;throw}
