param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.132'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$RunnerPath='notebooklm-webapp-bridge-source-v0.2.0/extension/content/notebooklm-runner.js'
$RunnerSha='855098a7c3549c8eabe7c128b694fd2a567ff974'
$InstructionB64='7J20IOyDiCDrhbjtirjrtoHsnZgg7Iug6recIOyGjOyKpOunjCDsgqzsmqntlbQg7Iqs65287J2065OcIOyekOujjOulvCDsg4jroZwg7IOd7ISx7ZWY7IS47JqULiDquLDsobQg7Iqs65287J2065OcIOyerOyCrOyaqSDquIjsp4AuIOyDiCDsiqzrnbzsnbTrk5wg7Lm065OcIOyDneyEsSDtm4Qg7Iuk7KCcIOuLpOyatOuhnOuTnOqwgCDqsoDspp3rkJjslrTslbwgRE9OReyeheuLiOuLpC4='
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$UserData=Join-Path $Base 'ChromeUserData'
$ExtensionRoot=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge'
$CftRoot=Join-Path $Base 'ChromeForTesting'
$RunnerFile=Join-Path $Root 'notebooklm-runner.0.2.39.slides.runtime.js'
$Receipt='AGENT_1.1.132_STABLE_RUNNER_SLIDES_GENERATION_RESULT.json'
$Marker=Join-Path $Root $Receipt
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function U([string]$b){[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b))}
function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($my+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function Save($o){$j=$o|ConvertTo-Json -Depth 100;$j|Set-Content -LiteralPath $Marker -Encoding UTF8;try{$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$j|Set-Content -LiteralPath (Join-Path $d $Receipt) -Encoding UTF8}}catch{}}
function DebugReady{try{$v=Invoke-RestMethod -Uri ("http://127.0.0.1:$Port/json/version") -TimeoutSec 2;return [bool]$v.webSocketDebuggerUrl}catch{return $false}}
function FindChrome{if(Test-Path -LiteralPath $CftRoot){$x=Get-ChildItem -LiteralPath $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction SilentlyContinue|Sort-Object FullName -Descending|Select-Object -First 1;if($x){return [string]$x.FullName}};foreach($c in @((Join-Path ${env:ProgramFiles} 'Google\Chrome\Application\chrome.exe'),(Join-Path ${env:ProgramFiles(x86)} 'Google\Chrome\Application\chrome.exe'),(Join-Path $env:LOCALAPPDATA 'Google\Chrome\Application\chrome.exe'))){if($c-and(Test-Path -LiteralPath $c)){return [string]$c}};throw 'CHROME_EXE_NOT_FOUND'}
function DedicatedProcs{try{return @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine-and$_.CommandLine-like("*"+$UserData+"*")})}catch{return @()}}
function StartDedicated{if(DebugReady){return};foreach($p in @(DedicatedProcs)){try{Stop-Process -Id ([int]$p.ProcessId) -Force -ErrorAction SilentlyContinue}catch{}};Start-Sleep -Milliseconds 700;$chrome=FindChrome;$args=@("--remote-debugging-port=$Port",'--remote-allow-origins=*',"--user-data-dir=$UserData",'--profile-directory=Default',"--load-extension=$ExtensionRoot",'--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',$TargetUrl);Start-Process -FilePath $chrome -ArgumentList $args|Out-Null;$d=(Get-Date).AddSeconds(25);do{Start-Sleep -Milliseconds 400;if(DebugReady){return}}while((Get-Date)-lt$d);throw 'CDP_PORT_NOT_READY'}
function Tabs{$o=(Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3).Content|ConvertFrom-Json;return @($o|Where-Object{[string]$_.type-eq'page'})}
function Recv($w,[int]$sec){$b=New-Object byte[] 262144;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter([Math]::Max(1000,$sec*1000));try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$z=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($z.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_CLOSED'};$m.Write($b,0,$z.Count)}while(-not$z.EndOfMessage);return([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{},[int]$receiveSec=8){$q.Value++;$id=$q.Value;$bb=[Text.Encoding]::UTF8.GetBytes((@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 40 -Compress));$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w $receiveSec;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e,[int]$receiveSec=8){$z=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true} $receiveSec;if($z.exceptionDetails){throw('JS_EXCEPTION '+($z.exceptionDetails|ConvertTo-Json -Compress))};return $z.result.value}
function Connect([string]$u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};return $w}
function EnsureExactTab{StartDedicated;$pages=@(Tabs);$exact=$pages|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1;if(-not$exact){$tab=$pages|Where-Object{[string]$_.url-like'https://notebook.google.com/*'}|Select-Object -First 1;if(-not$tab){$tab=$pages|Select-Object -First 1};if($tab){$w=Connect([string]$tab.webSocketDebuggerUrl);try{$q=0;[void](Send $w ([ref]$q) 'Page.enable' @{});[void](Send $w ([ref]$q) 'Page.navigate' @{url=$TargetUrl})}finally{$w.Dispose()}}};$d=(Get-Date).AddSeconds(30);do{Start-Sleep -Milliseconds 500;$exact=@(Tabs|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1);if($exact){return $exact[0]}}while((Get-Date)-lt$d);throw 'EXACT_NOTEBOOK_TAB_NOT_VERIFIED'}
if(Test-Path -LiteralPath $Marker -PathType Leaf){try{$prior=Get-Content -LiteralPath $Marker -Raw -Encoding UTF8|ConvertFrom-Json;Save $prior;$prior|ConvertTo-Json -Depth 100 -Compress;if([bool]$prior.ok){exit 0}else{exit 2}}catch{}}
$r=[ordered]@{ok=$false;action='AGENT_1.1.132_STABLE_RUNNER_SLIDES_GENERATION';version=$Version;targetUrl=$TargetUrl;runnerShaExpected=$RunnerSha;runnerShaActual='';runnerVerified=$false;runnerInjected=$false;exactTab=$false;taskType='SLIDES';generationReady=$false;runnerResult=$null;downloadAttempted=$false;driveMirrorAttempted=$false;normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;stage='START';error='';startedAt=(Get-Date).ToString('o')}
$w=$null
try{
  $r.stage='FETCH_RUNNER';$url='https://raw.githubusercontent.com/'+$Repo+'/main/'+$RunnerPath+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $RunnerFile -TimeoutSec 30;$r.runnerShaActual=(GitBlobSha1 $RunnerFile).ToLowerInvariant();if($r.runnerShaActual-ne$RunnerSha){throw 'RUNNER_SHA_MISMATCH'};$r.runnerVerified=$true
  $r.stage='EXACT_TAB';$tab=EnsureExactTab;$r.exactTab=([string]$tab.url-eq$TargetUrl);if(-not$r.exactTab){throw 'EXACT_TAB_FAILED'};$w=Connect([string]$tab.webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{});Start-Sleep -Seconds 2
  $r.stage='INJECT_STABLE_RUNNER';$src=Get-Content -LiteralPath $RunnerFile -Raw -Encoding UTF8;$src=$src.Replace('if (globalThis.__NLM_WEBAPP_BRIDGE_LOADED__) return;','globalThis.__NLM_WEBAPP_BRIDGE_LOADED__ = false;');$needle='chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {';$replacement='globalThis.__NLM_RUN_TASK__ = runTask; return; chrome.runtime.onMessage.addListener((message, _sender, sendResponse) => {';if(-not$src.Contains($needle)){throw 'RUNNER_EXPORT_PATCH_ANCHOR_NOT_FOUND'};$src=$src.Replace($needle,$replacement);$b64=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($src));$expr="(()=>{const s=new TextDecoder().decode(Uint8Array.from(atob('$b64'),c=>c.charCodeAt(0)));eval(s);return {ok:typeof globalThis.__NLM_RUN_TASK__==='function',url:location.href};})()";$inj=Eval $w ([ref]$q) $expr 20;if(-not[bool]$inj.ok){throw 'RUNNER_INJECTION_NOT_EXPORTED'};$r.runnerInjected=$true
  $r.stage='RUN_SLIDES';$task=[ordered]@{taskId='NLM_FRESH_SLIDES_20260829_1915_01';contentId='NLM-FRESH-E2E-SLIDES-20260829';taskType='SLIDES';sourceText='';instruction=(U $InstructionB64);language='ko-KR';timeoutSeconds=240};$tj=$task|ConvertTo-Json -Depth 10 -Compress;$rr=Eval $w ([ref]$q) ("globalThis.__NLM_RUN_TASK__("+$tj+")") 270;$r.runnerResult=$rr;$r.generationReady=([string]$rr.status-eq'DONE'-and[string]$rr.artifactType-eq'SLIDES'-and[string]$rr.captureMode-eq'SLIDES_READY');if(-not$r.generationReady){throw 'SLIDES_RUNNER_READY_GATE_FAILED'};$r.ok=$true;$r.stage='DONE'
}catch{$r.error=$_.Exception.Message;$r.stage='ERROR'}finally{if($w){try{$w.Dispose()}catch{}};$r.completedAt=(Get-Date).ToString('o');Save $r}
$r|ConvertTo-Json -Depth 100 -Compress
if($r.ok){exit 0}else{exit 2}
