param(
  [string]$ExpectedDeploymentId='AKfycbzz247_Mwl9c6N1WxmpHAttwHQJB6RCFtaY08XlHgxysz1iEzg7HWDXa3i5oXhDS1jo',
  [int]$MaxBindings=50
)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$SourceRepo='8friend8ship-cloud/Analyzer-12.09'
$SourceCommit='0ad86472116e73728d99c0c49d940e0a884d4739'
$SourceRel='apps-script/personaOrchestrationGate.gs'
$ExpectedSourceBlob='948c056e6d175b5b709b53955abdd3b83869b9c3'
$Contract='PERSONA_ORCHESTRATION_GATE_V1_20260828'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$Work=Join-Path $Base ('PersonaOrchestrationBindV1\'+(Get-Date -Format 'yyyyMMdd_HHmmss'))
$LocalReceipt=Join-Path $Base 'LocalAgent\WEBAPP_TEMPLATE_05_PERSONA_BIND_V1.json'
New-Item -ItemType Directory -Force -Path $Work|Out-Null

function GitBlob([string]$p){$b=[IO.File]::ReadAllBytes($p);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function FindCentral{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(!$d.Root){continue};foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ('내 드라이브\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveJson([string]$p,$o){$par=Split-Path -Parent $p;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};$o|ConvertTo-Json -Depth 50|Set-Content -LiteralPath $p -Encoding UTF8}
function SafeRun([string]$File,[string[]]$Args,[int]$Timeout=90,[string]$Cwd=''){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$File;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;if($Cwd){$psi.WorkingDirectory=$Cwd};$psi.Arguments=($Args|ForEach-Object{if($_ -match '[\s"]'){'"'+($_ -replace '"','\"')+'"'}else{$_}})-join ' ';$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();if(-not $p.WaitForExit($Timeout*1000)){try{& taskkill.exe /PID $p.Id /T /F 2>$null|Out-Null}catch{};return [ordered]@{ok=$false;exit=-1;timedOut=$true;stdout=$ot.Result;stderr=$et.Result}};return [ordered]@{ok=($p.ExitCode -eq 0);exit=$p.ExitCode;timedOut=$false;stdout=$ot.Result.Trim();stderr=$et.Result.Trim()}}
function SourceFiles([string]$dir){@(Get-ChildItem $dir -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Extension -in '.gs','.js','.json' -and $_.Name -ne '.clasp.json'})}
function Fingerprint([string]$dir){$parts=@();foreach($f in @(SourceFiles $dir|Sort-Object FullName)){$rel=$f.FullName.Substring($dir.Length).TrimStart('\').Replace('\','/');$parts+=($rel+':'+(Get-FileHash -Algorithm SHA256 $f.FullName).Hash)};if(!$parts.Count){return ''};$bytes=[Text.Encoding]::UTF8.GetBytes(($parts -join "`n"));$sha=[Security.Cryptography.SHA256]::Create();try{return ([BitConverter]::ToString($sha.ComputeHash($bytes))).Replace('-','')}finally{$sha.Dispose()}}
function DeploymentText($clasp,[string]$dir){$r=SafeRun $clasp @('deployments') 45 $dir;if(!$r.ok){$r=SafeRun $clasp @('list-deployments') 45 $dir};return $r}
function VerifyLive([string]$dir){$files=SourceFiles $dir;$joined=($files|ForEach-Object{try{Get-Content $_.FullName -Raw -Encoding UTF8}catch{''}})-join "`n";$queueHits=@($files|Where-Object{(Get-Content $_.FullName -Raw -Encoding UTF8) -match 'function\s+processTaskQueue\s*\(\s*\)'});[ordered]@{personaFileCount=@($files|Where-Object{$_.BaseName -eq 'PersonaOrchestrationGate'}).Count;queueDefinitionCount=$queueHits.Count;adapter=($joined -match 'PERSONA_ORCH_FACTORY_ADAPTER_V1');reviewPass=($joined -match 'function\s+personaReviewPass_');packReady=($joined -match 'function\s+personaPackReady_');crosscheck=($joined -match 'function\s+runGeminiProjectCrosscheckGate_');daily=($joined -match 'function\s+runDailyPersonaMaintenanceFromFactory_');promotionCandidates=@([regex]::Matches($joined,'function\s+([A-Za-z0-9_]*(?:promot|publish|template|factory)[A-Za-z0-9_]*)\s*\(')|ForEach-Object{$_.Groups[1].Value}|Sort-Object -Unique|Select-Object -First 40)}}
function Restore([string]$target,[string]$backup,$clasp,[string]$expectedFp){Get-ChildItem $target -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Extension -in '.gs','.js','.json' -and $_.Name -ne '.clasp.json'}|Remove-Item -Force -ErrorAction SilentlyContinue;foreach($f in @(Get-ChildItem $backup -File -Recurse -ErrorAction SilentlyContinue)){$rel=$f.FullName.Substring($backup.Length).TrimStart('\');$dest=Join-Path $target $rel;$par=Split-Path -Parent $dest;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};Copy-Item $f.FullName $dest -Force};$p=SafeRun $clasp @('push','--force') 150 $target;if(!$p.ok){throw ('ROLLBACK_PUSH_FAILED:'+($p.stderr+' '+$p.stdout).Trim())};$q=SafeRun $clasp @('pull') 90 $target;if(!$q.ok){throw 'ROLLBACK_PULL_FAILED'};$fp=Fingerprint $target;if($expectedFp -and $fp -ne $expectedFp){throw ('ROLLBACK_FINGERPRINT_MISMATCH:'+ $fp+':'+$expectedFp)};return [ordered]@{push=$p;pull=$q;fingerprint=$fp}}

$central=FindCentral;$driveReceipt=$(if($central){Join-Path $central 'Runtime_Readback\AppsScript_Persona\WEBAPP_TEMPLATE_05_PERSONA_BIND_V1.json'}else{''});$stage='INIT';$diag=@();$target=$null;$backup='';$sourceSha='';$beforeFp='';$push=$null;$read1=$null;$read2=$null;$rollback=$null;$pushDone=$false
try{
  $stage='CLASP_DISCOVERY';$clasp=(Get-Command clasp.cmd -ErrorAction SilentlyContinue);if(!$clasp){$clasp=Get-Command clasp -ErrorAction SilentlyContinue};if(!$clasp){throw 'CLASP_NOT_FOUND_EXISTING_BINDING_REQUIRED'}
  $stage='SOURCE_FETCH';$src=Join-Path $Work 'PersonaOrchestrationGate.gs';$url='https://raw.githubusercontent.com/'+$SourceRepo+'/'+$SourceCommit+'/'+$SourceRel+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $src -TimeoutSec 30;$sourceSha=(GitBlob $src).ToLowerInvariant();if($sourceSha -ne $ExpectedSourceBlob){throw ('PERSONA_SOURCE_SHA_MISMATCH:'+ $sourceSha+':'+$ExpectedSourceBlob)};$st=Get-Content $src -Raw -Encoding UTF8;foreach($needle in @('function personaReviewPass_','function personaPackReady_','function runGeminiProjectCrosscheckGate_','function runDailyPersonaMaintenanceFromFactory_')){if($st -notmatch [regex]::Escape($needle)){throw ('PERSONA_SOURCE_CONTRACT_MISSING:'+ $needle)}}
  $stage='BINDING_SCAN';$roots=@($Base,(Join-Path $env:USERPROFILE 'Documents'),(Join-Path $env:USERPROFILE 'Desktop'))|Where-Object{Test-Path $_ -PathType Container};$seen=@{};$bindings=@();foreach($root in $roots){foreach($f in @(Get-ChildItem -LiteralPath $root -Filter '.clasp.json' -File -Recurse -ErrorAction SilentlyContinue|Select-Object -First $MaxBindings)){try{$j=Get-Content $f.FullName -Raw -Encoding UTF8|ConvertFrom-Json;if($j.scriptId -and -not $seen[[string]$j.scriptId]){$seen[[string]$j.scriptId]=$true;$bindings += [ordered]@{scriptId=[string]$j.scriptId;dir=$f.Directory.FullName}}}catch{}}};if(!$bindings.Count){throw 'NO_EXISTING_CLASP_BINDING_FOUND'}
  $stage='TARGET_BY_DEPLOYMENT';$matches=@();foreach($b in $bindings){$dep=DeploymentText $clasp.Source $b.dir;$hit=[bool]($dep.ok -and (($dep.stdout+' '+$dep.stderr) -match [regex]::Escape($ExpectedDeploymentId)));$diag += [ordered]@{scriptId=$b.scriptId;dir=$b.dir;deploymentsOk=$dep.ok;deploymentMatch=$hit};if($hit){$matches+=$b}};if($matches.Count -ne 1){throw ('TARGET_DEPLOYMENT_MATCH_COUNT:'+ $matches.Count)};$target=$matches[0]
  $stage='PULL_BASELINE';$pull0=SafeRun $clasp.Source @('pull') 90 $target.dir;if(!$pull0.ok){throw ('BASELINE_PULL_FAILED:'+($pull0.stderr+' '+$pull0.stdout).Trim())};$beforeFp=Fingerprint $target.dir
  $stage='BACKUP';$backup=$(if($central){Join-Path $central ('Backups\AppsScript_Persona\WEBAPP_TEMPLATE_05\'+(Get-Date -Format 'yyyyMMdd_HHmmss'))}else{Join-Path $Work 'backup'});New-Item -ItemType Directory -Force -Path $backup|Out-Null;foreach($f in @(Get-ChildItem $target.dir -File -Recurse -ErrorAction SilentlyContinue)){$rel=$f.FullName.Substring($target.dir.Length).TrimStart('\');$dest=Join-Path $backup $rel;$par=Split-Path -Parent $dest;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};Copy-Item $f.FullName $dest -Force}
  $stage='PATCH';$files=SourceFiles $target.dir;$q=@($files|Where-Object{(Get-Content $_.FullName -Raw -Encoding UTF8) -match 'function\s+processTaskQueue\s*\(\s*\)'});if($q.Count -ne 1){throw ('PROCESSTASKQUEUE_DEFINITION_COUNT:'+ $q.Count)};$qt=Get-Content $q[0].FullName -Raw -Encoding UTF8;if($qt -notmatch 'PERSONA_ORCH_FACTORY_ADAPTER_V1'){$pat='function\s+processTaskQueue\s*\(\s*\)\s*\{';$adapter="`r`n  // PERSONA_ORCH_FACTORY_ADAPTER_V1`r`n  try {`r`n    if (typeof runDailyPersonaMaintenanceFromFactory_ === 'function') {`r`n      runDailyPersonaMaintenanceFromFactory_(SpreadsheetApp.getActiveSpreadsheet(), {source:'processTaskQueue'});`r`n    }`r`n  } catch (personaOrchMaintenanceError) {`r`n    console.warn('PERSONA_ORCH_MAINTENANCE_DEGRADED', String(personaOrchMaintenanceError && personaOrchMaintenanceError.message || personaOrchMaintenanceError));`r`n  }";$qt=[regex]::Replace($qt,$pat,'${0}'+$adapter,1);Set-Content $q[0].FullName $qt -Encoding UTF8};Copy-Item $src (Join-Path $target.dir 'PersonaOrchestrationGate.gs') -Force;$local=VerifyLive $target.dir;if($local.personaFileCount -ne 1 -or $local.queueDefinitionCount -ne 1 -or -not $local.adapter -or -not $local.reviewPass -or -not $local.packReady -or -not $local.crosscheck -or -not $local.daily){throw ('LOCAL_PATCH_VERIFY_FAILED:'+($local|ConvertTo-Json -Compress))}
  $stage='PUSH';$push=SafeRun $clasp.Source @('push','--force') 150 $target.dir;if(!$push.ok){throw ('CLASP_PUSH_FAILED:'+($push.stderr+' '+$push.stdout).Trim())};$pushDone=$true
  $stage='READBACK_X1';$pull1=SafeRun $clasp.Source @('pull') 90 $target.dir;if(!$pull1.ok){throw 'READBACK_X1_PULL_FAILED'};$read1=VerifyLive $target.dir;if($read1.personaFileCount -ne 1 -or $read1.queueDefinitionCount -ne 1 -or -not $read1.adapter -or -not $read1.reviewPass -or -not $read1.packReady -or -not $read1.crosscheck -or -not $read1.daily){throw ('READBACK_X1_CONTRACT_FAILED:'+($read1|ConvertTo-Json -Compress))}
  $stage='READBACK_X2';$pull2=SafeRun $clasp.Source @('pull') 90 $target.dir;if(!$pull2.ok){throw 'READBACK_X2_PULL_FAILED'};$read2=VerifyLive $target.dir;if($read2.personaFileCount -ne 1 -or $read2.queueDefinitionCount -ne 1 -or -not $read2.adapter -or -not $read2.reviewPass -or -not $read2.packReady -or -not $read2.crosscheck -or -not $read2.daily){throw ('READBACK_X2_CONTRACT_FAILED:'+($read2|ConvertTo-Json -Compress))}
  $stage='DEPLOYMENT_INVARIANT';$depAfter=DeploymentText $clasp.Source $target.dir;if(!$depAfter.ok -or (($depAfter.stdout+' '+$depAfter.stderr) -notmatch [regex]::Escape($ExpectedDeploymentId))){throw 'EXISTING_DEPLOYMENT_INVARIANT_FAILED'}
  $o=[ordered]@{ok=$true;status='PUSH_PULL_READBACK_X2_PASS';contract=$Contract;stage='DONE';scriptId=$target.scriptId;deploymentId=$ExpectedDeploymentId;backup=$backup;beforeFingerprint=$beforeFp;sourceCommit=$SourceCommit;sourceBlob=$sourceSha;readback1=$read1;readback2=$read2;promotionCandidates=$read2.promotionCandidates;diagnostics=$diag;newProjectCreated=$false;oauthChanged=$false;scopeChanged=$false;newDeployment=$false;newTrigger=$false;paidGeminiApiCalled=$false;at=(Get-Date).ToString('o')};SaveJson $LocalReceipt $o;if($driveReceipt){SaveJson $driveReceipt $o};$o|ConvertTo-Json -Depth 50 -Compress;exit 0
}catch{
  $err=$_.Exception.Message;if($pushDone -and $target -and $backup){try{$rollback=Restore $target.dir $backup $clasp.Source $beforeFp}catch{$rollback=[ordered]@{ok=$false;error=$_.Exception.Message}}};$o=[ordered]@{ok=$false;status=$(if($rollback -and $rollback.ok -ne $false){'FAILED_ROLLED_BACK'}else{'FAILED'});contract=$Contract;stage=$stage;error=$err;scriptId=$(if($target){$target.scriptId}else{''});deploymentId=$ExpectedDeploymentId;backup=$backup;beforeFingerprint=$beforeFp;sourceCommit=$SourceCommit;sourceBlob=$sourceSha;push=$push;readback1=$read1;readback2=$read2;rollback=$rollback;diagnostics=$diag;newProjectCreated=$false;oauthChanged=$false;scopeChanged=$false;newDeployment=$false;newTrigger=$false;paidGeminiApiCalled=$false;at=(Get-Date).ToString('o')};try{SaveJson $LocalReceipt $o}catch{};if($driveReceipt){try{SaveJson $driveReceipt $o}catch{}};$o|ConvertTo-Json -Depth 50 -Compress;exit 2
}