param([int]$DebugPort=9224)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7';$UserData=Join-Path $Base 'ChromeUserData';$CftRoot=Join-Path $Base 'ChromeForTesting';$FlowExt='';$FlowUrl='https://labs.google/fx/tools/flow';$NotebookExt=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge';$NotebookFront='https://notebooklm-webapp-bridge.vercel.app/'
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(!$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('내 드라이브\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c){return $c}}};return ''}
function FindFlowExt{foreach($p in @((Join-Path $env:USERPROFILE 'Downloads\flow-agent-bridge-v0.1.0\flow-agent-bridge-v0.1.0'),(Join-Path $env:USERPROFILE 'Downloads\flow-agent-bridge-v0.1.0'),(Join-Path $Base 'Extension\Flow-Agent-Bridge'),(Join-Path $Base 'Extension\Google-AI-Local-Bridge-Flow'))){if(Test-Path -LiteralPath (Join-Path $p 'manifest.json') -PathType Leaf){return $p}};return ''}
function Dedicated{try{@(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and ([string]$_.CommandLine).Contains($UserData)})}catch{@()}}
function NormalRoots{try{@(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{(-not $_.CommandLine -or -not([string]$_.CommandLine).Contains($UserData)) -and (-not $_.CommandLine -or ([string]$_.CommandLine)-notmatch '(?i)(^|\s)--type=')}|ForEach-Object{[int]$_.ProcessId})}catch{@()}}
function StopDedicated{foreach($p in @(Dedicated)){try{& taskkill.exe /PID ([int]$p.ProcessId) /T /F 2>$null|Out-Null}catch{}};Start-Sleep -Seconds 2}
$central=FindCentral;if(!$central){throw 'CENTRAL_DRIVE_ROOT_NOT_FOUND'};$FlowExt=FindFlowExt;if(!$FlowExt){throw 'FLOW_EXTENSION_PATH_NOT_FOUND'};$chrome=Get-ChildItem -LiteralPath $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction Stop|Sort-Object FullName -Descending|Select-Object -First 1;if(!$chrome){throw 'CFT_CHROME_NOT_FOUND'}
$normalBefore=@(NormalRoots);StopDedicated;$args=@("--user-data-dir=$UserData",'--profile-directory=Default','--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',("--load-extension=$FlowExt"),("--remote-debugging-port=$DebugPort"),'--remote-debugging-address=127.0.0.1',$FlowUrl);Start-Process -FilePath $chrome.FullName -ArgumentList $args -WorkingDirectory $chrome.Directory.FullName|Out-Null
$version=$null;$targets=@();$deadline=(Get-Date).AddSeconds(25);do{try{$version=Invoke-RestMethod -Uri ("http://127.0.0.1:$DebugPort/json/version") -TimeoutSec 2;$targets=@(Invoke-RestMethod -Uri ("http://127.0.0.1:$DebugPort/json/list") -TimeoutSec 2);if($version.webSocketDebuggerUrl -and @($targets|Where-Object{$_.type -eq 'page' -and ([string]$_.url).Contains('/fx/tools/flow')}).Count){break}}catch{};Start-Sleep -Milliseconds 500}while((Get-Date)-lt $deadline)
$page=$targets|Where-Object{$_.type -eq 'page' -and ([string]$_.url).Contains('/fx/tools/flow')}|Select-Object -First 1;if(!$page){throw 'FLOW_PAGE_NOT_FOUND'}
$node=Get-Command node.exe -ErrorAction SilentlyContinue;if(!$node){$node=Get-Command node -ErrorAction Stop};$js=Join-Path $env:TEMP ('flow-credit-'+[guid]::NewGuid().ToString('N')+'.mjs')
$code=@'
const wsUrl=process.argv[2];
function connect(url){return new Promise((resolve,reject)=>{const ws=new WebSocket(url);let seq=0;const pending=new Map();ws.onopen=()=>resolve({ws,send:(method,params={})=>new Promise((res,rej)=>{const id=++seq;pending.set(id,{res,rej});ws.send(JSON.stringify({id,method,params}));})});ws.onerror=reject;ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return};if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.rej(new Error(JSON.stringify(m.error))):p.res(m.result);}};});}
const c=await connect(wsUrl);try{const expr=`(()=>{const roots=[document],q=[document],seen=new Set(q);while(q.length){const r=q.shift();let els=[];try{els=[...r.querySelectorAll('*')]}catch{};for(const e of els){if(e.shadowRoot&&!seen.has(e.shadowRoot)){seen.add(e.shadowRoot);roots.push(e.shadowRoot);q.push(e.shadowRoot)}}}let texts=[],attrs=[];for(const r of roots){let els=[];try{els=[...r.querySelectorAll('*')]}catch{};for(const e of els){const t=(e.innerText||e.textContent||'').replace(/\s+/g,' ').trim();if(t&&t.length<300)texts.push(t);for(const a of ['aria-label','title','data-tooltip','alt']){const v=e.getAttribute?.(a);if(v)attrs.push(v)}}}const all=[...new Set([...texts,...attrs])];const emails=[...new Set(all.flatMap(x=>x.match(/[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}/ig)||[]))];const creditLines=all.filter(x=>/credit|credits|크레딧|AI\s*credit|AI\s*credits/i.test(x)).slice(0,80);const accountLines=all.filter(x=>/google account|account|계정|프로필|profile/i.test(x)&&x.length<220).slice(0,40);return {url:location.href,title:document.title,emails,creditLines,accountLines,bodyTextLength:(document.body?.innerText||'').length}})()`;const r=await c.send('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true,userGesture:false});console.log(JSON.stringify({ok:true,page:r.result?.value||null}));}finally{try{c.ws.close()}catch{};setTimeout(()=>process.exit(0),50)}
'@;Set-Content -LiteralPath $js -Value $code -Encoding UTF8
$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$node.Source;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.Arguments=('"'+$js+'" "'+[string]$page.webSocketDebuggerUrl+'"');$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();if(-not $p.WaitForExit(20000)){try{& taskkill.exe /PID $p.Id /T /F 2>$null|Out-Null}catch{};throw 'FLOW_CREDIT_NODE_TIMEOUT_20S'};$raw=$ot.Result.Trim();$err=$et.Result.Trim();Remove-Item $js -Force -ErrorAction SilentlyContinue;if(!$raw){throw ('FLOW_CREDIT_EMPTY:'+ $err)};$scan=($raw.Split("`n")|Select-Object -Last 1)|ConvertFrom-Json
StopDedicated;$args2=@("--user-data-dir=$UserData",'--profile-directory=Default','--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble');if(Test-Path -LiteralPath (Join-Path $NotebookExt 'manifest.json') -PathType Leaf){$args2+=("--load-extension=$NotebookExt")};$args2+=$NotebookFront;Start-Process -FilePath $chrome.FullName -ArgumentList $args2 -WorkingDirectory $chrome.Directory.FullName|Out-Null;Start-Sleep -Seconds 2
$normalAfter=@(NormalRoots);$missing=@($normalBefore|Where-Object{$normalAfter -notcontains $_});$result=[ordered]@{ok=[bool]($scan.ok -and $missing.Count -eq 0);action='FLOW_APPROVED_ACCOUNT_CREDIT_READONLY';flowUrl=$FlowUrl;emails=@($scan.page.emails);creditLines=@($scan.page.creditLines);accountLines=@($scan.page.accountLines);pageUrl=[string]$scan.page.url;pageTitle=[string]$scan.page.title;normalChromeUntouched=($missing.Count -eq 0);notebookDedicatedRestored=$true;generateClicked=$false;creditSpend=$false;oauthChanged=$false;scopeChanged=$false;chromeSettingsChanged=$false;readOnly=$true;checkedAt=(Get-Date).ToString('o')};$dir=Join-Path $central 'Runtime_Readback\Flow_Bridge_Direct';New-Item -ItemType Directory -Force -Path $dir|Out-Null;$path=Join-Path $dir 'FLOW_APPROVED_ACCOUNT_CREDIT_READONLY.json';$result|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $path -Encoding UTF8;$result['resultPath']=$path;$result|ConvertTo-Json -Depth 30 -Compress;exit $(if($result.ok){0}else{2})