param(
  [int]$DebugPort=9224,
  [switch]$NavigateWorkspace,
  [int]$TimeoutSeconds=120,
  [string]$CentralRootOverride=''
)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Version='FLOW_ACCOUNT_WORKSPACE_V2_20260829'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7';$UserData=Join-Path $Base 'ChromeUserData';$CftRoot=Join-Path $Base 'ChromeForTesting';$FlowUrl='https://labs.google/fx/tools/flow';$NotebookExt=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge';$NotebookFront='https://notebooklm-webapp-bridge.vercel.app/'
function FindCentral{if($CentralRootOverride -and (Test-Path -LiteralPath $CentralRootOverride)){return $CentralRootOverride};$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(!$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('내 드라이브\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c){return $c}}};return ''}
function FindFlowExt{foreach($p in @((Join-Path $env:USERPROFILE 'Downloads\flow-agent-bridge-v0.1.0\flow-agent-bridge-v0.1.0'),(Join-Path $env:USERPROFILE 'Downloads\flow-agent-bridge-v0.1.0'),(Join-Path $Base 'Extension\Flow-Agent-Bridge'),(Join-Path $Base 'Extension\Google-AI-Local-Bridge-Flow'))){if(Test-Path -LiteralPath (Join-Path $p 'manifest.json') -PathType Leaf){return $p}};return ''}
function Dedicated{try{@(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and ([string]$_.CommandLine).Contains($UserData)})}catch{@()}}
function NormalRoots{try{@(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{(-not $_.CommandLine -or -not([string]$_.CommandLine).Contains($UserData)) -and (-not $_.CommandLine -or ([string]$_.CommandLine)-notmatch '(?i)(^|\s)--type=')}|ForEach-Object{[int]$_.ProcessId})}catch{@()}}
function StopDedicated{foreach($p in @(Dedicated)){try{& taskkill.exe /PID ([int]$p.ProcessId) /T /F 2>$null|Out-Null}catch{}};Start-Sleep -Seconds 2}
function Pages{try{return @(Invoke-RestMethod -Uri ("http://127.0.0.1:$DebugPort/json/list") -TimeoutSec 3|Where-Object{$_.type -eq 'page'})}catch{return @()}}
function InvokeDom([string]$WsUrl,[bool]$AllowClick){
  $node=Get-Command node.exe -ErrorAction SilentlyContinue;if(!$node){$node=Get-Command node -ErrorAction Stop};$js=Join-Path $env:TEMP ('flow-workspace-'+[guid]::NewGuid().ToString('N')+'.mjs')
  $code=@'
const wsUrl=process.argv[2], allowClick=process.argv[3]==='1';
function connect(url){return new Promise((resolve,reject)=>{const ws=new WebSocket(url);let seq=0;const pending=new Map();ws.onopen=()=>resolve({ws,send:(method,params={})=>new Promise((res,rej)=>{const id=++seq;pending.set(id,{res,rej});ws.send(JSON.stringify({id,method,params}));})});ws.onerror=reject;ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return};if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.rej(new Error(JSON.stringify(m.error))):p.res(m.result)}}})}
const c=await connect(wsUrl);try{const expr=`(()=>{const norm=s=>String(s||'').trim().replace(/\\s+/g,' ');const all=[...document.querySelectorAll('button,[role="button"],a,input[type="submit"]')].filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&!e.disabled});const items=all.map((e,i)=>({i,text:norm(e.innerText||e.textContent||e.value||e.getAttribute('aria-label')||''),href:e.href||'',tag:e.tagName}));const text=(document.body?.innerText||'').slice(0,8000);const input=[...document.querySelectorAll('textarea,input[type="text"],[contenteditable="true"],[role="textbox"]')].find(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&!e.disabled});const url=location.href;let state='OTHER';if(/accounts\\.google\\.com/i.test(url))state='GOOGLE_LOGIN';else if(/labs\\.google\/fx\/tools\/flow/i.test(url)){state=input?'FLOW_WORKSPACE':'FLOW_LANDING_OR_CONSENT'}else if(/labs\\.google/i.test(url))state='GOOGLE_LABS_INTERMEDIATE';const password=!!document.querySelector('input[type="password"]')||/비밀번호|password/i.test(text);const emailPrompt=!!document.querySelector('input[type="email"]')||/이메일 또는 휴대전화|email or phone/i.test(text);let clicked=null;if(${allowClick?'true':'false'}&&!input){const groups=[[/^계속$/i,/^continue$/i,/^동의$/i,/^agree$/i,/^허용$/i,/^allow$/i,/^시작하기$/i,/^get started$/i,/^try flow$/i,/^open flow$/i,/^확인$/i,/^confirm$/i],[/open|resume|continue project|recent|프로젝트 열기|이어하기/i],[/new project|create project|새 프로젝트|새로 만들기/i]];outer:for(const group of groups){for(const it of items){if(group.some(rx=>rx.test(it.text))){try{all[it.i].click();clicked=it;break outer}catch{}}}}}return {url,title:document.title,state,inputFound:!!input,passwordPrompt:password,emailPrompt,clicked,buttons:items.slice(0,100),bodyText:text};})()`;const r=await c.send('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true,userGesture:true});console.log(JSON.stringify(r.result?.value||{}));}finally{try{c.ws.close()}catch{};setTimeout(()=>process.exit(0),40)}
'@;Set-Content -LiteralPath $js -Value $code -Encoding UTF8
  try{$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$node.Source;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.Arguments=('"'+$js+'" "'+$WsUrl+'" '+$(if($AllowClick){'1'}else{'0'}));$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();if(-not $p.WaitForExit(15000)){try{& taskkill.exe /PID $p.Id /T /F 2>$null|Out-Null}catch{};throw 'FLOW_DOM_TIMEOUT_15S'};$raw=$ot.Result.Trim();if(!$raw){throw ('FLOW_DOM_EMPTY:'+ $et.Result.Trim())};return (($raw.Split("`n")|Select-Object -Last 1)|ConvertFrom-Json)}finally{Remove-Item $js -Force -ErrorAction SilentlyContinue}
}
$central=FindCentral;if(!$central){throw 'CENTRAL_DRIVE_ROOT_NOT_FOUND'};$FlowExt=FindFlowExt;if(!$FlowExt){throw 'FLOW_EXTENSION_PATH_NOT_FOUND'};$chrome=Get-ChildItem -LiteralPath $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction Stop|Sort-Object FullName -Descending|Select-Object -First 1;if(!$chrome){throw 'CFT_CHROME_NOT_FOUND'}
$normalBefore=@(NormalRoots);StopDedicated;$args=@("--user-data-dir=$UserData",'--profile-directory=Default','--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',("--load-extension=$FlowExt"),("--remote-debugging-port=$DebugPort"),'--remote-debugging-address=127.0.0.1',$FlowUrl);Start-Process -FilePath $chrome.FullName -ArgumentList $args -WorkingDirectory $chrome.Directory.FullName|Out-Null
$deadline=(Get-Date).AddSeconds($(if($NavigateWorkspace){$TimeoutSeconds}else{30}));$history=@();$final=$null;$credentialRequired=$false
while((Get-Date)-lt $deadline){$targets=@(Pages);$page=$targets|Where-Object{([string]$_.url) -match 'accounts\.google\.com|labs\.google'}|Select-Object -First 1;if(!$page){Start-Sleep -Milliseconds 600;continue};$scan=InvokeDom ([string]$page.webSocketDebuggerUrl) ([bool]$NavigateWorkspace);$history += [ordered]@{at=(Get-Date).ToString('o');url=[string]$scan.url;title=[string]$scan.title;state=[string]$scan.state;inputFound=[bool]$scan.inputFound;clicked=$scan.clicked};$final=$scan;if($NavigateWorkspace -and [string]$scan.state -eq 'FLOW_WORKSPACE' -and $scan.inputFound){break};if($NavigateWorkspace -and [string]$scan.state -eq 'GOOGLE_LOGIN' -and ($scan.passwordPrompt -or $scan.emailPrompt)){$credentialRequired=$true;break};if(-not $NavigateWorkspace -and [string]$scan.state -eq 'FLOW_WORKSPACE'){break};Start-Sleep -Seconds 2}
$normalAfter=@(NormalRoots);$missing=@($normalBefore|Where-Object{$normalAfter -notcontains $_})
if($NavigateWorkspace){$ok=[bool]($final -and [string]$final.state -eq 'FLOW_WORKSPACE' -and $final.inputFound -and $missing.Count -eq 0);$result=[ordered]@{ok=$ok;action='FLOW_LOGIN_CONSENT_TO_WORKSPACE';version=$Version;workspaceReached=$ok;credentialEntryRequired=$credentialRequired;finalState=$(if($final){[string]$final.state}else{'NO_PAGE'});pageUrl=$(if($final){[string]$final.url}else{''});pageTitle=$(if($final){[string]$final.title}else{''});inputFound=$(if($final){[bool]$final.inputFound}else{$false});history=$history;normalChromeUntouched=($missing.Count -eq 0);generateClicked=$false;creditSpend=$false;credentialEnteredByAutomation=$false;checkedAt=(Get-Date).ToString('o')};$dir=Join-Path $central 'Runtime_Readback\Flow_Bridge_Direct';New-Item -ItemType Directory -Force -Path $dir|Out-Null;$path=Join-Path $dir 'FLOW_LOGIN_CONSENT_TO_WORKSPACE.json';$result|ConvertTo-Json -Depth 40|Set-Content -LiteralPath $path -Encoding UTF8;$result['resultPath']=$path;$result|ConvertTo-Json -Depth 40 -Compress;if($ok){exit 0}elseif($credentialRequired){exit 3}else{exit 2}}
if(-not $final -or [string]$final.state -ne 'FLOW_WORKSPACE'){throw 'FLOW_WORKSPACE_NOT_REACHED_FOR_CREDIT_READBACK'}
$scan=$final;$texts=@([string]$scan.bodyText);$emails=@([regex]::Matches([string]$scan.bodyText,'[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}','IgnoreCase')|ForEach-Object{$_.Value}|Select-Object -Unique);$creditLines=@(([string]$scan.bodyText -split "`r?`n")|Where-Object{$_ -match '(?i)credit|credits|크레딧'}|Select-Object -First 80)
StopDedicated;$args2=@("--user-data-dir=$UserData",'--profile-directory=Default','--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble');if(Test-Path -LiteralPath (Join-Path $NotebookExt 'manifest.json') -PathType Leaf){$args2+=("--load-extension=$NotebookExt")};$args2+=$NotebookFront;Start-Process -FilePath $chrome.FullName -ArgumentList $args2 -WorkingDirectory $chrome.Directory.FullName|Out-Null;Start-Sleep 2
$result=[ordered]@{ok=[bool]($missing.Count -eq 0);action='FLOW_APPROVED_ACCOUNT_CREDIT_READONLY';version=$Version;flowUrl=$FlowUrl;emails=$emails;creditLines=$creditLines;pageUrl=[string]$scan.url;pageTitle=[string]$scan.title;normalChromeUntouched=($missing.Count -eq 0);notebookDedicatedRestored=$true;generateClicked=$false;creditSpend=$false;readOnly=$true;checkedAt=(Get-Date).ToString('o')};$dir=Join-Path $central 'Runtime_Readback\Flow_Bridge_Direct';New-Item -ItemType Directory -Force -Path $dir|Out-Null;$path=Join-Path $dir 'FLOW_APPROVED_ACCOUNT_CREDIT_READONLY.json';$result|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $path -Encoding UTF8;$result['resultPath']=$path;$result|ConvertTo-Json -Depth 30 -Compress;exit $(if($result.ok){0}else{2})