param(
  [ValidateSet('Inventory','SyncRegistry','Stage','Rollback','LaunchDedicated')]
  [string]$Mode='Inventory',
  [string]$RegistryUrl='https://raw.githubusercontent.com/8friend8ship-cloud/notebooklm-webapp-bridge/main/config/managed-extension-autopilot-v1.json',
  [string]$SourceZip='',
  [string]$SourceDir='',
  [string]$SourceUrl='',
  [string]$ManifestSubPath='',
  [string]$ExpectedExtensionId='',
  [switch]$Apply,
  [switch]$RestartDedicatedChrome
)

$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='MANAGED_EXTENSION_AUTOPILOT_V1_20260828'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$Root=Join-Path $Base 'ManagedExtensions'
$StatePath=Join-Path $Root 'autopilot-state.json'
$LogRoot=Join-Path $Root 'Logs'
$DedicatedUserData=Join-Path $Base 'ChromeUserData'
New-Item -ItemType Directory -Force -Path $Root,$LogRoot,$DedicatedUserData|Out-Null

function Read-Json([string]$Path){if(-not(Test-Path -LiteralPath $Path)){return $null};try{return Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{return $null}}
function Save-State($State){$State.updatedAt=(Get-Date).ToUniversalTime().ToString('o');$State|ConvertTo-Json -Depth 40|Set-Content -LiteralPath $StatePath -Encoding UTF8}
function Get-State{ $s=Read-Json $StatePath; if(-not $s){$s=[pscustomobject]@{schema='MANAGED_EXTENSION_AUTOPILOT_STATE_V1';version=$Version;updatedAt='';extensions=@();history=@();policy=[pscustomobject]@{noDelete=$true;noCredentialRead=$true;noNewOAuth=$true;noNormalChromeRestart=$true;dedicatedChromeOnly=$true;preserveLastGood=$true;userFinalGate='CHATGPT_SITE_PERMISSION_ONLY'}}}; return $s }
function Add-History($State,$Action,$Name,$Status,$Detail){$State.history=@($State.history)+@([pscustomobject]@{at=(Get-Date).ToUniversalTime().ToString('o');action=$Action;name=$Name;status=$Status;detail=$Detail});if(@($State.history).Count -gt 300){$State.history=@($State.history|Select-Object -Last 300)}}
function Find-Chrome{ @((Join-Path $env:ProgramFiles 'Google\Chrome\Application\chrome.exe'),(Join-Path ${env:ProgramFiles(x86)} 'Google\Chrome\Application\chrome.exe'),(Join-Path $env:LOCALAPPDATA 'Google\Chrome\Application\chrome.exe'))|Where-Object{$_ -and (Test-Path -LiteralPath $_)}|Select-Object -First 1 }
function Resolve-ManifestRoot([string]$InputRoot,[string]$Sub){if($Sub){$p=Join-Path $InputRoot $Sub;if(Test-Path -LiteralPath (Join-Path $p 'manifest.json')){return (Resolve-Path $p).Path};throw 'MANIFEST_SUBPATH_NOT_FOUND'};if(Test-Path -LiteralPath (Join-Path $InputRoot 'manifest.json')){return (Resolve-Path $InputRoot).Path};$m=@(Get-ChildItem -LiteralPath $InputRoot -Filter manifest.json -File -Recurse -ErrorAction SilentlyContinue);if($m.Count -eq 0){throw 'MANIFEST_NOT_FOUND'};return ($m|Sort-Object{$_.Directory.FullName.Length}|Select-Object -First 1).Directory.FullName}
function Test-Manifest([string]$RootPath,$Manifest){$errors=@();if([int]$Manifest.manifest_version -ne 3){$errors+='MANIFEST_V3_REQUIRED'};if($Manifest.background -and $Manifest.background.service_worker){$p=Join-Path $RootPath ([string]$Manifest.background.service_worker);if(-not(Test-Path $p)){$errors+='MISSING_SERVICE_WORKER'}};foreach($spec in @($Manifest.content_scripts)){foreach($js in @($spec.js)){if($js -and -not(Test-Path (Join-Path $RootPath ([string]$js)))){$errors+=('MISSING_CONTENT_SCRIPT:'+$js)}}};return $errors}
function Get-TreeHash([string]$RootPath){$rows=@();Get-ChildItem -LiteralPath $RootPath -File -Recurse|Sort-Object FullName|ForEach-Object{$rel=$_.FullName.Substring($RootPath.Length).TrimStart('\\','/');$rows+=((Get-FileHash $_.FullName -Algorithm SHA256).Hash+'  '+$rel)};$tmp=Join-Path $env:TEMP ('ext_hash_'+[guid]::NewGuid().ToString('N')+'.txt');$rows|Set-Content $tmp -Encoding UTF8;try{return (Get-FileHash $tmp -Algorithm SHA256).Hash}finally{Remove-Item $tmp -Force -ErrorAction SilentlyContinue}}
function Upsert($State,$Entry){$e=@($State.extensions)|Where-Object{($_.name -eq $Entry.name) -or ($Entry.expectedExtensionId -and $_.expectedExtensionId -eq $Entry.expectedExtensionId)}|Select-Object -First 1;if($e){foreach($p in $Entry.PSObject.Properties){$e|Add-Member -NotePropertyName $p.Name -NotePropertyValue $p.Value -Force}}else{$State.extensions=@($State.extensions)+@($Entry)}}
function Stage-One($State,[string]$Zip,[string]$Dir,[string]$Url,[string]$Sub,[string]$ExtId,[bool]$DoApply){$temp='';$download='';try{if($Url){$download=Join-Path $env:TEMP ('managed_ext_'+[guid]::NewGuid().ToString('N')+'.zip');Invoke-WebRequest -UseBasicParsing -Uri $Url -OutFile $download -TimeoutSec 120;$Zip=$download};if($Zip){$temp=Join-Path $env:TEMP ('managed_ext_unpack_'+[guid]::NewGuid().ToString('N'));New-Item -ItemType Directory -Force -Path $temp|Out-Null;Expand-Archive -LiteralPath $Zip -DestinationPath $temp -Force;$input=$temp}elseif($Dir){$input=(Resolve-Path $Dir).Path}else{throw 'SOURCE_REQUIRED'};$mr=Resolve-ManifestRoot $input $Sub;$manifest=Read-Json (Join-Path $mr 'manifest.json');if(-not $manifest){throw 'MANIFEST_PARSE_FAILED'};$errs=@(Test-Manifest $mr $manifest);if($errs.Count){throw ('MANIFEST_INTEGRITY_FAILED:'+($errs -join '|'))};$safe=([string]$manifest.name -replace '[^A-Za-z0-9._-]+','_').Trim('_');$target=Join-Path (Join-Path $Root $safe) ([string]$manifest.version);New-Item -ItemType Directory -Force -Path $target|Out-Null;Copy-Item -Path (Join-Path $mr '*') -Destination $target -Recurse -Force;$hash=Get-TreeHash $target;$old=@($State.extensions)|Where-Object{$_.name -eq [string]$manifest.name}|Select-Object -First 1;$entry=[pscustomobject]@{name=[string]$manifest.name;version=[string]$manifest.version;expectedExtensionId=$ExtId;activePath=$target;previousPath=$(if($old){[string]$old.activePath}else{''});active=$true;treeSha256=$hash;sourceUrl=$Url;sourceZip=$Zip;sourceDir=$Dir;stagedAt=(Get-Date).ToUniversalTime().ToString('o');approval='AUTO_SAFE_EXISTING_SCOPE; NEW_PERMISSION_PROMPT=>USER_SITE_PERMISSION_GATE'};Upsert $State $entry;Add-History $State 'STAGE' $entry.name 'PASS' ('version='+$entry.version+';hash='+$hash);Save-State $State;return $entry}finally{if($temp -and (Test-Path $temp)){Remove-Item $temp -Recurse -Force -ErrorAction SilentlyContinue};if($download -and (Test-Path $download)){Remove-Item $download -Force -ErrorAction SilentlyContinue}}}
function Launch-Managed($State,[bool]$Restart){$chrome=Find-Chrome;if(-not $chrome){throw 'CHROME_EXE_NOT_FOUND'};$paths=@($State.extensions|Where-Object{$_.active -eq $true -and $_.activePath -and (Test-Path $_.activePath)}|ForEach-Object{$_.activePath}|Select-Object -Unique);if($paths.Count -eq 0){throw 'NO_ACTIVE_MANAGED_EXTENSIONS'};if($Restart){Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like "*$DedicatedUserData*"}|ForEach-Object{Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue};Start-Sleep 2};$args=@("--user-data-dir=$DedicatedUserData",'--no-first-run','--disable-default-apps',('--load-extension='+($paths -join ',')),'chrome://extensions/');Start-Process -FilePath $chrome -ArgumentList $args|Out-Null;return [pscustomobject]@{ok=$true;userDataDir=$DedicatedUserData;loadedPaths=$paths}}

$state=Get-State
if($Mode -eq 'Inventory'){[pscustomobject]@{ok=$true;version=$Version;state=$state;statePath=$StatePath}|ConvertTo-Json -Depth 40;exit 0}
if($Mode -eq 'Stage'){ $entry=Stage-One $state $SourceZip $SourceDir $SourceUrl $ManifestSubPath $ExpectedExtensionId ([bool]$Apply); if($Apply){$launch=Launch-Managed $state ([bool]$RestartDedicatedChrome)};[pscustomobject]@{ok=$true;entry=$entry;launch=$launch;statePath=$StatePath}|ConvertTo-Json -Depth 20;exit 0 }
if($Mode -eq 'SyncRegistry'){ $registry=Invoke-RestMethod -Uri $RegistryUrl -TimeoutSec 60;foreach($item in @($registry.extensions)){if([string]$item.installMode -eq 'AUTO_GITHUB_ZIP' -and $item.sourceUrl){try{Stage-One $state '' '' ([string]$item.sourceUrl) ([string]$item.manifestSubPath) ([string]$item.extensionId) $false|Out-Null}catch{Add-History $state 'SYNC_REGISTRY' ([string]$item.name) 'ERROR' $_.Exception.Message}}else{Add-History $state 'SYNC_REGISTRY' ([string]$item.name) 'OBSERVE' ([string]$item.installMode)}};Save-State $state;if($Apply){$launch=Launch-Managed $state ([bool]$RestartDedicatedChrome)};[pscustomobject]@{ok=$true;synced=@($registry.extensions).Count;launch=$launch;statePath=$StatePath;userFinalGate='Only review ChatGPT Computer Use site permissions after automatic staging/launch/readback PASS'}|ConvertTo-Json -Depth 20;exit 0 }
if($Mode -eq 'Rollback'){foreach($e in @($state.extensions|Where-Object{$_.previousPath -and (Test-Path $_.previousPath)})){if($ExpectedExtensionId -and $e.expectedExtensionId -ne $ExpectedExtensionId){continue};$x=$e.activePath;$e.activePath=$e.previousPath;$e.previousPath=$x;Add-History $state 'ROLLBACK' $e.name 'PASS' ('active='+$e.activePath)};Save-State $state;if($Apply){$launch=Launch-Managed $state ([bool]$RestartDedicatedChrome)};[pscustomobject]@{ok=$true;launch=$launch}|ConvertTo-Json -Depth 10;exit 0}
if($Mode -eq 'LaunchDedicated'){Launch-Managed $state ([bool]$RestartDedicatedChrome)|ConvertTo-Json -Depth 10;exit 0}
