param(
  [string]$TaskId='GEMINI_WEB_QA',
  [string]$FixtureId='',
  [string]$FixtureUrl='',
  [string]$PromptText='',
  [string]$CentralRootOverride='',
  [int]$DebugPort=9226,
  [int]$TimeoutSeconds=120
)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7';$UserData=Join-Path $Base 'ChromeUserData';$CftRoot=Join-Path $Base 'ChromeForTesting';$NotebookExt=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge';$NotebookFront='https://notebooklm-webapp-bridge.vercel.app/';$GeminiUrl='https://gemini.google.com/app'
function FindCentral{if($CentralRootOverride -and (Test-Path -LiteralPath $CentralRootOverride -PathType Container)){return $CentralRootOverride};$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(!$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('내 드라이브\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};throw 'CENTRAL_DRIVE_ROOT_NOT_FOUND'}
function Dedicated{try{@(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and ([string]$_.CommandLine).Contains($UserData)})}catch{@()}}
function NormalRoots{try{@(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{(-not $_.CommandLine -or -not([string]$_.CommandLine).Contains($UserData)) -and (-not $_.CommandLine -or ([string]$_.CommandLine)-notmatch '(?i)(^|\s)--type=')}|ForEach-Object{[int]$_.ProcessId})}catch{@()}}
function StopDedicated{foreach($p in @(Dedicated)){try{& taskkill.exe /PID ([int]$p.ProcessId) /T /F 2>$null|Out-Null}catch{}};Start-Sleep -Seconds 2}
function RestoreNotebook([IO.FileInfo]$Chrome){StopDedicated;$args=@("--user-data-dir=$UserData",'--profile-directory=Default','--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble');if(Test-Path -LiteralPath (Join-Path $NotebookExt 'manifest.json') -PathType Leaf){$args+=("--load-extension=$NotebookExt")};$args+=$NotebookFront;try{Start-Process -FilePath $Chrome.FullName -ArgumentList $args -WorkingDirectory $Chrome.Directory.FullName|Out-Null;Start-Sleep -Seconds 2;return $true}catch{return $false}}
$central=FindCentral;$chrome=Get-ChildItem -LiteralPath $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction Stop|Sort-Object FullName -Descending|Select-Object -First 1;if(!$chrome){throw 'CFT_CHROME_NOT_FOUND'}
if([string]::IsNullOrWhiteSpace($PromptText)){throw 'PROMPT_TEXT_REQUIRED'};if($PromptText.Length -gt 12000){$PromptText=$PromptText.Substring(0,12000)}
$normalBefore=@(NormalRoots);StopDedicated;$args=@("--user-data-dir=$UserData",'--profile-directory=Default','--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',("--remote-debugging-port=$DebugPort"),'--remote-debugging-address=127.0.0.1',$GeminiUrl);Start-Process -FilePath $chrome.FullName -ArgumentList $args -WorkingDirectory $chrome.Directory.FullName|Out-Null
$targets=@();$deadline=(Get-Date).AddSeconds(30);do{try{$targets=@(Invoke-RestMethod -Uri ("http://127.0.0.1:$DebugPort/json/list") -TimeoutSec 2);if(@($targets|Where-Object{$_.type -eq 'page' -and ([string]$_.url).Contains('gemini.google.com')}).Count){break}}catch{};Start-Sleep -Milliseconds 500}while((Get-Date)-lt $deadline)
$page=$targets|Where-Object{$_.type -eq 'page' -and ([string]$_.url).Contains('gemini.google.com')}|Select-Object -First 1;if(!$page){$rest=RestoreNotebook $chrome;throw 'GEMINI_PAGE_NOT_FOUND'}
$node=Get-Command node.exe -ErrorAction SilentlyContinue;if(!$node){$node=Get-Command node -ErrorAction Stop};$js=Join-Path $env:TEMP ('gemini-web-qa-'+[guid]::NewGuid().ToString('N')+'.mjs');$promptB64=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($PromptText))
$code=@'
const wsUrl=process.argv[2], prompt=Buffer.from(process.argv[3],'base64').toString('utf8'), timeoutMs=Number(process.argv[4]||120000);
function connect(url){return new Promise((resolve,reject)=>{const ws=new WebSocket(url);let seq=0;const pending=new Map();ws.onopen=()=>resolve({ws,send:(method,params={})=>new Promise((res,rej)=>{const id=++seq;pending.set(id,{res,rej});ws.send(JSON.stringify({id,method,params}));})});ws.onerror=reject;ws.onmessage=e=>{let m;try{m=JSON.parse(e.data)}catch{return};if(m.id&&pending.has(m.id)){const p=pending.get(m.id);pending.delete(m.id);m.error?p.rej(new Error(JSON.stringify(m.error))):p.res(m.result);}};});}
const c=await connect(wsUrl);const evalv=async expr=>(await c.send('Runtime.evaluate',{expression:expr,returnByValue:true,awaitPromise:true,userGesture:true})).result?.value;
try{
 const pre=await evalv(`(()=>{const tx=(document.body?.innerText||'').replace(/\\s+/g,' ').slice(0,8000);return {url:location.href,title:document.title,login:/sign in|로그인/i.test(tx),consent:/terms|privacy|agree|동의|약관/i.test(tx)&&!/recent|최근/i.test(tx),upgrade:/upgrade|구독하기|결제|payment/i.test(tx),body:tx.slice(0,2000)}})()`);
 if(pre.login||pre.consent||pre.upgrade){console.log(JSON.stringify({ok:false,stage:'ACCOUNT_OR_CONSENT_GATE',preflight:pre,submitted:false}));process.exitCode=2;}
 else {
  const p64=Buffer.from(prompt,'utf8').toString('base64');
  const fill=await evalv(`(()=>{const p=new TextDecoder().decode(Uint8Array.from(atob('${p64}'),c=>c.charCodeAt(0)));const roots=[document],q=[document],seen=new Set(q);while(q.length){const r=q.shift();let es=[];try{es=[...r.querySelectorAll('*')]}catch{};for(const e of es){if(e.shadowRoot&&!seen.has(e.shadowRoot)){seen.add(e.shadowRoot);roots.push(e.shadowRoot);q.push(e.shadowRoot)}}}const vis=e=>{const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>20&&r.height>20};let cand=[];for(const r of roots){try{cand.push(...r.querySelectorAll('textarea,[contenteditable=true],[role=textbox]'))}catch{}}cand=[...new Set(cand)].filter(vis);let e=cand.find(x=>/prompt|ask|message|gemini|입력|질문|메시지/i.test([x.getAttribute?.('aria-label'),x.getAttribute?.('placeholder')].filter(Boolean).join(' ')))||cand[0];if(!e)return {ok:false,reason:'INPUT_NOT_FOUND',count:cand.length};e.focus();if('value'in e){const set=Object.getOwnPropertyDescriptor(e.tagName==='TEXTAREA'?HTMLTextAreaElement.prototype:HTMLInputElement.prototype,'value')?.set;if(set)set.call(e,p);else e.value=p}else e.textContent=p;try{e.dispatchEvent(new InputEvent('input',{bubbles:true,inputType:'insertText',data:p}))}catch{e.dispatchEvent(new Event('input',{bubbles:true}))}e.dispatchEvent(new Event('change',{bubbles:true}));const v=('value'in e)?e.value:e.textContent;return {ok:v===p,tag:e.tagName,len:v.length}})()`);
  if(!fill?.ok){console.log(JSON.stringify({ok:false,stage:'INPUT_FILL',fill,submitted:false}));process.exitCode=3;}
  else {await c.send('Input.dispatchKeyEvent',{type:'keyDown',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});await c.send('Input.dispatchKeyEvent',{type:'keyUp',key:'Enter',code:'Enter',windowsVirtualKeyCode:13,nativeVirtualKeyCode:13});const start=Date.now();let last='',resp=null;while(Date.now()-start<timeoutMs){await new Promise(r=>setTimeout(r,2000));resp=await evalv(`(()=>{const tx=(document.body?.innerText||'').replace(/\\s+/g,' ').trim();const busy=/stop responding|응답 중지|generating|생성 중/i.test(tx);return {len:tx.length,busy,tail:tx.slice(-12000)}})()`);if(resp&&resp.len>last.length+200&&!resp.busy&&Date.now()-start>6000)break;last=resp?.tail||last;}console.log(JSON.stringify({ok:!!resp&&resp.len>200,stage:'RESULT',submitted:true,response:resp}));}
 }
}finally{try{c.ws.close()}catch{};setTimeout(()=>process.exit(process.exitCode||0),50)}
'@
Set-Content -LiteralPath $js -Value $code -Encoding UTF8
$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$node.Source;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.Arguments=('"'+$js+'" "'+[string]$page.webSocketDebuggerUrl+'" "'+$promptB64+'" '+([Math]::Min(120,$TimeoutSeconds)*1000));$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();$maxWait=([Math]::Min(120,$TimeoutSeconds)+30)*1000;if(-not $p.WaitForExit($maxWait)){try{& taskkill.exe /PID $p.Id /T /F 2>$null|Out-Null}catch{};$raw='';$err='NODE_TIMEOUT'}else{$raw=$ot.Result.Trim();$err=$et.Result.Trim()};Remove-Item $js -Force -ErrorAction SilentlyContinue
$parsed=$null;if($raw){try{$parsed=($raw.Split("`n")|Select-Object -Last 1)|ConvertFrom-Json}catch{}}
$restored=RestoreNotebook $chrome;$normalAfter=@(NormalRoots);$missing=@($normalBefore|Where-Object{$normalAfter -notcontains $_});$ok=($parsed -and [bool]$parsed.ok -and $missing.Count -eq 0 -and $restored)
$result=[ordered]@{ok=[bool]$ok;action='GEMINI_WEB_LEARNING_QA';taskId=$TaskId;fixtureId=$FixtureId;fixtureUrl=$FixtureUrl;provider='GEMINI_WEB_SUBSCRIPTION_UI';providerApiCalled=$false;separateApiCost=$false;result=$parsed;stderr=$err;normalChromeUntouched=($missing.Count -eq 0);notebookDedicatedRestored=[bool]$restored;newOauthOrScope=$false;billingChanged=$false;publicAction=$false;checkedAt=(Get-Date).ToString('o')};$dir=Join-Path $central 'Runtime_Readback\Gemini_QA';New-Item -ItemType Directory -Force -Path $dir|Out-Null;$path=Join-Path $dir ($TaskId+'_result.json');$result|ConvertTo-Json -Depth 40|Set-Content -LiteralPath $path -Encoding UTF8;$result['resultPath']=$path;$result|ConvertTo-Json -Depth 40 -Compress;if($ok){exit 0}else{exit 2}
