param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$ExtensionId='kieodjjlhpefnakodgllmpckepjaggbd'
$ExpectedName='Google AI Local Bridge v1'
$ExpectedVersion='1.0.2'
$ExpectedBuild='NLM_FALLBACK_ROUTE_20260829'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$Root=Join-Path $Base 'LocalAgent'
$ReceiptPath=Join-Path $Root 'GOOGLE_AI_ALWAYS_ON_NOTEBOOKLM_FALLBACK_V1.json'
$CanonicalRoot='extensions/google-ai-always-on-bridge/1.0.2'
New-Item -ItemType Directory -Force -Path $Root|Out-Null

$Canonical=@{
  'service-worker.js'=@{blob='c6ead8195c8fc1a48aab20c96587622ca76a3c38';sha256='689e03cac9e369b9d762728cb7d2236250abe7e33ed9564cc3565bf063c0fb44'}
  'content/notebooklm.js'=@{blob='9d1337dbf2318cd3c22d451dd919dd5bb2ee01f1';sha256='8c0f3afafb38a79b59977579126c025c573046fc8c680e5d4b2f3f517e758b5c'}
}

function Api([string]$Path){Invoke-RestMethod -Uri ('https://api.github.com/repos/'+$Repo+'/contents/'+$Path+'?ref=main&cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -Headers @{'User-Agent'='HomeDesign-AlwaysOn-NLM-Fallback';'Accept'='application/vnd.github+json'} -TimeoutSec 30}
function GitBlob([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return(($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join'')}finally{$s.Dispose()}}
function Sha256([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
function ReadJson([string]$Path){try{Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{$null}}
function FindCentral{$name=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$my=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(-not$d.Root){continue};foreach($c in @((Join-Path $d.Root $name),(Join-Path $d.Root ('My Drive\'+$name)),(Join-Path $d.Root ($my+'\'+$name)),(Join-Path $d.Root ('Google Drive\'+$name)))){if(Test-Path -LiteralPath $c -PathType Container){return$c}}};return''}
function SaveReceipt($o){$json=$o|ConvertTo-Json -Depth 30;$json|Set-Content -LiteralPath $ReceiptPath -Encoding UTF8;$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$json|Set-Content -LiteralPath (Join-Path $d 'GOOGLE_AI_ALWAYS_ON_NOTEBOOKLM_FALLBACK_V1.json') -Encoding UTF8}}
function AddCandidate([System.Collections.ArrayList]$List,[string]$Profile,[string]$Path){if(-not$Path){return};try{$p=(Resolve-Path -LiteralPath $Path -ErrorAction Stop).Path}catch{return};$m=Join-Path $p 'manifest.json';if(-not(Test-Path -LiteralPath $m -PathType Leaf)){return};$j=ReadJson $m;if(-not$j-or[string]$j.name-ne$ExpectedName){return};if(@($List|Where-Object{$_.path-eq$p}).Count-eq0){[void]$List.Add([pscustomobject]@{profile=$Profile;path=$p;version=[string]$j.version})}}
function ScanProfile([System.Collections.ArrayList]$List,[string]$Label,[string]$ProfileRoot){if(-not(Test-Path -LiteralPath $ProfileRoot -PathType Container)){return};foreach($n in @('Preferences','Secure Preferences')){$pref=Join-Path $ProfileRoot $n;if(-not(Test-Path -LiteralPath $pref -PathType Leaf)){continue};try{$data=Get-Content -LiteralPath $pref -Raw -Encoding UTF8|ConvertFrom-Json;$x=$data.extensions.settings.PSObject.Properties[$ExtensionId];if($x-and$x.Value.path){$p=[string]$x.Value.path;if(-not[IO.Path]::IsPathRooted($p)){$p=Join-Path $ProfileRoot $p};AddCandidate $List $Label $p}}catch{}}}
function GetCandidates{$list=New-Object System.Collections.ArrayList;$normal=Join-Path $env:LOCALAPPDATA 'Google\Chrome\User Data';if(Test-Path $normal){foreach($p in @(Get-ChildItem $normal -Directory -ErrorAction SilentlyContinue|Where-Object{$_.Name-eq'Default'-or$_.Name-like'Profile *'})){ScanProfile $list ('NORMAL_CHROME/'+$p.Name) $p.FullName}};ScanProfile $list 'HOMEDESIGN_CFT/Default' (Join-Path $Base 'ChromeUserData\Default');AddCandidate $list 'KNOWN_FALLBACK' (Join-Path $env:USERPROFILE 'Downloads\Google_AI_Always_On_Bridge_v1.0.1_fixed\extension');return@($list)}
function FetchCanonical([string]$Rel,[string]$Temp){$spec=$Canonical[$Rel];$r=Api ($CanonicalRoot+'/'+$Rel);if(([string]$r.sha).ToLowerInvariant()-ne$spec.blob){throw('CANONICAL_BLOB_MISMATCH:'+ $Rel)};[IO.File]::WriteAllBytes($Temp,[Convert]::FromBase64String(([string]$r.content-replace'\s','')));if((GitBlob $Temp).ToLowerInvariant()-ne$spec.blob){throw('DOWNLOADED_BLOB_MISMATCH:'+ $Rel)};if((Sha256 $Temp)-ne$spec.sha256){throw('DOWNLOADED_SHA256_MISMATCH:'+ $Rel)}}
function UpdateTarget($c,[string]$stamp){$path=[string]$c.path;$config=Join-Path $path 'config.js';if(-not(Test-Path -LiteralPath $config -PathType Leaf)){throw'CONFIG_MISSING'};$configBefore=Sha256 $config;$backup=Join-Path (Join-Path $Base 'Backups\GoogleAIAlwaysOnBridgeNLM') ($stamp+'_'+([string]$c.profile-replace'[^A-Za-z0-9_.-]','_'));New-Item -ItemType Directory -Force -Path (Join-Path $backup 'content')|Out-Null;$rels=@('service-worker.js','content/notebooklm.js');foreach($rel in $rels){$src=Join-Path $path ($rel-replace'/','\');if(Test-Path $src){$bak=Join-Path $backup ($rel-replace'/','\');$par=Split-Path -Parent $bak;if(-not(Test-Path $par)){New-Item -ItemType Directory -Force -Path $par|Out-Null};Copy-Item $src $bak -Force}};$temps=@{};try{foreach($rel in $rels){$dest=Join-Path $path ($rel-replace'/','\');$par=Split-Path -Parent $dest;if(-not(Test-Path $par)){New-Item -ItemType Directory -Force -Path $par|Out-Null};$tmp=$dest+'.nlmfallback';FetchCanonical $rel $tmp;$temps[$rel]=$tmp};foreach($rel in $rels){$dest=Join-Path $path ($rel-replace'/','\');Move-Item $temps[$rel] $dest -Force;if((Sha256 $dest)-ne$Canonical[$rel].sha256){throw('POST_SHA_MISMATCH:'+ $rel)}};if((Sha256 $config)-ne$configBefore){throw'CONFIG_MUTATION_DETECTED'};return[pscustomobject]@{ok=$true;profile=$c.profile;path=$path;backupPath=$backup;configPreserved=$true;serviceWorkerSha256=(Sha256 (Join-Path $path 'service-worker.js'));notebooklmSha256=(Sha256 (Join-Path $path 'content\notebooklm.js'))}}catch{foreach($rel in $rels){$bak=Join-Path $backup ($rel-replace'/','\');$dest=Join-Path $path ($rel-replace'/','\');if(Test-Path $bak){Copy-Item $bak $dest -Force};if($temps.ContainsKey($rel)){Remove-Item $temps[$rel] -Force -ErrorAction SilentlyContinue}};throw}}
function CdpPorts{$o=@();try{foreach($p in @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue)){$cmd=[string]$p.CommandLine;if($cmd-match'--remote-debugging-port(?:=|\s+)(\d+)'){$o+=[int]$Matches[1]}}}catch{};return@($o|Sort-Object -Unique)}
function EvalWs([string]$Ws,[string]$Expr){$node=Get-Command node.exe -ErrorAction SilentlyContinue;if(-not$node){$node=Get-Command node -ErrorAction SilentlyContinue};if(-not$node){return$null};$js=Join-Path $env:TEMP ('hd-nlm-reload-'+[guid]::NewGuid().ToString('N')+'.mjs');$code=@'
const u=process.argv[2],e=Buffer.from(process.argv[3],'base64').toString('utf8');const w=new WebSocket(u);let n=0,p=new Map();await new Promise((r,j)=>{w.onopen=r;w.onerror=j});w.onmessage=x=>{let m;try{m=JSON.parse(x.data)}catch{return}if(m.id&&p.has(m.id)){let q=p.get(m.id);p.delete(m.id);m.error?q.j(m.error):q.r(m.result)}};const s=(method,params={})=>new Promise((r,j)=>{let id=++n;p.set(id,{r,j});w.send(JSON.stringify({id,method,params}))});let z=await s('Runtime.evaluate',{expression:e,returnByValue:true,awaitPromise:true,userGesture:true});console.log(JSON.stringify(z.result?.value??null));w.close();
'@;Set-Content $js $code -Encoding UTF8;try{$b=[Convert]::ToBase64String([Text.Encoding]::UTF8.GetBytes($Expr));$out=& $node.Source $js $Ws $b 2>$null|Out-String;return$out.Trim()}catch{return$null}finally{Remove-Item $js -Force -ErrorAction SilentlyContinue}}
function ReloadExtension{foreach($port in @(CdpPorts)){try{$targets=@(Invoke-RestMethod ('http://127.0.0.1:'+ $port +'/json/list') -TimeoutSec 3);$t=$targets|Where-Object{$_.url-like('chrome-extension://'+$ExtensionId+'/*')-and$_.webSocketDebuggerUrl}|Select-Object -First 1;if(-not$t){continue};[void](EvalWs ([string]$t.webSocketDebuggerUrl) "(()=>{setTimeout(()=>chrome.runtime.reload(),100);return 'RELOAD_SCHEDULED'})()");Start-Sleep 4;$targets=@(Invoke-RestMethod ('http://127.0.0.1:'+ $port +'/json/list') -TimeoutSec 3);$t=$targets|Where-Object{$_.url-like('chrome-extension://'+$ExtensionId+'/*')-and$_.webSocketDebuggerUrl}|Select-Object -First 1;if($t){$v=EvalWs ([string]$t.webSocketDebuggerUrl) 'globalThis.__GOOGLE_AI_ALWAYS_ON_BUILD__||""';return[pscustomobject]@{requested=$true;verified=([string]$v).Contains($ExpectedBuild);build=[string]$v;port=$port}}}catch{}};return[pscustomobject]@{requested=$false;verified=$false;build='';port=$null}}

$started=(Get-Date).ToString('o');$updates=@();$errors=@();$stamp=Get-Date -Format 'yyyyMMdd_HHmmss'
try{$candidates=@(GetCandidates);if($candidates.Count-eq0){throw'INSTALLED_EXTENSION_PATH_NOT_FOUND'};foreach($c in $candidates){try{$updates+=UpdateTarget $c $stamp}catch{$errors+=([string]$c.profile+':'+$_.Exception.Message)}};if($updates.Count-eq0){throw('NO_TARGET_UPDATED:'+($errors-join'|'))};$reload=ReloadExtension;$rec=[ordered]@{ok=$true;action='GOOGLE_AI_ALWAYS_ON_NOTEBOOKLM_FALLBACK_V1';revision='V1_LAST_GOOD_SELECTOR_SAFE';startedAt=$started;completedAt=(Get-Date).ToString('o');extensionId=$ExtensionId;expectedVersion=$ExpectedVersion;expectedBuild=$ExpectedBuild;updatedTargets=$updates;errors=$errors;configContentRead=$false;configPreserved=$true;normalChromeTouched=$false;cdpReloadRequested=[bool]$reload.requested;cdpReloadVerified=[bool]$reload.verified;runtimeBuild=[string]$reload.build;reloadPending=[bool](-not$reload.verified);primaryNotebookBridgeChanged=$false;generateClicked=$false;creditSpend=$false;oauthChanged=$false;scopeChanged=$false;duplicateInstallCreated=$false};SaveReceipt $rec;$rec|ConvertTo-Json -Depth 30 -Compress;exit 0}catch{$errors+=$_.Exception.Message;$rec=[ordered]@{ok=$false;action='GOOGLE_AI_ALWAYS_ON_NOTEBOOKLM_FALLBACK_V1';revision='V1_LAST_GOOD_SELECTOR_SAFE';startedAt=$started;completedAt=(Get-Date).ToString('o');extensionId=$ExtensionId;updatedTargets=$updates;errors=$errors;configContentRead=$false;normalChromeTouched=$false;reloadPending=$true;primaryNotebookBridgeChanged=$false;generateClicked=$false;creditSpend=$false;oauthChanged=$false;scopeChanged=$false;duplicateInstallCreated=$false};SaveReceipt $rec;$rec|ConvertTo-Json -Depth 30 -Compress;exit 2}
