param([int]$MaxBindings=40)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$SourceRel='notebooklm-webapp-bridge-source-v0.2.0/apps-script/Code.gs'
$Expected='e7c22534048062eca913e2d1b5d8b3c6e7ac8b28'
$ExpectedVersion='0.2.10-queue-lock'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$Work=Join-Path $Base ('QueueIntegritySyncV2\'+(Get-Date -Format 'yyyyMMdd_HHmmss'))
$LocalReceipt=Join-Path $Base 'LocalAgent\NOTEBOOKLM_QUEUE_INTEGRITY_SYNC_V2.json'
New-Item -ItemType Directory -Force -Path $Work|Out-Null
function GitBlob([string]$p){$b=[IO.File]::ReadAllBytes($p);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function FindCentral{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(!$d.Root){continue};foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ('내 드라이브\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveJson([string]$p,$o){$par=Split-Path -Parent $p;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};$o|ConvertTo-Json -Depth 40|Set-Content -LiteralPath $p -Encoding UTF8}
function SafeRun([string]$File,[string[]]$Args,[int]$Timeout=90,[string]$Cwd=''){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$File;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;if($Cwd){$psi.WorkingDirectory=$Cwd};$psi.Arguments=($Args|ForEach-Object{if($_ -match '[\s"]'){'"'+($_ -replace '"','\"')+'"'}else{$_}})-join ' ';$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();if(-not $p.WaitForExit($Timeout*1000)){try{& taskkill.exe /PID $p.Id /T /F 2>$null|Out-Null}catch{};return [ordered]@{ok=$false;exit=-1;timedOut=$true;stdout=$ot.Result;stderr=$et.Result}};return [ordered]@{ok=($p.ExitCode -eq 0);exit=$p.ExitCode;timedOut=$false;stdout=$ot.Result.Trim();stderr=$et.Result.Trim()}}
$central=FindCentral;$driveReceipt=$(if($central){Join-Path $central 'Runtime_Readback\AppsScript_QueueIntegrity\NOTEBOOKLM_QUEUE_INTEGRITY_SYNC.json'}else{''});$stage='INIT';$diag=@();$target=$null;$backup='';$sourceSha='';$push=$null;$pull2=$null
try{
  $stage='CLASP_DISCOVERY';$clasp=(Get-Command clasp.cmd -ErrorAction SilentlyContinue);if(!$clasp){$clasp=Get-Command clasp -ErrorAction SilentlyContinue};if(!$clasp){throw 'CLASP_NOT_FOUND'}
  $stage='SOURCE_FETCH';$src=Join-Path $Work 'Code.gs';$url='https://raw.githubusercontent.com/'+$Repo+'/main/'+$SourceRel+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $src -TimeoutSec 30;$sourceSha=(GitBlob $src).ToLowerInvariant();if($sourceSha -ne $Expected){throw ('QUEUE_CODE_SHA_MISMATCH:'+ $sourceSha)}
  $text=Get-Content $src -Raw -Encoding UTF8;$checks=[ordered]@{version=($text -match [regex]::Escape($ExpectedVersion));lock=($text -match 'LockService\.getScriptLock');rowGuard=($text -match 'TASK_ROW_ID_MISMATCH');appendAtomic=(-not($text -match 'function appendTask_[\s\S]*?appendRow\('));idempotentDone=($text -match 'String\(item\.data\.STATUS\)==="DONE"')};if(@($checks.Values|Where-Object{-not $_}).Count){throw ('QUEUE_CODE_STATIC_FAILED:'+($checks|ConvertTo-Json -Compress))}
  $stage='BINDING_SCAN';$roots=@($Base,(Join-Path $env:USERPROFILE 'Documents'),(Join-Path $env:USERPROFILE 'Desktop'))|Where-Object{Test-Path $_ -PathType Container};$seen=@{};$bindings=@();foreach($root in $roots){foreach($f in @(Get-ChildItem -LiteralPath $root -Filter '.clasp.json' -File -Recurse -ErrorAction SilentlyContinue|Select-Object -First $MaxBindings)){try{$j=Get-Content $f.FullName -Raw -Encoding UTF8|ConvertFrom-Json;if($j.scriptId -and -not $seen[[string]$j.scriptId]){$seen[[string]$j.scriptId]=$true;$bindings += [ordered]@{scriptId=[string]$j.scriptId;dir=$f.Directory.FullName;claspPath=$f.FullName}}}catch{}}};if(!$bindings.Count){throw 'NO_EXISTING_CLASP_BINDING_FOUND'}
  $stage='BINDING_VERIFY';foreach($b in $bindings){$pull=SafeRun $clasp.Source @('pull') 70 $b.dir;if(!$pull.ok){$diag += [ordered]@{scriptId=$b.scriptId;dir=$b.dir;pullOk=$false;error=($pull.stderr+' '+$pull.stdout).Trim()};continue};$files=@(Get-ChildItem $b.dir -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Extension -in '.gs','.js','.json'});$joined=($files|ForEach-Object{try{Get-Content $_.FullName -Raw -Encoding UTF8}catch{''}})-join "`n";$score=0;if($joined -match 'NotebookLM_Task_Queue'){$score+=100};if($joined -match 'enqueueFromWriter_'){$score+=60};if($joined -match 'NotebookLM WebApp Bridge'){$score+=60};$diag += [ordered]@{scriptId=$b.scriptId;dir=$b.dir;pullOk=$true;score=$score};if($score -ge 160 -and (!$target -or $score -gt $target.score)){$target=[ordered]@{scriptId=$b.scriptId;dir=$b.dir;score=$score}}};if(!$target){throw ('NOTEBOOKLM_EXISTING_PROJECT_NOT_FOUND bindings='+$bindings.Count)}
  $stage='BACKUP';$backup=Join-Path $central ('Backups\AppsScript_QueueIntegrity\'+(Get-Date -Format 'yyyyMMdd_HHmmss'));if(!$central){$backup=Join-Path $Work 'backup'};New-Item -ItemType Directory -Force -Path $backup|Out-Null;foreach($f in @(Get-ChildItem $target.dir -File -Recurse -ErrorAction SilentlyContinue)){$rel=$f.FullName.Substring($target.dir.Length).TrimStart('\');$dest=Join-Path $backup $rel;$par=Split-Path -Parent $dest;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};Copy-Item $f.FullName $dest -Force}
  $stage='PUSH';$targetCode=Get-ChildItem $target.dir -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Name -eq 'Code.gs'}|Select-Object -First 1;if(!$targetCode){$targetCode=Get-Item (New-Item -ItemType File -Path (Join-Path $target.dir 'Code.gs') -Force)};Copy-Item $src $targetCode.FullName -Force;$push=SafeRun $clasp.Source @('push','--force') 120 $target.dir;if(!$push.ok){throw ('CLASP_PUSH_FAILED:'+($push.stderr+' '+$push.stdout).Trim())}
  $stage='PULL_READBACK';$pull2=SafeRun $clasp.Source @('pull') 70 $target.dir;if(!$pull2.ok){throw ('CLASP_PULL_READBACK_FAILED:'+($pull2.stderr+' '+$pull2.stdout).Trim())};$liveCode=Get-ChildItem $target.dir -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Name -eq 'Code.gs'}|Select-Object -First 1;$liveText=$(if($liveCode){Get-Content $liveCode.FullName -Raw -Encoding UTF8}else{''});$verified=[bool]($liveText -match [regex]::Escape($ExpectedVersion) -and $liveText -match 'TASK_ROW_ID_MISMATCH' -and $liveText -match 'LockService\.getScriptLock');if(!$verified){throw 'PULL_READBACK_CONTRACT_MISMATCH'}
  $o=[ordered]@{ok=$true;status='PUSH_PULL_READBACK_PASS';version=$ExpectedVersion;stage='DONE';scriptId=$target.scriptId;targetScore=$target.score;backup=$backup;sourceSha=$sourceSha;push=$push;pullReadback=$pull2;diagnostics=$diag;newProjectCreated=$false;oauthChanged=$false;scopeChanged=$false;generateClicked=$false;creditSpend=$false;at=(Get-Date).ToString('o')};SaveJson $LocalReceipt $o;if($driveReceipt){SaveJson $driveReceipt $o};$o|ConvertTo-Json -Depth 40 -Compress;exit 0
}catch{
  $o=[ordered]@{ok=$false;status='FAILED';version=$ExpectedVersion;stage=$stage;error=$_.Exception.Message;scriptId=$(if($target){$target.scriptId}else{''});backup=$backup;sourceSha=$sourceSha;push=$push;pullReadback=$pull2;diagnostics=$diag;newProjectCreated=$false;oauthChanged=$false;scopeChanged=$false;generateClicked=$false;creditSpend=$false;at=(Get-Date).ToString('o')};try{SaveJson $LocalReceipt $o}catch{};if($driveReceipt){try{SaveJson $driveReceipt $o}catch{}};$o|ConvertTo-Json -Depth 40 -Compress;exit 2
}
