param([int]$MaxCandidates=30)
$ErrorActionPreference='Stop';$ProgressPreference='SilentlyContinue'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$SourceRel='notebooklm-webapp-bridge-source-v0.2.0/apps-script/Code.gs'
$Expected='e7c22534048062eca913e2d1b5d8b3c6e7ac8b28'
$ExpectedVersion='0.2.10-queue-lock'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$Work=Join-Path $Base ('QueueIntegritySync\'+(Get-Date -Format 'yyyyMMdd_HHmmss'))
New-Item -ItemType Directory -Force -Path $Work|Out-Null
function GitBlob([string]$p){$b=[IO.File]::ReadAllBytes($p);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function FindCentral{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){if(!$d.Root){continue};foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ('내 드라이브\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path $c -PathType Container){return $c}}};throw 'CENTRAL_DRIVE_ROOT_NOT_FOUND'}
function SafeRun([string]$File,[string[]]$Args,[int]$Timeout=90,[string]$Cwd=''){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$File;$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;if($Cwd){$psi.WorkingDirectory=$Cwd};$psi.Arguments=($Args|ForEach-Object{if($_ -match '[\s"]'){'"'+($_ -replace '"','\"')+'"'}else{$_}})-join ' ';$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();if(-not $p.WaitForExit($Timeout*1000)){try{& taskkill.exe /PID $p.Id /T /F 2>$null|Out-Null}catch{};return [ordered]@{ok=$false;exit=-1;timedOut=$true;stdout=$ot.Result;stderr=$et.Result}};return [ordered]@{ok=($p.ExitCode -eq 0);exit=$p.ExitCode;timedOut=$false;stdout=$ot.Result.Trim();stderr=$et.Result.Trim()}}
$central=FindCentral;$readDir=Join-Path $central 'Runtime_Readback\AppsScript_QueueIntegrity';$backup=Join-Path $central ('Backups\AppsScript_QueueIntegrity\'+(Get-Date -Format 'yyyyMMdd_HHmmss'));New-Item -ItemType Directory -Force -Path $readDir,$backup|Out-Null
$clasp=(Get-Command clasp.cmd -ErrorAction SilentlyContinue);if(!$clasp){$clasp=Get-Command clasp -ErrorAction SilentlyContinue};if(!$clasp){throw 'CLASP_NOT_FOUND'}
$src=Join-Path $Work 'Code.gs';$url='https://raw.githubusercontent.com/'+$Repo+'/main/'+$SourceRel+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $src -TimeoutSec 30;$sha=(GitBlob $src).ToLowerInvariant();if($sha -ne $Expected){throw ('QUEUE_CODE_SHA_MISMATCH:'+ $sha)}
$text=Get-Content $src -Raw -Encoding UTF8
$checks=[ordered]@{version=($text -match [regex]::Escape($ExpectedVersion));lock=($text -match 'LockService\.getScriptLock');rowGuard=($text -match 'TASK_ROW_ID_MISMATCH');appendAtomic=(-not($text -match 'function appendTask_[\s\S]*?appendRow\('));idempotentDone=($text -match 'String\(item\.data\.STATUS\)==="DONE"')}
if(@($checks.Values|Where-Object{-not $_}).Count){throw ('QUEUE_CODE_STATIC_FAILED:'+($checks|ConvertTo-Json -Compress))}
$candidates=New-Object System.Collections.ArrayList
$roots=@($Base,(Join-Path $env:USERPROFILE 'Downloads'),(Join-Path $env:USERPROFILE 'Documents'),(Join-Path $env:USERPROFILE 'Desktop'))|Where-Object{Test-Path $_ -PathType Container}
foreach($root in $roots){foreach($f in @(Get-ChildItem -LiteralPath $root -Filter '.clasp.json' -File -Recurse -ErrorAction SilentlyContinue|Select-Object -First $MaxCandidates)){try{$j=Get-Content $f.FullName -Raw -Encoding UTF8|ConvertFrom-Json;if($j.scriptId){[void]$candidates.Add([ordered]@{scriptId=[string]$j.scriptId;dir=$f.Directory.FullName;source='LOCAL_BINDING'})}}catch{}}}
if($candidates.Count -eq 0){$list=SafeRun $clasp.Source @('list') 45;if($list.ok){$ids=[regex]::Matches(($list.stdout+' '+$list.stderr),'[A-Za-z0-9_-]{40,}')|ForEach-Object{$_.Value}|Select-Object -Unique|Select-Object -First $MaxCandidates;foreach($id in $ids){$dir=Join-Path $Work ('candidate_'+$id.Substring(0,8));New-Item -ItemType Directory -Force -Path $dir|Out-Null;$clone=SafeRun $clasp.Source @('clone',$id) 60 $dir;if($clone.ok){[void]$candidates.Add([ordered]@{scriptId=$id;dir=$dir;source='CLASP_LIST_EXISTING'})}}}}
if($candidates.Count -eq 0){throw 'NO_EXISTING_CLASP_BINDING_FOUND'}
$target=$null;$diag=@()
foreach($c in @($candidates)){$pull=SafeRun $clasp.Source @('pull') 60 $c.dir;if(!$pull.ok){$diag+=[ordered]@{scriptId=$c.scriptId;source=$c.source;pullOk=$false;error=($pull.stderr+' '+$pull.stdout).Trim()};continue};$files=@(Get-ChildItem $c.dir -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Extension -in '.gs','.js','.json'});$joined=($files|ForEach-Object{try{Get-Content $_.FullName -Raw -Encoding UTF8}catch{''}})-join "`n";$score=0;if($joined -match 'NotebookLM_Task_Queue'){$score+=100};if($joined -match 'enqueueFromWriter_'){$score+=60};if($joined -match 'NotebookLM WebApp Bridge'){$score+=60};$diag+=[ordered]@{scriptId=$c.scriptId;source=$c.source;pullOk=$true;score=$score;dir=$c.dir};if($score -ge 160 -and (!$target -or $score -gt $target.score)){$target=[ordered]@{scriptId=$c.scriptId;dir=$c.dir;score=$score;source=$c.source}}}
if(!$target){throw ('NOTEBOOKLM_EXISTING_PROJECT_NOT_FOUND:'+($diag|ConvertTo-Json -Depth 6 -Compress))}
foreach($f in @(Get-ChildItem $target.dir -File -Recurse -ErrorAction SilentlyContinue)){$rel=$f.FullName.Substring($target.dir.Length).TrimStart('\');$dest=Join-Path $backup $rel;$par=Split-Path -Parent $dest;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};Copy-Item $f.FullName $dest -Force}
$targetCode=Get-ChildItem $target.dir -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Name -eq 'Code.gs'}|Select-Object -First 1;if(!$targetCode){$targetCode=Get-Item (New-Item -ItemType File -Path (Join-Path $target.dir 'Code.gs') -Force)}
Copy-Item $src $targetCode.FullName -Force
$push=SafeRun $clasp.Source @('push','--force') 120 $target.dir
if(!$push.ok){$o=[ordered]@{ok=$false;status='CLASP_PUSH_FAILED';scriptId=$target.scriptId;backup=$backup;sourceSha=$sha;checks=$checks;push=$push;diagnostics=$diag;newProjectCreated=$false;oauthChanged=$false;scopeChanged=$false;at=(Get-Date).ToString('o')};$o|ConvertTo-Json -Depth 30|Set-Content (Join-Path $readDir 'NOTEBOOKLM_QUEUE_INTEGRITY_SYNC.json') -Encoding UTF8;$o|ConvertTo-Json -Depth 30 -Compress;exit 2}
$pull2=SafeRun $clasp.Source @('pull') 60 $target.dir;$liveCode=Get-ChildItem $target.dir -File -Recurse -ErrorAction SilentlyContinue|Where-Object{$_.Name -eq 'Code.gs'}|Select-Object -First 1;$liveText=$(if($liveCode){Get-Content $liveCode.FullName -Raw -Encoding UTF8}else{''});$verified=[bool]($pull2.ok -and $liveText -match [regex]::Escape($ExpectedVersion) -and $liveText -match 'TASK_ROW_ID_MISMATCH' -and $liveText -match 'LockService\.getScriptLock')
$o=[ordered]@{ok=$verified;status=$(if($verified){'PUSH_PULL_READBACK_PASS'}else{'PUSH_DONE_READBACK_FAILED'});scriptId=$target.scriptId;targetSource=$target.source;targetScore=$target.score;backup=$backup;sourceSha=$sha;checks=$checks;push=$push;pullReadback=$pull2;version=$ExpectedVersion;newProjectCreated=$false;oauthChanged=$false;scopeChanged=$false;at=(Get-Date).ToString('o')}
$o|ConvertTo-Json -Depth 30|Set-Content (Join-Path $readDir 'NOTEBOOKLM_QUEUE_INTEGRITY_SYNC.json') -Encoding UTF8
$o|ConvertTo-Json -Depth 30 -Compress
if($verified){exit 0}else{exit 3}
