param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='1.1.130'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$TargetUrl='https://notebook.google.com/notebook/8d1eda83-cfe3-4487-b2bc-266a5be3465c'
$TitleB64='7ZqM7IKs66W8IO2GteynuOuhnCDsnpDrj5ntmZTtlZjripQgQUkg7JuM7YGs7ZSM66Gc'
$ProjectKeyB64='MjAyNi0wOC0zMF9Db250ZW50T1NfQUnsvZjthZDsuKDsg53sgrDsm4ztgaztlIzroZzsmrBf66as7ISc7LmY'
$MyDriveKoB64='64K0IOuTnOudvOydtOu4jA=='
$FactoryB64='Tk9URUJPT0tMTV9GQUNUT1JZ'
$OutputB64='MDNfT1VUUFVUX0FVRElPX1ZJREVPX1NMSURFUw=='
function U([string]$b){[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($b))}
$ExactTitle=U $TitleB64;$ProjectKey=U $ProjectKeyB64;$MyDriveKo=U $MyDriveKoB64;$FactoryName=U $FactoryB64;$OutputName=U $OutputB64
$Port=9223
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$UserData=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\ChromeUserData'
$PythonVerifier=Join-Path $Root 'notebooklm_raw_download_capture.130.py'
$VerifyDir=Join-Path $Root 'RawVerifier130'
$Receipt='AGENT_1.1.130_EXACT_AUDIO_DOWNLOAD_DRIVE_VERIFY_RESULT.json'
$Marker=Join-Path $Root $Receipt
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function Raw([string]$p){'https://raw.githubusercontent.com/'+$Repo+'/main/'+$p+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ($MyDriveKo+'\'+$target)),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};''}
function Save($o){$j=$o|ConvertTo-Json -Depth 100;$j|Set-Content -LiteralPath $Marker -Encoding UTF8;try{$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$p=Join-Path $d $Receipt;$j|Set-Content -LiteralPath $p -Encoding UTF8;return $p}}catch{};''}
function Tabs{$o=(Invoke-WebRequest -UseBasicParsing -Uri ("http://127.0.0.1:$Port/json/list") -TimeoutSec 3).Content|ConvertFrom-Json;@($o|Where-Object{[string]$_.type-eq'page'})}
function Recv($w,[int]$sec){$b=New-Object byte[] 65536;$m=New-Object IO.MemoryStream;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter($sec*1000);try{do{$g=New-Object ArraySegment[byte] -ArgumentList @(,$b);$z=$w.ReceiveAsync($g,$c.Token).GetAwaiter().GetResult();if($z.MessageType-eq[System.Net.WebSockets.WebSocketMessageType]::Close){throw 'CDP_CLOSED'};$m.Write($b,0,$z.Count)}while(-not$z.EndOfMessage);([Text.Encoding]::UTF8.GetString($m.ToArray())|ConvertFrom-Json)}finally{$c.Dispose();$m.Dispose()}}
function Send($w,[ref]$q,[string]$method,[hashtable]$params=@{}){$q.Value++;$id=$q.Value;$bb=[Text.Encoding]::UTF8.GetBytes((@{id=$id;method=$method;params=$params}|ConvertTo-Json -Depth 30 -Compress));$g=New-Object ArraySegment[byte] -ArgumentList @(,$bb);$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.SendAsync($g,[System.Net.WebSockets.WebSocketMessageType]::Text,$true,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};while($true){$z=Recv $w 8;if($z.id-eq$id){if($z.error){throw('CDP_'+$method+':'+($z.error|ConvertTo-Json -Compress))};return $z.result}}}
function Eval($w,[ref]$q,[string]$e){$z=Send $w $q 'Runtime.evaluate' @{expression=$e;returnByValue=$true;awaitPromise=$true;userGesture=$true};$z.result.value}
function Click($w,[ref]$q,$x,$y){[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseMoved';x=[double]$x;y=[double]$y});[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mousePressed';x=[double]$x;y=[double]$y;button='left';clickCount=1});Start-Sleep -Milliseconds 100;[void](Send $w $q 'Input.dispatchMouseEvent' @{type='mouseReleased';x=[double]$x;y=[double]$y;button='left';clickCount=1})}
function Connect([string]$u){$w=New-Object System.Net.WebSockets.ClientWebSocket;$c=New-Object Threading.CancellationTokenSource;$c.CancelAfter(8000);try{[void]$w.ConnectAsync([Uri]$u,$c.Token).GetAwaiter().GetResult()}finally{$c.Dispose()};$w}
function ResolveDownloadDir{$pref=Join-Path $UserData 'Default\Preferences';if(Test-Path -LiteralPath $pref){try{$j=Get-Content -LiteralPath $pref -Raw -Encoding UTF8|ConvertFrom-Json;$p=[string]$j.download.default_directory;if($p-and(Test-Path -LiteralPath $p -PathType Container)){return [pscustomobject]@{path=$p;source='CHROME_PREFERENCE'}}}catch{}};$p=Join-Path $env:USERPROFILE 'Downloads';if(Test-Path -LiteralPath $p -PathType Container){return [pscustomobject]@{path=$p;source='WINDOWS_DOWNLOADS'}};throw 'NO_DOWNLOAD_DIRECTORY'}
function ResolveDriveProjectPath{$hits=@();foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(-not$r){continue};foreach($base in @((Join-Path $r $MyDriveKo),(Join-Path $r 'My Drive'),(Join-Path $r 'Google Drive'))){if(-not(Test-Path -LiteralPath $base -PathType Container)){continue};$p=Join-Path $base ($FactoryName+'\'+$OutputName+'\'+$ProjectKey);if(Test-Path -LiteralPath $p -PathType Container){$hits+=$p}}};@($hits|Select-Object -Unique)}
function NewestCompleted([string]$dir,[datetime]$since){@(Get-ChildItem -LiteralPath $dir -File -ErrorAction SilentlyContinue|Where-Object{$_.LastWriteTime-ge$since.AddSeconds(-2)-and$_.Length-gt0-and$_.Extension-notin@('.crdownload','.part','.tmp')}|Sort-Object LastWriteTime -Descending|Select-Object -First 10)}
function WaitStable([string]$path){$last=-1L;$same=0;for($i=0;$i-lt18;$i++){if(Test-Path -LiteralPath $path -PathType Leaf){$n=(Get-Item -LiteralPath $path).Length;if($n-gt0-and$n-eq$last){$same++}else{$same=0;$last=$n};if($same-ge3){return $true}};Start-Sleep -Milliseconds 500};$false}
$r=[ordered]@{ok=$false;action='AGENT_1.1.130_EXACT_AUDIO_DOWNLOAD_DRIVE_VERIFY';version=$Version;targetUrl=$TargetUrl;exactTitle=$ExactTitle;startedAt=(Get-Date).ToString('o');exactTab=$false;studioSelected=$false;exactTitleMatched=$false;cardEvidence=$null;menuClicked=$false;downloadClicked=$false;downloadPath='';downloadPathSource='';primaryDownload=$false;sourceFile=$null;pythonFetched=$false;pythonVerified=$false;pythonReceipt=$null;driveProjectPaths=@();driveCopy=$null;sha256='';state='ERROR';stage='START';normalChromeTouched=$false;bridgeChanged=$false;oauthChanged=$false;scopeChanged=$false;error='';centralPath=''}
$w=$null
try{
  $r.stage='EXACT_TAB';$tab=@(Tabs|Where-Object{[string]$_.url-eq$TargetUrl}|Select-Object -First 1);if(-not$tab){throw 'EXACT_NOTEBOOK_TAB_NOT_FOUND'};$r.exactTab=$true;$w=Connect([string]$tab[0].webSocketDebuggerUrl);$q=0;[void](Send $w ([ref]$q) 'Runtime.enable' @{});[void](Send $w ([ref]$q) 'Page.bringToFront' @{})
  $r.stage='STUDIO';$x=Eval $w ([ref]$q) "(() => {const K=String.fromCharCode(49828,53916,46356,50724),v=e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const e=[...document.querySelectorAll('[role=tab]')].filter(v).find(e=>String([e.innerText,e.textContent,e.getAttribute('aria-label')].join(' ')).includes(K));if(!e)return{ok:false};const b=e.getBoundingClientRect();return{ok:true,x:b.left+b.width/2,y:b.top+b.height/2}})()";if($x.ok){Click $w ([ref]$q) $x.x $x.y;$r.studioSelected=$true;Start-Sleep -Seconds 1}else{throw 'STUDIO_TAB_NOT_FOUND'}
  $r.stage='EXACT_CARD';$titleJson=$ExactTitle|ConvertTo-Json -Compress;$x=Eval $w ([ref]$q) "(() => {const wanted=String($titleJson),v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'};const all=[...document.querySelectorAll('div,section,article,[role=group],[role=region]')].filter(v).filter(e=>String(e.innerText||e.textContent||'').includes(wanted)).sort((a,b)=>String(a.innerText||'').length-String(b.innerText||'').length);for(const root of all){const text=String(root.innerText||root.textContent||'');if(!text.includes(wanted))continue;const bs=[...root.querySelectorAll('button,[role=button]')].filter(v);const more=bs.find(b=>{const t=String([b.innerText,b.textContent,b.getAttribute('aria-label'),b.getAttribute('title'),b.querySelector('mat-icon')?.textContent].join(' '));return /more_vert|more|menu/i.test(t)||t.includes(String.fromCharCode(45908,48372,44592))});if(more){const z=more.getBoundingClientRect();return{ok:true,x:z.left+z.width/2,y:z.top+z.height/2,text:text.slice(0,1200),candidateCount:all.length}}}return{ok:false,candidateCount:all.length,body:String(document.body?.innerText||'').slice(0,3000)}})()";if(-not$x.ok){throw 'EXACT_FRESH_AUDIO_CARD_MENU_NOT_FOUND'};$r.exactTitleMatched=$true;$r.cardEvidence=$x;Click $w ([ref]$q) $x.x $x.y;$r.menuClicked=$true;Start-Sleep -Milliseconds 600
  $di=ResolveDownloadDir;$r.downloadPath=$di.path;$r.downloadPathSource=$di.source;try{[void](Send $w ([ref]$q) 'Browser.setDownloadBehavior' @{behavior='allow';downloadPath=$di.path;eventsEnabled=$true})}catch{[void](Send $w ([ref]$q) 'Page.setDownloadBehavior' @{behavior='allow';downloadPath=$di.path})}
  $r.stage='DOWNLOAD_MENU';$x=Eval $w ([ref]$q) "(() => {const D=String.fromCharCode(45796,50868,47196,46300),v=e=>{if(!(e instanceof HTMLElement))return false;const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width>2&&r.height>2&&s.display!=='none'&&s.visibility!=='hidden'&&!e.disabled};for(const e of [...document.querySelectorAll('button,[role=button],[role=menuitem],a,div[tabindex]')].filter(v)){const t=String([e.innerText,e.textContent,e.getAttribute('aria-label'),e.getAttribute('title')].join(' '));if(t.includes(D)||/\bdownload\b/i.test(t)){const b=e.getBoundingClientRect();return{ok:true,x:b.left+b.width/2,y:b.top+b.height/2,text:t.slice(0,300)}}}return{ok:false,body:String(document.body?.innerText||'').slice(-2500)}})()";if(-not$x.ok){throw 'DOWNLOAD_MENU_ITEM_NOT_FOUND'};$clickAt=Get-Date;Click $w ([ref]$q) $x.x $x.y;$r.downloadClicked=$true
  $r.stage='WAIT_REAL_FILE';$until=(Get-Date).AddSeconds(180);$files=@();do{Start-Sleep -Milliseconds 700;$files=@(NewestCompleted $di.path $clickAt);if($files.Count-gt0){$p=[string]$files[0].FullName;if(WaitStable $p){break}else{$files=@()}}}while((Get-Date)-lt$until);if($files.Count-lt1){throw 'REAL_AUDIO_FILE_NOT_FOUND_AFTER_DOWNLOAD'};$fi=Get-Item -LiteralPath ([string]$files[0].FullName);$r.primaryDownload=$true;$r.sourceFile=[ordered]@{name=$fi.Name;fullName=$fi.FullName;size=[int64]$fi.Length;extension=$fi.Extension;lastWriteTime=$fi.LastWriteTime.ToString('o')};$r.sha256=(Get-FileHash -LiteralPath $fi.FullName -Algorithm SHA256).Hash.ToLowerInvariant()
  $r.stage='PYTHON_VERIFY';Invoke-WebRequest -UseBasicParsing -Uri (Raw 'local-agent/python/notebooklm_raw_download_capture.py') -OutFile $PythonVerifier -TimeoutSec 30;$r.pythonFetched=$true;Remove-Item -LiteralPath $VerifyDir -Recurse -Force -ErrorAction SilentlyContinue;New-Item -ItemType Directory -Force -Path $VerifyDir|Out-Null;$po=& python $PythonVerifier --source-file $fi.FullName --drive-dir $VerifyDir --expected-media audio 2>&1|Out-String;$pp=$po|ConvertFrom-Json;$r.pythonReceipt=$pp;$r.pythonVerified=([bool]$pp.ok-and[string]$pp.sourceSha256-eq$r.sha256-and[string]$pp.destinationSha256-eq$r.sha256-and[string]$pp.detectedMediaFamily-eq'audio'-and[bool]$pp.sourceImmutableVerified);if(-not$r.pythonVerified){throw('PYTHON_AUDIO_VERIFY_FAILED '+$po.Trim())}
  $r.stage='DRIVE_COPY';$deadline=(Get-Date).AddSeconds(90);$paths=@();do{$paths=@(ResolveDriveProjectPath);if($paths.Count){break};Start-Sleep -Seconds 3}while((Get-Date)-lt$deadline);$r.driveProjectPaths=$paths;if($paths.Count-lt1){throw 'DRIVE_PROJECT_SYNC_PATH_NOT_FOUND'};$destDir=$paths[0];$ext=[string]$fi.Extension;if(-not$ext-or$ext-in@('.bin','.dat','.download')){$ce=[string]$pp.detected.canonicalExtension;if($ce){$ext=$ce}else{$ext='.m4a'}};$name=$ProjectKey+'_AUDIO_OVERVIEW_'+(Get-Date -Format 'yyyyMMdd_HHmmss')+$ext;$dest=Join-Path $destDir $name;Copy-Item -LiteralPath $fi.FullName -Destination $dest -Force;Start-Sleep -Seconds 2;$df=Get-Item -LiteralPath $dest;$dsha=(Get-FileHash -LiteralPath $dest -Algorithm SHA256).Hash.ToLowerInvariant();if($df.Length-ne$fi.Length-or$dsha-ne$r.sha256){throw 'DRIVE_COPY_SIZE_OR_SHA_MISMATCH'};$r.driveCopy=[ordered]@{name=$df.Name;fullName=$df.FullName;size=[int64]$df.Length;sha256=$dsha;parent=$destDir};$r.ok=$true;$r.state='DOWNLOADED_VERIFIED_DRIVE_COPIED';$r.stage='DONE'
}catch{$r.error=$_.Exception.Message;$r.state='ERROR'}finally{if($w){try{$w.Dispose()}catch{}};$r.completedAt=(Get-Date).ToString('o');$r.centralPath=Save $r}
$r|ConvertTo-Json -Depth 100 -Compress
if($r.ok){exit 0}else{exit 2}
