const NLM_FACTORY_ADAPTER_VERSION='NLM_FACTORY_ADAPTER_V1_20260823';
const NLM_FACTORY_MASTER_ID='1C_CznU1Uo7dk-gKay3-oH8wFxutsGMlz27RSrbdVQwI';
const NLM_FACTORY_APP_ID='APP_NLM_BRIDGE';
const NLM_FACTORY_TARGET_ID='FPC_MEDIA_20260823';
function runNotebookLmBackdataFactoryControl10m(){return runNotebookLmFactoryAdapter_(false);}
function checkNotebookLmBackdataFactoryAdapter(){return runNotebookLmFactoryAdapter_(true);}
function runNotebookLmApiAbQaControl(){return notebookLmFactoryApiWindow_();}
function runNotebookLmFactoryAdapter_(healthOnly){const now=new Date(),props=PropertiesService.getScriptProperties(),bucket=Utilities.formatDate(now,'Asia/Seoul','yyyyMMddHHmm').slice(0,11),key='NLM_FACTORY_BUCKET';if(!healthOnly&&props.getProperty(key)===bucket)return{ok:true,skipped:true,reason:'SAME_10M_BUCKET'};const lock=LockService.getScriptLock();if(!lock.tryLock(5000))return{ok:false,reason:'LOCK_BUSY'};try{const central=SpreadsheetApp.openById(NLM_FACTORY_MASTER_ID),target=notebookLmFactoryTarget_(central),triggers=ScriptApp.getProjectTriggers().map(function(t){return t.getHandlerFunction();});const known=['processTaskQueue','buildTimeline','renderFrame','exportVideo','exportAudio'];const handlers=known.map(function(n){return{handler:n,present:typeof globalThis[n]==='function'};});const out={ok:true,appId:NLM_FACTORY_APP_ID,target:target,handlers:handlers,existingTriggers:triggers,bucket:bucket,checkedAt:now.toISOString(),version:NLM_FACTORY_ADAPTER_VERSION};notebookLmFactoryMark_(central,out);if(!healthOnly)props.setProperty(key,bucket);return out;}finally{lock.releaseLock();}}
function notebookLmFactoryApiWindow_(){const now=new Date(),hour=Number(Utilities.formatDate(now,'Asia/Seoul','H'));if([9,13,17,21].indexOf(hour)<0)return{ok:true,skipped:true,reason:'OUTSIDE_API_AB_WINDOW'};const props=PropertiesService.getScriptProperties(),key='NLM_API_AB_'+Utilities.formatDate(now,'Asia/Seoul','yyyyMMdd')+'_'+hour;if(props.getProperty(key)==='Y')return{ok:true,skipped:true,reason:'WINDOW_ALREADY_RUN'};const out={ok:false,degraded:true,appId:NLM_FACTORY_APP_ID,error:'MEDIA_API_EXECUTOR_NOT_MAPPED',decision:'DETERMINISTIC_TIMELINE_FIRST_API_ONLY_FOR_UNREPRESENTABLE_SCENE',version:NLM_FACTORY_ADAPTER_VERSION};notebookLmFactoryQa_(out,now);props.setProperty(key,'Y');return out;}
function notebookLmFactoryTarget_(central){const sh=central.getSheetByName('66_FACTORY_PRODUCTION_CONTROL');if(!sh||sh.getLastRow()<2)return{found:false};const rows=sh.getRange(2,1,sh.getLastRow()-1,26).getDisplayValues();for(let i=rows.length-1;i>=0;i--)if(String(rows[i][0])===NLM_FACTORY_TARGET_ID)return{found:true,queens:Number(rows[i][5]||0),seed:Number(rows[i][6]||0),t1:Number(rows[i][7]||0),t2:Number(rows[i][8]||0),assets:Number(rows[i][9]||0)};return{found:false};}
function notebookLmFactoryMark_(central,out){const sh=central.getSheetByName('66_FACTORY_PRODUCTION_CONTROL');if(!sh||sh.getLastRow()<2)return;const rows=sh.getRange(2,1,sh.getLastRow()-1,26).getDisplayValues();for(let i=rows.length-1;i>=0;i--)if(String(rows[i][0])===NLM_FACTORY_TARGET_ID){const present=out.handlers.filter(function(h){return h.present;}).map(function(h){return h.handler;});sh.getRange(i+2,25).setValue(present.length?'MEDIA_ADAPTER_SOURCE_READY_RUNTIME_X2_REQUIRED':'MEDIA_BOUND_HANDLER_MAPPING_REQUIRED');sh.getRange(i+2,26).setValue('NLM_LAST_ADAPTER='+out.checkedAt+';PRESENT='+present.join('|'));return;}}
function notebookLmFactoryQa_(out,now){const sh=SpreadsheetApp.openById(NLM_FACTORY_MASTER_ID).getSheetByName('67_FACTORY_QA_AB_LOG');if(!sh)return;sh.appendRow(['QA_NLM_'+Utilities.formatDate(now,'Asia/Seoul','yyyyMMdd_HH00'),Utilities.formatDate(now,'Asia/Seoul','yyyy-MM-dd HH:mm:ss')+' KST',NLM_FACTORY_APP_ID,'MEDIA_EDIT_FIXTURE_PENDING','OWN_TIMELINE_T1_T2','APPROVED_API_ON','','','','','','','','','','','','','',out.error,'','MEDIA_API_EXECUTOR_MAPPING_REQUIRED','NLM_FACTORY_ADAPTER_V1','PENDING']);}
