param()
$ErrorActionPreference='Continue';$ProgressPreference='SilentlyContinue'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent';New-Item -ItemType Directory -Force -Path $Root|Out-Null
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$Base=Join-Path $Root 'HomeDesignLocalAgent-1.1.36-base.ps1';$Credit=Join-Path $Root 'Inspect-FlowApprovedAccountCredits-1.1.38.ps1';$QaSync=Join-Path $Root 'Sync-CentralLearningQaAppsScript-1.1.38.ps1';$State=Join-Path $Root 'state.json'
$BaseUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/releases/1.1.36/HomeDesignLocalAgent.ps1';$BaseSha='20bb1a585dec23416204df71dc5e5701cdcf71f1'
$CreditUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/governor/Inspect-FlowApprovedAccountCredits.ps1';$CreditSha='625d5602671b914786fee4a74d6aaa8667fbf4a9'
$QaUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/governor/Sync-CentralLearningQaAppsScript.ps1';$QaSha='971d1e1fb7369b4d472ae7cf41b023f53becdd87'
function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[] ($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Fetch([string]$Url,[string]$Dest,[string]$Expected){$tmp=$Dest+'.download';Invoke-WebRequest -UseBasicParsing -Uri ($Url+'?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -OutFile $tmp -TimeoutSec 30;$actual=(GitBlobSha1 $tmp).ToLowerInvariant();if($actual -ne $Expected.ToLowerInvariant()){Remove-Item $tmp -Force -ErrorAction SilentlyContinue;throw ('SHA_MISMATCH:'+ $actual+':'+$Expected)};Move-Item $tmp $Dest -Force}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(!$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('내 드라이브\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};return ''}
function SaveReceipt([string]$Name,$Object){$c=FindCentral;if(!$c){return};$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$Object|ConvertTo-Json -Depth 60|Set-Content -LiteralPath (Join-Path $d $Name) -Encoding UTF8}
function RunPs([string]$Path,[int]$TimeoutSec,[string[]]$Extra=@()){$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName='powershell.exe';$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$psi.Arguments=(@('-NoProfile','-NonInteractive','-ExecutionPolicy','Bypass','-File',$Path)+$Extra|ForEach-Object{if($_ -match '\s'){'"'+$_+'"'}else{$_}})-join ' ';$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();if(-not $p.WaitForExit($TimeoutSec*1000)){try{& taskkill.exe /PID $p.Id /T /F 2>$null|Out-Null}catch{};return [ordered]@{ok=$false;exit=-1;timedOut=$true;stdout=$ot.Result;stderr=$et.Result}};return [ordered]@{ok=($p.ExitCode -eq 0);exit=$p.ExitCode;timedOut=$false;stdout=$ot.Result.Trim();stderr=$et.Result.Trim()}}
$started=(Get-Date).ToString('o');$err='';$baseRun=$null;$creditRun=$null;$qaRun=$null
try{Fetch $BaseUrl $Base $BaseSha;$baseRun=RunPs $Base 180}catch{$err+='BASE:'+($_.Exception.Message)+';'}
try{Fetch $CreditUrl $Credit $CreditSha;$creditRun=RunPs $Credit 90}catch{$err+='CREDIT:'+($_.Exception.Message)+';'}
try{Fetch $QaUrl $QaSync $QaSha;$central=FindCentral;$extra=@();if($central){$extra=@('-CentralRootOverride',$central,'-MaxProjects','20')};$qaRun=RunPs $QaSync 420 $extra}catch{$err+='QA:'+($_.Exception.Message)+';'}
$creditEvidence=($creditRun -and $creditRun.stdout -match 'FLOW_APPROVED_ACCOUNT_CREDIT_READONLY')
$qaEvidence=($qaRun -and $qaRun.stdout -match '(RUNTIME_TRIGGER_PASS|SYNC_PASS_RUNTIME_INSTALL_PENDING)')
$ok=[bool]($creditEvidence -and $qaEvidence)
$receipt=[ordered]@{ok=$ok;action='AGENT_1.1.38_FLOW_CREDIT_AND_CENTRAL_LEARNING_QA';agentVersion='1.1.38';startedAt=$started;base=$baseRun;credit=$creditRun;qaSync=$qaRun;creditEvidence=[bool]$creditEvidence;qaEvidence=[bool]$qaEvidence;generateClicked=$false;creditSpend=$false;apiBudgetCreatedOrRaised=$false;newOauthOrScope=$false;newProjectCreated=$false;error=$err;completedAt=(Get-Date).ToString('o')};SaveReceipt 'AGENT_1.1.38_FLOW_CREDIT_AND_CENTRAL_LEARNING_QA.json' $receipt
try{$s=$null;if(Test-Path -LiteralPath $State){$s=Get-Content $State -Raw -Encoding UTF8|ConvertFrom-Json};if(!$s){$s=[pscustomobject]@{}};$s|Add-Member agentVersion '1.1.38' -Force;$s|Add-Member agentMode 'FLOW_CREDIT_AND_LEARNING_QA_1.1.38' -Force;$s|Add-Member ok $ok -Force;$s|Add-Member status $(if($ok){'SELF_HEAL_PASS'}else{'PARTIAL_EVIDENCE_PENDING'}) -Force;$s|Add-Member updatedAt ((Get-Date).ToString('o')) -Force;$s|ConvertTo-Json -Depth 40|Set-Content $State -Encoding UTF8}catch{}
if($ok){exit 0}else{exit 2}
