param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$AgentVersion='1.1.26'
$Base=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7'
$Root=Join-Path $Base 'LocalAgent'
$ExtensionRoot=Join-Path $Base 'Extension\NotebookLM-WebApp-Bridge'
$UserData=Join-Path $Base 'ChromeUserData'
$CftRoot=Join-Path $Base 'ChromeForTesting'
$BackupRoot=Join-Path $Root 'Backups'
$StateFile=Join-Path $Root 'state.json'
$ReadbackFile=Join-Path $Root 'VIDEO_LOCAL_RUNTIME_READBACK.json'
$RecoveryFile=Join-Path $Root 'AGENT_1.1.26_RECOVERY.json'
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
New-Item -ItemType Directory -Force -Path $Root,$ExtensionRoot,$BackupRoot|Out-Null

function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[] ($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function ReadJson([string]$Path){if(-not(Test-Path -LiteralPath $Path)){return $null};try{return Get-Content -LiteralPath $Path -Raw -Encoding UTF8|ConvertFrom-Json}catch{return $null}}
function HostHealth{try{return Invoke-RestMethod -Uri 'http://127.0.0.1:8765/health' -Method Get -TimeoutSec 3}catch{return $null}}
function Dedicated{try{return @(Get-CimInstance Win32_Process -Filter "Name='chrome.exe'" -ErrorAction SilentlyContinue|Where-Object{$_.CommandLine -and $_.CommandLine -like "*$UserData*"})}catch{return @()}}
function StopDedicated{foreach($p in @(Dedicated)){try{Stop-Process -Id ([int]$p.ProcessId) -Force -ErrorAction SilentlyContinue}catch{}};Start-Sleep -Seconds 1}
function FindChrome{if(-not(Test-Path -LiteralPath $CftRoot)){return $null};return Get-ChildItem -LiteralPath $CftRoot -Recurse -Filter chrome.exe -File -ErrorAction SilentlyContinue|Sort-Object FullName -Descending|Select-Object -First 1}
function LaunchDedicated([string]$Front){$c=FindChrome;if(-not $c){throw 'CHROME_FOR_TESTING_NOT_FOUND'};$args=@("--user-data-dir=$UserData",'--profile-directory=Default',"--load-extension=$ExtensionRoot",'--new-window','--no-first-run','--no-default-browser-check','--disable-session-crashed-bubble',$Front);$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName=$c.FullName;$psi.WorkingDirectory=$c.Directory.FullName;$psi.UseShellExecute=$false;$psi.Arguments=($args|ForEach-Object{if($_ -match '\s'){'"'+$_+'"'}else{$_}})-join ' ';[void][Diagnostics.Process]::Start($psi);$deadline=(Get-Date).AddSeconds(12);do{Start-Sleep -Milliseconds 500;if((Dedicated).Count -gt 0){return}}while((Get-Date)-lt $deadline);throw 'DEDICATED_CHROME_START_FAILED'}
function GetRelease{$url='https://raw.githubusercontent.com/'+$Repo+'/main/runtime/stable/release.json?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();$r=(Invoke-WebRequest -UseBasicParsing -Uri $url -TimeoutSec 10).Content|ConvertFrom-Json;if(-not $r.enabled){throw 'BRIDGE_STABLE_DISABLED'};if([string]$r.action -ne 'apply'){throw 'BRIDGE_STABLE_NOT_APPLY'};if([bool]$r.requiresUserApproval){throw 'BRIDGE_RELEASE_REQUIRES_USER_APPROVAL'};return $r}
function TestRelease($r){try{$m=ReadJson (Join-Path $ExtensionRoot 'manifest.json');if(-not $m -or [string]$m.version -ne [string]$r.version){return $false};foreach($f in @($r.files)){$rp=[string]$f.path;if($rp -match '\.\.' -or [IO.Path]::IsPathRooted($rp)){return $false};$p=Join-Path $ExtensionRoot $rp.Replace('/','\');if(-not(Test-Path -LiteralPath $p)){return $false};if((GitBlobSha1 $p).ToLowerInvariant() -ne ([string]$f.gitBlobSha1).ToLowerInvariant()){return $false}};return $true}catch{return $false}}
function InstallRelease($r){$stamp=Get-Date -Format 'yyyyMMdd_HHmmss';$stage=Join-Path $Root ('Stage\Bridge_'+$stamp);$backup=Join-Path $BackupRoot ('Bridge_'+$stamp);New-Item -ItemType Directory -Force -Path $stage,$backup|Out-Null;foreach($f in @($r.files)){$rp=[string]$f.path;if($rp -match '\.\.' -or [IO.Path]::IsPathRooted($rp)){throw 'UNSAFE_RELEASE_PATH'};$dst=Join-Path $stage $rp.Replace('/','\');$par=Split-Path $dst -Parent;if($par){New-Item -ItemType Directory -Force -Path $par|Out-Null};$url=([string]$r.baseUrl).TrimEnd('/')+'/'+$rp+'?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();Invoke-WebRequest -UseBasicParsing -Uri $url -OutFile $dst -TimeoutSec 10;$actual=(GitBlobSha1 $dst).ToLowerInvariant();if($actual -ne ([string]$f.gitBlobSha1).ToLowerInvariant()){throw "EXTENSION_SHA_MISMATCH:$rp actual=$actual expected=$($f.gitBlobSha1)"}};if(Test-Path -LiteralPath $ExtensionRoot){Copy-Item -LiteralPath $ExtensionRoot -Destination (Join-Path $backup 'extension') -Recurse -Force};StopDedicated;Get-ChildItem -LiteralPath $ExtensionRoot -Force -ErrorAction SilentlyContinue|Remove-Item -Recurse -Force;Copy-Item (Join-Path $stage '*') -Destination $ExtensionRoot -Recurse -Force;if(-not(TestRelease $r)){throw 'EXTENSION_POST_INSTALL_VERIFY_FAILED'};LaunchDedicated ([string]$r.frontUrl);return $backup}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$root=[string]$d.Root;if(-not $root){continue};foreach($c in @((Join-Path $root $target),(Join-Path $root ('My Drive\'+$target)),(Join-Path $root ('내 드라이브\'+$target)),(Join-Path $root ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c){return $c}}};return ''}
function WriteState($r,[bool]$changed,[string]$backup){$h=HostHealth;$m=ReadJson (Join-Path $ExtensionRoot 'manifest.json');$ok=($h -and [bool]$h.ok -and [bool]$h.asyncJobs -and $m -and [string]$m.version -eq [string]$r.version -and (Dedicated).Count -gt 0 -and (TestRelease $r));$s=[ordered]@{ok=[bool]$ok;status=$(if($ok){'SELF_HEAL_PASS'}else{'SELF_HEAL_FAILED'});agentVersion=$AgentVersion;agentMode='DIRECT_BRIDGE_LAST_GOOD_HOST_PRESERVE_1.1.26';commandHostVersion=$(if($h){[string]$h.version}else{''});hostHealthy=$(if($h){[bool]$h.ok}else{$false});hostAsyncJobs=$(if($h){[bool]$h.asyncJobs}else{$false});extensionVersion=$(if($m){[string]$m.version}else{''});releaseActionId=[string]$r.actionId;dedicatedChromeRunning=((Dedicated).Count -gt 0);extensionChanged=$changed;backupPath=$backup;errors=@();updatedAt=(Get-Date).ToString('o')};$json=$s|ConvertTo-Json -Depth 20;$json|Set-Content -LiteralPath $StateFile -Encoding UTF8;$json|Set-Content -LiteralPath $ReadbackFile -Encoding UTF8;$central=FindCentral;if($central){try{$dest=Join-Path $central 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $dest|Out-Null;$json|Set-Content -LiteralPath (Join-Path $dest 'VIDEO_LOCAL_RUNTIME_READBACK.json') -Encoding UTF8}catch{}};return $s}

$result=[ordered]@{action='AGENT_1.1.26_DIRECT_BRIDGE_RECOVERY';startedAt=(Get-Date).ToString('o');hostBefore=$null;targetBridge='';installedBefore='';changed=$false;backupPath='';state=$null;ok=$false;error=''}
try{$h=HostHealth;$result.hostBefore=$h;if(-not($h -and [bool]$h.ok -and [bool]$h.asyncJobs)){throw 'EXISTING_HOST_NOT_HEALTHY'};$rel=GetRelease;$result.targetBridge=[string]$rel.version;$before=ReadJson (Join-Path $ExtensionRoot 'manifest.json');$result.installedBefore=$(if($before){[string]$before.version}else{'NONE'});if(-not(TestRelease $rel)){$result.backupPath=InstallRelease $rel;$result.changed=$true}elseif((Dedicated).Count -le 0){LaunchDedicated ([string]$rel.frontUrl)};$result.state=WriteState $rel $result.changed $result.backupPath;$result.ok=[bool]$result.state.ok;if(-not $result.ok){throw 'POST_RECOVERY_STATE_NOT_VERIFIED'}}catch{$result.error=$_.Exception.Message;$result.ok=$false};$result.completedAt=(Get-Date).ToString('o');$result|ConvertTo-Json -Depth 30|Set-Content -LiteralPath $RecoveryFile -Encoding UTF8;if($result.ok){exit 0}else{exit 2}