param()
$ErrorActionPreference='Continue'
$ProgressPreference='SilentlyContinue'
$AgentVersion='1.1.69';$Repo='8friend8ship-cloud/notebooklm-webapp-bridge'
$PinnedBase='49cf6a07cd7f39bb76a6f26526b89b21dbdf4c25';$PinnedFlow='a36541d4a1e3748f26ba6ccadd0777ae21d3d2e3'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent';$State=Join-Path $Root 'state.json';$Receipt=Join-Path $Root 'FLOW_DIRECT_BOOTSTRAP_R10_1.1.69.json';New-Item -ItemType Directory -Force -Path $Root|Out-Null
function Blob([string]$p){$b=[IO.File]::ReadAllBytes($p);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function Api([string]$p){Invoke-RestMethod -Uri ('https://api.github.com/repos/'+$Repo+'/contents/'+$p+'?ref=main&cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -Headers @{'User-Agent'='HomeDesign-Local-Agent';'Accept'='application/vnd.github+json'} -TimeoutSec 30}
function SaveJ([string]$p,$o){$d=Split-Path $p -Parent;if($d){New-Item -ItemType Directory -Force -Path $d|Out-Null};$o|ConvertTo-Json -Depth 50|Set-Content $p -Encoding UTF8}
function Central{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue){foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path $c){return $c}}};''}
$errors=@();$baseOk=$false;$flowOk=$false;$cdp=$false;$flowExit=-1;$stdout='';$central=Central
try{$r=Api 'local-agent/releases/1.1.68/HomeDesignLocalAgent.ps1';if(([string]$r.sha).ToLowerInvariant()-ne$PinnedBase){throw('BASE_SHA:'+ [string]$r.sha)};$p=Join-Path $Root 'HomeDesignLocalAgent-1.1.68-pinned.ps1';[IO.File]::WriteAllBytes($p,[Convert]::FromBase64String(([string]$r.content-replace'\s','')));if((Blob $p).ToLowerInvariant()-ne$PinnedBase){throw'BASE_LOCAL_SHA'};& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $p;$baseOk=($LASTEXITCODE-eq0);if(-not$baseOk){throw('BASE_EXIT_'+$LASTEXITCODE)}}catch{$errors+=('BASE:'+ $_.Exception.Message)}
try{$r=Api 'local-agent/governor/Inspect-FlowApprovedAccountCredits.ps1';if(([string]$r.sha).ToLowerInvariant()-ne$PinnedFlow){throw('FLOW_SHA:'+ [string]$r.sha)};$flow=Join-Path $Root 'Inspect-FlowEntry-V8-pinned.ps1';[IO.File]::WriteAllBytes($flow,[Convert]::FromBase64String(([string]$r.content-replace'\s','')));if((Blob $flow).ToLowerInvariant()-ne$PinnedFlow){throw'FLOW_LOCAL_SHA'};$flowOk=$true}catch{$errors+=('FLOW_SCRIPT:'+ $_.Exception.Message)}
for($i=0;$i-lt45;$i++){try{$x=Invoke-RestMethod 'http://127.0.0.1:9224/json/list' -TimeoutSec 2;if($x){$cdp=$true;break}}catch{};Start-Sleep -Seconds 2}
if($flowOk-and$cdp){try{$psi=New-Object Diagnostics.ProcessStartInfo;$psi.FileName='powershell.exe';$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;$a='-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$flow+'" -NavigateWorkspace -DebugPort 9224 -TimeoutSeconds 150';if($central){$a+=' -CentralRootOverride "'+$central+'"'};$psi.Arguments=$a;$p=New-Object Diagnostics.Process;$p.StartInfo=$psi;[void]$p.Start();$ot=$p.StandardOutput.ReadToEndAsync();$et=$p.StandardError.ReadToEndAsync();if(-not$p.WaitForExit(180000)){try{Stop-Process -Id $p.Id -Force}catch{};throw'FLOW_TIMEOUT'};$flowExit=[int]$p.ExitCode;$stdout=$ot.Result.Trim();if($flowExit-ne0){$errors+=('FLOW_EXIT_'+$flowExit+':'+$et.Result.Trim())}}catch{$errors+=('FLOW_RUN:'+ $_.Exception.Message)}}elseif(-not$cdp){$errors+='CDP_9224_NOT_READY'}
try{$s=if(Test-Path $State){Get-Content $State -Raw -Encoding UTF8|ConvertFrom-Json}else{[pscustomobject]@{}};$s|Add-Member agentVersion $AgentVersion -Force;$s|Add-Member status $(if($flowExit-eq0){'FLOW_R10_DIRECT_PASS'}else{'FLOW_R10_DIRECT_ATTEMPTED'}) -Force;$s|Add-Member updatedAt ((Get-Date).ToString('o')) -Force;SaveJ $State $s}catch{$errors+=('STATE:'+ $_.Exception.Message)}
$ok=($baseOk-and$flowOk-and$cdp-and$flowExit-eq0);$rec=[ordered]@{ok=$ok;action='FLOW_R10_DIRECT_BOOTSTRAP_TEST';agentVersion=$AgentVersion;baseAgent='1.1.68';flowScriptVersion='FLOW_PROJECT_LIST_NEW_PROJECT_V8_20260829';cdp9224Ready=$cdp;flowExitCode=$flowExit;flowStdout=$stdout;normalChromeTouched=$false;generateClicked=$false;creditSpend=$false;oauthChanged=$false;errors=$errors;at=(Get-Date).ToString('o')};SaveJ $Receipt $rec;if($central){SaveJ (Join-Path $central 'Runtime_Readback\FLOW_DIRECT_BOOTSTRAP_R10_1.1.69.json') $rec};$rec|ConvertTo-Json -Depth 50 -Compress;if($ok){exit 0}else{exit 2}
