param()
$ErrorActionPreference='Stop'
$ProgressPreference='SilentlyContinue'
$Version='appscript-0.3.8-task203-source-transport-preflight'
$WebAppScriptId='1XzludErvxZ3px6qf1aLNU4LZWVU9NqJXYzSrnOm0HoDjUR9XN8flhSir'
$FactoryScriptId='14OHCqUDMAgpqB6JvPw_XQfFH8NlIUlVUK163RrFH1Drz3HxIc53B4IL2'
$CanonicalEmail='homedesigntaedi@gmail.com'
$ExpectedWeb='afe09428756cb3269fa21d4b6567e99cb322b3c39def243adadd3c68c8a0e7b9'
$ExpectedFactory='a2e0b3014c8289b8e25687adb32da099710b72ec0a5e5161533f8f97ee6016a0'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent'
$Receipt='APPSCRIPT_TASK203_SOURCE_TRANSPORT_PREFLIGHT_0.3.8.json'
New-Item -ItemType Directory -Force -Path $Root|Out-Null
function FindCentral{$n=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));$m=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('64K0IOuTnOudvOydtOu4jA=='));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){foreach($c in @((Join-Path $d.Root $n),(Join-Path $d.Root ($m+'\'+$n)),(Join-Path $d.Root ('My Drive\'+$n)),(Join-Path $d.Root ('Google Drive\'+$n)))){if(Test-Path -LiteralPath $c -PathType Container){return $c}}};''}
function Save($o){$j=$o|ConvertTo-Json -Depth 50;$j|Set-Content -LiteralPath (Join-Path $Root $Receipt) -Encoding UTF8;try{$c=FindCentral;if($c){$d=Join-Path $c 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $d|Out-Null;$j|Set-Content -LiteralPath (Join-Path $d $Receipt) -Encoding UTF8}}catch{}}
function GitBlob([byte[]]$b){$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[]($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function ClaspPath{foreach($n in @('clasp.cmd','clasp.ps1','clasp')){$c=Get-Command $n -ErrorAction SilentlyContinue;if($c){return $c.Source}};foreach($p in @((Join-Path $env:APPDATA 'npm\clasp.cmd'),(Join-Path $env:APPDATA 'npm\clasp.ps1'))){if(Test-Path $p){return $p}};''}
function Run([string]$File,[string[]]$Args,[int]$Timeout=90,[string]$Cwd=''){$psi=New-Object Diagnostics.ProcessStartInfo;$ext=[IO.Path]::GetExtension($File).ToLowerInvariant();if($ext-eq'.cmd'){$psi.FileName=$env:ComSpec;$psi.Arguments='/d /s /c ""'+$File+'" '+(($Args|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')+'"'}elseif($ext-eq'.ps1'){$psi.FileName='powershell.exe';$psi.Arguments='-NoProfile -NonInteractive -ExecutionPolicy Bypass -File "'+$File+'" '+(($Args|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')}else{$psi.FileName=$File;$psi.Arguments=(($Args|ForEach-Object{'"'+($_-replace'"','\"')+'"'})-join' ')};$psi.UseShellExecute=$false;$psi.CreateNoWindow=$true;$psi.RedirectStandardOutput=$true;$psi.RedirectStandardError=$true;if($Cwd){$psi.WorkingDirectory=$Cwd};$p=[Diagnostics.Process]::Start($psi);if(-not$p.WaitForExit($Timeout*1000)){try{$p.Kill()}catch{};return [ordered]@{ok=$false;exit=124;stdout='';stderr='TIMEOUT'}};[ordered]@{ok=($p.ExitCode-eq0);exit=$p.ExitCode;stdout=$p.StandardOutput.ReadToEnd();stderr=$p.StandardError.ReadToEnd()}}
function Sha256([byte[]]$b){$s=[Security.Cryptography.SHA256]::Create();try{return (($s.ComputeHash($b)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function CloneAgg([string]$Clasp,[string]$Id,[string]$Label){$d=Join-Path $env:TEMP ('task203-transport-'+$Label+'-'+(Get-Date -Format 'yyyyMMdd_HHmmss_fff'));New-Item -ItemType Directory -Force -Path $d|Out-Null;$x=Run $Clasp @('clone-script',$Id) 150 $d;if(-not$x.ok){throw('CLONE_'+$Label+'_FAIL '+$x.stderr)};$parts=@();foreach($f in @(Get-ChildItem $d -Recurse -File|Sort-Object FullName)){$rel=$f.FullName.Substring($d.Length).TrimStart('\');$b=[IO.File]::ReadAllBytes($f.FullName);$parts+=($rel+'|'+$f.Length+'|'+(Sha256 $b))};Sha256 ([Text.Encoding]::UTF8.GetBytes(($parts-join "`n")))}
function PublicRaw([string]$Repo,[string]$Path,[string]$Sha){$o=[ordered]@{ok=$false;repo=$Repo;path=$Path;expectedSha=$Sha;actualSha='';bytes=0;error=''};try{$u='https://raw.githubusercontent.com/'+$Repo+'/main/'+$Path+'?cb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds();$wc=New-Object Net.WebClient;try{$wc.Headers['User-Agent']='HomeDesign-Task203-0.3.8';$b=$wc.DownloadData($u)}finally{$wc.Dispose()};$o.bytes=$b.Length;$o.actualSha=GitBlob $b;$o.ok=($o.actualSha-eq$Sha);if(-not$o.ok){$o.error='GIT_BLOB_SHA_MISMATCH'}}catch{$o.error=$_.Exception.Message};[pscustomobject]$o}
function PrivateGh([string]$Repo,[string]$Path,[string]$Sha){$o=[ordered]@{ok=$false;repo=$Repo;path=$Path;expectedSha=$Sha;actualSha='';bytes=0;ghPresent=$false;authOk=$false;error=''};try{$gh=Get-Command gh.exe -ErrorAction SilentlyContinue;if(-not$gh){$gh=Get-Command gh -ErrorAction SilentlyContinue};if(-not$gh){$o.error='GH_NOT_FOUND';return [pscustomobject]$o};$o.ghPresent=$true;$a=Run $gh.Source @('auth','status','-h','github.com') 30;$o.authOk=$a.ok;if(-not$a.ok){$o.error='GH_AUTH_UNAVAILABLE';return [pscustomobject]$o};$x=Run $gh.Source @('api','repos/'+$Repo+'/contents/'+$Path,'-H','Accept: application/vnd.github.raw+json') 60;if(-not$x.ok){$o.error='GH_API_FAIL '+$x.stderr;return [pscustomobject]$o};$b=[Text.Encoding]::UTF8.GetBytes($x.stdout.TrimEnd("`r","`n"));$o.bytes=$b.Length;$o.actualSha=GitBlob $b;$o.ok=($o.actualSha-eq$Sha);if(-not$o.ok){$o.error='GIT_BLOB_SHA_MISMATCH'}}catch{$o.error=$_.Exception.Message};[pscustomobject]$o}
$r=[ordered]@{ok=$false;action='READONLY_TASK203_SOURCE_TRANSPORT_PREFLIGHT';version=$Version;authorizedUserOk=$false;baselineUnchanged=$false;webAppAggregate='';factoryAggregate='';publicAnalyzer=$null;privateLibrarian=$null;privateScheduler=$null;gitPresent=$false;gitPublicLsRemote=$null;sourceTransportReady=$false;nextGate='SOURCE_TRANSPORT_FIX_REQUIRED';stage='START';error='';readOnly=$true;pushPerformed=$false;newProject=$false;newDeployment=$false;newTrigger=$false;oauthChanged=$false;scopeChanged=$false;normalChromeTouched=$false;startedAt=(Get-Date).ToString('o');completedAt=''}
try{$clasp=ClaspPath;if(-not$clasp){throw'CLASP_NOT_FOUND'};$auth=Run $clasp @('show-authorized-user','--json') 45;$r.authorizedUserOk=($auth.ok-and(($auth.stdout+$auth.stderr).ToLowerInvariant().Contains($CanonicalEmail)));if(-not$r.authorizedUserOk){throw'CLASP_AUTH_UNAVAILABLE'};$r.stage='BASELINE';$r.webAppAggregate=CloneAgg $clasp $WebAppScriptId 'web';$r.factoryAggregate=CloneAgg $clasp $FactoryScriptId 'factory';$r.baselineUnchanged=($r.webAppAggregate-eq$ExpectedWeb-and$r.factoryAggregate-eq$ExpectedFactory);if(-not$r.baselineUnchanged){throw'BASELINE_DRIFT_ABORT'};$r.stage='TRANSPORT';$r.publicAnalyzer=PublicRaw '8friend8ship-cloud/Analyzer-12.09' 'apps-script/ContentOS_Drive_JSON_Cache_V3.gs' '6fa5b3b597213eebf18c960bde6372c5b95eb67d';$r.privateLibrarian=PrivateGh '8friend8ship-cloud/contents-os-git' 'apps-script/Central_Librarian_Knowledge_Automation.gs' '4631330d911dc8b5ae8e92b07a150b7986d1bc7e';$r.privateScheduler=PrivateGh '8friend8ship-cloud/contents-os-git' 'apps-script/ContentOS_Unified_Scheduler.gs' '4bbabc0a1de6a176c0c580505af9b8aafa3d07cc';$git=Get-Command git.exe -ErrorAction SilentlyContinue;if(-not$git){$git=Get-Command git -ErrorAction SilentlyContinue};$r.gitPresent=($null-ne$git);if($git){$g=Run $git.Source @('ls-remote','https://github.com/8friend8ship-cloud/Analyzer-12.09.git','HEAD') 45;$r.gitPublicLsRemote=[ordered]@{ok=$g.ok;exit=$g.exit;stdout=$g.stdout.Trim();stderr=$g.stderr.Trim()}};$r.sourceTransportReady=([bool]$r.publicAnalyzer.ok-and[bool]$r.privateLibrarian.ok-and[bool]$r.privateScheduler.ok);$r.ok=$true;$r.stage='DONE';$r.nextGate=if($r.sourceTransportReady){'ROLE_SPLIT_ANALYSIS_0.3.9'}else{'USE_PUBLIC_RAW_PLUS_PRIVATE_EXISTING_LOCAL_OR_GH_FIX'}
}catch{$r.error=$_.Exception.Message;$r.stage='ERROR'}finally{$r.completedAt=(Get-Date).ToString('o');Save $r};$r|ConvertTo-Json -Depth 50 -Compress;if($r.ok){exit 0}else{exit 2}
