param()
$ErrorActionPreference='Continue';$ProgressPreference='SilentlyContinue'
$Root=Join-Path $env:LOCALAPPDATA 'HomeDesignAutomationV7\LocalAgent';New-Item -ItemType Directory -Force -Path $Root|Out-Null
$Repo='8friend8ship-cloud/notebooklm-webapp-bridge';$BaseAgent=Join-Path $Root 'HomeDesignLocalAgent-1.1.36-base.ps1';$Probe=Join-Path $Root 'Inspect-FlowApprovedAccountCredits.ps1';$StatePath=Join-Path $Root 'state.json'
$BaseUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/releases/1.1.36/HomeDesignLocalAgent.ps1';$BaseExpected='20bb1a585dec23416204df71dc5e5701cdcf71f1';$ProbeUrl='https://raw.githubusercontent.com/'+$Repo+'/main/local-agent/governor/Inspect-FlowApprovedAccountCredits.ps1';$ProbeExpected='625d5602671b914786fee4a74d6aaa8667fbf4a9'
function GitBlobSha1([string]$Path){$b=[IO.File]::ReadAllBytes($Path);$h=[Text.Encoding]::ASCII.GetBytes(('blob '+$b.Length+[char]0));$a=New-Object byte[] ($h.Length+$b.Length);[Buffer]::BlockCopy($h,0,$a,0,$h.Length);[Buffer]::BlockCopy($b,0,$a,$h.Length,$b.Length);$s=[Security.Cryptography.SHA1]::Create();try{return (($s.ComputeHash($a)|ForEach-Object{$_.ToString('x2')})-join '')}finally{$s.Dispose()}}
function FetchVerified([string]$Url,[string]$Dest,[string]$Expected){$tmp=$Dest+'.download';Invoke-WebRequest -UseBasicParsing -Uri ($Url+'?hdcb='+[DateTimeOffset]::UtcNow.ToUnixTimeMilliseconds()) -OutFile $tmp -TimeoutSec 30;$actual=(GitBlobSha1 $tmp).ToLowerInvariant();if($actual -ne $Expected.ToLowerInvariant()){Remove-Item $tmp -Force -ErrorAction SilentlyContinue;throw ('SHA_MISMATCH actual='+$actual+' expected='+$Expected)};Move-Item $tmp $Dest -Force}
function FindCentral{$target=[Text.Encoding]::UTF8.GetString([Convert]::FromBase64String('MDBf7KSR7JWZ7JeQ7J207KCE7Yq4'));foreach($d in @(Get-PSDrive -PSProvider FileSystem -ErrorAction SilentlyContinue)){$r=[string]$d.Root;if(!$r){continue};foreach($c in @((Join-Path $r $target),(Join-Path $r ('My Drive\'+$target)),(Join-Path $r ('내 드라이브\'+$target)),(Join-Path $r ('Google Drive\'+$target)))){if(Test-Path -LiteralPath $c){return $c}}};return ''}
function WriteCentral([string]$Name,$Object){$central=FindCentral;if(!$central){return};$dir=Join-Path $central 'Runtime_Readback';New-Item -ItemType Directory -Force -Path $dir|Out-Null;$Object|ConvertTo-Json -Depth 50|Set-Content -LiteralPath (Join-Path $dir $Name) -Encoding UTF8}
$baseExit=$null;$probeExit=$null;$probeOutput='';$err='';try{FetchVerified $BaseUrl $BaseAgent $BaseExpected;& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $BaseAgent;$baseExit=$LASTEXITCODE}catch{$baseExit=-1;$err='BASE:'+($_.Exception.Message)}
try{FetchVerified $ProbeUrl $Probe $ProbeExpected;$out=& powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File $Probe 2>&1;$probeExit=$LASTEXITCODE;$probeOutput=($out|Out-String).Trim()}catch{$probeExit=-1;$err+=(';PROBE:'+($_.Exception.Message))}
$probeOk=($probeExit -eq 0 -and $probeOutput -match '"action"\s*:\s*"FLOW_APPROVED_ACCOUNT_CREDIT_READONLY"' -and $probeOutput -match '"normalChromeUntouched"\s*:\s*true');$receipt=[ordered]@{ok=[bool]$probeOk;action='AGENT_1.1.37_FLOW_ACCOUNT_CREDIT_READBACK';agentVersion='1.1.37';baseExit=$baseExit;probeExit=$probeExit;probeOutput=$probeOutput;readOnly=$true;generateClicked=$false;creditSpend=$false;oauthChanged=$false;scopeChanged=$false;chromeSettingsChanged=$false;error=$err;at=(Get-Date).ToString('o')};WriteCentral 'AGENT_1.1.37_FLOW_ACCOUNT_CREDIT_READBACK.json' $receipt
try{$state=$null;if(Test-Path -LiteralPath $StatePath){$state=Get-Content -LiteralPath $StatePath -Raw -Encoding UTF8|ConvertFrom-Json};if(!$state){$state=[pscustomobject]@{}};$state|Add-Member -NotePropertyName agentVersion -NotePropertyValue '1.1.37' -Force;$state|Add-Member -NotePropertyName agentMode -NotePropertyValue 'FLOW_ACCOUNT_CREDIT_READBACK_1.1.37' -Force;$state|Add-Member -NotePropertyName ok -NotePropertyValue ([bool]$probeOk) -Force;$state|Add-Member -NotePropertyName status -NotePropertyValue $(if($probeOk){'SELF_HEAL_PASS'}else{'FLOW_CREDIT_READBACK_FAILED'}) -Force;$state|Add-Member -NotePropertyName updatedAt -NotePropertyValue ((Get-Date).ToString('o')) -Force;$state|ConvertTo-Json -Depth 40|Set-Content -LiteralPath $StatePath -Encoding UTF8}catch{}
if($probeOk){exit 0}else{exit 2}
